### ISSUE TITLE
Create PEM formatted RSA public key string from RSA Public Key

### ISSUE THREAD

**Issue by mparaz** [kjur/jsrsasign#10]
Hello,
I would like to ask for a method that creates the PEM formatted RSA public key string from RSA Public Key. This is the opposite of _KJUR.asn1.x509.SubjectPublicKeyInfo.setRSAPEM_ in _asn1x509-1.0.js_.

Or, I could try implementing it. I just need some tips.
Thanks!
Miguel

**Comment by imolfar** [comment]
It's actually in KJUR.asn1.x509.X509Util.getPKCS8PubKeyPEMfromRSAKey
