### ISSUE TITLE
How to convert the content of a DER formatted file to a PEM formatted String

### ISSUE THREAD

**Issue by smrita-garg** [kjur/jsrsasign#100]
Hi, 
I am also facing the problem while converting to PEM formatted string
Getting "Cannot read property 'ASN1Util' of undefined" error. On using asn1-1.0.js is not resloving the error. Please help me with appropriate js. 

Thanks & Regards
 Smrita

**Comment by kjur** [comment]
Hi @smrita-garg , did you use the whole of latest code?
https://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js
It seems to be lacking other necessary files.

**Comment by smrita-garg** [comment]
@kjur ...
thanks for the help!!

**Comment by smrita-garg** [comment]
@kjur ... I am getting the PEM formatted string but it is different from the string when I open the .cer file. 

Please help!!

**Comment by smrita-garg** [comment]
Hi kjur,

Problem is solved while using different method reading the file using FileReader API
Thanks & Regards
Smrita
