### ISSUE TITLE
empty payload/claims on npm version

### ISSUE THREAD

**Issue by mLuby** [kjur/jsrsasign#103]
works on the script version, which is surprising because it looks like the npm version is the same but with module.exports and [a header with typos](https://github.com/kjur/jsrsasign/pull/102/files)

**JS** `= ['eyJhbGciOiJSUzI1NiJ9', 'W29iamVjdCBPYmplY3Rd', 'PvoEGruO-ETcz0IaYcguMrqvU…']`
```html
<html><head>
  <script src="http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js"></script>
</head><body><script>
  var keys = KEYUTIL.generateKeypair("RSA", 1024);
  var jsonObject = {a:'hello world', b:123, c:[1]};
  var signedJSONWebSignature = KJUR.jws.JWS.sign('RS256', JSON.stringify({alg: 'RS256'}), jsonObject, keys.prvKeyObj);
  console.log('signedJSONWebSignature',signedJSONWebSignature.split('.'));
</script></body></html>
```
**Node** `= ['eyJhbGciOiJSUzI1NiJ9', '', 'PvoEGruO-ETcz0IaYcguMrqvU…']`
```js
var jsrsasign = require('jsrsasign');
var keys = jsrsasign.KEYUTIL.generateKeypair("RSA", 1024);
var jsonObject = {a:'hello world', b:123, c:[1]};
var signedJSONWebSignature = KJUR.jws.JWS.sign('RS256', JSON.stringify({alg: 'RS256'}), jsonObject, keys.prvKeyObj);
console.log('signedJSONWebSignature',signedJSONWebSignature.split('.'));
```

**Anyone have any ideas? Help very much appreciated! :)**

Also shouldn't `KJUR` need to be required under `jsrsasign.KJUR`?

**Comment by mLuby** [comment]
Figured it out?

The sPayload in `KJUR.jws.JWS.sign = function(alg, sHeader, sPayload, key, pass)` [is *not* `JSON.stringified`](https://github.com/kjur/jsrsasign/blob/master/jws-3.2.js#L448). This is a bit odd since the sHeader [a few lines above](https://github.com/kjur/jsrsasign/blob/master/jws-3.2.js#L436) *is*.

Not sure if this is intended behavior or not. At least it's worth documenting that on node `utf8tob64u(sPayload)` is undefined while on Chrome browser it is not.

**Comment by kjur** [comment]
Thank you for the report. However in latest version of jsrsasign npm module 4.9.0, utf8tob64u seems to be defined. Regards.
