### ISSUE TITLE
How to create a Certificate Signing Request and then a x509 cert using it.

### ISSUE THREAD

**Issue by ruslangabitov** [kjur/jsrsasign#104]
<code>jsrsasign</code> is a great library, helped me to easily create private keys and x509 certs, but I can't quite get how to create CSR file and then use it.

So the goal is to create an x509 cert using CSR and a CA.

In oppenssl it can be done using this commands
Create a CA:
<code>openssl req -new -x509 -days 365 -key ca-key.pem -sha256 -out *ca.pem*</code>
Create key for our cert:
<code>openssl genrsa -out *key.pem* 2048</code>
Create CSR using that key:
<code>openssl req -new -key *key.pem* -out *signingRequest.csr*</code>
Create x509 cert using our CA, key and CSR:
<code>openssl x509 -req -days 365 -in *signingRequest.csr* -CA *ca.pem* -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf</code>

How can I archive the same using <code>jsrsasign</code>?

I found a similar issue: https://github.com/kjur/jsrsasign/issues/68, but I still don't understand:
1) how to create a DER Certificate Signing Request before parsing it to PEM.
2) Use CA cert.

Thanks in advance!

**Comment by jirutka** [comment]
+1, I need this too.

**Comment by kjur** [comment]
I've release jsrsasign 4.9.0 today and it supports certificate signing request generation.
You can use KJUR.asn1.csr.CSRUtil.newCSRPEM method as following:
http://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.csr.CSRUtil.html#.newCSRPEM
pem = KJUR.asn1.csr.CSRUtil.newCSRPEM({
  subject: {str: '/C=US/O=Test/CN=example.com'},
  sbjpubkey: pubKeyObj,
  sigalg: "SHA256withRSA",
  sbjprvkey: prvKeyObj
});

**Comment by kjur** [comment]
Demo page is also added.
http://kjur.github.io/jsrsasign/tool_csr.html
