### ISSUE TITLE
Verify a JWT with an RSA Public Key in PEM Format

### ISSUE THREAD

**Issue by jedd-ahyoung** [kjur/jsrsasign#105]
I'm receiving an error when I do the following:

	jsrsasign.default.jws.JWS.verifyJWT('ey.......', '-----BEGIN RSA PUBLIC KEY-----
	MIIBCgKCAQEAwEYqf3HAL+h0CbcM6cnVfT6hDw0nNPkLYKld54qRYhJa+txnI8so
	bIhP4/1l3TnNZldFFOatRlZAxuNG8Dk4L/QQmDeIsOkYQ5oiytSCbUrJv44aOPjL
	G72XhVOaOLMT2vp/guOVAjTYOyF83asoOpPVtFeiBHhKudMrpPzeq3qwGMxfVVPy
	NlztFjnTlkAKMtkbkwcpzdTn4y/pDo47+LgkDckReoqTIK4Z1bp86Oa6eBOa7/6w
	hIXG3aCQiMQfJUBEBRA7mmV4g+jNWMhCBMEsOZj+KUErfilPv1FL4zP3E8kNCu+B
	GYCSuj0doIxreVHDifXd+5Lmhr6NDkhG5QIDAQAB
	-----END RSA PUBLIC KEY-----', { alg: 'RS256'});

The error is `not supported argument` and it looks as though the KeyUtil isn't recognizing the key. Why doesn't this work? I don't want to have to create an X.509 certificate as I have to use the public key on my server as well.

**Comment by kjur** [comment]
Sorry but jsrsasign doesn't support loading "RSA PUBLIC KEY". It only supports "PUBLIC KEY". Thanks.

**Comment by kjur** [comment]
Sorry I reopened by mistake.
