### ISSUE TITLE
hextob64 is not exposed in Node

### ISSUE THREAD

**Issue by vsimonian** [kjur/jsrsasign#111]
`hextob64u` is exposed, but the b64-equivalent `hextob64` is missing.

**Comment by kjur** [comment]
Thank you for the report. I'll add hex2b64 in the next release.

**Comment by kjur** [comment]
I've just released jsrsasign npm 4.8.4 to fix it. regards,

**Comment by vsimonian** [comment]
Thank you very much! :+1:
