### ISSUE TITLE
Encoding JWT Requests 

### ISSUE THREAD

**Issue by xcellenceit** [kjur/jsrsasign#112]
Found link to this repo from http://jwt.io/

Can you advise how to use it for creating JWT signed / encoded requests using this library. Is there any example / document on how to use this?

Thank you in advance.

**Comment by kjur** [comment]
Please take a look below:

JWT signing tutorial:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation

JWT Demo:
http://kjur.github.io/jsrsasign/tool_jwt.html

JWS signing api:
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.sign

JWT verification api:
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verifyJWT

**Comment by xcellenceit** [comment]
Hi, Thank you :)

**Comment by hardiksoneji** [comment]
@kjur 

Please give example of JWT decryption to original payload using js 

JWT signing tutorial:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation
By using signing we get token its ok.

JWT verification tutorial:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-verification
Using verification we just verified token 

But how to get decryption value(header , payload) ?

**Comment by kjur** [comment]
Hi @hardiksoneji, Here is sample.
# token is JWS or JWT signature.
header = KJUR.jws.JWS.readSafeJSONString(b64utoutf8(token.split(".")[0]))
payload = KJUR.jws.JWS.readSafeJSONString(b64utoutf8(token.split(".")[1]))
