### ISSUE TITLE
bower.json has kjur/jsjws

### ISSUE THREAD

**Issue by timchaffee** [kjur/jsrsasign#113]
Should the bower.json have jsrsasign  instead of kjur/jsjws ?

What about the version? 4.8.5?

**Comment by kjur** [comment]
Sorry. I forgot to update it. I'll release later.

**Comment by kjur** [comment]
I've fixed it. Now you can download the latest 4.8.6 of jsrsasign as following:
% bower install jsrsasign

**Comment by kjur** [comment]
I've fixed it. Now you can download the latest 4.8.6 of jsrsasign as following:
% bower install jsrsasign

**Comment by timchaffee** [comment]
Thank you! Very responsive!

**Comment by mayankbpatel** [comment]
I run this command in a completely clean project:
```
bower install jsrsasign --save
```
Then I run (to make sure installation is idempotent):
```
bower install
```
And now I get the following errors:

```
bower not-cached    git://github.com/kjur/jsrsasign=jsrsasign.git#~4.8.6
bower resolve       git://github.com/kjur/jsrsasign=jsrsasign.git#~4.8.6
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/kjur/jsrsasign=jsrsasign.git", exit code of #128 fatal: remote error:    kjur/jsrsasign=jsrsasign is not a valid repository name   Email support@github.com for help

Additional error details:
fatal: remote error:
  kjur/jsrsasign=jsrsasign is not a valid repository name
  Email support@github.com for help
```

Appreciate any help in getting past this.  Thanks.

**Comment by timchaffee** [comment]
I updated my bower.json to have this:

    "jsrsasign": "jsrsasign#~4.8.5",

and it worked. I am not sure why the --save puts in something that does not work.

**Comment by kjur** [comment]
Hi @mayankbpatel , @timchaffee . I'm sorry but I need some clarification.

In my bower.json, change

  "name": "kjur/jsrsasign",

to

  "name": "jsrsasign",
.

Will this fix the issue?

**Comment by kjur** [comment]
There is no comment on this. So I'll close this ticket.
