### ISSUE TITLE
EC private + public key format

### ISSUE THREAD

**Issue by harrisondkurtz** [kjur/jsrsasign#116]
I'm trying to export a EC public key in PEM format but I get the following error:

jsrsasign\lib\jsrsasign.js:273
);return v.ASN1Util.getPEMStringFromHex(k,"ENCRYPTED PRIVATE KEY")}}throw"unsupported object nor format

Here's the example I am using:

```
var jsr = require('jsrsasign')

var prvkey = jsr.KEYUTIL.generateKeypair("EC", "prime256v1");
var pubkey = prvkey.pubKeyObject;
var prvPEM = jsr.KEYUTIL.getPEM(prvkey, "PKCS8PRV")
var pubPEM = jsr.KEYUTIL.getPEM(pubkey);
```

I also noticed that the hex value of the EC keys were not asn1 encoded.

**Comment by kjur** [comment]
Above seems wrong and can be fixed as following:

var jsr = require('jsrsasign')
var keypair = jsr.KEYUTIL.generateKeypair("EC", "prime256v1");  /// <- FIXED
var prvkey = keypair.prvKeyObject; /// <- FIXED
var pubkey = keypair.pubKeyObject;
var prvPEM = jsr.KEYUTIL.getPEM(prvkey, "PKCS8PRV")
var pubPEM = jsr.KEYUTIL.getPEM(pubkey);

**Comment by harrisondkurtz** [comment]
Ah, thanks for that. I have another question. What format are the EC keys stored in? I assumed they were asn1 encoded but they are not:

var jsr = require('jsrsasign')
var ec = new jsr.crypto.ECDSA({"curve": "secp256r1"});
var pair = ec.generateKeyPairHex();
console.log(jsr.ASN1HEX.isASN1HEX(pair.ecprvhex));
console.log(jsr.ASN1HEX.isASN1HEX(pair.ecpubhex));

Output was false, false. 

If the keys are not encoded in asn1 format, is there a utility function provided by jsrsasign that could help me encode the keys?

**Comment by kjur** [comment]
Internal data of EC private key and public key are hexadecimal value of n and concatinated header, x and y value of coordinate.

**Comment by Zamicol** [comment]
The signature is the hex of ASN1 format and I can decode it easily.  

`<0x30> <length of message> <0x02> <length of R> <R> <0x2> <length of S> <S> ` 

Signature:
3045022100c4da6ba370f64fa381795ab53cd43190c643bec1905f8cbf549cef73e75cf158022075e9adeb1b18d14b37f2f3e87dedc1da35fac763972c265146a5d93303e90c1e

Decoded using a javascript tool:
https://lapo.it/asn1js/#304502206AA8EF89E0FEFDF97C01AF649F9B3FEE752587DFDF5A240C2923669F4407F1D20221008667E1F4B6553BB54E2732729455A05D6EA41F0E3EC7F412BA10B6BEED2251D3

I'm having more issues with the public key.  How is it encoded?  
Public key:
047eb9a9cd3722a4977320da2f733343c4c585376cf3f39fa7fa029eb6a9f750e39982f16cca04a3674ba8a2867d6fa6198826efb08663f6fd987770d814dab137

Using this tool, it says that it is misencoded:  http://asn1-playground.oss.com/

**Comment by kjur** [comment]
EC public key bytes is not encoded as ASN.1.

Uncompressed EC public key
    <0x04><x bytes><y bytes>

Compressed EC public key
    <0x02><x bytes> when y is even.
    <0x03><x bytes> when y is odd.
