### ISSUE TITLE
Cannot verify JWT token

### ISSUE THREAD

**Issue by tmschlot** [kjur/jsrsasign#118]
I am not able to verify a JWT token.  If I go to http://jwt.io and attempt to verify the same token, it works.  I've debugged the code and made sure I'm passing the same values to the KJUR.jws.JWS.verify method (even hard-coding the values to make sure they are the same), and jwt.io returns true, while my call returns false.  I'm using 4.9.

```javascript
key = window.b64utob64(key);
key = window.CryptoJS.enc.Base64.parse(key).toString();
var result = KJUR.jws.JWS.verify(token, key); // always false for me
```

I've also tried calling verifyJWT, but I get the same result.  (Probably because the underlying implementation calls verify, which isn't working.)

Again, I've put breakpoints in both my code and jwt.io, and at the point it calls verify, my code returns false while jwt.io returns true.  

Any ideas what's going on?  Or is this a bug?

**Comment by kjur** [comment]
As described in the manual, the 'key' shall be a hexadecimal string. If JWT generated at jwt.io with password "aaa", JWS.verify key shall be "616161" in jsrsasign.

**Comment by tmschlot** [comment]
I don't think I made my issue clear.  When I go to jwt.io, debug the JS, and call verify...

```Javascript
var result = KJUR.jws.JWS.verify(token, key);
```

I get a result of true.  When I debug my own code at the same call with the same values for both token and key, I get a result of false.  (I verified that I'm passing the same values by doing a direct comparison, and both returned true.)

I think if the issue was a hexidecimal key, I would have the same issue on jwt.io as I do in my own code, because the token and key are the same in both instances.  

Does that clarify my issue?  Or am I missing something?

**Comment by tmschlot** [comment]
I came back to this after letting it sit for a few days, and I think I've figured out what is going on.  On jwt.io, when the KJUR.crypto.Mac is created to verify the signature, the call to hextorstr(key) -- to set the <i>pass</i> field -- returns a very different value for the same key.  After a bit of digging, I see the implementation for that method has changed from...

```javascript
// on jwt.io
window.hextorstr = function (c) {
  return window.CryptoJS.enc.Hex.parse(c);
};
```

to 

```javascript
// in jsrsasign-4.9.0 (non-minified)
function hextorstr(sHex) {
    var s = "";
    for (var i = 0; i < sHex.length - 1; i += 2) {
        s += String.fromCharCode(parseInt(sHex.substr(i, 2), 16));
    }
    return s;
}
```

Based on what I've seen thus far, it looks like the verify call will work as long as you sign with the method included in the library.  However, if you sign with something outside the library, the verify will fail because of this change.  I don't have an example to support this position, though.  

Could you please review?

**Comment by kjur** [comment]
The "jwt.io" site is using my old version of jsrsasign 4.1.5.
In my jsrsasign CryptoJS library is used for Hmac.

https://code.google.com/p/crypto-js/#Progressive_HMAC_Hashing

var hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, "Secret Passphrase");

For this HMAC API, password shall be specifed as (raw) string not CryptoJS W-word object.
So hexadicmal string of password shall be converted by my hextorstr function not
a object by CryptoJS.enc.Hex.parsed method.

Sorry but your another ticket is also closed.

**Comment by tmschlot** [comment]
We gave up on trying to figure out what was going on with this.  We were passing a hex string of the password as @kjur stated but it just wasn't working.

Instead, we changed to using RSA keys and the verifyJWSByNE method, which worked as expected.
