### ISSUE TITLE
Support issuer values with '/' chars.

### ISSUE THREAD

**Issue by cblair** [kjur/jsrsasign#119]
From what I can tell, this is legal per https://tools.ietf.org/html/rfc3280#section-4.1.2.4. Feel free to set me straight.

I'm forking and will create a PR with AUT proposing a change.

**Comment by kjur** [comment]
Thank you for your mention. I'll grad if you can provide X500Name class in asn1x509.js update and test code for that. I hope some characters like "/", "=" and "\" can be escaped by back slash "\".

**Comment by cblair** [comment]
kjur, can you advise on how to build this? I've consulted https://github.com/kjur/jsrsasign/issues/57 (see what we have in https://github.com/mdcone/jsrsasign/blob/master/Makefile). But I'm minifying incorrect files, and not all the right ones. Thanks!

**Comment by kjur** [comment]
If you can't generate minified version of jsrsasign-latest-all-min.js, I'll do it. Please push your asn1x509.js and test code. It is enough for me. Thanks.

**Comment by cblair** [comment]
Thanks kjur, see PR here: https://github.com/kjur/jsrsasign/pull/121

**Comment by kjur** [comment]
Thank you for the pull request. I'll merge later.
