### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by tmschlot** [kjur/jsrsasign#120]
I previously posted this question: https://github.com/kjur/jsrsasign/issues/118

Since it is closed, I assume it is getting no views, though I have found what I believe to be a bug in the library.

**Comment by kjur** [comment]
The "jwt.io" site is using my old version of jsrsasign 4.1.5.
In my jsrsasign CryptoJS library is used for Hmac.

https://code.google.com/p/crypto-js/#Progressive_HMAC_Hashing

var hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, "Secret Passphrase");

For this HMAC API, password shall be specifed as (raw) string not CryptoJS W-word object.
So hexadicmal string of password shall be converted by my hextorstr function not
a object by CryptoJS.enc.Hex.parsed method.
