### ISSUE TITLE
Incompatible with Node version and JWT.io validator

### ISSUE THREAD

**Issue by itslenny** [kjur/jsrsasign#123]
This token was generated using the demo code with the password `616161`. If this is pasted into the validator at [jwt.io](http://jwt.io/) it says the signature is invalid.

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3IiOiJodHRwOi8vd3d3Lml0c2xlbm55c2ZhdWx0LmNvbSIsInNlcmlhbCI6Im1obWhobW5mZ2htaGZnbWZnaG1mZ2htZmdobSIsInByb2R1Y3QiOiJGaW5hbCBNYXJrZG93biIsImNyZWF0ZWRBdCI6MTQ0NDAwMjEwN30.NlYMkd79i0bzP1mJHqpl4ixor9Hr1XS7BF4j5MqICqE
```

I additionally tried this against the verify function of the node.js version by Auth0 [https://github.com/auth0/node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) and it also says the signature is invalid.

**Comment by kjur** [comment]
Password shall be "aaa" in jwt.io for hexadecimal passwod 616161 in jsrsasign. Thnx.

**Comment by itslenny** [comment]
@kjur  Hexadecimal? It also doesn't work with a string password such as "secret". How do you specify a string secret instead of a hexadecimal?

This token was encoded using the secret of "secret" and it also fails to validate.

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3IiOiJodHRwOi8vd3d3Lml0c2xlbm55c2ZhdWx0LmNvbSIsInNlcmlhbCI6ImFzZGZhc2Rmc2FkZnNkYWZhc2Rmc2FkZnNhZGZzYWRmZGYiLCJwcm9kdWN0IjoiRmluYWwgTWFya2Rvd24iLCJjcmVhdGVkQXQiOjE0NDQwMDM1NjB9.jSwuiqtIK_r4UejNCclsXMwrbHeXFX_MVzK8Qw5U6qY
```

**Comment by kjur** [comment]
This token is successfully verified by the password "616161" (i.e. "aaa") by jsrsasign.
For example following tool without acceptable issuer/subject/audiences:
http://kjur.github.io/jsrsasign/tool_jwtveri.html
Thanks.

**Comment by kjur** [comment]
The your first token 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3IiOiJodHRwOi8vd3d3Lml0c2xlbm55c2ZhdWx0LmNvbSIsInNlcmlhbCI6Im1obWhobW5mZ2htaGZnbWZnaG1mZ2htZmdobSIsInByb2R1Y3QiOiJGaW5hbCBNYXJrZG93biIsImNyZWF0ZWRBdCI6MTQ0NDAwMjEwN30.NlYMkd79i0bzP1mJHqpl4ixor9Hr1XS7BF4j5MqICqE"
is verified successfully with password "aaa" at http://jwt.io/ site.

**Comment by kjur** [comment]
Second token 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3IiOiJodHRwOi8vd3d3Lml0c2xlbm55c2ZhdWx0LmNvbSIsInNlcmlhbCI6ImFzZGZhc2Rmc2FkZnNkYWZhc2Rmc2FkZnNhZGZzYWRmZGYiLCJwcm9kdWN0IjoiRmluYWwgTWFya2Rvd24iLCJjcmVhdGVkQXQiOjE0NDQwMDM1NjB9.jSwuiqtIK_r4UejNCclsXMwrbHeXFX_MVzK8Qw5U6qY"
seems that its password is "aaa" and it can be verified with password "616161" in the following tool:
http://kjur.github.io/jsrsasign/tool_jwtveri.html
Thanks.
