### ISSUE TITLE
Need Help Understanding Error Message

### ISSUE THREAD

**Issue by AlaRuba** [kjur/jsrsasign#125]
Hi,

I am using these steps to generate an encrypted PKCS8 key, but the library is not reading it.

```
openssl genrsa -out file.pem -passout pass:file 1024
openssl pkcs8 -topk8 -inform pem -in file.pem -outform der -nocrypt -out file.der
```
I then submit the file.der to my javascript and store the key in var key and password in var passcode
```
var rawDerFileContents = key;
var hexDerFileContents = rstrtohex(rawDerFileContents);
var pemString = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, 'ENCRYPTED PRIVATE KEY');
var decryptedKeyHex = KEYUTIL.getKeyFromEncryptedPKCS8PEM(pemString, passcode);
```

However, I get an error saying UNcaught malformed format: SEQUENCE(0.0).items != 2:1

What does that mean?

**Comment by kjur** [comment]
Which do you need private key object or hexadecimal string of private key?
% openssl pkcs8 -topk8 -inform pem -in file.pem -outform der -nocrypt -out file.der
This command outputs unencrypted PKCS#8 private key. So following PEM header "ENCRYPTED PRIVATE KEY" shall be wrong:
var pemString = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, 'ENCRYPTED PRIVATE KEY'

The easiest way to load private key from OpenSSL will be following:
% openssl genrsa -out file.pem -passout pass:file 1024
% openssl pkcs8 -topk8 -inform pem -in file.pem -nocrypt -out file_noenc.pem      # SAVE AS PEM NOT DER

prvKey = KEYUTIL.getKEY(__file_noenc.pem__string__);

**Comment by AlaRuba** [comment]
Thanks so much for replying. This solves how I read in the PEM file.

However, what if I need to read in DER file, and can't use openssl to convert it? I was wondering how to read that in with your library.

**Comment by kjur** [comment]
Currently KEYUTIL.getKey doesn't support hexadecimal PKCS#8 DER private key while
it support hexdecimal PKCS#5 DER private key adn PKCS#8 DER public key.

So convert your key to PEM format string then you can read the PKCS#8 PEM private key.

var rawDerFileContents = key;
var hexDerFileContents = rstrtohex(rawDerFileContents);
var pem = KEYUTIL.getPEM(hexDerFileContents, "PKCS8PRV");
var prvKeyObj = KEYUTIL.getKEY(pem);
