### ISSUE TITLE
Need Help Convert a DER File to PEM File

### ISSUE THREAD

**Issue by AlaRuba** [kjur/jsrsasign#127]
Hi,

I'm reading in a PKCS #8 DER File. Thus, I want to read it in the browser, then convert it to PEM using your library so I can use the key. However, I encounter this problem while converting it.

I read the file (it is binary encoded btw) in like so
```
var selectedFile = event.target.files[0];
var reader = new FileReader();

reader.onload = function(event) {
    console.log(event.target.result)
    key = forge.util.binary.raw.encode(new Uint8Array(event.target.result));
};

reader.readAsArrayBuffer(selectedFile);

```

I then try to convert it via
```
var rawDerFileContents = key;
var hexDerFileContents = rstrtohex(rawDerFileContents);
var pem = KEYUTIL.getPEM(hexDerFileContents, "PKCS8PRV");
var prvKeyObj = KEYUTIL.getKEY(pem);
```
However, I get an error saying 
```
unsupported object nor format
```
from this line
```
var pem = KEYUTIL.getPEM(hexDerFileContents, "PKCS8PRV");
```
I was hoping you knew where I went wrong. Thanks.

**Comment by kjur** [comment]
Can you provide your sample hexadecimal string of DER encoded PKCS#8 private key which raising issue?

**Comment by kjur** [comment]
Hi @AlaRuba , I've show you a wrong code. I've confirmed the following works. Thanks.

var rawDerFileContents = key;
var hexDerFileContents = rstrtohex(rawDerFileContents);
var pem = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, "PRIVATE KEY");
var prvKeyObj = KEYUTIL.getKEY(pem);

**Comment by AlaRuba** [comment]
Thanks so much
