### ISSUE TITLE
Need more KJUR.asn1.cms.SignerInfo.dUnsignedAttrs

### ISSUE THREAD

**Issue by danieldeschamps** [kjur/jsrsasign#128]
How dificult is to implement KJUR.asn1.cms.SignerInfo.dUnsignedAttrs.
   id-aa-ets-certificateRefs
   id-aa-ets-revocationRefs
   id-aa-ets-escTimeStamp
   id-aa-ets-certValues
   id-aa-ets-revocationValues
   id-aa-ets-archiveTimestampV2
?

**Comment by kjur** [comment]
id-aa-ets-certificateRefs have been already implemented as KJUR.asn1.cades.CompleteCertificateRefs class. As for id-aa-ets-escTimeStamp and id-aa-ets-archiveTimestampV2, KJUR.asn1.cades.SignatureTimeStamp implementation can be referred.
But I can't say how difficult it is :( If you implement them please send me push request :)
