### ISSUE TITLE
Breaking API changes should not be in minor release

### ISSUE THREAD

**Issue by vsimonian** [kjur/jsrsasign#129]
In the latest minor release, several deprecated functions were cut from the JWS API.

>remove some old fashoned functions and methods which marked as "deprecated". Followings are removed:
>JWS.generateJWSByP1PrvKey
>JWS.generateJWSByKey
>JWS.generateJWSByNED
>JWS.verifyJWSByPemX509Cert

This is leading to failing code in dependent software and does not follow semver.

Per semver,

>**Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API**. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

With regards to deprecation specifically per the semver FAQ,

>Deprecating existing functionality is a normal part of software development and is often required to make forward progress. When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) issue a new minor release with the deprecation in place. Before you completely **remove the functionality in a new _major_ release** there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

Please restore the JWS functions in a minor release, and if necessary, please make a major release for the removal of the functions.

**Comment by kjur** [comment]
Thank you for the remind. I'll withdraw 4.10.0 release and release 5.0.0 without any major additional functionality.

**Comment by vsimonian** [comment]
Thanks, @kjur. I certainly hope I didn't sound harsh; when I noticed the code I was working with was failing due to this it caught me off guard.

Looking forward to 5.0.

**Comment by kjur** [comment]
Hi @vsimonian , I've released 5.0.0 today to fix semver issue. Thanks.

**Comment by vsimonian** [comment]
Thanks for the push of 5.0.0! However, 4.10.0 is still up on npm and is the latest version installed for v4-dependent packages.

**Comment by kjur** [comment]
How do I remove 4.10.0? I've done following command:
% npm deprecate jsrsasign@4.10.0 "semver violation"

**Comment by vsimonian** [comment]
I waited a while and tested installing jsrsasign into several dependent packages, and npm still matches deprecated versions when installing.

Perhaps unpublish may be the way to go, considering that the package has only been up for a day (it might not be too late)

**Comment by kjur** [comment]
Thanks. I'll try 'unpublish' later.

**Comment by kjur** [comment]
Migration guide is now provided.
https://github.com/kjur/jsrsasign/wiki/jsrsasign-JWS-API-4.9.2-to-5.0.0-migration-guide

**Comment by kjur** [comment]
Version 4.10.0 has been 'unpublish'ed.

**Comment by kjur** [comment]
So I'll close this ticket. If still having issue, I'll reopen.
