### ISSUE TITLE
CryptoJS AES support

### ISSUE THREAD

**Issue by tmschlot** [kjur/jsrsasign#131]
I'm referencing jsrsasign and attempting to encrypt some data using the CryptoJS AES implementation, but it fails.  When I reference CryptoJS directly, the encryption works.  

Here's an example of what I'm doing: http://plnkr.co/edit/ntXccrTdVufQuy2XF6Nh?p=preview

I'd like to use jsrsasign for other things I'm working on, so I'd prefer to use the implementation embedded in it if possible.  Is there something else I need to do to make this work using jsrsasign?  

Thanks.

**Comment by tmschlot** [comment]
I've gotten around this issue by including the CryptoJS aes rollup script file also.  (Alternatively, can use the individual components that make it up... https://code.google.com/p/crypto-js/source/browse/tags/3.1.2/builder/build.yml)

**Comment by kjur** [comment]
Thank you for the report. I'll close this ticket.
