### ISSUE TITLE
cannot sign JWS ES256: Uncaught init failed:can't find nthList object

### ISSUE THREAD

**Issue by coolaj86** [kjur/jsrsasign#133]
I opened up the console at http://kjur.github.io/jsrsasign/tool_csr.html and tried to sign a test object:

```js
var ecKeypair = KEYUTIL.generateKeypair("EC", "secp256r1");
var privkeypem = KEYUTIL.getPEM(ecKeypair.prvKeyObj, "PKCS5PRV", "this is my special passcode", "AES-128-CBC");
KJUR.jws.JWS.sign(null, { alg: 'ES256' }, { foo: 'bar', cty: "JWT" }, privkeypem, "this is my special passcode");
```

It failed with `Uncaught init failed:can't find nthList object`

**Comment by kjur** [comment]
Hi @coolaj86 , it seems that getPEM() don't work properly.

Does this help you?

    var kp = KEYUTIL.generateKeypair("EC", "secp256r1");
    var hSig = KJUR.jws.JWS.sign(null, '{"alg": "ES256"}', '{foo: "bar", cty: "JWT"}' , kp.prvKeyObj);

**Comment by kjur** [comment]
I think the issue was solved. So I'll close this ticket.
