### ISSUE TITLE
KJUR.crypto.Signature({'alg':'SHA256withECDSA'}).updateHex() method hashes twice when signing

### ISSUE THREAD

**Issue by jvsteiner** [kjur/jsrsasign#134]
I think I found a bug in the ECDSA signature module:

using the following code:

    var sig = new KJUR.crypto.Signature({'alg':'SHA256withECDSA'});
    sig.init(privkey);
    var sigValueHex = sig.signHex('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');

and then examining the `sig` object reveals that 

    sHashHex: "5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456"

this value is actually the hash-of-the-hash of `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

for example, in Python:

    from hashlib import sha256
    sha256("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".decode('hex')).hexdigest()

gets you `5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456`

this has been causing my signatures not to verify for the correct hash - but have confirmed that they do verify for the hash-of-a-hash using OpenSSL.

**Comment by kjur** [comment]
Thank you for the report. I'll check it.

**Comment by jvsteiner** [comment]
I should mention, I am using: `https://cdn.rawgit.com/kjur/jsrsasign/master/jsrsasign-latest-all-min.js` as the source in my project - it should be pulling the latest version from there.

**Comment by kjur** [comment]
Hi @jvsteiner , I've checked my code.

I've tried following code.

    var sig = new rs.crypto.Signature({alg: 'SHA256withECDSA'});
    sig.init(prvPEM);
    sig.updateString('aaa');
    var sigHex = sig.sign();

Then the resulting signature was successfully verifed by OpenSSL:
    % openssl dgst -sha256 -verify pubkey.pem -signature sig.bin aaa.txt

So it is not double-hashed. Thanks.

**Comment by jvsteiner** [comment]
Hi, the problem is not with the .updateString() method, but rather with the .updateHex() method, (or the signHex() convenience method that calls .updateHex() internally.)  I also get the right answer, but if you follow the steps in the original post, you can see the issue.

**Comment by kjur** [comment]
I've tried following codes and both are successfully verified by openssl.

    var sig = new rs.crypto.Signature({alg: 'SHA256withECDSA'});
    sig.init(prvPEM);
    sig.updateHex('616161');
    var sigHex = sig.sign();

    var sig = new rs.crypto.Signature({alg: 'SHA256withECDSA'});
    sig.init(prvPEM);
    var sigHex = sig.signHex('616161');

**Comment by kjur** [comment]
SHA256 of 0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 shall be "5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456" which is not double hash.

**Comment by jvsteiner** [comment]
I see - clearly what this method does, and what I imagine it should do are quite different.  In the case that I have a hex encoded hash value (not the original data - the data is already hashed elsewhere) and I need to sign it - how can I sign the hash value directly.  Your example (where '616161' may be hex encoded, but is obviously far too short to the hex-digest of some data) suggests that this may not be easily possible.  Am I right?

**Comment by jvsteiner** [comment]
in my use case - `0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` is the hash value - it's already the hash of the data - it should not be hashed again - i want to sign that value.

**Comment by kjur** [comment]
Sorry but you are wrong. It shall be input data to be signed for signHex() or updateHex().

**Comment by jvsteiner** [comment]
I'm not wrong - I have a different use-case.  I'd like to sign a pre-computed hash value, and not have it hashed again.  It's clear that it hashes the data (either str or hex) as provided, and this is precisely what you intended to do, however, in my case, I would like to not provide the data, but rather the digest of the data to be signed.  Is this possible?

**Comment by kjur** [comment]
For your use case, you can use KJUR.crypto.ECDSA class directly.

**Comment by jvsteiner** [comment]
thank you

**Comment by kjur** [comment]
I'll close this ticket.
