### ISSUE TITLE
Unable to resolve module fs when using 5.0.2 with React Native

### ISSUE THREAD

**Issue by marcusroberts** [kjur/jsrsasign#136]
When I upgraded from 5.0.1 to 5.0.2 and rebuilt my React Native app I have the following error in the ReactPackager phase:

"Unable to resolve module fs"

I think this is because fs isn't available for React Native apps perhaps?

**Comment by marcusroberts** [comment]
A quick read of the code shows its in the new file

jsrsasign/nodeutil-1.0.js

so this bug isn't jsrsasign itself.

**Comment by kjur** [comment]
Thank you for the report. It's not jsrsasign issue, is it. I'll close the ticket.

**Comment by sibeliusseraphini** [comment]
@marcusroberts did you find out how to fix this?

**Comment by sibeliusseraphini** [comment]
@kjur I would like to know whether it is possible to move node-utils to a contrib repository (or separate it in npm), so we could use this lib in react native or other projects that are pure js without nodejs

**Comment by marcusroberts** [comment]
Hi,

My fix was to move the library out of nam and into my source tree, and edit out the lines that referenced the FS module, the one line that starts with the define for readFileUTF8

// function readFileUTF8(

and  all these exports at the end

// exports.readFileUTF8 = readFileUTF8;
// exports.readFileHexByBin = readFileHexByBin;
// exports.readFile = readFile;
// exports.saveFile = saveFile;
// exports.saveFileBinByHex = saveFileBinByHex;

but it does mean I miss updates in the library at the moment.

**Comment by sibeliusseraphini** [comment]
I did the same here, thanks
