### ISSUE TITLE
Export public key as der for libtrust support

### ISSUE THREAD

**Issue by kidhasmoxy** [kjur/jsrsasign#137]
The Docker Libtrust library uses a "fingerprint" approach to generate the kid header for a JWT. Can jsrsasign support the generation approach listed below? 

I see that we can use the x509 utils to get a public key from a private RSA key object, but is there a way to DER encode the public key? 

From there, we should be able to run the digest and do the base32 encoding. 

https://github.com/docker/libtrust/blob/master/util.go#L195-L199
// Generate and return a 'libtrust' fingerprint of the public key.
	// For an RSA key this should be:
	//   SHA256(DER encoded ASN1)
	// Then truncated to 240 bits and encoded into 12 base32 groups like so:
	//   ABCD:EFGH:IJKL:MNOP:QRST:UVWX:YZ23:4567:ABCD:EFGH:IJKL:MNOP

**Comment by kjur** [comment]
I hope this solves:
    
    // let prvKey is private RSAKey object
    pubPEM = KEYUTIL.getPEM(prvKey, "PKCS8PUB");
    // pubHex will be a hexadecimal string of DER encoded PKCS#8 public key
    pubHex = KEYUTIL.getHexFromPEM(pubPEM);

**Comment by kidhasmoxy** [comment]
I'm getting an error thrown on the first line. I'm creating prvKey using KEYUTIL.getkey. Is that the right approach? 

/node_modules/jsrsasign/lib/jsrsasign.js:273
);return v.ASN1Util.getPEMStringFromHex(k,"ENCRYPTED PRIVATE KEY")}}throw"unsu

**Comment by kjur** [comment]
How did you use getKey?

Following code works in Node:

    var rs = require('jsrsasign');
    var kp = rs.KEYUTIL.generateKeypair("RSA", 2048);
    var pubPEM = rs.KEYUTIL.getPEM(kp.prvKeyObj, "PKCS8PUB");
    var pubHex = rs.KEYUTIL.getHexFromPEM(pubPEM);

**Comment by kidhasmoxy** [comment]
This is some example code that I'm using based off of your tutorial for generating a JWT. I have a string variable that holds an RSA Private Key (no password.) I'm able to generate the JWT just fine when I use KEYUTIL to create a private key object. 

var prvKey = a.KEYUTIL.getKey(sKey);

**Comment by kjur** [comment]
It seems that getKey and getPEM have issue in NodeJS.
To get PEM public key from private key, it requires to set isPublic flag.
This only work on RSA private key.

Here is work around and works fine:

    var rs = require('jsrsasign');
    var prvPEM = rs.readFile('bbb.p5prv');
    var prvHex = rs.KEYUTIL.getHexFromPEM(prvPEM);
    var prvObj = rs.KEYUTIL.getKey(prvHex, '', "pkcs5prv");
    prvObj.isPublic = true;
    var pubPEM = rs.KEYUTIL.getPEM(prvObj, "PKCS8PUB");
    var pubHex = rs.KEYUTIL.getHexFromPEM(pubPEM);

I'll fix this issue in the future version.

**Comment by kidhasmoxy** [comment]
That worked, thanks. You can shortcut it a bit by just using 'a.asn1.x509.X509Util.getPKCS8PubKeyPEMfromRSAKey(prvKey)' to get the public pem in one line.

Here's the routine I ended up with to match that libtrust spec. It may not be optimized but at least it works.
```javascript
    var pubHex = a.KEYUTIL.getHexFromPEM(a.asn1.x509.X509Util.getPKCS8PubKeyPEMfromRSAKey(prvKey));
    //console.log(pubHex);
    var md = new a.crypto.MessageDigest({alg: "sha256", prov: "cryptojs"}); // sjcl supports sha256 only
	md.updateHex(pubHex);
    var mdHex = md.digest();
    var fingerp = base32.encode(a.stoBA(a.hextorstr(mdHex.substr(0,60)))).match(/[\s\S]{1,4}/g).join(':');
```
