### ISSUE TITLE
Offer: Brief documentation on how to use jsrsasign with Parse.com's Cloud Code servers?

### ISSUE THREAD

**Issue by adonoho** [kjur/jsrsasign#139]
Mr. Urushima,

I have successfully deployed a recent version of your jsrsasign, v5.0.2, to Parse.com's Cloud Code servers. While it wasn't difficult to do, once I understood all of the moving pieces, it was somewhat involved for this JavaScript noobie.

Why does one want to use jsrsasign on Parse.com? They are running a Node.js-like environment. Basically, it is a V8 JavaScript engine and parts of Node.js. They only partially implement the Node.js crypto libraries. I use jsrsasign to implement digital signatures.

In any event, if you wish to publish this kind of use of jsrsasign, I'm happy to write up what I did.

Anon,
Andrew

**Comment by kjur** [comment]
Thank you for your information :)
