### ISSUE TITLE
Error with NPM - Cannot resolve module

### ISSUE THREAD

**Issue by simkessy** [kjur/jsrsasign#143]
I've installed it through NPM. But when I try to load it through webpack I get: 

```
ERROR in ./~/jsrsasign/lib/jsrsasign.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\Administrator\Dropbox\projects\spDash\node_modules\jsrsasign\lib
 @ ./~/jsrsasign/lib/jsrsasign.js 294:32-45 294:131-144 294:219-232 294:296-309 294:377-390
```

So it's looking for require fs but I'm not sure why or how to fix this.

**Comment by svevang** [comment]
I'm running into this same bug trying to integrate this library into react native.

It looks like there some node specific code was added in 5.0.2:
https://github.com/kjur/jsrsasign/commit/7844c0edaa720c875789c6f354ee3d09603b96b1#diff-92d0e5376f9e604e03fac86fbb661950R9

Downgrading to 5.0.1 allows my project to build.

 For this to be a pure javascript library, any references to node specific modules should be removed. All these new bundler tools (webpack, react native bundler etc) introspect on the common js module hierarchy.

**Comment by simkessy** [comment]
I gave up on this library and just went with cryptico instead.  Thanks for looking into it.

**Comment by mprihoda** [comment]
You can [configure webpack to provide empty node modules](http://webpack.github.io/docs/configuration.html#node). The methods will not work, of course, but that's not something you want to use in the browser anyway.

```js
{
  node: {
    fs: "empty"
  }
}
```
