### ISSUE TITLE
erroneous DER Integer encoding 

### ISSUE THREAD

**Issue by franziskuskiefer** [kjur/jsrsasign#145]
The integer encoding algorithm is producing wrong results. The following example encodes 9223372036854775500 to 9223372036854776000 for example.

    var KJUR = require('jsrsasign');
    var seq = new KJUR.asn1.DERSequence({'array':[new KJUR.asn1.DERInteger({'int':9223372036854775500})]});
    var hDATA = seq.getEncodedHex(); // this is 300b02090080000000000000c0, which is 9223372036854776000

**Comment by kjur** [comment]
Numbers in JavaScript is represented by floating numbers and they can't be represented integers strictly. So large integers will not work properly. This is not bug of DERInteger class. That's limitation of JavaScript.

As for large integers you can use BigInteger class like this:

i = new KJUR.asn1.DERInteger({'bigint': new BigInteger('76287755398823936', 10)});
