### ISSUE TITLE
Remove nodejs dependency

### ISSUE THREAD

**Issue by sibelius** [kjur/jsrsasign#147]
It will make easy to use other js environments like react native

**Comment by marcusroberts** [comment]
:+1:

**Comment by marcusroberts** [comment]
The library works brilliantly in React Native so it would be great to see it work straight from npm.

**Comment by kjur** [comment]
I've released 6.0.0 today which is now Node.js and "fs" safe. Please check it.

**Comment by kjur** [comment]
I've released 6.0.0 today which is now Node.js and "fs" safe. Please check it.
