### ISSUE TITLE
Better structure for the project

### ISSUE THREAD

**Issue by sibelius** [kjur/jsrsasign#148]
This code is great, thanks

I think you should think in reorganize the code:
- keep only the latest version in the master (use branches or releases to make old versions available)
- store all minified version in only one folder, maybe /dist or just minify after npm install ([npm-scripts](https://docs.npmjs.com/misc/scripts) or bower install

**Comment by zboralski** [comment]
:+1:

**Comment by kjur** [comment]
Currently I've done as your request:
- keep the latest version of jsrsasign-latest-all-min.js
- store all minified version into "min" folder.
