### ISSUE TITLE
JWT verification: Issue at property issue

### ISSUE THREAD

**Issue by yaswant-dowlut** [kjur/jsrsasign#151]
The function KJUR.jws.JWS.verifyJWT performs several checks on the JWT token to ensure its validity. One of the check is to ensure that the timestamp present in the iat field of the payload occurs before the current time. However, this may cause problems in certain situations.

I was recently trying to verify a token from a server and the timestamp that it was including in its iat field was always one minute ahead of the current time (probably because of a slight time misconfiguration on the server's side). This always caused the token verification to fail until I try to manually verify it again one minute later.

Therefore, it might be a good idea to make this check slightly more forgiving by verifying if the iat time is within +/- 5 minutes from the current time or so. I might be able to make a pull request for this. However, I need to make sure it is a good idea by hearing your views first.

Here's the line of code which is making this check:
[https://github.com/kjur/jsrsasign/blob/master/jws-3.3.js#L646](https://github.com/kjur/jsrsasign/blob/master/jws-3.3.js#L646)

**Comment by kjur** [comment]
I don't think most of JWT libraries supports such grace period issue. However I may add it in the future version.

**Comment by cblair** [comment]
Working on a similar issue, how about providing the time as a parameter to the verify function? Then you don't have to rely on system time being right, you can just tell it about the time to check validity against.

**Comment by kjur** [comment]
Hello. Now jsrsasign 5.0.12 supports grace period in JWS.verifyJWT so that it can be accepted when there is time between JWT generator and verifier.
