### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by PatHat** [kjur/jsrsasign#153]
Hello.
I was looking for a sample JavaScript code to call a Google API using OAuth2 but from a server so it would be doing a 2-legged OAuth there is no user interaction, similar to what this document describes: https://developers.google.com/identity/protocols/OAuth2ServiceAccount

Can this lib support this? I think it can take care of the JWT token creating and signing which is one step of the OAuth flow.  Has anybody tried this and successfully called a protected Google API?

**Comment by PatHat** [comment]
Hello.
I tried the online JWT tool ( https://kjur.github.io/jsrsasign/tool_jwt.html) and successfully generated a JWT token, which I then tried to use to call order to request an access token from the Google OAuth 2.0 Authorization Server (https://www.googleapis.com/oauth2/v4/token), however the Google steps for JWT creation requires a claim called scope (A space-delimited list of the permissions that the application requests): Does the jsrsasign library support this claim?

**Comment by kjur** [comment]
You can find JWT generation tutorial.
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation
You can add any parameters such like scope like this:
http://stackoverflow.com/questions/11126439/google-oauth-2-0-jwt-token-request-for-service-application
oPayload.scope = "https://www.googleapis.com/auth/userinfo.email"

**Comment by PatHat** [comment]
I want to use your code to make my own version of your cool Online JWT tool: 
Do I need the jws-3.2.js file or can I ignore it because is it obsolete now? Also can you share the stylesheet.css? I hope to add the required scope claim so the new version of the tool can generate a JWT that Google can accept.

**Comment by kjur** [comment]
Off course you can use those codes because it's open source software.
jws-3.2.js is not necessary since jsrsasign-latest-*.js concludes new jws.js.
You can find JS and CSS codes used by tool_jwt.html from its code:
https://github.com/kjur/jsrsasign/blob/master/tool_jwt.html

**Comment by PatHat** [comment]
I do not see the stylesheet.css file anywhere. Nothing here /jsrsasign/stylesheets

Also, what is this tool version I see under mobile/tool_jwt.html?

Btw I was able to successfully use your tool to generate a JWT that Google accepted!

**Comment by kjur** [comment]
Did you see gh-pages branch?
https://github.com/kjur/jsrsasign/tree/gh-pages
I hope you can find them.
They are third party JSs and CSSs. So please care about their licenses.
