### ISSUE TITLE
error decoding JWT created by jsrsasign

### ISSUE THREAD

**Issue by gamedevhelper** [kjur/jsrsasign#154]
I am trying to parse a signed HS512 JWT created by this project using https://github.com/jwtk/jjwt (Java library).  Using the exact same key I can't parse JWT with Java lib because I get "JWT signature does not match locally computed signature".  I am confused because I though all JWT are interoperable between any computer languages as long as it follows https://tools.ietf.org/html/rfc7519

**Comment by kjur** [comment]
Sorry but I can't find its cause of issue. Could you point out them?

**Comment by kjur** [comment]
It seems no response. I'll close this ticket.
