### ISSUE TITLE
"bower install jsrsasign --save" is broken

### ISSUE THREAD

**Issue by ltrillaud** [kjur/jsrsasign#156]
HI
Thank you for your great library, but the bower installation is broken.
if you try this : 
`$ bower install jsrsasign --save`
`bower jsrsasign#* cached git://github.com/kjur/jsrsasign.git#5.0.5`
`bower jsrsasign#* validate 5.0.5 against git://github.com/kjur/jsrsasign.git#*`
 `bower kjur/jsrsasign#~5.0.5 install kjur/jsrsasign#5.0.5`

I retrieved the download in : 
`bower_components/kjur/jsrsasign`.
All the other components doesn't use their git namespace.
It should be : `bower_components/jsrsasign`

But worse, the bower.json is broken with this line added : 
`"kjur/jsrsasign": "jsrsasign#~5.0.5"`
It should be : 
`"jsrsasign": "~5.0.5"`

From the Bower doc : 

> 
Bower doesn’t support GitHub-style namespacing (org/repo), 
however you are encouraged to namespace related packages 
with -, for example, angular- and paper-.

For exemple : `"kjur-jsrsasign": "~5.0.5"`

For reference, you can see this original issue in the bower repository : 
[bower/bower/issues/2179](https://github.com/bower/bower/issues/2179)

Thanks

Laurent

**Comment by kjur** [comment]
@ltrillaud Thank you for letting me know. I'll fix it this week end.

**Comment by ltrillaud** [comment]
Thank you for your quick answer.

**Comment by kjur** [comment]
I've fixed in the latest version. Thanks.
