### ISSUE TITLE
KJUR.asn1.csr.CSRUtil.newCSRPEM fails with Uncaught TypeError: KJUR.asn1.ASN1Util.newObject is not a function

### ISSUE THREAD

**Issue by marcusroberts** [kjur/jsrsasign#157]
I've reduced by test case to the following code - I can happily generate key pairs, convert them to PEM, read the back as keys, so believe most functions are working, but I'm not able to generate a CSR with the following code in Chrome for Mac or Safari for Mac:

  var kp = JSRSA.KEYUTIL.generateKeypair("RSA", 1024);

  var device_csr = KJUR.asn1.csr.CSRUtil.newCSRPEM({
    subject: {str: '/C=GB/ST=England/L=London/O=Test/CN=browser1'},
    sbjpubkey: kp.pubKeyObj,
    sigalg: "SHA256withRSA",
    sbjprvkey: kp.prvKeyObj
  });

Uncaught TypeError: KJUR.asn1.ASN1Util.newObject is not a function
_setRSAKey @ index.js:30117
KJUR.asn1.x509.SubjectPublicKeyInfo @ index.js:30117
setSubjectPublicKeyByGetKey @ index.js:30129
KJUR.asn1.csr.CSRUtil.newCSRPEM @ index.js:30129

**Comment by kjur** [comment]
Thank you for your report. Hmm..., I've confirmed the following code works properly. 

<html>
<head>
<script language="JavaScript" type="text/javascript" src="https://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js"></script>
</head>
<body>
<script>
function aaa() {
  var kp = KEYUTIL.generateKeypair("RSA", 1024);
  var csrPEM = KJUR.asn1.csr.CSRUtil.newCSRPEM({
    subject: {str: '/C=GB/ST=England/L=London/O=Test/CN=browser1'},
    sbjpubkey: kp.pubKeyObj,
    sigalg: "SHA256withRSA",
    sbjprvkey: kp.prvKeyObj
  });
  alert(csrPEM);
}
</script>
<button onclick="aaa();">aaa</button>
</body>
</html>

**Comment by kjur** [comment]
Thank you for your report. Hmm..., I've confirmed the following code works properly. 

    <html>
    <head>
    <script language="JavaScript" type="text/javascript" src="https://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js"></script>
    </head>
    <body>
    <script>
    function aaa() {
      var kp = KEYUTIL.generateKeypair("RSA", 1024);
      var csrPEM = KJUR.asn1.csr.CSRUtil.newCSRPEM({
        subject: {str: '/C=GB/ST=England/L=London/O=Test/CN=browser1'},
        sbjpubkey: kp.pubKeyObj,
        sigalg: "SHA256withRSA",
        sbjprvkey: kp.prvKeyObj
      });
      alert(csrPEM);
    }
    </script>
    <button onclick="aaa();">aaa</button>
    </body>
    </html>

**Comment by marcusroberts** [comment]
Your test code works for me too.  I'm using the npm version in a ReactJS app, so suspect webpack or some other part of the transformation is to blame.  I'll let you know what I find.

**Comment by marcusroberts** [comment]
Your test page works for me too.  

I'm using the code in a React app, with the library loaded via npm, from my packages

"jsrsasign": "^5.0.2"

I'll dig in

**Comment by marcusroberts** [comment]
Sorry, the problem was my own fault - there was a name conflict with another library using the KJUR.asn1 library, removing that library resolved the issue.

**Comment by kjur** [comment]
Thank you for letting me know. I'm grad to hear that.
