### ISSUE TITLE
JWT token created in jsrasign does not verify on jwt.io

### ISSUE THREAD

**Issue by Deracination** [kjur/jsrsasign#158]
A token created using the example in "Tutorial-for-JWT-generation" fails with an 'invalid signature' when verified on https://jwt.io/

**Comment by kjur** [comment]
Following code generates HS256 JWT with password "aaa" (i.e. 0x616161).

    var sJWT = KJUR.jws.JWS.sign("HS256", sHeader, sPayload, "616161");

So type "aaa" at "VERIFY SIGNATURE" text field of https://jwt.io/ site. This will work.

**Comment by Deracination** [comment]
Sorry, I missed the earlier closed issue on exactly this topic

**Comment by kjur** [comment]
No problem. I've added some note for jwt.io site.

https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation
