### ISSUE TITLE
Non minified version of jsrsasign

### ISSUE THREAD

**Issue by zboralski** [kjur/jsrsasign#159]
Would it be possible to distribute a non-minified version jsrsasign ? If we include any minified libraries inside a chrome extension it gets rejected by default. Thanks

**Comment by kjur** [comment]
You can generate non minified version of library just concatinating all *.js and ext/*.js files.

**Comment by sebadoom** [comment]
@kjur That won't work, there is a certain order to the libraries. I just tried doing what you said and I get undefined symbols (which are defined later on). I wonder how the Makefile actually works.
