### ISSUE TITLE
Demo CSR generation tool broken

### ISSUE THREAD

**Issue by RavenousWolf** [kjur/jsrsasign#161]
The CSR demonstration tool creates a CSR which doesn't include the subject. The tool is located here: http://kjur.github.io/jsrsasign/tool_csr.html.

Line 40:
 ` "subject": subject,`

Should be:
` "subject": {"str" : subject},`

**Comment by kjur** [comment]
Thank you for letting me know. I'll fix it later.

**Comment by kjur** [comment]
I've fixed it in the latest version. Thanks.
