### ISSUE TITLE
malformed plain PKCS8 private key(code:001)

### ISSUE THREAD

**Issue by kyokku** [kjur/jsrsasign#162]
Hello,
I'm generating encrypted PKCS8 and CSR based on the example [http://kjur.github.io/jsrsasign/tool_csr.html](url) then trying to decrypt it using PKCS5PKEY.getKeyFromEncryptedPKCS8PEM but it throws:
> 
malformed plain PKCS8 private key(code:001)
>

```javascript
function getKey() {
	var f1 = document.form1;
	var subject = f1.subject.value;
	  try {
		var kp = KEYUTIL.generateKeypair("RSA", 2048);
		var pem = KJUR.asn1.csr.CSRUtil.newCSRPEM({
				  "subject": subject,
				  "sbjpubkey": kp.pubKeyObj,
				  "sigalg": "SHA1withRSA",
				  "sbjprvkey": kp.prvKeyObj
				});
		var passw = "12345678a";
		var pkpem = KEYUTIL.getPEM(kp.prvKeyObj, "PKCS8PRV",passw);
                
                //next line fails with malformed plain PKCS8 private key(code:001) :(
		var key = PKCS5PKEY.getKeyFromEncryptedPKCS8PEM(pkpem, passw);
		alert("Type:"+key.type+" - isPrivate:"+key.isPrivate);
	  } catch (ex) {
		alert("Failed: " + ex);
	 }
}
```

What  I'm doing wrong? 
Thanks in advanced.

**Comment by kjur** [comment]
Thank you for letting me know. I've reproduced the issue. I'll investigate it.

**Comment by kjur** [comment]
It was a bug because of wrong ordering of CryptoJS files in jsrsasign-latest-all-min.js. I've released fixed release. Thanks.
