### ISSUE TITLE
sample-rsasign.html - key is too short for SigAlg

### ISSUE THREAD

**Issue by balamkumar** [kjur/jsrsasign#164]
I am trying to test reassign with my own RSA 2048 key, but getting below error. Its working with 1024 key, is that mean demo site does not support 2048 key size?

http://kjur.github.io/jsrsasign/sample-rsasign.html
Uncaught key is too short for SigAlg: keylen=99,sha256

**Comment by kjur** [comment]
Hi @balamkumar , I've confirmed that it works with my RSA 2048bit PKCS#1 private key. As error message, private key seems wrong.

**Comment by balamkumar** [comment]
@kjur Thanks for your reply. You are right, I can sign with new openssl private key 2048. But in my application, I am generating RSA key with following Java code, and I can to do cipher and decipher the message successfully with crypto-js, when i use jsrsasign for signing the message, getting above error. Is there anything not compatible in my code for jsrsasign?

_java.security.KeyPairGenerator generator=KeyPairGenerator.getInstance("RSA", "SunRsaSign");
java.security.spec.RSAKeyGenParameterSpec spec=new RSAKeyGenParameterSpec(2048, RSAKeyGenParameterSpec.F4);
generator.initialize(spec);
KeyPair kp = generator.generateKeyPair();
return getPrivateKeyBase64(kp.getPrivate());_

**Sample Private Key**
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCayJUnBZXsJzytlpfUoRxSbYdHGBojtigJz+2usMOaXuWIVxrs9JyLWybgeACnZ1IS+OzzSmCTyy3jnT9QIoMhXdcKf+WTn6EthlbSTXDObiHazH8OZm4WOf+zxSKo7a3bJRnFg9dJhgED5iEARvHs7PjqdPLRLeKtzk/RoG6Qwvgb5Lj5QSUfN51HHtsZSMi+vtxWJ9OiwFFxNUykoPQp/QT0CbKu+Ry5GaiSNnz9a0wPEaPE2VjPn+KHSD9IwOdLlm36rdcNTxG4ZBi+LNrmU+kprWsTBelfR6HNEjclDaVq3IkUgJR7J/V4H3oSqdEe/Txhh+Qc9IxlCNEGmB+1AgMBAAECggEAIPczfRodcixxKe926txdcdjOBQBHIO/82woj7x7Kqign7r/OhkUayjthrlEgoobI3i2SGcbvhsqxPVcSUvjmwMaBtETFGonXBCEmgKfprK2cHEONk/2Q2L8FjL4hwaTNcG0Ybg7EXW5i7Peoc6yoffOCmDzMMmz5aFcWfOkUY1QrnxwQWZtnz+poIF5KDXeUVGp9VTO9ybGCRL+BD2To4sTW/YadOxaRwx2CVRjIATGtUrbu9zLldQ/U7KccLQ6VjOH976jhrugZXFjGQINdQ9roR3Geqim/VbAcY/KKkvTvutzBng2jcyd8+vEvniaJPzlUSf6CNRoblsDLjkYxAQKBgQD/ZsY/1dahBKh1tJLOplSvdyk0sKhjaJC2glhf1U+GF4RbcffuxFYH6AACQSv5MTm7fE4GjXJRxlHdDlYELHX2Ku2vJSPQ+PPSvzRwZ1nyLB+kb5bFE3jLO0R5ClB7W6ndKh9NBiIK2E1MnWGDgKYm2LmnNkugSRJBUSDfjYJJ4QKBgQCbJXGHq5UKXtHEceSXCT6HeIoRcQYKjn4teIhgtPHVOfIVDSw8Rh/RxNNEn2ixUd3igzTbDxeQOc+LPasXH3hXqX1MsBKHDjKr31wkJvYp/34ITltZ0Jdl053hV0NR0rdBtXzGxUbZu+PwAjVQfSPFwNfI5vThDTYZB0fSrXiYVQKBgGyKdP50Fn7fx+geEbYZIixf6/ckjKuSqM2nn3863E0UeX+Tc9bZQeaiRj6vC80finWPYmmOe2MdcXUMvqmPa6JupAynMA2Df7u03shWY/dzoQ71DZI7sD5Otc7q/0Ett4bye9L0JEuPmWpSCDsm1XX07RGPFZzM8SEpJVtcfF6BAoGAc6D4eDD9J3l7xXlM8PRG0hiYbl9aLUv95k3K9qhlBJHnRqFGsrVgyapz+tUD5gQp5sP7BLi+yxMLB6+yb81Yl50OcbVYWafPRCF4Psl69dohSHd9xfacn5uUM3oiBj2Rrztf/5TQNT6/pwU+Tvq1SpFrQaRAJer+wrCWawI2uvECgYBOGS0aYwpI8xNQIZGk+dYdx4Iu1Meph/XkJn62yYz1yWdLpm62Ic7DWSjiH9Yv4bFXkXp93e5/83U/NgYxtHgrzub7XyiLWgmNsFqqtBe1mTPCa5A+xEN81JZmmEPw4crtc9mDD3rtWj4NJeE4uLzfBKHVA6cRtSNK5DR2QZWiWg==

**Comment by kjur** [comment]
Hi. Your key is PKCS#8 private but:

- plain private key not encrypted key
- missing PEM header (like "----- BEIGN PRIVATE KEY ------")

Sorry but sample-rsasign.html only supports encrypted private key.

**Comment by balamkumar** [comment]
Thanks. Is there any sample to use my plain PKCS#8 key and sign the message?

**Comment by enthudrives** [comment]
@kjur I'm facing the same issue as @balamkumar . Is there a way to sign my PKCS#8 key? 
I tried something like this: 
```
var key = KEYUTIL.getKeyFromPlainPrivatePKCS8PEM(key);
var signature = key.signStringWithSHA1(str);
```
Doesn't seem to return the expected value

**Comment by kjur** [comment]
Hello @enthudrives , Please try following:

    var prvKeyObj = KEYUTIL.getKey(__PLAINPKCS8PEM__);
    var sig = new KJUR.crypto.Signature({"alg": "SHA1withRSA"});
    sig.init(prvKeyObj);
    sig.updateString('aaa');
    var hSigVal = sig.sign();

**Comment by balamkumar** [comment]
@kjur Thanks, it works. but the Signature length is always 512. May I know why?

**Comment by kjur** [comment]
It seems that there is no further question. I'll close this ticket.
