### ISSUE TITLE
KJUR.crypto.Signature memory leak

### ISSUE THREAD

**Issue by cblair** [kjur/jsrsasign#165]
Possible memory leak:

![image](https://cloud.githubusercontent.com/assets/464451/14084027/a71da492-f4cd-11e5-8d7c-2f7a14f20f95.png)

I'm using the methods from http://www.nearform.com/nodecrunch/self-detect-memory-leak-node/. Somewhere in my project I have a memory leak, and so far this is the only thing being reported (quite a lot).

Caveats -
- memwatch can be fooled by sudden huge memory spikes. I don't think that's the case here, but could be a possibility.

**Comment by Ruffio** [comment]
@cblair can you pinpoint it a little bit further where the memory leak is? 
Perhaps come up with a sample code that can demonstrate the memory leak?

**Comment by Ruffio** [comment]
@kjur this issue should be closed due to lack of response from originator. The issue was created on the 28th of May 2016 and there have been no responses since...

**Comment by cblair** [comment]
@Ruffio sorry no new information for this, I don't have code now that will expose this. Agree to close, reopen if issue is seen in the future.
