### ISSUE TITLE
unsupported public key alg: ecdsa

### ISSUE THREAD

**Issue by apowers313** [kjur/jsrsasign#167]
I'm trying to verify a signature of a base64url encoded string. My code is:

``` js
console.log ("Expected signature (base64url):", sigRef);
var hexSig = rs.b64utohex(sigRef);
var sig = new KJUR.crypto.Signature({"alg": "SHA256withECDSA", "prov": "cryptojs/jsrsa"});
// initialize for signature validation
console.log ("Cert:\n" + certChain[0]);
sig.initVerifyByCertificatePEM(certChain[0]); // signer's certificate
// update data
console.log("Body:\n" + body);
sig.updateString(body);
// verify signature
console.log ("hexSig:\n" + hexSig);
var isValid = sig.verify(hexSig);
```

And the output complains that ECDSA isn't supported... which seems odd since that is [contrary to the documentation](http://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Signature.html#constructor). Is this a bug? Or am I misunderstanding how verify() should work?

Output:
> Expected signature (base64url): uyjDJpNJoKN9C2hq8I-wgUxkduwAWXQQC9uqkTuGzNk=
Cert:
-----BEGIN CERTIFICATE-----
MIICnTCCAkOgAwIBAgIORvCM1auU6FYVXUebJHcwCgYIKoZIzj0EAwIwUzELMAkG
A1UEBhMCVVMxFjAUBgNVBAoTDUZJRE8gQWxsaWFuY2UxHTAbBgNVBAsTFE1ldGFk
YXRhIFRPQyBTaWduaW5nMQ0wCwYDVQQDEwRDQS0xMB4XDTE1MDgxOTAwMDAwMFoX
DTE4MDgxOTAwMDAwMFowZDELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUZJRE8gQWxs
aWFuY2UxHTAbBgNVBAsTFE1ldGFkYXRhIFRPQyBTaWduaW5nMR4wHAYDVQQDExVN
ZXRhZGF0YSBUT0MgU2lnbmVyIDMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASK
X+p3W2j1GV4lQwn7HXNj4lh9e2wAa6J9tBIQhbQTkqMvNZGnHxOn7yTZ3NpYO5ZG
Vgr/XC66qli7BWA8jgTfo4HpMIHmMA4GA1UdDwEB/wQEAwIGwDAMBgNVHRMBAf8E
AjAAMB0GA1UdDgQWBBRckNF+zzxMuLvm+qRjLeJQf0DwyzAfBgNVHSMEGDAWgBRp
EV4taWSFnZa41v9czb88dc9MGDA1BgNVHR8ELjAsMCqgKKAmhiRodHRwOi8vbWRz
LmZpZG9hbGxpYW5jZS5vcmcvQ0EtMS5jcmwwTwYDVR0gBEgwRjBEBgsrBgEEAYLl
HAEDATA1MDMGCCsGAQUFBwIBFidodHRwczovL21kcy5maWRvYWxsaWFuY2Uub3Jn
L3JlcG9zaXRvcnkwCgYIKoZIzj0EAwIDSAAwRQIhALLbYjBrbhPkwrn3mQjCERIw
kMNNT/lfkpNXH+4zjUXEAiBas2lP6jp44Bh4X+tBXqY7y61ijGRIZCaAF1KIlgub
0g==
-----END CERTIFICATE-----
Body:
ew0KICAiYWFpZCI6ICIwMDE2IzAwMDEiLA0KICAiYXR0ZXN0YXRpb25Sb290Q2VydGlmaWNhdGVzIjogWw0KICAgIA0KICBdLA0KICAiZGVzY3JpcHRpb24iOiAiVHJ1bHlTZWN1cmUgRmFjZSBvciBWb2ljZSIsDQogICJhdXRoZW50aWNhdG9yVmVyc2lvbiI6IDEsDQogICJ1c2VyVmVyaWZpY2F0aW9uRGV0YWlscyI6IFsNCiAgICBbDQogICAgICB7DQogICAgICAgICJ1c2VyVmVyaWZpY2F0aW9uIjogOA0KICAgICAgfQ0KICAgIF0sDQogICAgWw0KICAgICAgew0KICAgICAgICAidXNlclZlcmlmaWNhdGlvbiI6IDE2DQogICAgICB9DQogICAgXQ0KICBdLA0KICAiYXR0YWNobWVudEhpbnQiOiAxLA0KICAia2V5UHJvdGVjdGlvbiI6IDEsDQogICJtYXRjaGVyUHJvdGVjdGlvbiI6IDEsDQogICJ0Y0Rpc3BsYXkiOiAxLA0KICAidGNEaXNwbGF5Q29udGVudFR5cGUiOiAidGV4dC9wbGFpbiIsDQogICJpc1NlY29uZEZhY3Rvck9ubHkiOiBmYWxzZSwNCiAgImljb24iOiAiZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFHQUFBQUJnQ0FZQUFBRGltSGM0QUFBWXVFbEVRVlI0WHUxZENWaFRWOXArYjI1V0lJU3dCaEFCVVFRQndYMUhzSlZ1dHAxYXg2N1lzZHFaMXBsYXUycGJhMUg3YTdYVDNiRWRxL08zdFoyeHRMYlRwNHJXWFZ3cmFOMUFjRVZsQzN0WWtwRGszdk0vNXlTeG9DS0wydmhyN3ZQdzhJU2NjODg1Ny90dDV6dmZ2WEJ3WHk1RmdIUHA2TzdCNFNiQXhVTGdKc0JOZ0lzUmNQSHdiZzF3RStCaUJGdzh2RnNEM0FTNEdBRVhEKy9XQURjQkxrYkF4Y083TmNCTmdJc1JjUEh3N1dvQUlVUUN1Rk1XWGVTSmNCd25YcWx2bXdRUVFuamFrZU00b1l1RHU3c0JhQS9IeXhKQUNKRnlIR2VqQ0JKQ1pBQ0NBTWpwUnplcUhVS0E0bW9Cb09jNHp1ckE4UUttTGU5d0NRR1VNU3IxaEJBdGdCa0F4Z0VJYTBGQXUyYXJRMU84ZVJ0UklhVVlOUU1vQnZBVGdBODVqcXQxWXRzbUFVN0pKNFQwQWJBYVFBd2hoR3JCelF2WGRWd1p4M0hVaEZQOENwcWFtaWFvMWVxOGx0YUZtWGpuK0JkSi9tNEt2aWlLVkkxb0crZlBkWnp1VFhkcktyWHNoK000dWRGb0xDd29LQmc1Y09EQXFwYWFjQWtCZ2lETWswZ2tiempBbHdLZ1VaRDc2am9Db2tRaXNabk5abmw1ZWZuaXlNakltWmNRUUVOTkdpN2w1ZVhKWTJKaTluSWMxMDhVUlJ2SGNaUUF0LzNwT3ZoT0swTURHbWxwYWVtUitmUG5EMTIyYkpuUmlUblRBQ2NqQlFVRmtkSFIwZnNJSWY0QVdLZkxFT0Iyd2xjbTVHS0JwWGpaSkJLSlZLL1hWMjNZc0NGNTBxUkp4NXlZdHlSQTNMZHZYNStCQXdmdUpvUjRBNkR4UDkwTE9MMTZ5OTlYSnhQWHNmY2w2dXFjOWUrM202U1lYb3laSUpGSStJcUtpb1kxYTlhTW1USmx5bjZIQmdndENTQWJOMjZNR3pObXpFNEFGeE53eGREMU91TFpxVnZUVlpmV1c3R3pwQUVsalRUOEpnaFFTVEVneUF0UldnWGtVcnZ5WG1jVnZwd0dNQUwwZW4xRFptYm03ZE9uVDg4bGhQcG1yaFVCV0xkdVhWeGFXaG9sUUgwRkRlZ1VLTDlIWXhvbDE1a0ZaSjJweFpJRDFUaFUzb1JtcXdDT0E2UThoeEJ2QlVhRWVDRWh5QVBKSVo1SURGUkJLZWV2SnhHWDFRQzlYdCtZbVprNWR2cjA2VGswdEw4cENLQXJOVmxGL1BOd05kN0lMb2JaN0lpY0pSTDRlc29SNWlVRkwrRlEwbVJEVlpNTkdxVVU5L2RVWS9xQUFNUUhlRjR2aldpVGdGV3JWdDArWThZTXFnRTNEd0hmSDYvRHRJM25VRjF2QWdHSFVHOEZwdlVQeE9CZ0R3UXJlSEFpZ1FFY0RsU2FrRlBhaEMxbkd4RG1vOERjWVFFWUhxYUJncGRjYTIyNGRRaW9ORnJ4ek1aaS9MZWdHa1FRb0ZNcnNUZzFGQS8yOW9WQ0ttbHQ4QWxRYjdZaXI3UUpYNStxUjNhWkVVOG4rT0tSM2xwb1BXWFhrb1JiZ3dDNnlyV242akE1Nnl4cUc4MDBkWXRuQitxd0lLVWJsTkxMUzdVenExSnJzbUh0NlRxc0xEQ2dtNWNVTXdjSElscXJZbjdqR2x5M0RnR3ZaNWRnOFo1eVFMUkJycERqKzNzaWtSYnRBMGs3UUZJaVJFSlFXRzFFNW9sNm5HcXdZV2FpTCtKMG50ZENFMjUrQXB5eDN1aC9GMkQzdVhvV1hQNGhSb3ZQeG9aQjY2bm9zQkJUSXN3MkVRZktHNUZkYWtTNFJvNzdvalR3bEYxVmxIUUxFRUFBaXlBaWRPa1IxRFdaQVFtUEQ5TEM4TmVrb0M2WkVZcVl2c0dDTHdwcW9aSko4SENVQmdGZThpN2RxNjJOR0ExRGI1b29pRXB1cWNHSWlIOGVBMFFCSGlvNXZyMHZBbU1qZmJvS0d1ZzlHNjBDMXAycXc4bGFFeDdzNllQb1FLK3VtS1JiUUFNQW5LNXJSdTlsZVlCZ1JhUy9KNzY3S3hpSjNmdzZiSDR1MTVBaUp3Z2lmcTB3NHVlejlaZ1lyVVV2WDFWblNiZzFDTmhmM29TaFh4WXdEVWp1cnNhS3REQkUrSGwxV1FNdW5JMndEQ1dRWDJYRTBXb1QwaUo5NEVQM0V4Mm45aFlnZ0FEZkhhL0J3OStmQWlmaDhGQ01GaCtuZFlkV2RlM2llWXJpeVNvVGlwdHNTTko1ZElhRVc0QUFBSjhjcXNTeldXZkE4VHhlSEJTRWVhTkNJRzhqL3UrNDhMWnV5Uko4RFJiVW1Hd0k4cExEWDhWRDB2NW00ZVluZ01MMFRxNGVzellVZ1pQSzhPSHRvWGltbnowQzZvU3A2QkF2RkUyclFGQnJzc0pESVlXWHJOM1V4YzFOZ0hNUHNIQ2ZIbk0ybndWNEdaYVBDOGNUZlh5dlYzS04zVmNVN1VUSXBheGU2a3JrM1JvRS9MdWdGcXNPVllCd0VydzBWSWVVN2pTTGZrTmMxNGNBQW5Dc1JNVnhlMVoyY1lYMXNwSVd4L2VzcktKOTI4bGEyNGNnN2RwYVE1TVpCcHA5SmdRK0tpbThWYlNHN1BJWFRUdTB2T2pNT3ppZHJqQjY3UW1nbUJDUmNDYXpGVGFCUUttUVFpNnpsNDIyWE1odjZ5UXdOOXRnc2dpUVNUbDRLR1NRU0NSWFhMU3pyMDBRWUc0V29GTHc0SG4ra2o3T2RvSW9vdEZrWmNUU0F4YnFnTnVhajgwbXdOaHNZL2tmaFpSbjg3Zlg3VndaWC90WUxIZC9vYUh6YnhlUGRTR01KYlFVaGNtbWt3am5pVmpuZDhLQ0lKTENrOVhjN2dNbHBMcW1rYXVwTmNGcUUrR2xrc1BUUzRHd0VEV1NoNFNqV3dnOXhRU3FhNXV3NzBnNVRwNnNSbWxaQTZvTlpuaW9aQWdMOFVhd3Z5ZHVUKzZCUU1kQnlQNkRSZGk0c3hTMGVuVkFmQkI2UldpUnZhOFk1NHJyVUZ0dmhxOUdoWmpvQUtTTUNJVy9SczNBYW02MkllKzRIZ2Z6cXFDdmJrUkZaUU1JNGFEeGtzTmJyY0RRZmtFWU9pZ1NFczVlVFZOV1ljQ1czV2R4NG1RTmFneG0yQVFSYWc4NUlydjdZRWhTR09KaS9DR1hzekpZYk5oMkR2dVBub2RJT053K0lneDk0M1RZblhzV2gvT3JvRkxLY0ZkcU5QSlA2SEhvV0FXcjFSbVkwQjJqaDRlQXArY0pIUFVSQkR2M2xtSFhnU0pDanh3VFlnTEkzV042Y2p3djZSb0JoSURmblhPZUxQcGtEMWRWWXlTRUk1eEtMbU9TYnpUWllCTkZLR1E4NXI2WWpGRkR3bEd1cjhHS1ZYbll1T3NzckJZYi9IeFVVSHZKb2E5cWdza2hxWTg5RUllL3BBOWcycEMxcVJBTGwrNkJLQkQwQ05ld2hSY1ZVMEFGY0ZSNENDQ1R5VERsb1VROC9FQWMxVFY4bjNVTVg2NCtpbHFEQ1lRajBIZ3FtTGxxTWdtZ0duRnZhaFJlZW1ZWXBGSWVaODdXNHVQUGM1QnpxSXhWOTBsbFBLUVNDY3dXS3lqcnZqNGVtRFFoSHZlbDlZSmNJY05ISy9ZaDg2ZDgyRVNDZTIrTFFxQ3ZGNzVaY3d3bXN3WEJnV3E4OVVvS2lzN1Y0dTJsZTVnUUR1cXJ3K3pwSXhFUVlQYzkxYlZHdlBQSkxpcEVoQVpqejZRUElJOC8ySmNxVCtjSklJU3VSK1RmVy9ZTCtXRjlBYlg5WkhCaUNIZjNtQ2hvTlVvVWx6WGdjRjQ1Y281V1lPYTBvUmcyb0R0V2ZuY1lYM3gzR0JhcmdMNnhBWmo2U0NMOHRGN0lQVmlDTDFZZlFXMmRDVkhoV3J6OTJoaUU2THlSdGVrNFd3emQrbE9GRFEvVklEckNsK250Z2J3eVZOZWFtRWtabkJpTVdjK09nc1ZpeGN3RlczQ3VoR1kvQ1lZUDZJYUh4c1d5eUtTa3ZCNEhqK3FoMGFqdzNKVEJzRm9GTFB0cVAxYXZPODdBSHpXa08xS0doek4vY2I2c0FhdCt6R01tTWpqQUV5OC9QUlNEK29maG8rVy80TnUxeHlBU0VUSXBEMWFaN3pBaVFRRmVtUGZpS0dqVWNzeGNzQmxuenRYQnkxT0J0MTRlalVIOVFoa0JldytjeC93UGQxSGhJRXFGakZ2NDhuQXlaR0JVMXdnUUNSRk1aaXMvWi9GMnN1ZkFlWHFDVDU1OVlnQTNmbHljWGVVQTFCbk1PRlJRam02QjNsQ3FaSGg5OFZhY1BGTU5tVXlLVjU0ZWlqdFRlekxiYVRSWjhQNnlYN0J1MjJsMlNQN204Nk53MjZnZVdMdnhOdzBZMERjWXo2UW5JamhJQS9BU3JGNTdEQ3YrZlFnY1JIUUw4Y0hpMTFJWUljL1AzUVRxSTNpSkJDLy9aUWpHcGNVNEhEZEJWVTBUOUpWTmlPMFZnTUxUMVpqenpuYVVWelRBUjZQQ3dwbXA2QnRIaTd5QkpxTVY4ei9ZamgyL25BZkg4WGhzZkR5ZWVqUUovL2dpbDJrQUpTRFEzd1BEazhJUUZla0xoWUlIRVFtRzlnK0R2NThIM3Y5c0w5TkVjRHdtUFJpUHlRLzFaWmo4YTlWQmZQSHRFVW80Nlo4UXhNMlpNWm9FK0h0Mm5ZQm1xOEMvK2U0T3NuUHZHWTRHTkQzQ2ZiamgvY01RMjlNUEVXRmFOaGxQRHhwNWNNZzVVSXBaaXpmRFlySEJVNlhBeFB0aUVhcXord1dhS3RpMnN3alpPZWZZNTJtVEJpTDl3WVRmQ0JDQlI4YkhZMXI2QU1kR2lzT1dQV2Z4eHVLdExQZ09DdkRHZ2xkR3dXSVRNV1B1UmpTYmJVd3dZNkw4a0RhNkIzcUUrVUFYNU1tMHpUNGY0SWQxQlhoLytUNElnb0RFUGpvc25Ea0dHbzJTM1o4NjBjKyszby8velR6RUJHUkFnZzV6bmsvRzE5OGZSZWFhZkFnRWVHSjhISjZZbU1UOGw2UEE5b0lqWHZYalVYejRyeHltSGZHOUEvREdjeVBoNVNGSHhydmJrWE9rbkk1Qm5ub2trWnYweHlUQzA0b0FkTkVFRVlEL2JOVkI4c1dxZ3h3VkFSb0xVT2VtVUVpZ0MvQkNURTgvM0pVU2hhU0VZT3pZZXc2ei83NFZSQlNacmVicGdRYjMyNDZSU2kwRmcvN3R5WWxKZU9xeGZxMEllR0pDSXFZK21nU0p4QjZaYk50OUJyUGYyUTZSRWFER29sa3AwSGdyOGVaN08zRDRtSjZoU0VuZ0pUeFVLaWwwL2g2SWl3N0Vvdy8wUVZpb2xrbmppbFVIQVNMaWp1UWVlTzI1VWN3dk9BbFl2U1lmN3kzUFlmNm1aNFF2NXI0MEdqK3VMM1NZSUE1VEo4YmpzUWxKVU1oNU5pZEttcjB2d2I1RHhaajlkamFhVE0xUUtlVjQ5YS9ERUJyc2plbHpOcURSMkV5eElmTmVHczNGOXc1eVJrT2Q5d0hPdWlCRGc1bHMybjZLMjdIdkhEbDUxc0RWMVpzaGlDd29aV1pJSnBmaitTa0RvUFZSNGRXM3Q3Sy9lM3JKOGNpNFdPZ0MxU3pzbytwTHU5RHY2Ty9ZWGpyRTlOSzJJbUR5aEg1NDh0RytiTEZVdExJMjVHTEJKMGZaZ25VQjNzd0U5WWp3UTJWVlBUYnRPSXM5KzB0d3VyZ09kWVptR2g5ZmlQbjZ4ZW13WUZZS1ZtY2R4NHBWdjdKNzNablNBNi8rclRVQm1Xdnk4T0h5M0FzRXpIdHBOUDdySUlCR1ZVOU9qTU9raWYwZ2w5Rnd0WFdvYWpaYm1VbjlhZk5KdHFZeHc4SVJvdlBDVi8vTlp3My8vR2dpZWZ6QlJJNlhTcGd6N3BJRzBFNDJtOEFiVFJiaW9WSndsZFZOcEtLeWtUdFhZc0RKb2pyOHRPVTRqQ1lySkJ5UEIrL3NoWlJoNFhqeHJjM01BU3NWY3N4OVlSUkdEdWwrVWZ4TVlMT0pMT3lVeTNoa09YMkFDRnhNd05xZjg3SHcwMzBPQXRSWS9Ob1lCQVI2Z0NPQVNxbUF2c0tNaXFvNm5ENWZqL3pDQ216ZVd3UkxzeFZhalNmZWVUMEZKODdVNGIzUDlzRW0ySkRZSndqL00yc010TjRxQjVJRXk3NDZnTSsvcFQ2R3crQ2tZTXlla1l5dnZqL0NmQUFsWVBLRU9QenA0ZjZRTVUxdVRRRFZoazNaSi9IMjByMHdtU3p3MFNpaFVrcFJxbTlFU0pBYTgxNU1KbjE2QnpITDVTakU2N3dHMENpb3JzN01yOTFjUUpMaWc3bGVrWDVFem1yN0NHcnFUSGh0d1NZY0txeGtKbVhDbmRGNCtBL3hlSDNSTnViODZIWGI4QWo4ZGZKQUJBZlovUUNWNU1iR1ptemJjd2JCZ2Q0WW1CUjZCUTBBMXF3L2pvV2Y3bUlTekRUZzlWVFVOMWlRYzdBRUtjTWlFUm1oaFl4dHZBakt5aHZ4NnFMTk9INjZCbHFOQ2d0bXBrQWhsMkxPdTlrb0xqTXcwelZueGtqbVJDa3E5UTBtelA5Z0ozYm4ycDN3MUlmamtmN0hmbGp5ZVk2ZEFFand4UGhZUFBuSWdEWUpvRkhYd285MjRrQ2VubWFKN0w2TzQzSHZiYjN3N0pSQnhOTkRmblVFaUNJUnFtdk0vT3gzTmhPVDBjSWxENDBrL3I0cWp0cmJraklEVm1jVnNvME5WZEhucHc3Q3VMSFJMTFJiOGMxaE5OUHFOQTRZMWk4VWlmRTYwTDBEamRGUEZkVmdSODU1dlBEVUVLU2w5R1FFc0REMEVnMEFmbHAvSElzKzNjVmlmR3JLRnIyYWlsSjlFMll2M29iZVVUNFlQVFFDR3JVQ01wa0VKV1dOeUZ4ekRBM0dadlNMRGNLOGwxUGg2U25IOHYvOGltOStPZ1pSc0tGUHJ3Q01IaFlPVDVVTUo4N1dZUDJXVTJpMkNBanZwc0hNYWNPUUVLdTdFSVpTQWlZOUVJTXBqdzVza3dBYU9uKzNKaDhmZjc0Zm9taGptcVJTeWZINnN5T1FPaUx5Nm5mQ2pJQmFNLy9HTzV2Sm9XT1ZIRWM0SXVGcFFNT3hWQVNWYUxsQ2lyRWpJekQ1ajRrSUNmWkdSYVVScTdPTzRvZWZUOEpvdEREN2I5K1IyaldSZnBaS09jeDViaVRHam83Q21vMEZXTGgwTHozUXdwOG05TVhVeC9vNWZBQWw0Q1FXZkxxRDJWaTZDVnBNQ2Fob3hPdUx0a09nTnA5dzlCeWVYVFJMU1MrbGdzZTB4L3RqL0xoWXBwbG56K3Z4eWNxajJKVmJ6UFlhTEkvdmNLUzBQWTN0bjN3b0VXbXBQU0RqZVh6dzJTLzRkazBCODdhUDNkOGJmMzU4MEdVSnNHczA4T3VSRXN4OWZ5Y3FxcHNjK3hVZFp2MXRKQldZcXllQW1pQ2JJUEo3Y3NySTBjSlN6dEFnRUVFUU9adWxHVEs1RkFGK0tzVDAwS0JQYkJqOGZaVU9Nd08yYXp4V1dJR2p4NnZaNW9odWR1dzdXZ204MVVwRWRWZGoySUF3K1BtcGNUUy9CbnNPbkdIRTlJc1B3Y0NrWUFZU1hkeXAwd1pzMlhPQ09YQzY0Um1iSE0zaTgxMi9uRVZwWlFNYW01cGhGUVJBc0VkY09uOFY0bnI1STZGUE1KTis1MVZSV1krZE9hVTRmcW9LUm1NenkwMTVLdVhRNmRRWW1oU091Qmd0QTVtS0NOMHc1aDRxWllGQ1Frd2doZzhLWS91TnkrV0xXRkZBZVFNV0xkMkpuRVBsTEZwNjRhbkJ1T2YyYUxyTHYzb0NuRkdRUGRwanpwemxONmprMnlNVlp2WGFtSnpUOTdBTW5zTStPcDkwc21jbDdiRjFhK2QyT1dmbmJPSDhybVVmYXRib3hVSlhSMTYyTGJDb0ZOQThFTTNYMEhEVWVhcDErVVNpWTNWWFNOVFJlV1R2TGNMQ2YreEJmYjBKc2RIK2VHdG1LblFCYXFaa0R1ZmJkU2Q4cmN2VG5YRjBhOGk3L3Nsc0VWRnZGWmlQVVBJYzFFcFp1dyt6WFNEdktrL042SDJNcG1aOCt1VitmTGV1a01IOXdCM1JlT0V2UThIVHZjYU5TRURYb2I2MEp3VmdiMGtENXU0cFozdVNFYUdlZUg2SUR0NVhWODNXNFNuUzhZL21uOGY4ajNOUm9xOEhCd2xlbk5vWGY3ZzcwV2tSWEtNQnpucExLcFhNZG5aNFNaMXJTRmYzWFVFTjB0ZWNnVTBFSnZiV1lza2QzZUdqa0xaYkU5cTVrZHB1dlhkL0JYYnZQd01iUkNnbEV0eHpXeVI2UkFTNmxnQTZYYU1nb3Q1a2hWb3VoY2QxZWdxRkV2Q2Z2R3BNWG51RzVXM1M0L3p3VVZwM1ZzL1pYbEh1dFNLQStoS2FKbkg2UXA2M1A1VHR1RnlqQVN3OEE5RFlMS0swc1JtZWNnbEMxWXBycmdsMGpCV0hLdkgwK2lLYTZjTXJnM1NZbXh6Q01xM1hTK3N1UjF6TGdPQWk1Kzg2QXB3a1dBU0NIZWNNMEtubDZPUG5jYzNLUlp5QjA5djc5Smk5NVR5TDJkOGMwUTF2akxTbm1uOVBBcTZnVGE0bGdKRkFnQXFUQlQrZXJFT2Nyd3FEZFo2UU9vN3Vyc1lNMkhONkJQUDNsR05lZGluVHVUbkpvWmd6UFBoR0FkOHBnOWZtVFBneXBkWWR4bytDcFcrMDRxZVR0VkFURSs2SkRZYVhVbjVWUU5GN21xMENYdDFXakk5ekt4aXA3NDROdzdTa3dOL04vbmNBQU5kclFFdHZSTXY2dmp4V0E1bzdTNC9XUXVQUjlmcE51ckx6QmhPZVdIc1cyVVVHK0hncDhQVURVYmlqbS8zUS9nYTViaHdDblByWVlCSHdUVUVOR3BvRlBKbmd6eDRYN1FwZWRHVzdTeG94L29kVHFHNHdJeXJBRTkrTzc0a0VYMldYN25lZENMdXhDSENTUUZNQm00N1hJYWUyR2YyRHZUQXF4QVBlblN2N2hsVWsrQ0JYajFlM25tZFp1RWNTQXJFa3JUdThyMVBJMjBXQ2Jqd0NXcHFrZy9vbUxQblZmbTd3Vkx3L0J1aFU5aEN5dlNJcEFMK1dtVEE1NnhTTzZwdllXZk9IYWVHWTFqL29ScEwrRzhjSnR5VTlWRHdxNnEzNExMOEtQNTl1d0ovNmFER3h0eSs4Vkk3OHN1UDh0V1YvMnNkb0UvSGVMK1dZdTdQRW5vT1c4TmczS1FiOWdydjBHRkVYaGJ0RDNXNWNEV2lwQ1UzTlZtdzVYb0VQODAySThaSGgzcDRhRE5GNXdjZUR2aVduZFZCUGs2bzBtdnB6VmhHcWpCWW0vV0VhSlFxbXhrSHVPR3p2RURTL1Q2TWJud0Q3WHNGZTJVRGZidkxtTGowS3FreTRKOEliUTBPOUVCZW9SSGUxUFdUVm0yeklyelRpNDl4SzVKWTFzTzIyaE9jeGQxUUlaZzBOYnRkMC9UNll0eHJsL3djQnppblRBNWtUVmMzNHFxQWEvOG12UVpIQkNwMjNGREUrQ3BaaVB0MW9SWEZkTTZ0MlkrZmNFZ21TSXpSWU5qb1NQWFZ0VjBTN0FQaVdDdTc2alZobkFLQWlZeFZFRkZZMVkxdEpQYkxQTldCdnFSSFZSaXNyeUtMZnkzZ09zZjRxM0JYbGc4Y1MvTkJIZTBPRm5oZTdyTXNTMEpIWDFleHc1UXVibkxtZUpxdUk0OVVtRk5hYWNicmVBcXNJUkdya0dCWGloUWdOZllENjkwMjhkVUtZTGpybmExVVgxTEJxMWFxeGJiNnVadjM2OWZGang0NmxCRnpwaFUwWEQ5Q0p1WFc4YWF0QldOcnh0Mk9zcm16Z09qN3lWYmRzS2ZtWEhFbGVVUU15TXpON2p4OC9mZ2ZIY2I2RUVJR2poUzZYdmpYeEJsLy9WUU40dFRlNFJBTW9sanpQODhYRnhUWExseSsvWSs3Y3ViOW1abVppNHNTSkYxNVpSbDlieWFXa3BHalhyVnUzVmFGUXhMdGZXM20xUEZ6b1R3c1oyQ3RBOC9QekN5ZE1tRENtc0xCUW41R1JRVEl5TXNRTDByeDE2MVpwYW1xcVozNSsvb0pldlhwTjQzbmVTcDhQNEdpQmpmdnFNZ0lpQlpIbkJZUEJJTXZPenY3eS92dnZuNzUxNjlhbTFOUlU5bkwwaXdsUWpoOC9QdnI5OTkvL1hxZlRoY3RrTXF1akZNVnRkcnBBQVgybWd2NVlMQmJaNGNPSGl6TXlNaVprWldYbFpXUmttRE15TWxvVFFNbElUMC8zV0xseXBjL01tVE5IcEtlbi96MGtKQ1RNMjl1YlBTam52anFQQUQwek5oZ01LQ3dzTEZtNWN1WE1wVXVYYmt0TFM2dmJzR0dEMGVsYkw1WnNhVXhNakthZ29FQ2JuSnpjZmZyMDZWTWpJaUlHKy9qNCtNdm9ZeSsvMWJ0MGZqYTNUZzhXK1ZpdFZsdGRYVjNWaVJNbmNwY3NXYkppMTY1ZFowSkRRMnRMU2tvTWpyY1NYNXh0dWZCWkhoRVJvUzBxS3ZJQzRLSFZhdFdqUjQvV3FWUXF1VWhMQWR4WHV3aElKQkxPWkRKWnRtL2ZycSt0cmFVUHRCa2pJaUlhaTRxS2FoMy8yT0VDanBlejdkVHB5blcwZUJMd0xDOHZwM3Q5S3YxdVA5QXU5SmZrZzJ3Nm5ZNit3cmVwdkx5OHdRRitxLzhwMHhhbzlPOFVkTGxHbzVFcmxVcVoyeGwzSEgybjh6V2J6VmFEZ1QzTFQzK28wNzNFZ3JRbjFmUjc1MzlSYXE5dHgyZDRhN1JrQlJ5T3B6ZmFOTjF1VUYwc0RHNEMzQVM0R0FFWEQrL1dBRGNCTGtiQXhjTzdOY0JOZ0lzUmNQSHdiZzF3RStCaUJGdzh2RnNEM0FTNEdBRVhEKy9XQUJjVDhIOTk5ZTB6bjlqdS93QUFBQUJKUlU1RXJrSmdnZz09IiwNCiAgImFzc2VydGlvblNjaGVtZSI6ICJVQUZWMVRMViIsDQogICJhdXRoZW50aWNhdGlvbkFsZ29yaXRobSI6IDEsDQogICJwdWJsaWNLZXlBbGdBbmRFbmNvZGluZyI6IDI1NiwNCiAgImF0dGVzdGF0aW9uVHlwZXMiOiBbDQogICAgMTU4ODANCiAgXSwNCiAgInVwdiI6IFsNCiAgICB7DQogICAgICAibWFqb3IiOiAxLA0KICAgICAgIm1pbm9yIjogMA0KICAgIH0NCiAgXSwNCiAgInRjRGlzcGxheVBOR0NoYXJhY3RlcmlzdGljcyI6IFsNCiAgICB7DQogICAgICAid2lkdGgiOiAzMjAsDQogICAgICAiaGVpZ2h0IjogNDgwLA0KICAgICAgImJpdERlcHRoIjogMTYsDQogICAgICAiY29sb3JUeXBlIjogMiwNCiAgICAgICJjb21wcmVzc2lvbiI6IDAsDQogICAgICAiZmlsdGVyIjogMCwNCiAgICAgICJpbnRlcmxhY2UiOiAwDQogICAgfQ0KICBdDQp9
hexSig:
bb28c3269349a0a37d0b686af08fb0814c6476ec005974100bdbaa913b86ccd9
>
> /Users/apowers/Documents/Google Drive/Backup/Projects/mds/node_modules/jsrsasign/lib/jsrsasign.js:258
if(typeof KJUR=="undefined"||!KJUR){KJUR={}}if(typeof KJUR.crypto=="undefined"||!KJUR.crypto){KJUR.crypto={}}KJUR.crypto.Util=new function(){this.DIGESTINFOHEAD={sha1:"3021300906052b0e03021a05000414",sha224:"302d300d06096086480165030402040500041c",sha256:"3031300d060960864801650304020105000420",sha384:"3041300d060960864801650304020205000430",sha512:"3051300d060960864801650304020305000440",md2:"3020300c06082a864886f70d020205000410",md5:"3020300c06082a864886f70d020505000410",ripemd160:"3021300906052b2403020105000414",};this.DEFAULTPROVIDER={md5:"cryptojs",sha1:"cryptojs",sha224:"cryptojs",sha256:"cryptojs",sha384:"cryptojs",sha512:"cryptojs",ripemd160:"cryptojs",hmacmd5:"cryptojs",hmacsha1:"cryptojs",hmacsha224:"cryptojs",hmacsha256:"cryptojs",hmacsha384:"cryptojs",hmacsha512:"cryptojs",hmacripemd160:"cryptojs",MD5withRSA:"cryptojs/jsrsa",SHA1withRSA:"cryptojs/jsrsa",SHA224withRSA:"cryptojs/jsrsa",SHA256withR
Signature: unsupported public key alg: ecdsa

**Comment by kjur** [comment]
Hi, could you try to use sig.init(CERTPEM) instead of sig.initVerifyByCertificatePEM(CERTPEM)? Then let me know the result? The [initVerifyByCertificatePEM](http://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Signature.html#.initVerifyByCertificatePEM) is a deprecated method. Thanks.

**Comment by kjur** [comment]
I think the issue was solved. So I'll close this ticket.
