### ISSUE TITLE
Get certificates signature algorithm 

### ISSUE THREAD

**Issue by carlskii** [kjur/jsrsasign#168]
Hi,

Is there any way to get a X.509 certificates signature algorithm & keysize ?

**Comment by kjur** [comment]
Hi @carlskii , there is no specific function for them but you can do as following:

"""
// RSA key size or ECC curve name

var pubkey = KEYUTIL.getKey(pem);

if (pubkey instanceof ECDSA)
  console.log(pubkey.curveName);
else if (pubkey instanceof RSAKey)
  console.log("RSA" + pubkey.n.bitLength());
else
  console.log(pubkey);

// certificate signature algorithm

var hex = X509.pemToHex(pem);

var sigAlgOidHex = ASN1HEX.getDecendantHexVByNthList(hex, 0, [1, 0]);
var sigAlgOidInt = KJUR.asn1.ASN1Util.oidHexToInt(sigAlgOidHex);
var sigAlgName = KJUR.asn1.x509.OID.oid2name(sigAlgOidInt);
"""

**Comment by carlskii** [comment]
Perfect thanks very much.
