### ISSUE TITLE
mapping oid's from getV3ExtInfoListOfCertHex(hex)

### ISSUE THREAD

**Issue by carlskii** [kjur/jsrsasign#170]
Hi, I'm using the `getV3ExtInfoListOfCertHex(hex)` method which gets a list of extensions from my X.509 certificate like this: 

```
[ { posTLV: 960, oid: '2.5.29.19', critical: true, posV: 984 },
  { posTLV: 1000, oid: '2.5.29.15', critical: true, posV: 1024 },
  { posTLV: 1032, oid: '2.5.29.14', critical: false, posV: 1050 },
  { posTLV: 1094, oid: '2.5.29.35', critical: false, posV: 1112 } ]
```
This is the output from the openssl command line (`openssl x509 -in cert4.txt -text -noout`)

```
X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                82:3A:52:4C:AF:33:96:F9:64:4E:C6:C0:DE:98:7D:8A:74:2B:BE:39
            X509v3 Authority Key Identifier: 
                keyid:C1:77:B1:2D:9D:6B:FD:51:C5:13:88:06:93:60:1E:87:7D:F9:34:0F
```

Is there a way to extract the mappings for the oid's to provide a similar output ? 

i.e. Extract the values for the X509v3 Subject Key Identifier and X509v3 Authority Key Identifier.

**Comment by kjur** [comment]
Sorry but there's no API for it. It need to be implemented by other APIs. Thanks.

**Comment by kjur** [comment]
Hi @carlskii , I've added X509.getInfo() method for your requirements above in the latest release 5.0.10 today. Please take a look. Thanks.

**Comment by carlskii** [comment]
Thanks for this - superb ! I'll take a look.

**Comment by carlskii** [comment]
One thing here. Any possibility of getting this as a JSON string ?

**Comment by kjur** [comment]
Sorry but I don't have any plan for it.
