### ISSUE TITLE
getNotBefore() & getNotAfter() returning strange time formats

### ISSUE THREAD

**Issue by carlskii** [kjur/jsrsasign#171]
I'm trying to format the outputs from the getNotBefore() & getNotAfter() functions, however they appear to dropping the first part of year. e.g.

Openssl reports the time for test cert as: 

    Validity
            Not Before: Jan 14 22:45:12 2016 GMT
            Not After : Sep 22 14:39:52 2016 GMT

jsrsasign, is returning this:  

    Not Before: 160114224512Z
    Not After: 160922143952Z

i.e. dropping the 20 from the beginning.

**Comment by kjur** [comment]
It's the correct ASN.1 UTCTime encoding. Plz see API DOCUMENTS.

**Comment by herrjemand** [comment]
@kjur you mean ASN.1 GeneralizedTime. UTCTime uses 4 digit year

**Comment by samueldiethelm** [comment]
In case someone else comes across this thread: you can easily parse this timestamp with `zulutodate` which is included in `jsrsasign`

Check here https://github.com/kjur/jsrsasign/issues/246
