### ISSUE TITLE
verify token create by JJWT in RS256 into Jsrasign

### ISSUE THREAD

**Issue by GuillaumeUnice** [kjur/jsrsasign#173]
Hi, every

I have generate a JWT and I have is Public Key. When I verify on https://jwt.io/ it's ok.

But I don't understand what function jsrasign use to have the same result.

I write the token and the public Key for you

Token
`eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTQ2MTI0NDg0Mjg4Nn0.TvTF49ACcE-RjgucDsGyuvR_MSwQjEjdbp7UuUrny1fgqLiUdShmghnjfZUBwlYhImlCqumCVl2AfK8c6jEzZKvtJZW4-hqWNHRDz_rHQzT6NLzNjR8d6dR3LBzMxomywmB5Co4ki7kHfhRItADTxUQ97XiYy1QLTyME9Nl5dwjRET7X7yb4P2AcdVcf7FxT-Nc2cNVj4hI2XRKeaemMD5qwo_nVAaLZ22IC1BNseuAWAlWAjv6mK-HHA_cwCKl36641fPT0-vDzdDbaJsylHj1_-PE043o5vfsjTgvHSpJxFNXqG17XCVurdV7Mo41NkPuD5qAbYBOXSt8L6NQZlA`

Public KEY
`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiB66HYE5NbFDnY22dL00ie0FEI0BeeS8OOR18Yp6Dfd14GsIjl+kk9oAJKlecHDeBX6wwZRPrakSo9E432kB2v7rnZSAkAvr61AmdLjbNAnjqO5D8V8J0t5eOxzI5PmrXHyXXwNmbekeclOt0pMc1SeF9NMDbESRgz8LVg9CuZMkxzuzlG4+Fklfi4aJrkG0ex1e0PXwCyP9FqjLdaE+ijZl7zVXvBrvpqhB4IYy0yC/GCyg69WRhhbiUGFHXIRtWQd90yd3e996Iq0s8RA2wNHtyzhX/a9KubwnUc8XstTZb4TeO8gaVpGODKU95DXz2lnwVHA9nwwtMRAfSM6EBwIDAQAB
-----END PUBLIC KEY-----`

**Comment by kjur** [comment]
Your key and JWT is successfully verified by jsrsasign.
Please see tutorial.

https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-verification
