### ISSUE TITLE
Verify Certificate against a root Cert

### ISSUE THREAD

**Issue by genaromadrid** [kjur/jsrsasign#176]
Hey,

I been looking for a way to verify that a certificate was generated with a certain root certificate and no luck so far. 

In OpenSSL you can do it with `openssl verify -verbose -CAfile cacert.pem  certificate.pem`.
Any help would be very appreciated.

Great code btw.
Cheers

**Comment by kjur** [comment]
I'm sorry but currently jsrsasign don't have any certificate validation methods. Thanks.

**Comment by genaromadrid** [comment]
@kjur thanks for the quick response!

**Comment by genaromadrid** [comment]
Hey @kjur i'm working on this and apparently, to verify a certificate against a rootCA, you have to get the signing fingerprint first. 

To get that fingerprint, you have to build the TBSCertificate. I been trying to build it like this:

```javascript
certificate = new jsrsasign.X509();
certificate.readCertPEM(pem);

o = new KJUR.asn1.x509.TBSCertificate();
o.setSerialNumberByParam(int: certificate.getSerialNumberHex())
o.setSignatureAlgByParam(name: certificate.getSignatureAlgorithmField())
o.setSubjectByParam(str: certificate.getSubjectString())
// ...
fingerprint = jsrsasign.crypto.Util.hashHex(o.getEncodedHex(), 'sha1');
```
The problem is that my certificate has some extensions that `jsrsasing` library does not support.
I found the function `X509.getHexTbsCertificateFromCert(hex)` that returns a position?

How can i build a TBSCertificate from an X509 Certificate?

Thanks!!

**Comment by kjur** [comment]
Hi. You can get SHA1 hash of tbsCertificate by following:

```JavaScript
var rs = require('jsrsasign');
var pem = rs.readFile("file.cer");
var hex = rs.X509.pemToHex(pem);
var hTbsCert = rs.ASN1HEX.getDecendantHexTLVByNthList(hex, 0, [0]); // 1st child of SEQ is tbsCert
var hHashTbsCert = rs.crypto.Util.sha1(hTbsCert);
console.log(hHashTbsCert);
```

**Comment by genaromadrid** [comment]
Perfect!! that help me a lot. So i learn that to verify a certificate agains a rootCA you don't actually need the fingerprint of the TBSCertificate but the TBSCertificate itself. 
So, after all, It was really simple to verify a certificate:

```javascript
var rs = require('jsrsasign');

// Load certificate data
var pem = rs.readFile('file.pem');
var certificate = new jsrsasign.X509();
certificate.readCertPEM(pem);

var hTbsCert = rs.ASN1HEX.getDecendantHexTLVByNthList(certificate.hex, 0, [0]);
var alg = certificate.getSignatureAlgorithmField();
var signature = rs.X509.getSignatureValueHex(certificate.hex);

// Verify against CA
var pemCa = rs.readFile('file_ca.pem');
var sig = new rs.crypto.Signature({alg: alg});
sig.init(pemCa);
sig.updateHex(hTbsCert);
sig.verify(signature); // true if CA signed the certificate
```

There's something that intrigues me though, why jsrsasign does not support this? i thought that it was used for SSL in some cases. Anyways... Should i add this to a Pull Request? Do you think is a good contribution?

Cheers

**Comment by sbweeden** [comment]
I am trying to use the above pattern with the CA cert:

-----BEGIN CERTIFICATE-----
MIICPjCCAeOgAwIBAgIIfOrEOH4trxYwCgYIKoZIzj0EAwIwcjELMAkGA1UEBhMC
VVMxFzAVBgNVBAoTDlN0cm9uZ0F1dGggSW5jMRowGAYDVQQLExFGb3IgVEVTVCBV
c2UgT25seTEuMCwGA1UEAxMlVVRIUyBUZXN0IEVDRFNBIFRva2VuIENsYXNzIDIg
Um9vdCBDQTAeFw0xNTAzMDMxODQ5MDBaFw00NTAzMDMxODQ5MDBaMHIxCzAJBgNV
BAYTAlVTMRcwFQYDVQQKEw5TdHJvbmdBdXRoIEluYzEaMBgGA1UECxMRRm9yIFRF
U1QgVXNlIE9ubHkxLjAsBgNVBAMTJVVUSFMgVGVzdCBFQ0RTQSBUb2tlbiBDbGFz
cyAyIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ853hwMuelbGV0
NVGFZ078I5FKqwMstM6Ij5z1M9oHqtKz6jU3d/jwUesKVwYFiT9nfCRKBbMZqfiM
U9KdrUzoo2MwYTAdBgNVHQ4EFgQUEFkQlqWMdAwZ3r6i7wckVaoy9+owDwYDVR0T
AQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQQWRCWpYx0DBnevqLvByRVqjL36jAOBgNV
HQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwIDSQAwRgIhAN0pph40pNzsm/9/wHMYu6ko
NSFKRrIREXPmQQ49/XRmAiEAoS0z5pEpSVXmLuNUV7MJ+khNEc+SMlJ6fezxtnPZ
Ui0=
-----END CERTIFICATE-----

and the issued cert:


-----BEGIN CERTIFICATE-----
MIIEHzCCAwegAwIBAgIIL2BtCes8rq4wDQYJKoZIhvcNAQELBQAwcDELMAkGA1UE
BhMCVVMxFzAVBgNVBAoTDlN0cm9uZ0F1dGggSW5jMRowGAYDVQQLExFGb3IgVEVT
VCBVc2UgT25seTEsMCoGA1UEAxMjVVRIUyBUZXN0IFJTQSBUb2tlbiBDbGFzcyAy
IFJvb3QgQ0EwHhcNMTUwMzEyMjM0MDI5WhcNMjUwMzEyMjM0MDI5WjByMQswCQYD
VQQGEwJVUzEXMBUGA1UEChMOU3Ryb25nQXV0aCBJbmMxGjAYBgNVBAsTEUZvciBU
RVNUIFVzZSBPbmx5MS4wLAYDVQQDEyVVVEhTIFRFU1QgTWl4ZWQgVG9rZW4gQ2xh
c3MgMiBCYXRjaCAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEArhdn0CmR0qy
JsJCgQpRgsFdrHoL0gczrp9lAPtyK/IJBRwARwn8keT+pmHJU4h0yfiBQnnX6Icj
JauomtSnYaOCAYQwggGAMG0GCCsGAQUFBwEBBGEwXzAyBggrBgEFBQcwAoYmaHR0
cDovL29jc3AudXRocy53ZWJzaXRlL2MycnNhcm9vdC5jcnQwKQYIKwYBBQUHMAGG
HWh0dHA6Ly9vY3NwLnV0aHMud2Vic2l0ZS9vY3NwMB0GA1UdDgQWBBQQpg/yo3BV
QRZpbY7gQdiG8J5YEDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFL1Tx08YeusK
KkhbfNNeCD/xRSQaMIGwBgNVHR8EgagwgaUwgaKgKqAohiZodHRwOi8vb2NzcC51
dGhzLndlYnNpdGUvYzJyc2Fyb290LmNybKJ0pHIwcDEsMCoGA1UEAwwjVVRIUyBU
ZXN0IFJTQSBUb2tlbiBDbGFzcyAyIFJvb3QgQ0ExGjAYBgNVBAsMEUZvciBURVNU
IFVzZSBPbmx5MRcwFQYDVQQKDA5TdHJvbmdBdXRoIEluYzELMAkGA1UEBhMCVVMw
DgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCIbLGu2zTPRMh9uF2A
6xKU1aKaTSIm70NYglU9h6uqkFQZRDYkzZfcVcJj5ppZbGp6vf49TNQwKv1x0oaX
d0rQfD9ICbMOagl7CalA2yjJ4tnJZB6LnUQttwxdkyGxmiTjgxzLzkf7JS0UFAfi
yiiqyOjD/d+Iy+5sXwI08tYR+fScSX3UAcw5ZFMBEg1BEMPBsQBgedsOUoxDQutO
9Wui3el3xHmUa78RDf5oEWvk51yty2rIGo/F2WJbsgD85ToXJyUoLvbaTyLc4bFC
U0rF4tbAyMqXk91oQTRWjM19bm25wGbTHbY1pt7/OJVZmv3LGGOEIzVfmKnrmC3K
RaCf
-----END CERTIFICATE-----


Every time I try to do a verify, I get an error: "signature is not a ASN.1 sequence"

Any ideas as to why?

**Comment by kjur** [comment]
Hi @sbweeden , it seems those certificates wrong.

a) FIRST CERT: self signed root certificate with ECC key
b) SECOND CERT: ECC public key certificate signed by RSA key

So, b) is not issued by a). That's why signature of b) can't be verified with a).

**Comment by sbweeden** [comment]
Ok - fair enough. Thanks for getting back to me.

**Comment by herrjemand** [comment]
@sbweeden 

/**
 * Takes a PEM encoded certificate chain array and verifies it
 * @param  {String[]} certificates - PEM certificate chain
 * @return {Boolean}               - Returns if certificate chain can be validated
 */
var verifyCertificateChain = (certificates) => {
    let valid = true;

    for(let i = 0; i < certificates.length; i++) {
        let Cert        = certificates[i];
        let certificate = new jsrsasign.X509();
        certificate.readCertPEM(Cert);

        let CACert = '';
        if(i + 1 >= certificates.length) {
            CACert = Cert;
        } else {
            CACert = certificates[i + 1];
        }

        let certStruct   = jsrsasign.ASN1HEX.getTLVbyList(certificate.hex, 0, [0]);
        let algorithm    = certificate.getSignatureAlgorithmField();
        let signatureHex = certificate.getSignatureValueHex()

        // Verify against CA
        let Signature = new jsrsasign.crypto.Signature({alg: algorithm});
        Signature.init(CACert);
        Signature.updateHex(certStruct);
        valid = valid && Signature.verify(signatureHex); // true if CA signed the certificate
    }

    return valid
}

**Comment by kjur** [comment]
Hi all, this may be simpler one :)
```JavaScript
const verifyCertificateChain = (certificates) => {
    let valid = true;
    for(let i = 0; i < certificates.length; i++) {
	let issuerIndex = i + 1;
	// If i == certificates.length - 1, self signed root ca
	if (i == certificates.length - 1) issuerIndex = i;
	issuerPubKey = jsrsasign.KEYUTIL.getKey(certificates[issuerIndex]);
        const certificate = new jsrsasign.X509(certificates[i]);
        valid = valid && certificate.verifySignature(issuerPubKey);
    }

    return valid;
}
```

**Comment by trasherdk** [comment]
Okay, those snippets looks like something I could use.

I'm currently terminating TLS, and verifying client certificate, on Apache, and proxy to a node server.
```conf
	SSLEngine on

	SSLCertificateFile	"/etc/httpd/certs/host.example.com.crt"
	SSLCertificateKeyFile	"/etc/httpd/certs/host.example.com.key"
	SSLCertificateChainFile	"/etc/httpd/certs/ca.crt"
	SSLCACertificateFile	"/etc/httpd/certs/ca.crt"

	<Directory "/path/to/example.com/user">

	# Certificate authorization
		# require a client certificate which has to be directly
		# signed by our CA certificate in ca.crt
		SSLVerifyClient		require
		SSLVerifyDepth		1
		SSLOptions		+FakeBasicAuth
		SSLRenegBufferSize	2048000
		SSLRequire		(%{SSL_CLIENT_S_DN_Email} eq "user@example.com")
	
	</Directory>
```

What would the flow look like, if I hit the node app directly, without Apache? Do you have an example somewhere?

**Comment by kjur** [comment]
Hi @trasherdk , sorry but jsrsasign will not provide TLS connection.

**Comment by trasherdk** [comment]
@kjur I get that `jsrsasign` does not provide any client/server connection stuff, but deals only with certificates.

Given a nested structure of certificate issuers, like:
```
RootCA
├── Sub1CA
│   ├── App1CA
│   └── App2CA
└── Sub2CA
    ├── App1CA
    └── App2CA
```
I need to know witch  CA signed a client certificate. Users with certificate signed by `Sub1CA/App1CA` should not be able to access a server with a certificate signed by `Sub2CA/App1CA` or `Sub1CA/App2CA` but might be allowed to access `Sub2CA/App2CA`

Does that make any sense?

I have a minimal [client/server tls/socket](https://github.com/trasherdk/node-test-snippets/tree/master/socket-tls) thing.

Hmm. I think I need to set up that nested CA thing to make a reasonable test case. I'll be back :smiley:
