### ISSUE TITLE
关于解密时报错

### ISSUE THREAD

**Issue by ugvgylkm** [kjur/jsrsasign#177]
http://kjur.github.io/jsrsasign/sample-rsasign.html 这个dome 在解密时报错，js版本jsrsasign 5.0.10

报如下错误
jsrsasign-latest-all-min.js:280 Uncaught malformed X.509 certificate PEM (code:003)

**Comment by kjur** [comment]
Hello @ugvgylkm . Thank you for your report. I'll check it later.

**Comment by kjur** [comment]
Hello @ugvgylkm . I've fix it in the latest release 5.0.11. This issue was raised because of lacking X509v1 certificate support in KEYUTIL.getKey. Now KEYUTIL.getKey supports X509v1 certificate.
