### ISSUE TITLE
Generated JWT via jws.sign() are invalid via jws.verify()

### ISSUE THREAD

**Issue by cblair** [kjur/jsrsasign#178]
Might be missing something, but seems straight forward. Some of these return from jws.verify(), and some return false:

Generate JWT:
```
var jsrsasign = require('jsrsasign');
var jws = jsrsasign.jws.JWS;

function generate(jwt, key) {
    var header = JSON.stringify({
        alg: ALG_TYPE,
        typ: 'JWT'
    });

    var payload = JSON.stringify(jwt.payload);
    return jws.sign(ALG_TYPE, header, payload, key);
}

var role = 10;
var time = jsrsasign.jws.IntDate.get('now');
var key =  '11111111111111111111';
var alg = 'HS256';

var jwt = JwtUtils_1.generate({
    header: {
        alg: alg,
        typ: 'JWT'
    },
    payload: {
        iss: 'http://localhost',
        //nbf: time - 1000000000,
        nbf: time,
        //iat: time - 1000000000,
        iat: time,
        exp: time + 1000000000,
        name: 'JimBob',
        sub: 'JimBob',
        IpAddress: 'localhost',
        role: [role]
    }
}, key);

console.log(jwt);
```

Validate JWT:
```
jsrsasign.jws.JWS.verify(jwt, key, alg)); // returns false
```

**Comment by cblair** [comment]
I'll be updating test/qunit-do-jws-sign.html to see if I'm doing something wrong, or I can find an issue.

**Comment by kjur** [comment]
Please take a look test/qunit-do-jws-sign-hs.html for your example. I can't identify your issue at this stage. So I'll close this ticket.

**Comment by cblair** [comment]
Wil do, thanks.

**Comment by cblair** [comment]
Hmm, by sanitized example above seems to be working just fine (made a few updates from some silly errors). So still trying to root cause why my real code is failing.

**Comment by cblair** [comment]
@kjur, updated comments. Confirmed failure in the file you mentioned.

**Comment by cblair** [comment]
Ah crap. Never mind, I was providing the alg arg wrong. Passing now:

```
- verifyJWT(jwt, key, {alg: alg})
+ verifyJWT(jwt, key, {alg: [alg]})
```

**Comment by kjur** [comment]
It's nice the issue was solved ;)

**Comment by cblair** [comment]
Yep. Sorry for the confusion. : )
