### ISSUE TITLE
jsrsasign.js:295 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by gingters** [kjur/jsrsasign#184]
Hello,

we use jsrsasign.js in the browser, and for that we load the `jsrsasign.js` file from the lib folder of the npm package. However, it expects an `exports` object which isn't available in browsers.

So when using the library, you get this error message in the browsers console:
`jsrsasign.js:295 Uncaught ReferenceError: exports is not defined` 

We can't even work around this by creating a global `exports` object in the browser, as we also include other scripts like system.js that behave wrongly when they detect an exports object.

I tried to load jsrsasign through systemjs in a second approach, however the lib does `require('fs')` which isn't available in the browser too.

Please safeguard the exports section to check for the exports object to be available before using it.
Also, please don't rely on 'fs'.

**Comment by lgh06** [comment]
Maybe you should use Webpack or Browserify

**Comment by allansli** [comment]
+1 

exports.SecureRandom = SecureRandom;

**Comment by fberlin** [comment]
+1

**Comment by satlom** [comment]
+1
Please FIX!!!!
Very annoying!

**Comment by kjur** [comment]
I've released 6.0.0 today which is now Node.js and "fs" safe. Please check it.

**Comment by victorlin** [comment]
still seeing this problem

**Comment by kjur** [comment]
npm/lib/jsrsasign.js will work only for Node.js and other packager like WebPack or others on the browser is not supported. There is no plan to add those support.

Please use jsrsasign http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js for browsers.

**Comment by saranglohar** [comment]
Mr. Kenji,  
I am glad to say u that u have given a nice explanation to fix this problem. 
Thank You!
