### ISSUE TITLE
Problem with Encrypted PKCS#5

### ISSUE THREAD

**Issue by frikeldon** [kjur/jsrsasign#185]
Hello

i'm trying to implement JSON Web Signature with your library, and I have problems encrypting and decrypting RSA keys.

When I decrypt the key, only de exponent is equal in the original and the decrypted key.

Here is my code:
```javascript
var passcode = 'passcode';

var generated = new RSAKey();
generated.generate(1024, '10001');

var encrypted = PKCS5PKEY.getEryptedPKCS5PEMFromRSAKey(generated, passcode);
var decryptedKeyHex = PKCS5PKEY.getDecryptedKeyHex(encrypted, passcode);

var decrypted = new RSAKey();
decrypted.readPrivateKeyFromASN1HexString(decryptedKeyHex);

['coeff', 'd', 'dmp1', 'dmq1', 'e', 'n', 'p', 'q'].forEach(function(prop) {
    console.log(prop + ' --> ' + (generated[prop] === decrypted[prop] ? 'OK' : 'KO'));
});
```

What's i'm doing wrong?

Thanks

**Comment by kjur** [comment]
PKCS5PKEY is deprecated. Please use KEYUTIL.getKey().
https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey

**Comment by frikeldon** [comment]
i tried it with KEYUTIL methods with the same result, only de exponent is equal in the original and the decrypted key.

```javascript
var passcode = 'passcode';
var rsaKeypair = KEYUTIL.generateKeypair('RSA', 1024);
var encrypted = KEYUTIL.getPEM(rsaKeypair.prvKeyObj, 'PKCS5PRV', passcode, 'AES-256-CBC');
var decrypted = KEYUTIL.getKey(encrypted, passcode, 'PKCS5PRV');
['coeff', 'd', 'dmp1', 'dmq1', 'e', 'n', 'p', 'q'].forEach(function(prop) {
    console.log(prop + ' --> ' + (rsaKeypair.prvKeyObj[prop] === decrypted[prop] ? 'OK' : 'KO'));
});
```

**Comment by kjur** [comment]
Parameter values like 'p' or 'q' are independent objects so that they can't be compared by "===" operator. They shall be compared by "A.compareTo(B)" method.

**Comment by kjur** [comment]
It seems that there is no further question. I'll close this ticket. Thanks.
