### ISSUE TITLE
Transform PKCS#5 in DER to RSA object

### ISSUE THREAD

**Issue by gordilloedwin** [kjur/jsrsasign#186]
Hello KJUR

It's me again, I have another question for you, one I haven't been able to solve, I have DER encoded PKCS#5 private key file which is encrypted but I haven't been able to translate that into a RSA object which I need to sign a string. 

I have tried many different approaches but none seem to work. 

I already have the HEX code of the encrypted private key, is there a function that can do that for me?
that is, translate this hex into RSA object I can use to sign a string? 

Thanks in advance!!

**Comment by gordilloedwin** [comment]
oh I already figure it out!! awesome library !!

**Comment by kjur** [comment]
@gordilloedwin , It seems already solved. :)
