### ISSUE TITLE
Unable to validate a token generated with JJWT

### ISSUE THREAD

**Issue by jmdesprez** [kjur/jsrsasign#187]
Hello,
I've a strange behaviour with jsrasign 5.0.6. 

Given public key and curve defined like this:
```javascript
var publicKey = '046401cd84959536bfd310f1266f76ad0d7481622133512851be4c94e059ff1f4b3185eb5ade273a9578274c3d1143ce43abf8a460843a4aa246e479c2520ea0ac'
var curve = 'P-256'
```
And given a valid token like this one: `eyJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJUZXN0Iiwic3ViIjoiQWxpY2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE0Njk2MDkxMDksImV4cCI6MTUwMTE0NTEwOSwiYXVkIjoiVGVzdCBhdWRpZW5jZSJ9.MEUCIQD4rwV75OAQfwqRlpBIlTblPdG3XFrxcTRsYHJkzDmemQIgQyV-3QfkSmM1rQf4lFUC3DKIDfTJKjJCR8e4zvIUYf0`

The following code works as expected:
```javascript
var parts = $scope.token.split('.')
var header = parts[0]
var payload = parts[1]
var signature = parts[2]
var sig = new KJUR.crypto.Signature({'alg': 'SHA256withECDSA', "prov": "cryptojs/jsrsa"});
sig.initVerifyByPublicKey({'ecpubhex': publicKey, 'eccurvename': curve})
sig.updateString(header + '.' + payload)
var isSignValid = sig.verify(b64utohex(signature))// this result can be trusted
```

But this code always return false even if the signature is valid:
```javascript
// from http://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey
// ECC public key parameters: param={xy: xy, curve: curveName}
// NOTE: ECC public key 'xy' shall be concatination of "04", x-bytes-hex and y-bytes-hex.
var pubKey = KEYUTIL.getKey({'xy': publicKey, 'curve': curve});
var isTokenValid = KJUR.jws.JWS.verifyJWT($scope.token, pubKey, {
    alg: ["ES256"]
}); // this is always false even if the token is valid
```

I've perform some debugging but javascript is not my cup of tea :-/
The problem seems to be located in ecdsa-modified-1.0.js at line 567:
```javascript
if ((((concatSig.length / 2) * 8) % (16 * 8)) != 0)
    throw "unknown ECDSA concatinated r-s sig  length error";
```
This method is called from jws-3.3.js at line 448:
```javascript
try {
	hASN1Sig = KJUR.crypto.ECDSA.concatSigToASN1Sig(hSig);
} catch (ex) {
    return false;
}
```

So it look like I have a problem with the length of the signature. But `KJUR.crypto.Signature` doesn't complain about this.
I've check in JJWT (https://github.com/jwtk/jjwt) how to configure the length of the signature but it doesn't seems to be possible.

I don't even known if it's a problem with my token (which have bad signature length) or if the problem is related to the way I use KJUR?

How can I validate a token generated from JJWT?

Thanks

**Comment by kjur** [comment]
Is the token "eyJhbGciOiJFUzI1NiJ9..." is generated by JJWT, right? This has wrong signature value in ASN.1 R and S format for ECDSA JWS signature. ECDSA JWS signature value shall have concatination of R||S, not ASN.1 R, S signature as defined in A.3.1. 
https://tools.ietf.org/html/rfc7515#appendix-A.3.1

KJUR.crypto.Signature.sign() and verify() will handle ASN.1 R, S signature and they can't be used for JWS signature value. It shall be converted from ASN.1 format to concatinated format by KJUR.crypto.ECDSA.asn1SignToConcatSig() method.

Please ask JJWT to fix this bug.

**Comment by jmdesprez** [comment]
Hello,

Yes, the token is generated by JJWT :)

Thank you for the explanation, it's very clear.
