### ISSUE TITLE
How do I get public key info?

### ISSUE THREAD

**Issue by sportnet2016** [kjur/jsrsasign#188]
I'd like to know how do I get this info (public key bit):

Subject Public Key Info:
            Public Key Algorithm: **rsa**Encryption
                **Public-Key: (2048 bit)**

**Comment by kjur** [comment]
Do you mean getting public key info from a certificate?

1) to get algorithm

There are two way to find algorithm.

[X509.getPublicKeyFromCertPEM](https://kjur.github.io/jsrsasign/api/symbols/X509.html#.getPublicKeyFromCertPEM) will return a key object such as RSAKey, KJUR.crypto.{DSA/ECDSA}. Then you can check it by instanceof operator.

```JavaScript
key = X509.getPublicKeyFromCertPEM(pem);
if (key instanceof RSA) {
} else if (key instanceof KJUR.crypto.ECDSA) {
} else if (key instanceof KJUR.crypto.DSA) {
}
```

[X509.getPublicKeyInfoPropOfCertPEM](https://kjur.github.io/jsrsasign/api/symbols/X509.html#.getPublicKeyInfoPropOfCertPEM) will return a JSON object which has hexadecimal string of algorithm OID. Then you can get its OID name.

```JavaScript
prop = X509.getPublicKeyPropOfCertPEM(pem);
oidhex = prop.algoid;
oid = KJUR.asn1.ASN1Util.oidHexToInt(oidhex);
name = KJUR.asn1.x509.OID.oid2name(oid); //such as rsaEncryption/dsa/ecPublicKey
```

2) to get RSA key size

You can get it as following:

```JavaScript
rsaKeyObj = X509.getPublicKeyFromCertPEM(pem);
rsaKeySize = rsaKeyObj.n.bitLength();
```
