### ISSUE TITLE
key is too short for SigAlg: keylen=99,sha1

### ISSUE THREAD

**Issue by ztlyde** [kjur/jsrsasign#189]
My private key generated by the JDK tools keytool, when using this jsrsasign.js signature appear this error 'Uncaught key is too short for SigAlg: keylen=99,sha1'

But I don't have any problems in Java.

Below is my code:
var rsa = new RSAKey();
rsa.readPrivateKeyFromPEMString( rsaPrivateKey );
document.getElementById ('code2').innerHTML = rsa.signString( preSignContent, "sha1" );

**Comment by kjur** [comment]
Please try following:
```JavaScript
var prvKey = KEYUTIL.getKey(rsaPrivateKey);
var sig = new KJUR.crypto.Signature({"alg": "SHA1withRSA"});
sig.init(prvKey); 
sig.updateString(preSignContent)
var sigValueHex = sig.sign()
document.getElementById ('code2').innerHTML = sigValueHex;
```
Please see wiki:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-Signature-class

**Comment by ztlyde** [comment]
Thank you!

**Comment by q010p** [comment]
hi
when i try 
`var absolutePath = path.resolve('assets/private.rsa');
        var privateKey = fs.readFileSync(absolutePath, "utf8");
var prvKey = jsrAsign.KEYUTIL.getKey(privateKey);
        var sig = new jsrAsign.KJUR.crypto.Signature({"alg": "SHA1withRSA"});
        sig.init(prvKey);
        sig.updateString(toEncrypt);
        return  sig.sign().toString("base64");`
the return string is longer than string that java returns and when i try in online tools the length of string is same java
`PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(pkcs8EncodedBytes);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            PrivateKey privateKey = kf.generatePrivate(keySpec);
            Signature privateSignature = Signature.getInstance("SHA1withRSA");
            privateSignature.initSign(privateKey);
            privateSignature.update(message.getBytes());

            byte[] signature = privateSignature.sign();
            String returnString = Base64.encodeToString(signature, NO_CLOSE);
`
please help me

**Comment by q010p** [comment]
hi
when i try
`var absolutePath = path.resolve('assets/private.rsa');
 var privateKey = fs.readFileSync(absolutePath, "utf8");
 var prvKey = jsrAsign.KEYUTIL.getKey(privateKey);
 var sig = new jsrAsign.KJUR.crypto.Signature({"alg": "SHA1withRSA"});
 sig.init(prvKey);
 sig.updateString(toEncrypt);
 return sig.sign().toString("base64");`

the return string is longer than string that java returns and when i try in online tools the length of string is same as java
my java code :
`PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(pkcs8EncodedBytes);
 KeyFactory kf = KeyFactory.getInstance("RSA");
 PrivateKey privateKey = kf.generatePrivate(keySpec);
 Signature privateSignature = Signature.getInstance("SHA1withRSA");
 privateSignature.initSign(privateKey);
 privateSignature.update(message.getBytes());
 byte[] signature = privateSignature.sign();
 String returnString = Base64.encodeToString(signature, NO_CLOSE);`

**Comment by kjur** [comment]
How about to change the last line:
```JavaScript
 return jsrAsign.hextob64(sig.sign())
```
