### ISSUE TITLE
Still wrong jsrsasign.js in npm-package 6.0.1

### ISSUE THREAD

**Issue by fberlin** [kjur/jsrsasign#190]
The file jsrsasign.js in npm-package 6.0.1 differs from jsrsasign-latest-all-min.js.

I still get the "exports is not defined" error using the npm-package. (#184)

When i use  jsrsasign-latest-all-min.js. the error is gone.

**Comment by kjur** [comment]
I think you use jsrsasign.js in npm package on the environment which is not Node.js. It is intended that jsrsasign.js of npm is only for use on Node.js.

**Comment by fberlin** [comment]
Yes I'm using jsrsasign in a client javascript application. I was not aware that the npm-package was for Node.js only. I will stick to  jsrsasign-latest-all-min.js.
