### ISSUE TITLE
No Documentation on Implementation

### ISSUE THREAD

**Issue by ccarterc** [kjur/jsrsasign#192]
I have been unable to locate documentation that describes which file is needed in order to use the library.  e.g.  I want to use the library on a website (actually in the browser, no server implementation) to parse and validate JWT.

I download the latest release which contains a lot of files and folders.  Which files are needed?

**Comment by kjur** [comment]
Did you see tutorials?
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-verification
