### ISSUE TITLE
Need to encrypt ECC private key generated with KEYUTIL.generateKeyPair

### ISSUE THREAD

**Issue by dsgill** [kjur/jsrsasign#193]
Hi,

I have created keys using generateKeyPair. Some of these keys are RSA, some are ECC. Now I need to encrypt those keys. I have found an API to encrypt plain RSA keys, but I am having trouble locating an API to encrypt plain ECC keys. Would you please point me in the right direction?

Thank you.

Don

**Comment by kjur** [comment]
Hi. To get PKCS#8 encrypted ECC private key, you can do as following:

```JavaScript
kp = KEYUTIL.generateKeypair("EC", "secp256k1");
pem = KEYUTIL.getPEM(kp.prvKeyObj, "PKCS8PRV", "pass");
```

**Comment by dsgill** [comment]
Thank you kjur!
