### ISSUE TITLE
How to tell if private key is encrypted

### ISSUE THREAD

**Issue by dsgill** [kjur/jsrsasign#196]
Hi kjur,

Which API in jsrsasign should I use to determine if a private key is encrypted or not? If encrypted I also need to extract the encryption algorithm used. Maybe a parse routine, but I don't know which one?

Thank you.

Don

**Comment by kjur** [comment]
Generally, [KEYUTIL.getKey](https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey) can be used to load any format of keys such as PKCS#1, PKCS#8, encrypted, plain, JWK, hexadecimal or others. Format detection is done by automatically. As for encrypted or plain, the difference is just only providing password in a argument or not.

```JavaScript
k1 = KEYUTIL.getKey(PEM_PKCS8_ENCRYPTED_PRIVATE_KEY, "password");
k1 = KEYUTIL.getKey(PEM_PKCS8_ENCRYPTED_PRIVATE_KEY);
```

As for finding private key encryption algorithm, sorry but there is no public method in jsrsasign. Please you need to find it in the source codes.

**Comment by dsgill** [comment]
But I have the situation that I don't know if the private key is encrypted or not. When I look at the private key string (which is in PEM format) it states it is encrypted and the algorithm used to encrypt it. If I can see that by examining the key visually without the use of the password, I would like to determine that programmatically without the password. When I try to use getKey on an encrypted PEM private key without the password I get an exception. I don't want to decrypt it, only to extract the unencrypted content. For example,
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,E2BB720AC488F15DE0D08F79AF7170C8

is unencrypted while the actual key content is encrypted. Is there an API I can use to get this info?

**Comment by kjur** [comment]
Sorry but there is no such API.
