### ISSUE TITLE
Parse CSR string

### ISSUE THREAD

**Issue by nathalials** [kjur/jsrsasign#197]
I'd like to know how to parse CSR information from a CSR string
Information like subject (common name), Organization, Organization Unit, Locality, State, Country

**Comment by nathalials** [comment]
For example, this pem string:

-----BEGIN CERTIFICATE REQUEST-----
MIICljCCAX4CAQAwUTELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAjI3MQswCQYDVQQH
DAJzcDENMAsGA1UECgwEdGVzdDELMAkGA1UECwwCc3AxDDAKBgNVBAMMA29yZzCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMChYaRSN83Pv5EElAtWIyVn
Cp/KgPcjES1vOtAhjDs7jec8uH95PhEauO7IqxrwZmNxw9hRThx4URiJHUci4fkV
+kkfoDmxMRMMG9PtA5eM5ij5EHF/3gxjdpF0Q1LHJ45POMPKoKhg9NMeTvak9EL2
EFIr4dfUmOAFNy3lBHskogwKvwYmqLtPMf21ZZ6C/xhQ0te/AzJOuYr43tkvJHHv
fLutso1NZCZpxGQCVq0qJQLg0jpbm/PWeUNOYnfOzyZ/DMpAhKpH99hT8PhSqPqQ
0Wr1YCVaw4ERcvwogaiYH/Wge6+FYRSqU2A3FsIIV2DVbPD35CHmyue/SeXMMIEC
AwEAAaAAMA0GCSqGSIb3DQEBCwUAA4IBAQCURxZrYhny6uViTctXsKRK4gMAWQG7
3qzYac4t9CU5bnv1R1Ln3dV8pr2aJOD5fWPn/Bns1Mxy0j+OCQzB4vZwsk8FRs8u
XDZN70+Og4TSHyM4/KpVLqdVmVC8pyvarhir1W5d5dhB+pFqK29zvWpmE+t4xkse
Kyo0Szhgf4Wue1C7nQcBuVLWFOVKSSRABO0G4dHmznWAceK6lkj4udD766U5oqL4
KNFTQ6MSxzjX6o5blvKIlxOeKnhMQC7fy6u00AWHNmPdN9y3kyOltrFTvgaOVOmm
eE8tsV2XikQ22SOMJzEe1KqdQKZn/huZP7Wg3apVFYJxAGGTnW2vkxoZ
-----END CERTIFICATE REQUEST-----

**Comment by kjur** [comment]
As I wrote before, CSR and certificate is very similar strucutre. Please refer x509-1.0.js source code.

**Comment by nathalials** [comment]
But I tried to use x509 methods to get the CSR information and it's not working.

For exemple, I did this:

`const x509 = new X509()
const raw = '-----BEGIN CERTIFICATE REQUEST-----
MIICljCCAX4CAQAwUTELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAjI3MQswCQYDVQQH
DAJzcDENMAsGA1UECgwEdGVzdDELMAkGA1UECwwCc3AxDDAKBgNVBAMMA29yZzCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMChYaRSN83Pv5EElAtWIyVn
Cp/KgPcjES1vOtAhjDs7jec8uH95PhEauO7IqxrwZmNxw9hRThx4URiJHUci4fkV
+kkfoDmxMRMMG9PtA5eM5ij5EHF/3gxjdpF0Q1LHJ45POMPKoKhg9NMeTvak9EL2
EFIr4dfUmOAFNy3lBHskogwKvwYmqLtPMf21ZZ6C/xhQ0te/AzJOuYr43tkvJHHv
fLutso1NZCZpxGQCVq0qJQLg0jpbm/PWeUNOYnfOzyZ/DMpAhKpH99hT8PhSqPqQ
0Wr1YCVaw4ERcvwogaiYH/Wge6+FYRSqU2A3FsIIV2DVbPD35CHmyue/SeXMMIEC
AwEAAaAAMA0GCSqGSIb3DQEBCwUAA4IBAQCURxZrYhny6uViTctXsKRK4gMAWQG7
3qzYac4t9CU5bnv1R1Ln3dV8pr2aJOD5fWPn/Bns1Mxy0j+OCQzB4vZwsk8FRs8u
XDZN70+Og4TSHyM4/KpVLqdVmVC8pyvarhir1W5d5dhB+pFqK29zvWpmE+t4xkse
Kyo0Szhgf4Wue1C7nQcBuVLWFOVKSSRABO0G4dHmznWAceK6lkj4udD766U5oqL4
KNFTQ6MSxzjX6o5blvKIlxOeKnhMQC7fy6u00AWHNmPdN9y3kyOltrFTvgaOVOmm
eE8tsV2XikQ22SOMJzEe1KqdQKZn/huZP7Wg3apVFYJxAGGTnW2vkxoZ
-----END CERTIFICATE REQUEST-----'

x509.readCertPEM(raw)
const sub = x509.getSubjectString().CN

`

I got this result:
sub = "/undefined="

**Comment by kjur** [comment]
Off course, they have some small differences. The same code can't be used.

**Comment by nathalials** [comment]
Would you mind telling me some tips to parse the CSR, please

**Comment by kjur** [comment]
Sorry but just read and understand x509-1.0.js source code will helps you.

**Comment by sportnet2016** [comment]
First, I converted from PEM string to hexadecimal.
Then I took a look at some x509-1.0.js class and found some ASN1HEX methods, but still I couldn't parse CSR too.
kjur, could you show an example of one info

**Comment by nathalials** [comment]
@kjur  @sportnet2016  I tried this too. But I was not able to parse csr info yet. Any tips? Pls.

**Comment by kjur** [comment]
Hi @nathalials and @sportnet2016 , I've added [KJUR.asn1.csr.CSRUtil.getInfo](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.csr.CSRUtil.html#.getInfo) method to get some field values such as a subject name or public key in the latest 6.1.3 release. Please try it.
