### ISSUE TITLE
Can I use this lib to read a CSR PEM and "extract"the info from it ?

### ISSUE THREAD

**Issue by leandrodvd** [kjur/jsrsasign#200]
I have a string containing a CSR in PEM format that I receive from an external service and I need to "read" this CSR PEM and present it's content to the user.

I found some methods to generate the CSR PEM from the  CSR data, but I couldn't find a method to the opposite, get the CSR info from an existing CSR PEM.

Is there anything ready in this lib that I can use for that ?

**Comment by leandrodvd** [comment]
Same questions was already asked here in Issue #197. Closing this one.

**Comment by kjur** [comment]
Hi @leandrodvd , I've added [KJUR.asn1.csr.CSRUtil.getInfo](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.csr.CSRUtil.html#.getInfo) method to get some field values such as a subject name or public key in the latest 6.1.3 release. Please try it.
