### ISSUE TITLE
jsrsasign inserting \r\n in PEM files

### ISSUE THREAD

**Issue by dsgill** [kjur/jsrsasign#201]
Hi Kjur,

I use jsrsasign to produce CRSs and private keys, both in PEM file format. I've noticed that in both cases, the pem files produced contain \r\n characters embedded in them as line separators. Private kets, CSRs, and certs from other sources do not contain these characters. Doesn't the presence of these characters in the file cause a problem for consumers of the file? Is there a way in the API to cause jsrsasign to not insert these characters into the PEM files? Thank you.

Don

**Comment by kjur** [comment]
As stated in the RFC 7468 Textual Encodings of PKIX, PKCS, and CMS Structures, PEM usually concludes newlines.
https://tools.ietf.org/html/rfc7468

**Comment by kjur** [comment]
I think just string replacing for \r\n will meet your requirement.
