### ISSUE TITLE
What is the date type of X509 certificate

### ISSUE THREAD

**Issue by rdesgrange-lf** [kjur/jsrsasign#203]
Hi. 

I tried to validate certificate with jsrsasign. Here is the code :
```js
'use strict';
const rs = require('jsrsasign');
const x509 = rs.X509();
x509.readCertPEM('<the cert as a string>');
console.log(x509.getNotAfter());
```
It display me something like that : 171014121549Z

What is this date type ? Moment.js doesn't know about it, neither epoch converter or other tool I found on the web, and the doc says nothing about it (http://kjur.github.io/jsrsasign/api/symbols/X509.html#getNotAfter). Maybe I didn't look in the right place ? 

In advance thanks.

**Comment by kjur** [comment]
171014121549Z is UTCTime notation. Please see https://tools.ietf.org/html/rfc5280#section-4.1.2.5.1

**Comment by kjur** [comment]
You can convert from UTCTime string to UNIX origin time by forrowing method:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.IntDate.html#.getZulu
