### ISSUE TITLE
V8 JavaScript Engine Compatibility

### ISSUE THREAD

**Issue by reedjeffry** [kjur/jsrsasign#205]
Hello,
I am trying to use jsrsasign within the appery.io platform. The platform supports adding 3rd party JavaScript libraries. However, the platform reports many errors with http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js. Can someone confirm if jsrsasign and dependencies supports the V8 JavaScript Engine?

regards

**Comment by Ruffio** [comment]
This looks like it is more a question than an issue reported. What kind of errors do you see? Is this still an issue?

**Comment by Ruffio** [comment]
@reedjeffry What you say?

**Comment by Ruffio** [comment]
@kjur this issue should be closed due to lack of response from originator. The issue was created on 19th of October 2016 but no responses since then...

**Comment by kjur** [comment]
Sorry but this ticket will be closed since there isn’t any further information.
