### ISSUE TITLE
String length limitation using JWT and secret key using HMAC-SHA*.

### ISSUE THREAD

**Issue by mookman288** [kjur/jsrsasign#206]
Hi, 

I originally posted this with an author of a different JWT library, but his work shows that it may not be an issue with his library, but with kjur/jsrsasign. I've included the pertinent information below, but if you'd like, you can view the entire thread, and @lcobucci's response, here:

https://github.com/lcobucci/jwt/issues/127

> I'm trying to integrate JWT between my API client, and API endpoint. Currently I'm just generating a string-based secret key using openssl_random_pseudo_bytes, converted from binary to hexadecimal. I'm using lcobucci/jwt (^3.2,) and kjur/jsrsasign (^6.1.1) from @kjur to facilitate communication.

> The issue that I'm having is that when I use a key with string length greater than 115 characters it fails validation, no matter what. If I trim the key down to 115 characters, I'm able to both sign and validate.

>Here's some sample tokens:

>kjur/jsrsasign:

>7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a:
>```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.UOir1kEf5v6g-KVUdYIS4eqXei8CBdctMn5pWfiL4aPzXWFTMt7hP5a4YCes063WF8Vear4WunrCdxC-HkkZTA
```
>7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0:
>```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.SzRW7n6I4HENi8knpS6NTCGHIT4MKgHX9UTzGZkp8O6E7eWegmkHcVHDrx18l1aGsZR07Yu6TitrPfEEiqCdAg
```

>lcobucci/jwt: 

>7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0a:
>```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.-GzjQGyDbDvDw_KISK1HPHdNivRpYqNEdm5OMFputKNORSb6nv8fNj7Fk7LvRUp-djUsw346QgHECFSuFGytlA
```
>7e65f6f2ef2298d16b15a8788b6e1aa9ae81ac205fe959d112c75bf715af9e0
>```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0IjoidGVzdCJ9.SzRW7n6I4HENi8knpS6NTCGHIT4MKgHX9UTzGZkp8O6E7eWegmkHcVHDrx18l1aGsZR07Yu6TitrPfEEiqCdAg
```

>Here's a verification tool by @kjur - https://kjur.github.io/jsrsasign/tool_jwt.html

>I just noticed that the tokens are identical using the 115 character key, versus the 116 character key. That explains why the library that generated the token is the only one that can validate it when using these longer keys. 

I hope this helps.

**Comment by kjur** [comment]
I don't think it is HMAC key length issue. "jsrsasign" has no HMAC key length limitation and
has automatic HMAC key type detection.

In the "tool_jwt.html" page, HMAC password type will be detected automatically.

Please take a look following API references:

https://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.sign
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Mac.html#.setPassword

In your case

- odd length string: password specified as string automatically
- even length [0-9A-fa-f]+ string: password specified as hexadecimal string automatically

To specify HMAC password type explicitly, please use attributes like following:

- {"utf8": "aaa"} - UTF-8 string
- {"rstr": "aaa"} - raw string
- {"hex": "616161"} - hexadecimal string
- {"b64": "Mi79.."} - Base64 encoded string
- {"b64u": "Mi7-_.."} - Base64URL encoded string

"jwt.io" page using old jsrsasign. So verification result will be the same.
