### ISSUE TITLE
Invalid CADES signature

### ISSUE THREAD

**Issue by SorianoMarmol** [kjur/jsrsasign#214]
Hi all

I've problems to get a valid CADES BES signature

I'm trying to validate the signature using http://signatures-conformance-checker.etsi.org/ and it's said that the signature is Invalid

With this:
      

`
    **sd = KJUR.asn1.cms.CMSUtil.newSignedData({**

          content: {
              type: '1.2.840.113549.1.7.1',
              hex: stringbuf 
          },

          certs: [cert_pem],
          signerInfos: [{

              hashAlg: 'sha512',
              sAttr: {
                  SigningTime: {timestamp},
                  SigningCertificateV2: {
                     array: [cert_pem],
                      // hashAlg: 'sha512', // **other error:** contentInfo.content.signedData.signerInfos.signerInfo[0].signedAttrs.attribute[2].attrValues.essSigningCertificateV2[0].certs.essCertIDV2[0].certHash field seems not to be present. Not found tag 4 corresponding to OCTET STRING in the field. Instead it has been found tag number 6 corresponding to type OBJECT IDENTIFIER

                  },

              },
              signerCert: cert_pem,
              sigAlg: 'SHA256withRSA', 
              signerPrvKey: private_key_pem,
          }]
      });
`

Error is:

> There has been a problem while trying to assign names to the ASN1 components.
The application will go on and check only fields with names assigned. Some of the fields will likely not be processed.
The problem has occurred in field: contentInfo.content.signedData.signerInfos.signerInfo[0].signedAttrs.attribute[3].attrValues.essSigningCertificateV2[0].certs.essCertIDV2[0] field seems not to be present. Not found tag 16 corresponding to SEQUENCE/SEQUENCE OF in the field. Instead it has been found tag number 4 corresponding to type OCTET STRING

The output around certificate V2 is

>         SEQUENCE

          ObjectIdentifier (1 2 840 113549 1 9 16 2 47)

          SET

            SEQUENCE

              SEQUENCE
                **OCTETSTRING** 8a261a06e05c28a092daa3d9455d337b645ae884bfdf240988181e9ecfa62322
                SEQUENCE
                  SEQUENCE
                    SET
                      SEQUENCE
                        ObjectIdentifier countryName (2 5 4 6)
                        PrintableString 'ES'
                    SET
                      SEQUENCE
                        ObjectIdentifier organization (2 5 4 10)
                        UTF8String 'FNMT-RCM'
                    SET
                      SEQUENCE
                        ObjectIdentifier organizationalUnit (2 5 4 11)
                        UTF8String 'Ceres'
                    SET
                      SEQUENCE
                        ObjectIdentifier commonName (2 5 4 3)
                        UTF8String 'AC FNMT Usuarios'
                  INTEGER 216384ff5bc3f9ea55f29427f9a36f1a
      SEQUENCE
        ObjectIdentifier SHA256withRSA (1 2 840 113549 1 1 11)
        NULL
      OCTETSTRING 80d118311bf91054f1599e0557178fcf..(total 256bytes)..53bf5e11db61a3de59b30cea6c054efd

In addition, I found a example with a Cades valid signature

 

     SEQUENCE
          OBJECT IDENTIFIER 1.2.840.113549.1.9.16.2.47 (signingCertificateV2)
           SET (1 elem)
             SEQUENCE (2 elem)

     SEQUENCE (1 elem)
      SEQUENCE (3 elem)
        SEQUENCE (2 elem)
         OBJECT IDENTIFIER 1.3.14.3.2.26 (SHA-1)
         NULL
        OCTET STRING (20 byte) 440B88D2FCCABA200C7EFD1AE5A1FFC35062BD89 (hash)
        SEQUENCE (2 elem)
          SEQUENCE( 1 elem)
           SEQUENCE (3 elem)
             SET (1 elem)
              SEQUENCE (2 elem)
                OBJECT IDENTIFIER 2.5.4.6 (countryName)
                PrintableString ES
             SET (1 elem)
               SEQUENCE (2 elem)
                 OBJECT IDENTIFIER 2.5.4.10 (organizationName)
                 PrintableString FNMT
             SET (1 elem)
               SEQUENCE (2 elem)
                 OBJECT IDENTIFIER 2.5.4.11 (organizationalUnitName)
                 PrintableString FNMT Clase 2 CA
          INTEGER 1019118382 (número de serie del certificado que se usó para firmar)
`

It seems that a valid signature insert info about the hash before the hash
"OBJECT IDENTIFIER 1.3.14.3.2.26 (SHA-1)" but kjur does'nt include this info if it's sha256 but I think this isn't the issue

If i edit the js including r.push(new f.AlgorithmIdentifier({name:h}))

the error said
> <CheckFailure check="Initial steps" testedBy="Tool">There has been a problem while trying to assign names to the ASN1 components.
The application will go on and check only fields with names assigned. Some of the fields will likely not be processed.
The problem has occurred in field: contentInfo.content.signedData.signerInfos.signerInfo[0].signedAttrs.attribute[3].attrValues.essSigningCertificateV2[0].certs.essCertIDV2[0].certHash field seems not to be present. Not found tag 4 corresponding to OCTET STRING in the field. Instead it has been found tag number 6 corresponding to type OBJECT IDENTIFIER
contentInfo.content.signedData.signerInfos.signerInfo[0].signedAttrs.attribute[3].attrValues.essSigningCertificateV2[0].certs.essCertIDV2[1] field seems not to be present. Not found tag 16 corresponding to SEQUENCE/SEQUENCE OF in the field. Instead it has been found tag number 4 corresponding to type OCTET STRING
</CheckFailure>

If I use other validation system like https://www.firma.infocert.it/utenti/verifica.php
it said: 	**Firma non Valida
Formato dell'attributo SigningCertificateV2 non valido**

**Comment by kjur** [comment]
SigningCertificate and SigningCertificateV2 attribute encoding bug was fixed after the version 9.1.0 (2020-Aug-24). Then I've verified a jsrsasign generated CAdES-BES signature by ETSI conformance checker successfully:
 http://signatures-conformance-checker.etsi.org/

I've confirmed its conformance with ETSI EN 319 122-1 v1.1.1 Building Blocks and Baseline.

So this ticket will be closed. Thank you.
