### ISSUE TITLE
Valid signature fails to verify using jsrsasign, but verifies with nodeJS crypto module

### ISSUE THREAD

**Issue by D-Nice** [kjur/jsrsasign#219]
Using node.JS' crypto module, the following signature is verified successfully:

```javascript
const verifier = crypto.createVerify('sha256WithRSAEncryption');
verifier.update(atob(oraclize_doc));
awsSignatureValid = verifier.verify(awsPublicCertificateRSA, awsSignature, 'base64');
```

Re-using the above code into what I believe is a jsrsasign equivalent for the browser, fails:
```javascript
var sig = new KJUR.crypto.Signature({ "alg": "SHA256withRSA" });
sig.init(awsPublicCertificateRSA);
sig.updateString(atob(oraclize_doc));
awsSignatureValid = sig.verify(new Buffer(atob(awsSignature)).toString('hex'));
```
returns 0 for awsSignatureValid

The variables across the two are the exact same
Also tried variations such as:
```javascript
var publicKey = KJUR.KEYUTIL.getKey(awsPublicCertificateRSA);
awsSignatureValid = publicKey.verifyWithMessageHash(ba2hex(sha256(atob(oraclize_doc))), new Buffer(awsSignature).toString('hex'));
```
still returns 0

Is there a compatibility issue with jsrassign, or is something on my end being done incorrectly?

**Comment by kjur** [comment]
```JavaScript
sig.updateString(atob(oraclize_doc));
```
Type of updateString argument seems wrong.

**Comment by D-Nice** [comment]
It takes a string, and oraclize_doc is a base64 encoded string, and atob decodes it into:
```
{
  "privateIp" : "172.31.50.80",
  "devpayProductCodes" : null,
  "availabilityZone" : "us-east-1c",
  "accountId" : "595816825690",
  "version" : "2010-08-31",
  "instanceId" : "i-0643469898a683c28",
  "billingProducts" : null,
  "instanceType" : "t2.micro",
  "pendingTime" : "2016-11-11T16:59:18Z",
  "imageId" : "ami-30176327",
  "architecture" : "x86_64",
  "kernelId" : null,
  "ramdiskId" : null,
  "region" : "us-east-1"
}
```

**Comment by kjur** [comment]
I've just added "datasign" and "dataverify" sample node script to repository.

https://github.com/kjur/jsrsasign/blob/master/sample_node/datasign
https://github.com/kjur/jsrsasign/blob/master/sample_node/dataverify

Any generated signature can also be verified by OpenSSL dgst command.
I hope those scripts help your investigation.

**Comment by kjur** [comment]
My Node.js crypto verified properly:

```JavaScript
var crypto = require('crypto');
var fs = require('fs');
var text = fs.readFileSync('aaa.txt');
var pub = fs.readFileSync('a.pub');
var signature = fs.readFileSync('a.sig');
var verifier = crypto.createVerify('RSA-SHA1');
verifier.update(text);
var isValid = verifier.verify(pub, signature, 'raw');
console.log("isValid=" + isValid);
```

How about to modify as following:

```JavaScript
awsSignatureValid = sig.verify(b64tohex(awsSignature));
```

**Comment by D-Nice** [comment]
Thanks for the replies, I'll play around with the scripts some more to see if I can find the culprit.

**Comment by D-Nice** [comment]
Thank you for the help Kenji, it was in fact an issue with the signature's hex conversion from base64. Your scripts helped me in finding and confirming it!
