### ISSUE TITLE
Is your openpgpjs usage lgpl okay?

### ISSUE THREAD

**Issue by mrichards-mdsol** [kjur/jsrsasign#224]
I started the discussion here
https://github.com/openpgpjs/openpgpjs/issues/506

I'm not a lawyer, but my interpretation of LGPL would mean a different way to import it into jsrsasign. What do you think here?

If you do need legal expertise maybe one of the non-profits like http://www.fsf.org/ might have someone who can advise.

**Comment by kjur** [comment]
Thank you for your reminder. I think I will remove DSA support until I find another suitable DSA library.

**Comment by kjur** [comment]
I've removed openpgpjs derived codes in jsrsasign 7.0.0 released today. Most of DSA class was re-written. So all of LGPL codes and its license are removed. Thanks.
