### ISSUE TITLE
Hex-encoded DER private to public key

### ISSUE THREAD

**Issue by gabmontes** [kjur/jsrsasign#225]
Hi @kjur! The lib is impressive, still I'm having some trouble to find out the way to do a specific task.

I have an hex-encoded DER private key string like '3074020101...' and need to obtain the associated public key, also in hex-endoded DER string format. How can I do that?

Thanks!!!

**Comment by kjur** [comment]
Can you show me your public key? I'll check it and provide a solution :)

**Comment by gabmontes** [comment]
Sure. From my private key in the same format, I need to obtain this public key (EC secp256k1):

'3056301006072a8648ce3d020106052b8104000a0342000426f5292eabca0365e1a26d318377f25b920a1d426d2fde130fbca618395537a6bb421645f6d26fa8bf4f23866d26cfc2bc81c4527066c08506c4b75466db6407'

**Comment by kjur** [comment]
Hi @gabmontes , you can load your public key as following:

```JavaScript
var pubKey = KEYUTIL.getKey("3056...", null, "pkcs8pub");
```

pubKey will be a KJUR.crypto.ECDSA key object for your public key. Thanks.

**Comment by gabmontes** [comment]
Thanks @kjur!

My initial question was how to load the private key and from that key, obtain the public key. But with the help of your answer on how to load the public key and taking a deeper look at the code, I found that I can load my private key using a code similar to this:

```js
var hKey = '3074020101...'

var key = ASN1HEX.getVbyList(hKey, 0, [1], "04")
var curveNameOidHex = ASN1HEX.getVbyList(hKey, 0, [2,0], "06")
var pubkey = ASN1HEX.getVbyList(hKey, 0, [3,0], "03").substr(2)
var curveName = KJUR.crypto.OID.oidhex2name[curveNameOidHex]

var ec = new KJUR.crypto.ECDSA({'name': curveName})
ec.setPublicKeyHex(pubkey)
ec.setPrivateKeyHex(key)
ec.isPublic = false
```

That code is what `getKey()` does on case 10.2 at https://github.com/kjur/jsrsasign/blob/cf31c931bd67d68278c45dba885f057e13bba507/keyutil-1.0.js#L1510. 

Is there a reason why the case I'm facing with is not supported by `getKey()`, as that piece of code only deals with encrypted ECDSA strings but not plain hex strings?

Thanks again!!

**Comment by kjur** [comment]
I can help you if you send me your code and a key which the error raised with. Thanks.

**Comment by gabmontes** [comment]
@kjur I created the private key using a simple Python code:

```python
import ecdsa, binascii
binascii.hexlify(ecdsa.SigningKey.generate(curve=ecdsa.SECP256k1).to_der())
```

The private key just created is, lets say:

`30740201010420026d5595f47e203d3c73c06977cd5a962dcfac688677ba4f1dd6f25018fd226ea00706052b8104000aa14403420004c3e9f0932bed4af185d614d01bda0fcbf9948cbe7c0d47f7c25f7818d576a6834b59a22f1e9fe626ea0dc0699893aa1a96762772e4199cb9de45e429ca402092`

I'm unable to load that key using `KEYUTIL.getKey()` as it reaches the end of the function and throws `not supported argument`. The following code do work:

```js
const hexKey = '3074020101...' // copied key above
const key = rs.ASN1HEX.getVbyList(hexKey, 0, [1], '04')
const curveNameOidHex = rs.ASN1HEX.getVbyList(hexKey, 0, [2, 0], '06')
const pubkey = rs.ASN1HEX.getVbyList(hexKey, 0, [3, 0], '03').substr(2)
const curveName = rs.crypto.OID.oidhex2name[curveNameOidHex]
const ec = new rs.crypto.ECDSA({ curve: curveName })
ec.setPublicKeyHex(pubkey)
ec.setPrivateKeyHex(key)
ec.isPublic = false
```

I can even get the public key in the same DER format with:

```js
new rs.asn1.x509.SubjectPublicKeyInfo(ec).getEncodedHex() // '3056301006072a8648ce...'
```

It would be great if `getKey()` is able to parse that key as it does with many other formats.

**Comment by kjur** [comment]
Thank you. I'll investigate it later.

**Comment by kjur** [comment]
Hi @gabmontes . There was a pull request to resolve this which adds support for hex pkcs8 private key.
https://github.com/kjur/jsrsasign/pull/163
I'll merge it later. Thanks.

**Comment by gabmontes** [comment]
Thanks @kjur ! That would be a great addition! Looking forward to updating my package with the merged functionality as soon as you are done with it.
