### ISSUE TITLE
Incorrect parameter in `getKey()`

### ISSUE THREAD

**Issue by gabmontes** [kjur/jsrsasign#227]
When `getKey()` parses case 10.2, private key by encrypted PKCS#5 PEM ECDSA string, it creates a new ECDSA passing the curve name to the constructor in the `name` property:

https://github.com/kjur/jsrsasign/blob/cf31c931bd67d68278c45dba885f057e13bba507/keyutil-1.0.js#L1521

The issue is the constructor requires the `curve` property instead:

https://github.com/kjur/jsrsasign/blob/master/ecdsa-modified-1.0.js#L497

So, when parsing the key with `getKey()`, the curve name will be always the default `secp256r1`.

**Comment by kjur** [comment]
Thank you. I'll investigate it later.

**Comment by kjur** [comment]
Hi @gabmontes , thank you. You are right. I'll fix it soon.

**Comment by kjur** [comment]
I've fixed it today's release 7.1.0.
