### ISSUE TITLE
Proper way to create a OpenSSL oneline format string from object

### ISSUE THREAD

**Issue by gabmontes** [kjur/jsrsasign#229]
Given a set of attributes, i.e in an object as follows:

```js
const subjectData = {
  O: 'Organization',
  CN: 'First Last',
  C: 'AU',
  localityName: 'Brisbane', 
  stateOrProvinceName: 'QLD',
  street: '123 main st',
  postalCode: '4120'
}
```

What is the proper way of creating the `subject` property needed to call `newCSRPEM()`?

```js
KJUR.asn1.csr.CSRUtil.newCSRPEM({
  subject: subjectData,
  ...
)
```

Passing the object as shown, throws the error `AttributeType name undefined: localityName` even when the attribute is defined in `KJUR.asn1.x509.OID`.

Please advise. Thanks!!

**Comment by kjur** [comment]
AttributeType name shall be defined in KJUR.asn1.x509.OID.atype2oidList.
Then you can use newCSRPEM as following:

```JavaScript
KJUR.asn1.csr.CSRUtil.newCSRPEM({
  subject: {str: "/CN=First Last/O=Organization/postalCode=4120/STREET=123 main st/L=Brisbane/ST=QLD/C=AU"},
  ...
)
```

**Comment by gabmontes** [comment]
Thanks @kjur !

Passing the object, as long as the keys match the defined ones in `KJUR.asn1.x509.OID.atype2oidList` as you said, works awesome.
