### ISSUE TITLE
package.json license

### ISSUE THREAD

**Issue by markalanrichards** [kjur/jsrsasign#230]
Would it be okay to replace the package.json license field that currently states MIT with something that shows off the mixed licence manner of this project.

Perhaps to point at a LICENSE file that cites the licence for the majority of code, which you have chosen MIT for and that also cites how to find the ext folder licences too.

If you try to put together a licences statement in a dependent project, so you can appropriately share them with your users, you might only find the ext folder and I guess other users might be skipping adding these ext folder licenses into their own copyright declarations.

If you try npm-licence in a project that depends on jsrsasign, you can probably see how easy it is to miss the ext folder ones.

Best
Mark

**Comment by kjur** [comment]
I couldn't understand npm-licence usage at a glance. If you can provide package.json pull request, I can merge it. Thanks.
