### ISSUE TITLE
Consider code splitting to avoid bloat on client

### ISSUE THREAD

**Issue by akselnordal** [kjur/jsrsasign#231]
Hi,

first of all - thanks for a great library! It would be great if the build/consumption process was a bit more transparent and in style with current popular library implementations; ie.
- code splitting, so that a client that only needs a the jwt-verification methods using a specific algorithm such as RS256 (assymetric encryption/verification) does not need to download and parse the entire library (85 kb - using min/gzip). Using CommonJs/ES6-modules instead of using a global library namespace would be a great start
- include a package.json that includes the build steps, to easy the effort for other contributors to create PRs

For examples, have a look at lodash and rx.js which applies similar approaches

**Comment by kjur** [comment]
There are part of JS files following URLs:

http://kjur.github.io/jsrsasign/ext/
https://github.com/kjur/jsrsasign/tree/gh-pages/ext
http://kjur.github.io/jsrsasign/min/
https://github.com/kjur/jsrsasign/tree/gh-pages/min

such as 

http://kjur.github.io/jsrsasign/ext/base64-min.js

You can choose part of JS files for your minimum requirement such as HS* JWS verification.

I'm planning to provide some set of library which is not full package such as HS* JWS or RSA signing/verification.

**Comment by brockallen** [comment]
> I'm planning to provide some set of library which is not full package and for limited usage such as HS* JWS or RSA signing/verification.

Was this ever done or published?

**Comment by kjur** [comment]
@brockallen Please see following:
https://github.com/kjur/jsrsasign/wiki/NOTE-jsrsasign-subset-package
