### ISSUE TITLE
X509 v3 extension parsing issue

### ISSUE THREAD

**Issue by sbweeden** [kjur/jsrsasign#235]
Started with this cert pem:
-----BEGIN CERTIFICATE-----
MIICLjCCARigAwIBAgIECmML/zALBgkqhkiG9w0BAQswLjEsMCoGA1UEAxMjWXVi
aWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwIBcNMTQwODAxMDAwMDAw
WhgPMjA1MDA5MDQwMDAwMDBaMCkxJzAlBgNVBAMMHll1YmljbyBVMkYgRUUgU2Vy
aWFsIDE3NDI2MzI5NTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKQjZF26iyPt
bNnl5IuTKs/fRWTHVzHxz1IHRRBrSbqWD60PCqUJPe4zkIRFqBa4NnzdhVcS80nl
ZuY3ANQm0J+jJjAkMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS4y
MAsGCSqGSIb3DQEBCwOCAQEAZTmwMqHPxEjSB64Umwq2tGDKplAcEzrwmg6kgS8K
PkJKXKSu9T1H6XBM9+LAE9cN48oUirFFmDIlTbZRXU2Vm2qO9OdrSVFY+qdbF9ot
i8CKAmPHuJZSW6ii7qNE59dHKUaP4lDYpnhRDqttWSUalh2LPDJQUpO9bsJPkgNZ
AhBUQMYZXL/MQZLRYkX+ld7llTNOX5u7n/4Y5EMr+lqOyVVC9lQ6JP6xoa9q6Zp9
+Y9ZmLCecrrcuH6+pLDgAzPcc8qxhC2OR1B0ZSpI9RBgcT0KqnVE0tq1KEDeokPq
F3MgmDRkJ++/a2pV0wAYfPC3tC57BtBdH/UXEB8xZVFhtA==
-----END CERTIFICATE-----

Pasted jsrsasign-latest-all-min.js into Chrome developer console, then ran the following:

var mycert="-----BEGIN CERTIFICATE-----\n"+"MIICLjCCARigAwIBAgIECmML/zALBgkqhkiG9w0BAQswLjEsMCoGA1UEAxMjWXVi\n"+"aWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwIBcNMTQwODAxMDAwMDAw\n"+"WhgPMjA1MDA5MDQwMDAwMDBaMCkxJzAlBgNVBAMMHll1YmljbyBVMkYgRUUgU2Vy\n"+"aWFsIDE3NDI2MzI5NTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKQjZF26iyPt\n"+"bNnl5IuTKs/fRWTHVzHxz1IHRRBrSbqWD60PCqUJPe4zkIRFqBa4NnzdhVcS80nl\n"+"ZuY3ANQm0J+jJjAkMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS4y\n"+"MAsGCSqGSIb3DQEBCwOCAQEAZTmwMqHPxEjSB64Umwq2tGDKplAcEzrwmg6kgS8K\n"+"PkJKXKSu9T1H6XBM9+LAE9cN48oUirFFmDIlTbZRXU2Vm2qO9OdrSVFY+qdbF9ot\n"+"i8CKAmPHuJZSW6ii7qNE59dHKUaP4lDYpnhRDqttWSUalh2LPDJQUpO9bsJPkgNZ\n"+"AhBUQMYZXL/MQZLRYkX+ld7llTNOX5u7n/4Y5EMr+lqOyVVC9lQ6JP6xoa9q6Zp9\n"+"+Y9ZmLCecrrcuH6+pLDgAzPcc8qxhC2OR1B0ZSpI9RBgcT0KqnVE0tq1KEDeokPq\n"+"F3MgmDRkJ++/a2pV0wAYfPC3tC57BtBdH/UXEB8xZVFhtA==\n"+"-----END CERTIFICATE-----\n";

var x509hex = X509.pemToHex(mycert);

X509.getHexOfTLV_V3ExtValue(x509hex, "1.3.6.1.4.1.41482.2");

This returned:

"312e332e362e312e342e312e34313438322e312e32300b06092a864886f70d01010b03820101006539b032a1cfc448d2"

However I think that is not quite right. I expected the value to be shorter, actually this much:
"312e332e362e312e342e312e34313438322e312e32"

If I use: openssl x509 openssl x509 -in mycert.pem -text
that shows correctly formatted output.

Similarly if I use a pure ASN1 decoder like: https://lapo.it/asn1js/
And paste in the certificate PEM data (without --- header/footer), I get back the correct octet string value of:
1.3.6.1.4.1.41482.1.2

**Comment by kjur** [comment]
Thank you for your report. I'll investigate it.

**Comment by kjur** [comment]
Your certificate seems correct as ASN.1 syntax but not correct for X.509v3 extension.
Your extension:
```
    [3] {
      SEQUENCE {
        SEQUENCE {
          OBJECT IDENTIFIER '1 3 6 1 4 1 41482 2'
          OCTET STRING '1.3.6.1.4.1.41482.1.2'
          }
        }
      }
```
Proper extension value shall be excapsulated by OCTET STRING as this sample:
```
    [3] {
      SEQUENCE {
        SEQUENCE {
          OBJECT IDENTIFIER authorityKeyIdentifier (2 5 29 35)
          OCTET STRING, encapsulates {
            SEQUENCE {
              [0]
                A1 72 5F 26 1B 28 98 43 95 5D 07 37 D5 85 96 9D
                4B D2 C3 45
              }
            }
          }
```
