### ISSUE TITLE
Why is PKCS1 public key not supported?

### ISSUE THREAD

**Issue by cristianocoelho** [kjur/jsrsasign#237]
I'm wondering this, I see you can read a pem PKCS1 private key in order to sign something, but if you want to use the same format for a public key it won't work, and you need to either convert it to another format or use the object/hex format (such as {n: "..", e:"..."})
Am I missing something? I'm talking about public keys created as "-----BEGIN RSA PUBLIC KEY-----... "

**Comment by kjur** [comment]
Hi. As you said jsrsasign doesn't support PKCS#1 public key since OpenSSL seems not to support PKCS#1 public key export/import. I couldn't find any DSA or ECDSA PKCS#1 public key example.

**Comment by venik** [comment]
Hi. I faced the same problem and wrote small function to create RSA object with PKCS1 ASN.1 (without begin rsa public ....). I hope it will people who google for the same)

function getRsaFromPubKey(pubKeyB64: string): RSAKey {
    const pubKeyDecoded = b64tohex(pubKeyB64);

    // jsrsasign cannot build key out of PEM or ASN.1 string, so we have to extract modulus and exponent
    // you can get some idea what happens from the link below (keep in mind that in JS every char is 2 bytes)
    // https://crypto.stackexchange.com/questions/18031/how-to-find-modulus-from-a-rsa-public-key/18034#18034
    const modulus = pubKeyDecoded.substr(50, 128);
    const exp = pubKeyDecoded.substr(182, pubKeyDecoded.length);

    return KEYUTIL.getKey({n: modulus, e: exp});
}

https://gist.github.com/venik/a9c02e065adaf13be4dba4b305869e93

**Comment by getify** [comment]
@kjur my openssh (not openssl) absolutely creates PKCS1 public PEM keys. I just did it with this command:

```
ssh-keygen -f ~/.ssh/id_rsa -m 'PEM' -e > public.pem 
```

I know jsrsasign supports PKCS1 private keys, so it would be really nice if it could also support that format of public key. Please consider re-opening this feature request.

**Comment by getify** [comment]
@venik thank you for that code. I just tried this:

```js
getRsaFromPubKey(`-----BEGIN RSA PUBLIC KEY-----
MIICCgKCAgEAyqnNDb+8w27aLj8rbA3GtrMRkcHFZeE1a/W3i4jjj92KyHEMMPoU
ErnOLaVchO1g/Z0TG38BjJllcXdHvPBtbhZmjLpXLbzqZuhNRdrji4VU+AsByYQH
1+6vDBRIkNvpBgP0rAIyFUcnapRq4E42mtLqJUFXlyGSBmgkeEouYTcBlO4oasH1
3NH4hfLS6Z6NoXCaZwDwLqPNjZVUrZlocwwoAs1C1rJErWD9f7QsFZa93zV1zTKF
FsNQSeYxvFf9cL0zK57z1OJPmMfOyCZa95TWNRTVSU37GWeew1IfMRowlN1djqEp
OFvIPD/6P9593pkvZ61oEWCMcKw/9nG0W3Dpmu9JUDljElnBUAViBG29/g6dRsGK
FYNQRCXFd+bNsjQovErlqIfm43yvGa6pa0crzHglfOD6tFvGY6pzVLhX7ybfa7sO
uNdLVWVvoQmSj2sSk68jTXS9m6zN29SCJd9Jp2dou7wiG5vOuU/y90H+8gi2AwO7
re4u1mj4L7grvDCmWJ0FaOMPZS6TQ/9coHRH/5ABRAEJQHjc0Z4DaV8ZVosclJA0
U/+GtmKtc00suWK0ae7DuvN/y9cShEorrZUNdM62j6dnmP1J0RVdW8UZ8RXgdllE
2Ai1zguyWVndzAVVEZOznnXOR1D8fWOD5BzLkm1bU48rkWE0DUWf8PECAwEAAQ==
-----END RSA PUBLIC KEY-----`);
```

It produced this console output:

```
RSAKey {n: BigInteger, e: Infinity, d: null, p: null, q: null, …}
```

That looks awfully suspicious to me, of `e` being value `Infinity`. That's bad, right?

Moreover, I tried to create a signature with the private key, and then verify it with this public key, and the verification failed (no error, just not a match).

So it seems like maybe your conversion routine isn't quite right? Or am I missing something else?

**Comment by venik** [comment]
@getify I think you RSA length is different to mine (I think I used rsa 512). So you will need to fix constants to make it work. this link https://lapo.it/asn1js/ would help (as expected it shows correct exponent). But be advised, to make n strictly positive it has additional 0 in front of MSB 1 which is not a part of they key - you will need to discard it

**Comment by Arucard89** [comment]
Is there any way to convert rsa key object to pem PKCS#1?
