### ISSUE TITLE
Infinite loop when validating an invalid DSA signature

### ISSUE THREAD

**Issue by nemesv** [kjur/jsrsasign#238]
The following code goes to an infinite loop:

    dsa.verifyWithMessageHash("033d9e479b5af8c425c63dd457c0026fef5f9c96", "302c0214240000000000000000000000000000000000000002140000000000000000000000000000000000000000");

After some investigation we realized that the line `var w = s.modInverse(q);` fails because `s` is zero.

In theory these checks supposed to prevent this:

	// NIST FIPS 186-4 4.7 DSA Signature Validation (p19)
	// 3.1. 0 < r < q
	if (BigInteger.ZERO.compareTo(r) > 0 || r.compareTo(q) > 0)
	    throw "invalid DSA signature";

	// 3.2. 0 < s < q
	if (BigInteger.ZERO.compareTo(s) > 0 || s.compareTo(q) > 0)
	    throw "invalid DSA signature";

In our understanding to make sure that `s` is **Greater and not Equal to 0** the correct code should be `BigInteger.ZERO.compareTo(s) >= 0`. The same is true for all the other 3 checks.

**Comment by kjur** [comment]
Thank you for your report. I'll fix in the future release.

**Comment by kjur** [comment]
The fix will be released in coming 7.1.6. Thanks.

**Comment by kjur** [comment]
I've released 7.2.0 today and issue was fixed. Thanks.

**Comment by nemesv** [comment]
Thanks for the fix!
