### ISSUE TITLE
Does jsrsasign.js on npm package work with browser?

### ISSUE THREAD

**Issue by maruilian11** [kjur/jsrsasign#242]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs). We have hosted your popular lib on https://cdnjs.com. And we fetch your `jsrsasign.js` from [npm package](https://www.npmjs.com/package/jsrsasign). But recently some users responded that files can't work with browser, we should fetch `jsrsasign-latest-all-min.js` instead. So I just want to confirm if `jsrsasign.js` on npm package is not for browser usage before we delete them on cdnjs server.
Thank you very much!

https://github.com/cdnjs/cdnjs/issues/10881#issuecomment-289203659

**Comment by kjur** [comment]
jsrsasign.js from npm is not available for web browsers. Please use jsrsasign-latest-all-min.js on browsers. Thanks.

**Comment by maruilian11** [comment]
Thank you :)

**Comment by froatsnook** [comment]
I'm using `"jsrsasign": "^5.0.12"` from npm in the browser using webpack.  To fix the errors with `fs`, put:

```javascript
  node: {
    fs: "empty",
  },
```

in your webpack config.

**Comment by maruilian11** [comment]
Hi @kjur, is it possible to rename `jsrsasign-latest-all-min.js` to `jsrsasign-all-min.js` in future versions? Because we provide all versions of lib on cdnjs website, use `latest` in filename may be a little confused.
thank you.

**Comment by maruilian11** [comment]
Sorry, our manager want me to confirm more clearly because if we remove files from our server, that will influence all users. Do all versions on npm package not work with browser?
thanks!

**Comment by kjur** [comment]
Yes, all versions on npm package not work with browser.

**Comment by maruilian11** [comment]
@kjur Thanks for quick reply! And is it possible to rename `jsrsasign-latest-all-min.js`? Because we fetch files  directly by auto-update bot. Thanks!

**Comment by kjur** [comment]
@maruilian11 What name do you need?

**Comment by maruilian11** [comment]
`jsrsasign-all-min.js` will be fine. Thank you very much! Sorry for asking about modifying.

**Comment by kjur** [comment]
Is it fine if keep providing following URL?:
https://kjur.github.io/jsrsasign/jsrsasign-all-min.js

For backword compatibility I'll also keep providing
https://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js.

I'll just copy from jsrsasign-latest-all-min.js to
jsrsasign-all-min.js.

**Comment by maruilian11** [comment]
yes, it's fine! thanks!

**Comment by kjur** [comment]
Hi @maruilian11 , I've added jsrsasign-all-min.js and also in the future releases.
https://kjur.github.io/jsrsasign/jsrsasign-all-min.js

**Comment by maruilian11** [comment]
@kjur Sorry for mistaking your meaning! We still need the file put on repo, so we can use **git tags** to fetch the file automatically.

**Comment by kjur** [comment]
Which branch shall be tagged for jsrsasign-all-min.js, master or gh-pages?

https://github.com/kjur/jsrsasign/tree/master
https://github.com/kjur/jsrsasign/tree/gh-pages

**Comment by maruilian11** [comment]
@kjur Either of them is ok, thank you.

**Comment by kjur** [comment]
@maruilian11 ,
"jsrsasign-all-min.js" is now placed in master branch.
https://github.com/kjur/jsrsasign/tree/master
Thanks.

**Comment by kjur** [comment]
Hi @maruilian11 .
These don't seem proper jsrsasign.js. They use jsrsasign JavaScript code for Node.js which is not work on browser. So these CDNs don't work properly. Please fix them.
https://cdnjs.com/libraries/jsrsasign

**Comment by maruilian11** [comment]
@kjur Sorry for the late reply.
@PeterDaveHello Please take a look. Files on cdnjs git repo have been updated, but the website link seems not.
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jsrsasign/7.2.1
https://cdnjs.com/libraries/jsrsasign/7.2.1

**Comment by kjur** [comment]
Hi @maruilian11 , currently https://cdnjs.com/libraries/jsrsasign/ works fine in the latest version. Thanks.

**Comment by maruilian11** [comment]
@kjur Yes, but old versions before v7.2.1 still using the wrong files, we should fix it. Sorry, it may take some times to do that since we got lot of work to do.

**Comment by kjur** [comment]
@maruilian11 I got it. Thanks.

**Comment by maruilian11** [comment]
Looks like all versions are using the right file now. :smile:
