### ISSUE TITLE
Failure to validate JWT correctly.

### ISSUE THREAD

**Issue by dancrumb** [kjur/jsrsasign#243]
I have some code intended to validate a JWT.

The JWT is:

```
var jwt = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJkcnVtbmV5QGplbGx5dmlzaW9uLmNvbSIsImlhdCI6MTQ5MDY3MTk2OCwiZXhwIjoxNDkwNjc1NTY4fQ.h_7rQ2LlNM7mONQRixmSHtmJdmK4b3ojzcAU8toUDQ0fJKZVu4H7p2peF9HeA5NNFpU6zNAffykocyCkdtbPcCQDhJDR4mugHqUpnDIXqACqehdR63ce0rZWUd1KHXTFEmhSmGRRiRJ4jasqx4xieHXKpqIQenD2xaSgXdvLW0o\'
```

The certificate string is:
```
var certString = '-----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIfJIADeEl0lnjoy9I9KEIiv3/GiHz6MZlUlz4Z9nMhT14NXArrOkhiQZHJVvKYxqOCWvzNSRWGgwDBc/OhK1InFl4HseCkIkpJ5evHPUDa8TCgKuej4IJehvac+7tlInX0Y+7RArO2HbqzjGE4cFmxcbAufK6VwNcB4EVI1vfPQIDAQAB-----END PUBLIC KEY-----'
```

With this code:

```
var pubkey = KEYUTIL.getKey(certString);
var isValid = KJUR.jws.JWS.verifyJWT(jwt, pubkey, { alg: 'RS256' });
```

`isValid` is coming back as false. However, I have confirmed that the signature is valid using https://jwt.io/

What am I missing here?

**Comment by kjur** [comment]
It seems "jwt" is wrong token since it concludes "backslash" at the end of string which is not permitted character for Base64URL encoding.

**Comment by dancrumb** [comment]
I think that must be a typo.

I get the same result with:

`jwt = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJkcnVtbmV5QGplbGx5dmlzaW9uLmNvbSIsImlhdCI6MTQ5MDgzOTcxMSwiZXhwIjoxNDkwODU3NzExfQ.YvzedqQ2r_eQ6_I684FiJ-DBBgkm6AwANn5aOyvOT5nyUn8rm0-z8OiIOJqx2sG6hS6674zxJbcoo1wFs8fJSpZal01-aw9UC-3PrBaAWUS00FXh0d9Rej-g2ZzY1EHoS2Or83mI96V-hO3Bql-KXiWDZJ00JMFd19pJHKa1ceU';`

Can you repoen and take another look, please?

**Comment by kjur** [comment]
I've check it. Its RSA signature and JWS signature is fine but JWT properties seem wrong. Please see following API document for JWT property validation:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verifyJWT

**Comment by dancrumb** [comment]
Thanks.

I figured out that the issue is that the `alg` property in the `acceptField` *MUST* be an array, even if there's only on valid algorithm.
