### ISSUE TITLE
KEYUTIL is not defined

### ISSUE THREAD

**Issue by nukec** [kjur/jsrsasign#245]
I am using angular2 implementation of oidc for identity server authorization. This is the implementation: https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.validation.ts

Problem here is that KEYUTIL is not defined after authorization with IdentityServer4. What could cause a KEYUTIL is not defined issue? Missing some library ?

**Comment by kjur** [comment]
Sorry but I've never tested and supported jsrsasign with Angular2. It seems jsrsasign is not loaded properly.
