### ISSUE TITLE
NotBefore and NotAfter are not complete

### ISSUE THREAD

**Issue by lutchit** [kjur/jsrsasign#246]
Hello, 

In x509-1.1.js, I think there is a mistake about notAfter() and notBefore() functions. In returned strings, first two numbers are missing.

For example, if you parse the given example here: http://kjur.github.io/jsrsasign/tool_certview.html , you obtain: From 100531061808Z To 200528061808Z
But you should obtain: From **20**100531061808Z To **20**200528061808Z.

**Comment by kjur** [comment]
Sorry but this works as designed.
https://kjur.github.io/jsrsasign/api/symbols/X509.html#getNotBefore
getNotBefore and getNotAfter function returns a string contents of UTCTime or GeneralizedTime.
In this certificate, it has "100531061808Z" of UTCTime and it will not return "YYYYmmDDHHMMSSZ" format string for UTCTime. Thanks.

**Comment by lutchit** [comment]
Then, how do you know if the certificate is in 2000's or 1900's ?
I don't find any documentation that says that UTCTime is "YYmmDDHHMMSSZ", can you help me to clarify this point ?

Do you know how to parse notBefore and notAfter to obtain Date in JS ? Something like this ;

```
var notAfter = new Date('20' + c.getNotAfter().slice(0,2),
                        c.getNotBefore().slice(2,4) - 1,
                        c.getNotBefore().slice(4,6),
	
                        c.getNotBefore().slice(6,8),
                        c.getNotBefore().slice(8,10),
                        c.getNotBefore().slice(10,12));
```

Thanks

**Comment by kjur** [comment]
At this time "jsrsasign" doesn't provide any function or method to get "Date" object from validity field. So you need to implement it. Please see definition of validity field.
https://tools.ietf.org/html/rfc5280#section-4.1.2.5.1

**Comment by kjur** [comment]
Hi @lutchit , I've added zulutodate converter function in the latest release 7.1.3.
https://kjur.github.io/jsrsasign/api/symbols/global__.html#zulutodate
You can do as 
```JavaScript
var notAfter = zulutodate(c,getNotAfter());
```
Sample tool page is also updated.
https://kjur.github.io/jsrsasign/tool_certview.html

Thanks.

**Comment by lutchit** [comment]
Hi @kjur,

Thank you a lot for your personal investment to answer my request. It's exactly what I want.

Have a good day, thanks.
