### ISSUE TITLE
Too big bundle for npm

### ISSUE THREAD

**Issue by mtrias** [kjur/jsrsasign#247]
Hi!

The npm bundle of this project is `286K`, and since the distribution does not contain the sources (like when imported through Bower) i'm forced to include the whole bundle in the browser even if I use a couple of functions.

Do you think the `package.json` file could be updated in order to include the source files? (BTW I could not find a package.json in this repo, i'm assuming is being generated somewhere else ?)

I'm able to submit a PR once I know what's the right thing to do.

![image](https://cloud.githubusercontent.com/assets/801752/24615353/678d9394-1864-11e7-8703-731428612e1e.png)

**Comment by kjur** [comment]
Thank you for your comment. If you send me your pull request, I'm grad to merge it.

**Comment by mtrias** [comment]
Ok, wow. Took a deeper look at this project and found it a bit more difficult to solve than what I expected. 

The major issue I found is that source files are scattered around a few places instead of in an `/src` folder like it's done in other javascript projects.

Since i'm new to this project, I'm pretty sure I missed a lot of things, so take all this as ideas / suggestions. I'm not 100% sure all this is right. 

Here's one way to fix my issue:
1. create an `npm/src` directory
2. symlink all the source files into it
3. run `npm publish` in the `npm` directory

That's a bit dirty, but should work.

Now the right way to do it, would break backwards compatibility and require a major version bump, and surely a lot of help from you.

1. move `npm/README` to `/README`. (It looks like the information in `/README` is already present in `npm/README`)
2. move `npm/lib` to `/lib` ?
3. move `npm/package.json` to `/package.json`
4. create an `/src` directory and move all the source files into it.
5. update the rest as needed (`Makefiles`, etc)
6. mark npm-util as ignored in `/package.json`

**Comment by kjur** [comment]
Thank you for your advice. I may update them in the future.
