### ISSUE TITLE
Upgrade from old version call to jws.verifyJWSByPemX509Cert

### ISSUE THREAD

**Issue by sattaman** [kjur/jsrsasign#248]
While implementing an [ID server client](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/JavaScriptImplicitClient%20Manual/index.html), I have been trying to update some code which calls

`if (jws.verifyJWSByPemX509Cert(id_token, cert)) {`

as far as I can tell this needs to change to 

`if (KJUR.jws.JWS.verify(id_token, cert)) {`
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verify

I am hitting the following error though

```
// 3.3. check whether key is 
RSAKey obj if alg is RS* or PS*.
    if (algType == "RS" || algType == "PS") {
    if (!(key instanceof RSAKey)) {
        throw "key shall be a RSAKey obj for RS* and PS* algs";
    }
} 
```

I have created a question on[ SO here](http://stackoverflow.com/questions/43189577/when-using-identity-server-login-do-i-need-to-validate-implicit-flow-token). I can delete either this issue or the SO question if the crosspost is an issue. 

Can anyone advise?

**Comment by kjur** [comment]
Please try following:
```JavaScript
pubKey = KEYUTIL.getKey(cert);
if (KJUR.jws.JWS.verify(id_token, pubKey)) {
...
```
