### ISSUE TITLE
Failure to validate signature

### ISSUE THREAD

**Issue by ohadbp** [kjur/jsrsasign#249]
Hey, 

I am signing a message on server using Java and trying to validate signature on client.
Using the example in the Signature class tutorial this is my verification code:

`var cert = "-----BEGIN CERTIFICATE REQUEST-----" +
                "MIIBzjCCATcCAQAwgY0xCzAJBgNVBAYTAlVTMREwDwYDVQQIEwhOZXcgWW9yazER" +
                "MA8GA1UEBxMITmV3IFlvcmsxETAPBgNVBAoTCE91dGJyYWluMREwDwYDVQQLEwhP" +
                "dXRicmFpbjERMA8GA1UEAxMIT3V0YnJhaW4xHzAdBgkqhkiG9w0BCQEWEHJuZEBv" +
                "dXRicmFpbi5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOjWo5P3dvUI" +
                "usrwy36RATmP7iUUC8U1FuYtKEHBCWOLNlFV2sCElshm1q4lOqTiZR4ZDml/lRgF" +
                "HSQQ7SKW1138iVdH2P+WyRYd55lFeORQpN3kdeu3e5crr+Wxqqz07epaEAQfou7m" +
                "pIqmeDswlM812WB9rOIy+vW1wohdwfSbAgMBAAGgADANBgkqhkiG9w0BAQUFAAOB" +
                "gQAVKb8uXBjnvUOBplVYdtyNJ45NvKa/tITnRpPxbPaeMgdzTVD21LhijzRHhigs" +
                "QeN8hm+FH5cs8J7BXZgTdIfnT6n/+tIqshriYxZPSMoSOPKURtwvunSADPFHxD+X" +
                "yxV1vXOZWhdeHeK8wIxUzGMkGXxjuNRM9qXKYXarhA2pGA==" +
                "-----END CERTIFICATE REQUEST-----";
        var sig = new KJUR.crypto.Signature({"alg": "SHA256withRSA"});
        sig.init(cert); // signer's certificate
        sig.updateString(origUrl);
        var isValid = sig.verify(signedUrl);`

However, it fail on the sig.init() step with the error: 'Uncaught init failed:not supported argument'

I also tried using Public Key instead of a certificate but verification keep failing for some reason.
I am pretty sure the signature is valid because verify it on server pass successfully.

Any idea?

Thanks.

**Comment by kjur** [comment]
Your "cert" is not proper X.509 certificate. It's "Certfificate Request". You need to provide a certificate for it.
