### ISSUE TITLE
what does that mean？ PKCS1_OAEP?   * NOTE: (*) is not supported in Java JCE，how about python?

### ISSUE THREAD

**Issue by x-falcon** [kjur/jsrsasign#250]
Here is supported canonicalized cipher algorithm names and its standard names:
<ul>
<li>RSA - RSA/ECB/PKCS1Padding (default for RSAKey)</li>
<li>RSAOAEP - RSA/ECB/OAEPWithSHA-1AndMGF1Padding</li>
<li>RSAOAEP224 - RSA/ECB/OAEPWithSHA-224AndMGF1Padding(*)</li>
<li>RSAOAEP256 - RSA/ECB/OAEPWithSHA-256AndMGF1Padding</li>
<li>RSAOAEP384 - RSA/ECB/OAEPWithSHA-384AndMGF1Padding(*)</li>
<li>RSAOAEP512 - RSA/ECB/OAEPWithSHA-512AndMGF1Padding(*)</li>
**NOTE: (*) is not supported in Java JCE.<br/>**
Currently this class supports only RSA encryption and decryption. 
However it is planning to implement also symmetric ciphers near in the future.

## I use encryptOAEP(), but can't decode on server.
how ever the  encrypt()  work well.

Does OAEP not support JCE , Python ?

**Comment by kjur** [comment]
Sorry but I don't know OAEP support in Python. I think BouncyCastle JCE supports RSA OAEP.
https://www.bouncycastle.org/java.html

**Comment by x-falcon** [comment]
well, thank you
