### ISSUE TITLE
Bower installation Broken

### ISSUE THREAD

**Issue by aagrawal20** [kjur/jsrsasign#252]
I tried install jsrsasign through bower install jsrsassign --save and it gives an error
bower jsrsasign=jsrsasign#5.0.1       not-cached https://github.com/kjur/jsrsasign=jsrsasign.git#5.0.1
bower jsrsasign=jsrsasign#5.0.1          resolve https://github.com/kjur/jsrsasign=jsrsasign.git#5.0.1
bower jsrsasign#*                         cached https://github.com/kjur/jsrsasign.git#7.1.3
bower jsrsasign#*                       validate 7.1.3 against https://github.com/kjur/jsrsasign.git#*
bower jsrsasign=jsrsasign#5.0.1          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/kjur/jsrsasign=jsrsasign.git", exit code of #128 fatal: unable to access 'https://github.com/kjur/jsrsasign=jsrsasign.git/': The requested URL returned error: 400

Additional error details:
fatal: unable to access 'https://github.com/kjur/jsrsasign=jsrsasign.git/': The requested URL returned error: 400

**Comment by kjur** [comment]
Sorry but the error was not reproduced in the latest version.

Please try "bower install jsrsasign".
