### ISSUE TITLE
Consider adding option to verify existing PKCS7 signature and parse data into CMS objects

### ISSUE THREAD

**Issue by chaki90** [kjur/jsrsasign#259]
I only see the option to create my CMS signed data. But, what about parsing existing CMS signed data and verifying the signature?

**Comment by kjur** [comment]
Thank you for your comment. It may be added in the future release.

**Comment by kjur** [comment]
CMSUtil.verifySignedData method is added in 8.0.4 release today.
https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.cms.CMSUtil.html#.verifySignedData
