### ISSUE TITLE
generate ecdsa key 

### ISSUE THREAD

**Issue by KhaRoMa** [kjur/jsrsasign#262]
how i can generate key  : k1PrvP8PPem used to signe JWS

**Comment by kjur** [comment]
Try this:

```JavaScript
kp = KEYUTIL.generateKeypair("EC", "secp256r1");
pem = KEYUTIL.getPEM("kp.prvKeyObj, "PKCS8PRV");
```

**Comment by KhaRoMa** [comment]
i tried this but i can't extract the private key like this:

kp = KEYUTIL.generateKeypair("EC", "secp256r1");
pem = KEYUTIL.getPEM("kp.prvKeyObj, "PKCS8PRV");

var prv = KEYUTIL.getKey(pem );


 Uncaught TypeError: KEYUTIL.getPEM is not a function

**Comment by kjur** [comment]
Sorry but I couldn't reproduce the error:
```JavaScript
kp = KEYUTIL.generateKeypair("EC", "secp256r1");
pem = KEYUTIL.getPEM(kp.prvKeyObj, "PKCS8PRV");
prv = KEYUTIL.getKey(pem); // prv = kp.prvKeyObj
```
This works fine.
