### ISSUE TITLE
X509.parseExt() fails for V3 certificate without any extensions

### ISSUE THREAD

**Issue by aseigler** [kjur/jsrsasign#265]
Example cert (from https://github.com/Unicon/cas-adfs-integration/blob/master/cas-server-support-wsfederation/src/test/resources/adfs-signing.crt):

```
-----BEGIN CERTIFICATE-----
MIIC3DCCAcSgAwIBAgIQfvG8NFyPxbVHf9gz7U8TOTANBgkqhkiG9w0BAQsFADAq
MSgwJgYDVQQDEx9BREZTIFNpZ25pbmcgLSBhZGZzLmV4YW1wbGUuY29tMB4XDTE0
MDIyNjIyMDcyOVoXDTE1MDIyNjIyMDcyOVowKjEoMCYGA1UEAxMfQURGUyBTaWdu
aW5nIC0gYWRmcy5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJTATfLi3ZWlVemGuK576Sup3dNBD+hRs1Ki+VBk4WszR2+/UIiUkraK
VcnUgNpCrBGna1VntVmxZSGZyaLoFQq//RkLNKqRUfl5aMYBXiEa0r7sh4INRXtj
gKtBXne1ifxLMdZTtyYfOKWX6GMzi9bLyen+cIMgODivnpiFG8MuxL32ZeChC3if
uYojwgGgPb6u/o0bKjTr07GvuQyhpfwzmF/6ZYK/3a/NWJ5P1RtsUhtuFoOWJqn8
cxn4AzcJTuxKyIUEgxpWaW+iRwqPALtgr+EhXbRR/2kDnJCGxh7PEXEUkKSA7AWx
kqB6VZU+V2g5vwLWyI8Ke09h7xSZ0z8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
fVY/99ZPq1k/uHI+pM+sigus7Jm2wfY0y95wDK265ZuhMKEiNYdOzT9tsXGFe4Aq
9DDygixD0Zk2Ud0q3F1Y1eyxXn5JATmW6iyMtr5x/dhRnzQSZWJw0evAxC2OjHSB
i3dQwcP6fjWFA1VH9r+1HQyEangF2AyTUoRddFh7UcoxzYFfhDCyNU9xOaovXNuE
g6H9KJX41xBSLnI8cBg+rAGelXWuLVdrJ3CJ0c6WB9iDrq96vGW0HuKXgeKbq/xD
V5el1gq/hD+kqd9lVSIAR73tLyl7WC++nSpj6JLuNAzA36Cxu1dNaGscaMPgegQK
h4JQjIleD89XV2sdjwXsog==
-----END CERTIFICATE-----
```

**Comment by kjur** [comment]
Thank you for your report. I'll investigate it.

**Comment by kjur** [comment]
Hi. Sorry but X.509v3 certificate without any extension is not supported now. This issue will be fixed in the future. Thanks.

**Comment by Ruffio** [comment]
How come this issue is closed, when it is still an issue? The issue should be closed when it no longer exists. I have searched the wiki/documentation and can find no reference to, that v3 without extension is not supported.

I really think that this is a cool project and would love to implement this so I can avoid a round trip to the server. Do we have an ETA of the implementation? Can I help with test or something else?

**Comment by kjur** [comment]
X.509v3 certificate without any extension supported in 7.2.2 released today.

**Comment by Ruffio** [comment]
That is so cool. I will have a go at it tomorrow. Thanks :-)
