### ISSUE TITLE
cdnjs at Cloudflare not available

### ISSUE THREAD

**Issue by Ruffio** [kjur/jsrsasign#267]
I just want the pure min.js version, but I can't download it from: https://cdnjs.com/libraries/jsrsasign

The page points to these but none are working:
https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/7.2.1/jsrsasign.js
https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/7.2.1/jsrsasign.min.js
https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/7.2.1/jsrsasign.min.js.map

I just get a:
404 Not Found
---
nginx

**Comment by kjur** [comment]
Sorry but please escalate it to CDNJS. CDNJS is providing wrong jsrsasign.js file which will not work properly on browsers. I've mentioned it but there is no response.

**Comment by Ruffio** [comment]
Roger that. Can I email you?
