### ISSUE TITLE
Unable to parse base64 encoded

### ISSUE THREAD

**Issue by Ruffio** [kjur/jsrsasign#268]
I have imported latest jsrsasign-all-min.js.

using this on a page:
 var cert = new X509();
        cert.readCertPEM(metadataInput);
        alert(cert.getSubjectString());

where metadataInput is the below string:

-----BEGIN CERTIFICATE-----
MIIFEjCCAvqgAwIBAgIBAjANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJESzEWMBQGA1UEChMNVmVqbGUgS29tbXVuZTEkMCIGA1UEAxMbVmVqbGUgS29tbXVuZSBGZWRlcmF0aW9uIENBMB4XDTE0MDIwMzIwNTYwMFoXDTM0MDIwMzIwNTYwMFowTjELMAkGA1UEBhMCREsxFjAUBgNVBAoTDVZlamxlIEtvbW11bmUxJzAlBgNVBAMTHlZlamxlIEtvbW11bmUgSWRlbnRpZnkgU2lnbmluZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL68mPxwqGaTQjVkZCH+nt/fl6EEiNhguJtROZDTG5+RNIG4s4+M50pl3CaQzkohoiekgkNzogOP2LG1tlpjRNy2DstU37E836BgNA0Itz4m/rVNNPfzVtf8mvUPf7Ond0aWl3pofgKSNgfEGvphD2zaM2heFSNGQniBxyGz5TA0qmNByw08pwCs0aC6NyxUR/o++imbCb2jqhUi6ddWjPwhlMWmP9/aQf9oBFoWYKfsQl1hQRMHHJErBY4r1TA/tbfcwCYtVV3OjCcOMt2l0B+cU56hZGUjdHAAazSZVRXBrEvZyIN9Yo1ViNrZoL3iuvmfzZObkFb0zGMdRK7e9UdGz5r7IG5PLHeLFiSubCfrvJabiwBg7o+jtgn+Snt5SyLcpD/4ieP2nZA+Y+mdjxo3jY5P73u5RWato/bRKGdFoXPJ2mxZaC0LboPbbGhUYjD1swzB7i5vSn4upfIJLUmxLsr9iJKvt/0kfVa/rRacMhk9xO3XwEFNiODWa4Ibzp5opG6dK/7P/peaSWxH1x95SKjDoLH9rlH0Tz01y+PZFDQx6v3V084cJSv+ESEU68z7T8kD6Y695+3XOV/PoCEMEQVTXIuOx2CzEGooKsggyOrhr9sCKy7e9AN4NGYW7izAvfG1mYWZiYJuuYBV9+/AwtlWb/njNdi2Yi4oR+ttAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAEzA8f43xrCFJEq0sC4Q8ruvOncTaud/QY1NPcDyMnRA0+28bhSnvqSB5NjKz5zARL5Z19/T/TYx3tvSYXLVyHzyWRBvk2oPjKZ3/gcOuQrtQAp4F1GBdVRKUNM+YONuVYAynR+EsP7PCpzx+j+wsLFAYSYYGc1Rm7ZjhwlECxUEO6ts9K5rlHehuCjxBw3LQkBvEifVfL6NPcGgCj8XYlzO/gEnBm85OeEoOcWiuXY68l9uJ8nPPJNzdOhQrrcZ/izakf2vtkj8pEOYAWP77Lw60nQ1M/5GF/zBQZkcsaSB8qdIgVujN/bdKkuOjIndBVE1Imaq5wlACTBnP7hFWJVRDDphZmtvBjuFPL9nrn2BI3ZenhMMeEw/+hntqvJiybSkviy+LjV4th+8zHB25Isb3ODQK1sZPGOLzvNJVlCZYhcm0OyybhEmHu2YweeFjPDL9xE9cw2nu+qp+MlJvxtyFwZ31QLzAHCrDXmrbypXkxegUQgWU8UB3u7sekYNn+LDmSqw3A+jTLSQaEGGcQKvdIHCIxofoEy5Nn+A8gNQVSFP2of2KMLSPFQpnxy5wnJOvApe0yBdLpnL1IrnoEzM3ysrNHES+Yy7GSqVwYuAaqbL5U8x0NzaQGapuEddkJIAlxBKyYifbDF4JtqaHGkIK9eWXxkIjMSrXq4CImi+
-----END CERTIFICATE-----

But the script fails with:
![2017-06-15_16h37_54](https://user-images.githubusercontent.com/1877612/27186750-8f8fd4c4-51e9-11e7-904c-577b402e067a.png)

**Comment by kjur** [comment]
This is the same issue as #265 . This is a X.509v3 certificate without any extension. The jsrsasign will not support such certificate for now and it will be fixed in the future. Thanks.

**Comment by Ruffio** [comment]
I can confirm that this issue has been resolved.
