### ISSUE TITLE
b64tohex is exported twice in npm package v7.2.2

### ISSUE THREAD

**Issue by DonGissel** [kjur/jsrsasign#270]
When running the NPM package (`jsrsasign.js` in v7.2.2) through a bundler like RollupJS, I'm warned that `b64tohex` is exported twice, and indeed it is: on line 270 and again on 286. While there might be some way of ignoring this error, it's not a nice thing to do. You should probably just remove that one duplicate export. ;-)

**Comment by kjur** [comment]
I've fixed in 8.0.0 release today. Thanks.
