### ISSUE TITLE
Links til subset packages are not working

### ISSUE THREAD

**Issue by Ruffio** [kjur/jsrsasign#272]
If you go to: https://github.com/kjur/jsrsasign/wiki/NOTE-jsrsasign-subset-package and try to download the subset packages then you get:

![image](https://user-images.githubusercontent.com/1877612/27687515-6ad57c3a-5cd7-11e7-8c3d-f1da7f0388f6.png)

**Comment by kjur** [comment]
I've fixed wiki today. Thanks.

**Comment by Ruffio** [comment]
Is it still not possible to download the subset packages:

![image](https://user-images.githubusercontent.com/1877612/27772568-8675af92-5f65-11e7-90a2-059314b1abea.png)
