### ISSUE TITLE
Incorrect calculation of SHA1 fingerprint at demosite

### ISSUE THREAD

**Issue by Ruffio** [kjur/jsrsasign#273]
I would like to calculate the SHA1 fingerprint/thumbprint.

I found out that the demosite 'Online Certificate Viewer' (https://kjur.github.io/jsrsasign/tool/tool_certview.html) is calculating the SHA1 Thumbprint, which is cool :-) However the calculation is incorrect :-(

Using this certificate:
-----BEGIN CERTIFICATE-----
MIIGYDCCBUigAwIBAgIEU7s4dDANBgkqhkiG9w0BAQsFADBAMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MR0wGwYDVQQDDBRUUlVTVDI0MDggT0NFUyBDQSBJSTAeFw0xNTEyMzAxMjE4MDNaFw0xODEyMzAxMjE2NTBaMIGeMQswCQYDVQQGEwJESzEyMDAGA1UECgwpRGFubWFya3MgQXBvdGVrZXJmb3JlbmluZyAvLyBDVlI6MjAxMjQ1MTIxWzAgBgNVBAUTGUNWUjoyMDEyNDUxMi1VSUQ6NjQyOTA2OTgwNwYDVQQDDDBEYW5tYXJrcyBBcG90ZWtlcmZvcmVuaW5nIC0gRGFubWFya3MgQXBvdGVrZXJmb3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQNL1iA9kO241weNpuTm/OoU5i9kOpp+/Vi6OmY14aYEIpgDEWr6nfeGugrsFyR2crOxr7iRhngUykUnSsfSqPkhhGiXdcPtEplSubCzP08zf/0PyIyyV5LoBEZr60M7LmahPuQojb09sKdCTEDMk46LCeISEQGI/ZggALH1SRSQiodctQvVN98okuaJDobgbTi/P2sMu3OK/JSbQrI2kn5d4ShUlWIBkZqsRUBNRmrvfBQzZpv2+mkDMFGouYzSkYccPivzQCx8BV9e2QdrB6KVnT6m/l5ND0d3qY41h0i/CffnjofQmoaQ1a3xO82+A6EF+Dl3QF5WcmfR2Z2C6rAgMBAAGjggMBMIIC/TAOBgNVHQ8BAf8EBAMCA7gwgYkGCCsGAQUFBwEBBH0wezA1BggrBgEFBQcwAYYpaHR0cDovL29jc3AuaWNhMDIudHJ1c3QyNDA4LmNvbS9yZXNwb25kZXIwQgYIKwYBBQUHMAKGNmh0dHA6Ly92LmFpYS5pY2EwMi50cnVzdDI0MDguY29tL29jZXMtaXNzdWluZzAyLWNhLmNlcjCCAUMGA1UdIASCATowggE2MIIBMgYKKoFQgSkBAQEDBDCCASIwLwYIKwYBBQUHAgEWI2h0dHA6Ly93d3cudHJ1c3QyNDA4LmNvbS9yZXBvc2l0b3J5MIHuBggrBgEFBQcCAjCB4TAQFglUUlVTVDI0MDgwAwIBARqBzEZvciBhbnZlbmRlbHNlIGFmIGNlcnRpZmlrYXRldCBn5mxkZXIgT0NFUyB2aWxr5XIsIENQUyBvZyBPQ0VTIENQLCBkZXIga2FuIGhlbnRlcyBmcmEgd3d3LnRydXN0MjQwOC5jb20vcmVwb3NpdG9yeS4gQmVt5nJrLCBhdCBUUlVTVDI0MDggZWZ0ZXIgdmlsa+VyZW5lIGhhciBldCBiZWdy5m5zZXQgYW5zdmFyIGlmdC4gcHJvZmVzc2lvbmVsbGUgcGFydGVyLjAzBgNVHREELDAqgShhcG90ZWtlcmZvcmVuaW5nZW5AYXBvdGVrZXJmb3JlbmluZ2VuLmRrMIGXBgNVHR8EgY8wgYwwLqAsoCqGKGh0dHA6Ly9jcmwuaWNhMDIudHJ1c3QyNDA4LmNvbS9pY2EwMi5jcmwwWqBYoFakVDBSMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MR0wGwYDVQQDDBRUUlVTVDI0MDggT0NFUyBDQSBJSTEQMA4GA1UEAwwHQ1JMMzExNzAfBgNVHSMEGDAWgBSZj7oNia4hGkJ6Cq4aTE4i/xDrjDAdBgNVHQ4EFgQUc/W+LbQMXATob80qxnVNE5DeDagwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAWgMjuLxT1GtEfWxR6Giqj2wUZxn0EecPWrWotL5Rvl5kNDXajcnsdAzEBS+0ZCXP1i/to+tupkQOs/o0cO759nBIY0O8ZbOvzsKBeLxWdQp2EuLZKDBwLpN49i8yzSJYWd7/KfH15DcNICvDwHPL6SBjwokCuz5dTFVdjXybOrIihRg8zRKZ4Utm1NV2Rfoh4C9D50uIMgcaIJ2WrhD4uIUbomqy9Ex0qUmTAV6eZh5ynCjlVYie3UqeJ+UoVfpsNMFNRJdoeKsn6g1WU2rgoKzYAzliiC89n3hrNbm7rcBLgDFfWsHUtO1w2PDfRAqJcHWoTQiIQNUCPTa8B9LZ8g==
-----END CERTIFICATE-----

The site calculates to: 633186e0b930dabbbcc87cae4a805687b84359ce
![image](https://user-images.githubusercontent.com/1877612/27707868-26c0ea6c-5d17-11e7-94c5-94c28b36a142.png)

However the correct value is: c5 79 c1 02 9a da 6e a3 f5 11 d8 ab 11 89 9b 0c 64 5f f0 f0
![image](https://user-images.githubusercontent.com/1877612/27707903-45dc6bb0-5d17-11e7-9c77-b3686334e9c2.png)

I can see that the following js script is used to calculate the hash:
var f = function(s) { return KJUR.crypto.Util.hashString(s, 'sha1'); }
  document.form1.thumb1.value = f(c.hex);

**Comment by kjur** [comment]
Certificate viewer will not work as the same reason for #269. Thanks.

**Comment by Ruffio** [comment]
I don't understand. As I understand it, when calculating the thumbprint, it is just a SHA1 hash of the certificate hex encoded, right? What has that to do with the functions?

**Comment by kjur** [comment]
I've fixed it in 8.0.1 release today. Thanks.

**Comment by Ruffio** [comment]
I can confirm that this issue has been fix. Nice (and really fast) work. Thanks :-)

**Comment by mm-gmbd** [comment]
@kjur - a convenience method provided by the X509 class to get the SHA1 thumbprint would be very nice :)

This is a fantastic library BTW - thanks!!

**Comment by kjur** [comment]
Hi @mm-gmbd , How about this:
```JavaScript
KJUR.crypto.Util.sha1(pemtohex(CERTPEM))
```

**Comment by mm-gmbd** [comment]
I used:

```
KJUR.crypto.Util.hashHex(x509Obj.hex, 'sha1')
```

from looking at the source code of the page referenced in this ticket, but I'm guessing `KJUR.crypto.Util.sha1(x509Obj.hex)` is a wrapper for the same method 😃 

A mention of this method in the documentation for the X509 object would be very helpful, as it took be a bit of searching to find. Or, as I was originally suggesting, maybe a method such as

```
x509Obj.getThumbprint()
```

that wraps this method underneath would be helpful. Happy to implement and open a PR
