### ISSUE TITLE
Help with old version of jsrasign to new? 

### ISSUE THREAD

**Issue by Shadowman4205** [kjur/jsrsasign#275]
Hello i want use one npm package  [oidc](https://github.com/edwinf/oidc-client-node) but it based on old version of jsrasign, any help to cnverting this part of code 

```
var r = require('jsrasign')'
var jws = new r.jws.JWS();
 if (jws.verifyJWSByPemX509Cert(id_token, cert)) {
utility.log("verified x509 cert");
 var id_token_contents = JSON.parse(jws.parsedJWS.payloadS);
```
To new version?

**Comment by kjur** [comment]
Hi. How about this?

```JavaScript
var r = require('jsrasign')'
var jws = new r.jws.JWS();
var pubkey = r.KEYUTIL.getKey(cert);

if (jws.verify(id_token, pubkey)) {
  utility.log("verified x509 cert");
  var id_token_contents = JSON.parse(jws.parsedJWS.payloadS);

**Comment by Shadowman4205** [comment]
there is not parsedJWS, i did something like this 

```
  const pubKey = r.KEYUTIL.getKey(cert);
if (r.KJUR.jws.JWS.verify(id_token, pubKey)) {
var id_token_contents = r.KJUR.jws.JWS.parse(id_token)
}
```
after that i need nonce? but seeing id_token_contents.nonce, it does not have got nonce?
is this too changed?

**Comment by Shadowman4205** [comment]
ok like i see inside 
id_token_contents there property 

> payloadPP: ' {......... ,\n  "nonce": "14260149392509666", .........}'

is there any function to get it if no ok i know what to do.

**Comment by kjur** [comment]
You can refer the nonce value  by id_token_contents.payloadObj.nonce. Thanks.
