### ISSUE TITLE
jws.JWS.verify fails after the latest update on 8.0.2

### ISSUE THREAD

**Issue by haripriyamoda** [kjur/jsrsasign#276]
In the file jsrsasign/src/jws-3.3.js

if (typeof RSAKey === undefined) _RSAKey = RSAKey; 

This line actually breaks the code, I think its a typo should be

 if (typeof RSAKey !== undefined) _RSAKey = RSAKey;

**Comment by kjur** [comment]
Thank you for letting me know. I've fixed in release 8.0.3. Thanks.

**Comment by bankair** [comment]
Both of you, guys, are awesome ! Thanks for the fix ;)
