### ISSUE TITLE
Invalid CMS when SigningTime is specified

### ISSUE THREAD

**Issue by dannief** [kjur/jsrsasign#277]
I am able to create a CMS using the default for SigningTime. Following the example in the [CMSUtil docs](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.cms.CMSUtil.html), the following works

```
var sd = KJUR.asn1.cms.CMSUtil.newSignedData({
  content: {str: "jsrsasign"},
  certs: [certPEM],
  signerInfos: [{
    hashAlg: 'sha256',
    sAttr: {
      SigningTime: {}
      SigningCertificateV2: {array: [certPEM]},
    },
    signerCert: certPEM,
    sigAlg: 'SHA256withRSA',
    signerPrvKey: prvPEM
  }]
});
```

However, If I explicitly set the SigningTime, then I am unable to parse the SigningTime on the server. I am using C#'s [SignedCms class](https://msdn.microsoft.com/en-us/library/system.security.cryptography.pkcs.signedcms(v=vs.110).aspx). I get the following exception message _CryptographicException: ASN1 bad tag value met._

```
var sd = KJUR.asn1.cms.CMSUtil.newSignedData({
  content: {str: "jsrsasign"},
  certs: [certPEM],
  signerInfos: [{
    hashAlg: 'sha256',
    sAttr: {
      SigningTime: {str: '20140517093800Z'}
      SigningCertificateV2: {array: [certPEM]},
    },
    signerCert: certPEM,
    sigAlg: 'SHA256withRSA',
    signerPrvKey: prvPEM
  }]
});
```
Is this **`SigningTime: {str: '20140517093800Z'}`** the right way to set the SigningTime?

Thanks

**Comment by kjur** [comment]
Sorry but It seems not SigningTime issue. This works properly:
```JavaScript
var t = new KJUR.asn1.cms.SigningTime({str: '140517093800Z'});
t.getEncodedHex()
301c06092a864886f70d010905310f170d3134303531373039333830305a
```

**Comment by dannief** [comment]
Are you saying the way, I am setting the SigningTime is correct? If so do you know why I would get parse errors. I have tried parsing with 2 different libraries on the backend.

**Comment by kjur** [comment]
{str: '140517093800Z'} will generate UTCTime of SigningTIme and {str: '20140517093800Z'} will generate GeneralizedTime of SigningTime. Both are acceptable. Did you try to verify your signature by openssl?
```
openssl cms -verify -inform DER -in [CMSSIG.der] -content [CONTENTDATA.bin] -no_signer_cert_verify
```
Sample signatures in the test code have been verified successfully and I can find any ASN.1 parse issue. As you mentioned, I'll close this ticket.
