### ISSUE TITLE
"Sign message" does not work

### ISSUE THREAD

**Issue by mg6maciej** [kjur/jsrsasign#280]
https://kjur.github.io/jsrsasign/sample/sample-ecdsa.html

TypeError: sig.initSign is not a function

**Comment by kjur** [comment]
Hi @mg6maciej , thank you for letting me know. I've fixed it. Thanks.

**Comment by mg6maciej** [comment]
There is a problem with verifying too.

TypeError: sig.initVerifyByPublicKey is not a function

**Comment by kjur** [comment]
I'll fix it later. Thanks.

**Comment by kjur** [comment]
I've fixed it. Thanks.

**Comment by robbiemu** [comment]
hmm, I'm getting this error with initVerifyByPublicKey and I just installed it today
