### ISSUE TITLE
Uncaught can't find PEM header: undefined

### ISSUE THREAD

**Issue by pgonzaleznetwork** [kjur/jsrsasign#285]
Downloaded the API from https://cdnjs.com/libraries/jsrsasign

Then I get the above error when doing the folllowing

`x = new X509();
        x.readCertPEM(samlConfig.certificate);
        console.log(x.getInfo());`

**Comment by kjur** [comment]
Argument for readCertPEM shall be a string of PEM formatted certificate. It doesn't seem samlConfig.certificate  have a such string. Thanks.

**Comment by Ruffio** [comment]
@pgonzaleznetwork are you sending the header? What exactly are you giving as argument?

**Comment by pgonzaleznetwork** [comment]
@Ruffio I think I understand the error now, i'm passing this

`"MIICajCCAdOgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBSMQswCQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBMGA1UECgwMT25lbG9naW4gSW5jMRcwFQYDVQQDDA5zcC5leGFtcGxlLmNvbTAeFw0xNDA3MTcxNDEyNTZaFw0xNTA3MTcxNDEyNTZaMFIxCzAJBgNVBAYTAnVzMRMwEQYDVQQIDApDYWxpZm9ybmlhMRUwEwYDVQQKDAxPbmVsb2dpbiBJbmMxFzAVBgNVBAMMDnNwLmV4YW1wbGUuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDZx+ON4IUoIWxgukTb1tOiX3bMYzYQiwWPUNMp+Fq82xoNogso2bykZG0yiJm5o8zv/sd6pGouayMgkx/2FSOdc36T0jGbCHuRSbtia0PEzNIRtmViMrt3AeoWBidRXmZsxCNLwgIV6dn2WpuE5Az0bHgpZnQxTKFek0BMKU/d8wIDAQABo1AwTjAdBgNVHQ4EFgQUGHxYqZYyX7cTxKVODVgZwSTdCnwwHwYDVR0jBBgwFoAUGHxYqZYyX7cTxKVODVgZwSTdCnwwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOBgQByFOl+hMFICbd3DJfnp2Rgd/dqttsZG/tyhILWvErbio/DEe98mXpowhTkC04ENprOyXi7ZbUqiicF89uAGyt1oqgTUCD1VsLahqIcmrzgumNyTwLGWo17WDAa1/usDhetWAMhgzF/Cnf5ek0nK00m0YZGyc4LzgD0CROMASTWNg=="`

Is it because I'm missing the begin and end certificate request headers?

**Comment by kjur** [comment]
```JavaScript
x = new X509(); x.readCertHex(b64tohex(samlConfig.certificate)); console.log(x.getInfo());
```

**Comment by pgonzaleznetwork** [comment]
I got it to work now @kjur by passing the headers, as specified in the specification for PEM format

`-----BEGIN CERTIFICATE-----
MIICajCCAdOgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBSMQswCQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBMGA1UECgwMT25lbG9naW4gSW5jMRcwFQYDVQQDDA5zcC5leGFtcGxlLmNvbTAeFw0xNDA3MTcxNDEyNTZaFw0xNTA3MTcxNDEyNTZaMFIxCzAJBgNVBAYTAnVzMRMwEQYDVQQIDApDYWxpZm9ybmlhMRUwEwYDVQQKDAxPbmVsb2dpbiBJbmMxFzAVBgNVBAMMDnNwLmV4YW1wbGUuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDZx+ON4IUoIWxgukTb1tOiX3bMYzYQiwWPUNMp+Fq82xoNogso2bykZG0yiJm5o8zv/sd6pGouayMgkx/2FSOdc36T0jGbCHuRSbtia0PEzNIRtmViMrt3AeoWBidRXmZsxCNLwgIV6dn2WpuE5Az0bHgpZnQxTKFek0BMKU/d8wIDAQABo1AwTjAdBgNVHQ4EFgQUGHxYqZYyX7cTxKVODVgZwSTdCnwwHwYDVR0jBBgwFoAUGHxYqZYyX7cTxKVODVgZwSTdCnwwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOBgQByFOl+hMFICbd3DJfnp2Rgd/dqttsZG/tyhILWvErbio/DEe98mXpowhTkC04ENprOyXi7ZbUqiicF89uAGyt1oqgTUCD1VsLahqIcmrzgumNyTwLGWo17WDAa1/usDhetWAMhgzF/Cnf5ek0nK00m0YZGyc4LzgD0CROMASTWNg==
-----END CERTIFICATE-----`

You were right I was passing the wrong format. Thank you so much for such a quick response!

**Comment by kjur** [comment]
Hi @pgonzaleznetwork 

May I some correction?

> Is it because I'm missing the begin and end certificate request headers?

It's "CERTIFICATE" header not "CERTIFICATE REQUEST" header.

Also, your certificate PEM is not correct format.
Generally PEM certificate has new lines for each 64 characters
of base64 string.

Your wrong PEM certificate works on jsrsasign however
will not work on OpenSSL. 

So I would recommend to use "b64tohex(samlConfig.certificate)".

**Comment by pgonzaleznetwork** [comment]
Thank you very much for the feedback @kjur. I've found working with you very pleasant, I didn't expect such good help. 

Can I ask just a follow up question. In the getInfo() method I get the following response

notBefore: 140717141256Z
 notAfter: 150717141256Z

Do you have a class/method to convert these to human readable date format? Thanks in advance!

**Comment by kjur** [comment]
@pgonzaleznetwork , you can use zulutodate method.

https://kjur.github.io/jsrsasign/api/symbols/global__.html#zulutodate

**Comment by pgonzaleznetwork** [comment]
Thank you!
