### ISSUE TITLE
Question: implementing the package with react native

### ISSUE THREAD

**Issue by assafb81** [kjur/jsrsasign#286]
Hi,
I want to add digital signature to a react native application.
The application receive data in JSON format and should validate that data while the application will hold the public key.

I am using RN version 0.45.1

Thanks,

**Comment by kjur** [comment]
Sorry but I don't know much about React.js. Please read sample codes and API manual of jsrsasign carefully and apply jsrsasign to React.js Thanks.

**Comment by assafb81** [comment]
thanks, I will check it out
