### ISSUE TITLE
generate RSAKey object 

### ISSUE THREAD

**Issue by assafb81** [kjur/jsrsasign#288]
I am trying to use jsrsasign package in my react native application.
how can I generate RSAKey object that will use me for encrypt and decrypt message, my code is (according to the sample - [https://github.com/kjur/jsrsasign/wiki/Tutorial-for-Signature-class](url)
```
import kjur from 'jsrsasign';
.....
const sig = new kjur.Signature({'alg': 'SHA256withRSA});
sig.init(privateKey) <- private key to encrypt?
sig.updateString('demoMessage');
const sigValueHex = sig.sign();

const sig1 = new kjur.Signature({ 'alg': 'SHA256withRSA' });
sig1.init(publicKey); <- public key?
sig1.updateString('demoMessage');
isValid = sig1.verify(sigValueHex);
console.log('isValid:', isValid);
```

**Comment by kjur** [comment]
Please use encrypt and decrypt class of Cipher class:

https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html#.encrypt
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html#.decrypt

**Comment by assafb81** [comment]
I could not figure out what is: 'RSAKey object' that KJUR.crypto.Cipher.decrypt/KJUR.crypto.Cipher.encrypt methods use

**Comment by kjur** [comment]
RSAKey object can be created by KEYUTIL.generateKeypair or KEYUTIL.getKey.
