### ISSUE TITLE
JavaScript Exception: init failed: not supported argument

### ISSUE THREAD

**Issue by dennis82m** [kjur/jsrsasign#290]
calling jsrsasign.jws.JWS.sign results in "JavaScript Exception: init failed: not supported argument" using

```
let header = {
  "typ":"JWT",
  "alg":"RS256"
};

let payload = {
  "iss":"a",
  "sub":"b",
  "aud":"c"
};

/* not base64 encoded */
let secret = "d";

console.log(jsrsasign.jws.JWS.sign(null, header, payload, secret));
```

**Comment by kjur** [comment]
You need to specify RSA private key for your RS256 algorithm header.

**Comment by dennis82m** [comment]
yeah sure as within the fourth parameter "secret" so I specified the key
