### ISSUE TITLE
Verification fails when signing data with BouncyCastle (C#)

### ISSUE THREAD

**Issue by assafb81** [kjur/jsrsasign#291]
Hi,
I am failing to verify data signed on server side using BouncyCaslte (c#).
the signing code is:

```
// Prepare data to sign as bytes[]
byte[] dataToSign = Encoding.UTF8.GetBytes(data);

var keyParamAsPEM = (AsymmetricCipherKeyPair)pemReader.ReadObject();
AsymmetricKeyParameter key = keyParamAsPEM.Private;

var keyParameter = new RsaKeyParameters(key.IsPrivate, ((RsaPrivateCrtKeyParameters) key).Modulus, ((RsaPrivateCrtKeyParameters) key).Exponent);

// Init alg
ISigner sig = SignerUtilities.GetSigner("SHA256withRSA");

// Populate key
sig.Init(true, keyParameter);

// Calc signature
sig.BlockUpdate(dataToSign, 0, dataToSign.Length);
byte[] signature = sig.GenerateSignature();

// Base 64 encode the sig so its 8-bit clean
string Signature = Convert.ToBase64String(signature);
```

the `Signature `value is:
`"EU5wG64joOWjOlDjcm80o7Vbm65XDx2BzFDp05llYhnHRbz87TVkdaWRJpRvFUpDSirmohSBoilC0TkWY1tfSHWvpKndfd5cvPiZBXtNGVAxHf4s/5gj3oYmDqvwuWGhZfUKVkxyby6nkaLwuDU45eC+DD1JDA4PGGtz+I2uTBs="`

the verification code in JS is:
```
// public key is a constant (
const pubKey = rsa.KEYUTIL.getKey(PUBLIC_KEY);
const rsaObj = new rsa.Signature({ alg: 'SHA256withRSA' });
rsaObj.init(pubKey);
rsaObj.updateString(JSON.stringify(data));
const isValid = rsaObj.verify(signature);

```

and `signature` value is:
`"EU5wG64joOWjOlDjcm80o7Vbm65XDx2BzFDp05llYhnHRbz87TVkdaWRJpRvFUpDSirmohSBoilC0TkWY1tfSHWvpKndfd5cvPiZBXtNGVAxHf4s/5gj3oYmDqvwuWGhZfUKVkxyby6nkaLwuDU45eC+DD1JDA4PGGtz+I2uTBs="`

I think this has something to do with `JSON.stringify(data)`?
the data is stored as JSON object:
1. On the server side I am using to convert JSON object to string: 
```
using (JsonTextReader reader = new JsonTextReader(file))
{
   JObject dataObj = (JObject) JToken.ReadFrom(reader);
   string data = JsonConvert.SerializeObject(data.GetValue("Data"));
}
return data;
```
2. On the client side I am using `JSON.stringify(data)`

**Update**
Few attempts to solve the issue:
1. sign the data differently on the server:
`sig.Init(true, key);` instead of `sig.Init(true, keyParameter);`

2. change the way of extracting the data in the server and client side:

**server**
```
using (JsonTextReader reader = new JsonTextReader(file))
{
   JObject dataObj = (JObject) JToken.ReadFrom(reader);
   string data = data.GetValue("Data").ToString();
}
return data;
```

**client**
`string newData = JSON.stringify(data).slice(1, -1);`

I've checked on text editor the values of 'data' and 'signature' and the values on the server and on the client side are identical.

**Comment by kjur** [comment]
Sorry but I couldn't catch your issue.

**Comment by kjur** [comment]
Please take a look following wiki page to verify Java generated signature with jsrsasign library.
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-interoperability-with-java-signing
This program uses Sun JCE provider by default but also works with BouncyCastle JCE provider.

**Comment by assafb81** [comment]
The JAVA code is not relevant for me, I looked at it for reference in the past.
I am working with C# and BouncyCaslte library.
I manage to generate, sign and validate when I write in C# and when I do it in JS - so I am guessing the code is correct.
But when I try to sign data in C# (server side) and validate in JS (client side) it keep failing. I can't find the reason for that.

**Comment by kjur** [comment]
Sorry but jsrsasign signature generation is interoperable with other languages and crypto libraries. It seems there is some problem in your code. I can't provide any further support.

**Comment by assafb81** [comment]
Ok, thanks
