### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by pgonzaleznetwork** [kjur/jsrsasign#295]
Hi, 

I'm getting the following error

`TypeError: Cannot read property 'length' of null
    at X509.getInfo (jsrsasign-all-min.js:formatted:13121)
    at Object.parseSamlData (app.js:65)`

Here are the details from the stack trace

**parseSamlData**

```
x = new X509();
x.readCertPEM(samlConfig.certificate);
samlConfig.certificate = x.getInfo();
```

**X509.getInfo**

```
B += "X509v3 Extensions:\n";
z = this.aExtInfo;
for (var r = 0; r < z.length; r++) {
```

in x.getInfo() x is fully defined, not null, but aExtInfo seems to be null

```
aExtInfo:null
foffset:0
getExtAIAInfo:ƒ ()
getExtAuthorityKeyIdentifier:ƒ ()
getExtBasicConstraints:ƒ ()
getExtCRLDistributionPointsURI:ƒ ()
getExtCertificatePolicies:ƒ ()
getExtExtKeyUsageName:ƒ ()
getExtInfo:ƒ (n)
getExtKeyUsageBin:ƒ ()
getExtKeyUsageString:ƒ ()
getExtSubjectAltName:ƒ ()
getExtSubjectAltName2:ƒ ()
getExtSubjectKeyIdentifier:ƒ ()
getInfo:ƒ ()
getIssuerHex:ƒ ()
getIssuerString:ƒ ()
getNotAfter:ƒ ()
getNotBefore:ƒ ()
getPublicKey:ƒ ()
getPublicKeyContentIdx:ƒ ()
getPublicKeyHex:ƒ ()
getPublicKeyIdx:ƒ ()
getSerialNumberHex:ƒ ()
getSignatureAlgorithmField:ƒ ()
getSignatureAlgorithmName:ƒ ()
getSignatureValueHex:ƒ ()
getSubjectHex:ƒ ()
getSubjectString:ƒ ()
getVersion:ƒ ()
hex:
"308202e4308201cca00302010202106ef7eb5b48f52380438653b6f81df914300d06092a864886f70d01010b0500302e312c302a0603550403132341444653205369676e696e67202d20616466732e636f72652e636e68696e642e636f6d301e170d3137303332333134333230375a170d3138303332333134333230375a302e312c302a0603550403132341444653205369676e696e67202d20616466732e636f72652e636e68696e642e636f6d30820122300d06092a864886f70d01010105000382010f003082010a0282010100ceb22047e0a866828209ed632be069c18595e385af96b7ec9ab9c29150aa0b5d08836939b83f1d1950f1f695c63ab0d6e0df3b1c045c4ef6443404494afcaa5cb9099d8d278ec2fc42a102a2611855a052065858f1d41fc1c18d1aa5539ed51bcb436a2f18afb75b53cf91f561142006a93896cbb3690210bc30910b877df2d7e8020191a966bb887dab8ac66a6c1b5753a8d7bdd82fbc92059fedc778ab7c384bef7d6b52bdf864bd5582a45a7e33f49ff5b8fb61480e219e340eea624009866166ab70421e89eeb73ee81a17ed2d1dddc4d609f81de9c4b57026284b03b1f7bf11095da0e8437de6adf7d0e57c652e241a6e7e61fcf900eed14bdeda4bd9150203010001300d06092a864886f70d01010b050003820101007dd1a0062e956b9d8689e5a3a04a8ac4582aa68dbe6edd393159acffc638a3a7e7fd9bc8250a472e55f3e6e3d61dc5df131b25363fa952c78d74daa53c4b8afd87cac7871e0a6d9b5ab679c036550495f5d90bf716b18841eecada21921c26b1cca508ae89bdeb22d7a0ace82569fd05bbcccb330c1b65fd13ec4ccdfbee45cb934741de905ae641bbec8b785e631f9dfb01f4c716b881e4a235b668a80c4545b69d29a20502c49c56262bad92bb634afc4d87bfab334e29c29b3c6c2d25838e860298b596df2e940f8c9f987568f3cf2196cf5f1e7ab9e265fec3a5c336b83de714b3ade0241a9953d186a815ced46d6e860b90179e7f7db239091df9b861d1"
parseExt:ƒ ()
readCertHex:ƒ (l)
readCertPEM:ƒ (l)
verifySignature:ƒ (n)
version:3
__proto__:Object

```

Please advise why it's null.

**Comment by kjur** [comment]
Can you provide your PEM certificate to investigate the issue?

**Comment by pgonzaleznetwork** [comment]
Here

`MIIC5DCCAcygAwIBAgIQbvfrW0j1I4BDhlO2+B35FDANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNBREZTIFNpZ25pbmcgLSBhZGZzLmNvcmUuY25oaW5kLmNvbTAeFw0xNzAzMjMxNDMyMDdaFw0xODAzMjMxNDMyMDdaMC4xLDAqBgNVBAMTI0FERlMgU2lnbmluZyAtIGFkZnMuY29yZS5jbmhpbmQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzrIgR+CoZoKCCe1jK+BpwYWV44WvlrfsmrnCkVCqC10Ig2k5uD8dGVDx9pXGOrDW4N87HARcTvZENARJSvyqXLkJnY0njsL8QqEComEYVaBSBlhY8dQfwcGNGqVTntUby0NqLxivt1tTz5H1YRQgBqk4lsuzaQIQvDCRC4d98tfoAgGRqWa7iH2risZqbBtXU6jXvdgvvJIFn+3HeKt8OEvvfWtSvfhkvVWCpFp+M/Sf9bj7YUgOIZ40DupiQAmGYWarcEIeie63PugaF+0tHd3E1gn4HenEtXAmKEsDsfe/EQldoOhDfeat99DlfGUuJBpufmH8+QDu0Uve2kvZFQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQB90aAGLpVrnYaJ5aOgSorEWCqmjb5u3TkxWaz/xjijp+f9m8glCkcuVfPm49Ydxd8TGyU2P6lSx4102qU8S4r9h8rHhx4KbZtatnnANlUElfXZC/cWsYhB7sraIZIcJrHMpQiuib3rItegrOglaf0Fu8zLMwwbZf0T7EzN++5Fy5NHQd6QWuZBu+yLeF5jH537AfTHFriB5KI1tmioDEVFtp0pogUCxJxWJiutkrtjSvxNh7+rM04pwps8bC0lg46GApi1lt8ulA+Mn5h1aPPPIZbPXx56ueJl/sOlwza4PecUs63gJBqZU9GGqBXO1G1uhguQF55/fbI5CR35uGHR`

**Comment by kjur** [comment]
Your certificate doesn't have any X.509v3 extension. That's why getInfo() fails. Sorry but I'll fix this in the future version. Thanks.

**Comment by pgonzaleznetwork** [comment]
Thanks!
