### ISSUE TITLE
Support for constructed/indefinite-length decoding

### ISSUE THREAD

**Issue by yellowjackets200** [kjur/jsrsasign#299]
I was recently testing the library and realized that apparently there is no support available for constructed/indefinite-length decoding.

For example, the following:

`ASN1HEX.isASN1HEX('2480040201020000')`

returns `false`, despite being a valid ASN.1 structure.

As far as I can see, this is due to the fact that `ASN1HEX.getLblen` returns -1 in such cases. For malformed strings it returns -2, which makes me think this type of decoding is treated as an error as well.

Because of this, I am not able to verify a DER CMS SignedData structure with this characteristics using:

`KJUR.asn1.cms.CMSUtil.verifySignedData`

where the first sequence is of type "constructed/indefinite-length". The error I get is _Uncaught checking tag doesn't match: 0!=06_

Maybe I am missing something, so I would appreciate your help with this issue. Thanks!

**Comment by kjur** [comment]
Hi. Sorry but currently jsrsasign only supprts ASN.1 DER not BER. That means indefinite length is not supported.
