### ISSUE TITLE
How to parse internal values of a timestamp response

### ISSUE THREAD

**Issue by badis** [kjur/jsrsasign#302]
I have used openssl commands in this webpage: https://www.freetsa.org/index_en.php to generate timestamp files (tsr).
I couldn't find any javascript solution to get internal values on the timestamp response.
Does this library to able to do it. And it would much better if it's able to do it in node.js as I have node.js script wrapping openssl commands.

**Comment by kjur** [comment]
Sorry but jsrsasign doesn't have any parsing API for time stamp response nor token now. They may be provided in the future. Thanks.
