### ISSUE TITLE
JSON Web Encryption

### ISSUE THREAD

**Issue by FranklinYu** [kjur/jsrsasign#305]
This is a feature request.

It would be greatly appreciated if encoding and decoding of [JSON Web Encryption](https://tools.ietf.org/html/rfc7516) is supported.

**Comment by martin-rydes** [comment]
@kjur it's been a long time since this thread, has this been implemented?
We are in need for a library to decode JSON Web Encryption that can be used without ejecting Expo

**Comment by kjur** [comment]
Sorry but there is no plan to implement this for now.
