### ISSUE TITLE
TypeError: sig.initSign is not a function in CertificationRequest#sign

### ISSUE THREAD

**Issue by enuoCM** [kjur/jsrsasign#307]
Following codes will throw "sig.initSign is not a function" exception.

KJUR.asn1.csr.CSRUtil.newCSRPEM({
            subject: {
                str: "/C=US/O=Test"
            },
            sbjpubkey: pubKeyObj,
            sigalg: "SHA256withECDSA",
            sbjprvkey: prvKeyObj
        });

**Comment by ksachdeva** [comment]
Facing the same issue

**Comment by ksachdeva** [comment]
Just checked in the source code is failing because in https://github.com/kjur/jsrsasign/blob/master/src/asn1csr-1.0.js#L114 should be `init` and not `initSign`

**Comment by kjur** [comment]
It will be fixed in the next release. Thanks.

**Comment by dominiclaudate** [comment]
Any information on when the next version with this fix will be released? Just ran into it today.
