### ISSUE TITLE
Subset packages

### ISSUE THREAD

**Issue by oliveti** [kjur/jsrsasign#313]
Hi,

Thank you for this useful library !

I saw you now provide subset libraries : https://github.com/kjur/jsrsasign/wiki/NOTE-jsrsasign-subset-package

I'm interested in using it with npm but I can not find it in the installed package. 
Would it be possible for you to provide it ?

Thank you

**Comment by kjur** [comment]
8.0.6 released today and it was added to npm/lib. Thanks.
