### ISSUE TITLE
Make jsrsasign-all-min.js available to npm package

### ISSUE THREAD

**Issue by dackmin** [kjur/jsrsasign#314]
Hey !

As we are all migrating away from bower to use webpack & yarn, it would be really appreciated if you also included the minified `jsrsasign-all-min.js` to your npm release, so we can use it for front-end projects as well 😄 

Thanks !

**Comment by dackmin** [comment]
And `jsrsasign-jwths-min.js` 😄

**Comment by kjur** [comment]
8.0.6 released today and this issue was fixed. Thanks.
