### ISSUE TITLE
Cannot read property 'getKeyFromEncryptedPKCS8PEM' of undefined

### ISSUE THREAD

**Issue by deanmono** [kjur/jsrsasign#316]
Importing the library from npm via webpack, I receive the following console error when trying to use the PKCS5PKEY class (other classes, such as crypto, work fine)...

`ERROR TypeError: Cannot read property 'getKeyFromEncryptedPKCS8PEM' of undefined`

from following class reference...
`const decodedKey = new KJUR.PKCS5PKEY.getKeyFromEncryptedPKCS8PEM(key, priv);`

**Comment by kjur** [comment]
I'm afraid that you may use old package. PKCS5PKEY class have been removed in the latest package.
