### ISSUE TITLE
Problem with signing and verifying

### ISSUE THREAD

**Issue by PhillippOhlandt** [kjur/jsrsasign#320]
Hey,

I have a hard time to get this to work. Here is my current code for signing and verifying so far:

```javascript
var fs = require('fs');
var rs = require('jsrsasign');
var rsu = require('jsrsasign-util');

var pem = rsu.readFile('public/certs/key.pem');

var sign = function (data) {
    var header = JSON.stringify({
        alg: 'RS256',
        typ: 'JWT'
    });
    var payload = JSON.stringify(data);
    var sJWT = rs.KJUR.jws.JWS.sign("RS256", header, payload, secretJwk());

    return sJWT;
};

var verify = function (signed) {
    return rs.KJUR.jws.JWS.verifyJWT(signed, publicJwk(), {alg: ['rsa']}); //RSA256 as alg doesnt work somehow
};

function secretJwk() {
    return rs.KEYUTIL.getKey(pem, '');
}

function publicJwk(){
    return rs.KEYUTIL.getKey(pem, '');
}
```

I mostly copied it together from examples. The HTML files and the wiki examples are completely different which is really confusing. So, I managed to sign it but for some reason I can't verify it. 

```
> cr = require('./auth/consentRequest.js')
{ sign: [Function: sign], verify: [Function: verify] }
> var signed = cr.sign({foo: "bar"})
undefined
> signed
'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.UBU_OakKEMN-NhO2AfHTUMq1rsjHKc7pJxUclJX9BvI4AU_bDpe-dBbDfTmqSFE45PX8FGCXdUl5_gJtbc8OZcAWpaltDwmhQ-Z_nxDYoAq9D0fYnNjsfx8axGfTE_D8ayENmvMIK143kt-cKWO-WjFbUKvoDDwC6aQiAMaF8R1XX0SxMGqXb7w44E8xRDB2mryV-54i2JwiMA3aWzqPa5z0BPirOEnnpnSvnf1KvxsisMiHf4asRhSxDHeJXI1DCdJ4MzK7x4jooWXN5cxbH4BHMItprvdABPqqxTViaLkeKzUKBmrEYhZVJoV65LGdG1SVi-bCeZCno66WnjX0xw'
> cr.verify(signed)
false
>
```

I am not sure why it says that it's not valid. Help appreciated :)

**Comment by PhillippOhlandt** [comment]
I also wanted to thumbprint my cert:

```javascript
kid: rs.KJUR.jws.JWS.getJWKthumbprint(secretJwk())
```

Which gives me `unsupported algorithm for JWK Thumprint`. I am able to thumbprint on that cert with a JWT/JWS/JWT lib in Elixir, tho.

**Comment by PhillippOhlandt** [comment]
ping @kjur :)

**Comment by kjur** [comment]
You are signing and verifying with the same key. That's the cause of issue.

**Comment by shinde-prasad** [comment]
@kjur I would like to know, how we can get public key from chain certificate  .pem  file. ( **_file has 3 certificates in it and we have to fetch first one which is public key_**)
Expecting your speedy assistance.

**Comment by kjur** [comment]
@shinde-prasad Split it to 3 pem strings, then you can get the public key from them.

**Comment by shinde-prasad** [comment]
> [kjur](/kjur)

but how  we can split keys in this case, split probability could increase based on ---- in the starting,
`-----BEGIN CERTIFICATE-----
content
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
content
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
content
-----END CERTIFICATE-----`

If you have any sample code it will really help.
