### ISSUE TITLE
TypeError: Cannot read property 'getPublicKey' of undefined at e in jsrsasign/lib/jsrsasign.js — line 236

### ISSUE THREAD

**Issue by hongshanzhu** [kjur/jsrsasign#321]
var jsrsasign = require('jsrsasign');

var sd="MIIMuwYJKoZIhvcNAQcCoIIMrDCCDKgCAQExCzAJBgUrDgMCGgUAMIHDBgkqhkiG9w0BBwGggbUEgbIFAAAAAQEGAAAAgBm6X07aOLFz02s5/01XqZwWvYHB7+a4Witx9+0UGtOsapuXb+xvNaO0Xo29BofwXDACXW6ZNo8gQM5IVWbxPq/bFSyDtEqmK/lSI6yBRy3eI1RHjBl5q+gLhBwknqpKc7wB4ci0tuY47fdCilz0WGbljc7jOQ0YxV9pYbmcUU7KBwAAABEzNTk0MDkwODAwMDI3MTAwMQQAAAAMKzE0MDg1NTUxMjM0oIIJGjCCBMcwggOvoAMCAQICCAQNg8wuQ5Y9MA0GCSqGSIb3DQEBCwUAMHIxLDAqBgNVBAMMI0FwcGxlIENvcnBvcmF0ZSBBdXRoZW50aWNhdGlvbiBDQSAxMSAwHgYDVQQLDBdDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTcxMDI2MTkyMjIxWhcNMTkxMTI1MTkyMjIxWjCBqDEqMCgGCgmSJomT8ixkAQEMGmlkZW50aXR5OmlkbXMuZ3JvdXAuOTc5OTEzMRkwFwYDVQQDDBBjdG13ZWIuYXBwbGUuY29tMSUwIwYDVQQLDBxtYW5hZ2VtZW50OmlkbXMuZ3JvdXAuOTQxMDIwMRMwEQYDVQQKDApBcHBsZSBJbmMuMSMwIQYKCZImiZPyLGQBGRYTQ2VydGlmaWNhdGUgTWFuYWdlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANQZ/UWVJsDN1uaQe6tIsPJbUjqaZUR3Fptxis3acy3+Lbsk9VaQ6Vp8WkUupGZGxD3TdY+/QTVmXVOyeCT7TkPUDjhoaZkceDYVuPdPRl1623dWkoa7zp5cED/neasZTyNEHgVHzNldxVBogdZzyNaB0Y+shYuFRuuX/bIOgrx0ZNOCWWEnjBwnfOsCrioLxh/+tWedJP23zGKyIKlofCZBRyeSVSqFHd8g0wLoO+f3mTCKYzftWDsdDPIgmOYyrrqJ6vDTPthDrr4eKKAY9cejZ3YPS6kLecom5+0hM7XTGNLXl4NCs1Wil6fpXw+paa7KNPbDgGxZ7pYPjJtrWc0CAwEAAaOCASgwggEkMHgGCCsGAQUFBwEBBGwwajAyBggrBgEFBQcwAoYmaHR0cDovL2NlcnRzLmFwcGxlLmNvbS9jb3JwYXV0aGNhMS5kZXIwNAYIKwYBBQUHMAGGKGh0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtY29ycGF1dGgxMDkwHQYDVR0OBBYEFGpOiHUgMY7H99g1kBrtK1xe/nJjMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUFiBxLz9/c/PhervsSX9XlO2TsZ8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5hcHBsZS5jb20vY29ycGF1dGhjYTEuY3JsMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAo0YeyhQXaNgKDJiZoGenJ1TcyCMHQZjn2gT6bLJG2t0xiaYsNRvIoHJAZ5WJ44gs8F6B9nDFA3uELvXLw7q9tNd81zVUsdiHDi5soNLKWAzLmTto/rt34c5pguYv6QWYU+JRnxWPC0g9Rh9sIV4CU13fFjfC3mJuzUstYxsRzQhprbnhTd/cIlU7HNCc8tNwCESrhMSNqdMI9TTeb7SAOShCq7S2lCTt2rOtka0V4pmh0FCb9IpxKzHGe9h+Lz1PK3hbeqXK9VYEu2snnRcNh6+zyaOe2HgGOEcHBx1m7RAFXbKl3nVrFMwShvdlrnvBzlcvBSk9OhKan+D7Jt9NFTCCBEswggMzoAMCAQICCBMv13MGMmG9MA0GCSqGSIb3DQEBCwUAMGYxIDAeBgNVBAMMF0FwcGxlIENvcnBvcmF0ZSBSb290IENBMSAwHgYDVQQLDBdDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTMwNzE2MTk0OTEzWhcNMjkwNzE3MTkyMDQ1WjByMSwwKgYDVQQDDCNBcHBsZSBDb3Jwb3JhdGUgQXV0aGVudGljYXRpb24gQ0EgMTEgMB4GA1UECwwXQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxKtVXiaKmbF6U0BStiFB9NYDftcShvJOGjoagcBbm2RAj0NzwEoYvy5rdNw4ujA6YMyxaEpB9Q7JMqcZk+Lfnup46v+PsvYADE6yHtfPh4cK3w1kAz8jL2OXk/n7mvCjzkqCUS1+TzFyfbsiDcaO1uo6SCpIu0KqIk8zV2LoLf/TaB2ef1WfFB1h9ZKdHYSaTDNwQOVabFl/RRQpYQCgMeYjGAcHlGk1ktQFZraWjE9tZZiRLVu3G0yrHhGfcqufaUMojCs4M9KvvqdAzn3f5LkZEMe91S04xYooCExv/j4kwEaYkoqZDPySfmLS343HE8aDVNb1lIKSLI8HHGIKSQIDAQABo4HwMIHtMEEGCCsGAQUFBwEBBDUwMzAxBggrBgEFBQcwAYYlaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwNC1jb3Jwcm9vdDAdBgNVHQ4EFgQUFiBxLz9/c/PhervsSX9XlO2TsZ8wEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBQ1ICbOhb5JJiAB3cju/z1oyNDf9TAyBgNVHR8EKzApMCegJaAjhiFodHRwOi8vY3JsLmFwcGxlLmNvbS9jb3Jwcm9vdC5jcmwwDgYDVR0PAQH/BAQDAgEGMBAGCiqGSIb3Y2QGGAIEAgUAMA0GCSqGSIb3DQEBCwUAA4IBAQCQdG54NYqdQowG2MsYytjErwb8JScRVoTFgwSQgUioyXLemNcFHQTS1N/6/LY0uYw6/fVHI1JbcvzYoZTMmRmh23EvUv7/8tYdtD6GXR6Titz5mlnX4yaleFkkJzSKBvOSNi35oyUbpoaFAzFYAcTkGzJ4JGBRSFPkvWUDS+ijlyjTKCl9QD925rJm9MUxEEtH1xYPGsPhGG4wm+JJGId/ZuWehlyDeGbtR17ejFKDnB+DG/ecrV7Aoxkvy4NlzBSm+RUIdkyrEf/MPb+feKAl85xUmvkneS6keLn/1Ff4ksTj2Oga/8ztA7MnWnwYGj6uFVaKOACqkCMqPAeffnmdMYICsDCCAqwCAQEwfjByMSwwKgYDVQQDDCNBcHBsZSBDb3Jwb3JhdGUgQXV0aGVudGljYXRpb24gQ0EgMTEgMB4GA1UECwwXQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTAggEDYPMLkOWPTAJBgUrDgMCGgUAoIIBBzAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNzExMTUwMjU2NDZaMCMGCSqGSIb3DQEJBDEWBBQhG8XT75SdnGT93zw2zA7Gg2k6LzCBpwYJKoZIhvcNAQkPMYGZMIGWMAsGCWCGSAFlAwQBKjAIBgYqhQMCAgkwCgYIKoUDBwEBAgIwCgYIKoUDBwEBAgMwCAYGKoUDAgIVMAsGCWCGSAFlAwQBFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcwDgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3DQMCAgEoMA0GCSqGSIb3DQEBAQUABIIBAJLxS1KQFr5r3sDou8vN9wCyyYdRmOKoEg7Zp7wuq3y/r1//WdkZQN6JmlbodKJly3XD8xIKPWMAxAp1Da6j1HsbCFk7xIRcpkP8zT5aIMCuv6jNhP9ejWLnKm3RhmXYme+KnLSVyRwDBA1FmytRPHDJSHush6PUIy8mrDidu4u4tYVD7mfEYwNe8Tb8uKijksLnhm26HxU69+1w6xkDgUmLeyqx2DeMF3PErCN1Bl2ikZldWIPd2dEETZv9JXtltLjl23N+W0gROW5PqWdNqesAB1C2aknERJ7ydmdvyfMf3aXwNi2OY5j9/Q0S6GWwe371qbuKds9C7IrzCJMCZiU=";
var value = new Buffer(sd, 'base64');
console.log(value);
var cms = value.toString('hex');
console.log(cms);
var result = jsrsasign.KJUR.asn1.cms.CMSUtil.verifySignedData({ "cms": cms })
console.log(result);
if(result && result.isValid)
{
    console.log(result.parse.econtent);
    console.log(data = Buffer.from(result.parse.econtent, 'hex').toString('utf8'));
}

**Comment by kjur** [comment]
I'm afraid you are using old version of jsrsasign npm module. Please update it.
