### ISSUE TITLE
Convert Hexadecimal RSA Private Key to PEM formatted

### ISSUE THREAD

**Issue by sivakrishna0205** [kjur/jsrsasign#322]
I tried to convert it using 

KJUR.asn1.ASN1Util.getPEMStringFromHEX(hexkey,"RSA PRIVATE KEY") 

it wont give me the  correct PEM format as expected 
Previously i made it using Python.But now the code to be written in client side.
Can u resolve this issue

**Comment by kjur** [comment]
Please use hextopem defined in base64x.js. Thanks.

**Comment by sivakrishna0205** [comment]
I have hexkey like this '2d2d2d2d2d42454749....'
when i try to convert it into PEM format.It is giving me some other PEM which is not same as the PEM i got using Python.

this is the PEM i got:   'LS0tLS1CRUdJTiBF...'

this is the actual pem: 'MIIEowIBAAKCAQE'

**Comment by kjur** [comment]
Hex value shall be PKCS#1 private key formatted value which is ASN.1 DER encoded.

**Comment by sivakrishna0205** [comment]
Hi thanks for your information.

I give the hex formatted data like ASN.1 DER encoded  but RSA Private key generated is different.

I am getting an encrypted hex data can you show me what are the steps to convert it into unencrypted RSA private key

**Comment by kjur** [comment]
Sorry but I can't private any solution since I can find how your hex data is encrypted.

**Comment by sivakrishna0205** [comment]
can u tell me how to convert PKCS8 Encrypted key to RSA Private Key

**Comment by kjur** [comment]
You can get RSAKey object of private key as following:
```JavaScript
var pem = hextopem(hexStr, "PRIVATE KEY");
var pkey = KEYUTIL.getKey(pem, passcode);
```

**Comment by sivakrishna0205** [comment]
Uncaught this only supports TripleDes
