### ISSUE TITLE
ECDSA curve secp521r1 doesn't work

### ISSUE THREAD

**Issue by garrethjeremiah** [kjur/jsrsasign#323]
Content signed with secp521r1 fails to verify (whereas signing with secp256r1 does verify)

IN several areas secp521r1 seems to be defined, but not in others (e.g. I can't init(ECDSA_secp521r1_PEMkey) but I can with the method below.  Even with using the method below, the signed content fails verification (but succeeds if I change to secp256r1).

Can you help?

```var curveName = 'secp521r1'
//var curveName = 'secp256r1'

var ec = new KJUR.crypto.ECDSA({'curve': curveName});
var keypair = ec.generateKeyPairHex();
var pubhex = keypair.ecpubhex; // hexadecimal string of EC public key
var prvhex = keypair.ecprvhex; // hexadecimal string of EC private key (=d)
var sigalg = 'SHA512withECDSA'

// ECDSA signing
var sig = new KJUR.crypto.Signature({'alg': sigalg});
sig.init({d: prvhex, curve: curveName});
sig.updateString('Simple Test');
var sigValueHex = sig.sign();

// ECDSA verifying
var sig2 = new KJUR.crypto.Signature({"alg": sigalg, "prov": "cryptojs/jsrsa"});
sig2.init({xy: pubhex, curve: curveName});
sig2.updateString('Simple Test');
var isValid = sig2.verify(sigValueHex);
if (isValid) {
  alert('yes')
} else {
  alert('no')
}
```

**Comment by kjur** [comment]
As noted here, secp521r1 curve is not supported:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.ECDSA.html#constructor
Thanks.

**Comment by garrethjeremiah** [comment]
I can appreciate it is not CURRENTLY supported.  Is it something that
will/can be supported in the future?

On Sun, Jan 21, 2018 at 3:51 PM, Kenji Urushima <notifications@github.com>
wrote:

> As noted here, secp521r1 curve is not supported:
> https://kjur.github.io/jsrsasign/api/symbols/KJUR.
> crypto.ECDSA.html#constructor
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__kjur.github.io_jsrsasign_api_symbols_KJUR.crypto.ECDSA.html-23constructor&d=DwMCaQ&c=6j73AXQl6SGc2MABPbS4oQ&r=HozSfjCRqm0taOOV2YjslTBfPl5d6beaOB4EWhEc9yk&m=TQmeWSRQzLbtYSAWNzLVgCw54zPwflas8LaKPYbMI1M&s=3WOpiTaJ4Kberdm8S2CNbOuhdB4F0GqFTrDGhKpOQdc&e=>
> Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kjur_jsrsasign_issues_323-23issuecomment-2D359279841&d=DwMCaQ&c=6j73AXQl6SGc2MABPbS4oQ&r=HozSfjCRqm0taOOV2YjslTBfPl5d6beaOB4EWhEc9yk&m=TQmeWSRQzLbtYSAWNzLVgCw54zPwflas8LaKPYbMI1M&s=hOIdr-ByMyKNLk8IFBJpoBmxh9lS1cvem0Fow_rvtYw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARjYYy28UeYbZLHobfOyUFPqO61cFcq0ks5tM6NYgaJpZM4Rl9az&d=DwMCaQ&c=6j73AXQl6SGc2MABPbS4oQ&r=HozSfjCRqm0taOOV2YjslTBfPl5d6beaOB4EWhEc9yk&m=TQmeWSRQzLbtYSAWNzLVgCw54zPwflas8LaKPYbMI1M&s=O1m-yFmo9Juudm0zc2Pd3Qgwe67IA2CUnyIZmSs06g4&e=>
> .
>



-- 
Garreth J Jeremiah
Director of Technical Account Management
m: +1.416.277.8304 | e: garreth.jeremiah@tanium.com

<https://www.tanium.com/>
2200 Powell Street, 5th Floor, Emeryville, CA
<https://urldefense.proofpoint.com/v2/url?u=https-3A__maps.google.com_-3Fq-3D2200-2BPowell-2BStreet-2C-2B5th-2BFloor-2C-2BEmeryville-2C-2BCA-2B94611-26entry-3Dgmail-26source-3Dg&d=DwMFaQ&c=6j73AXQl6SGc2MABPbS4oQ&r=vypFoX-94zokzag-9xkCnE4K4dn759P5X8DOqvMLGB0&m=tPu9gFQhqPK-R4af-DevRu61Z_KWFfHquy4YlMPDzHY&s=lFAipzIdHAk9Il_WFrmxurlBWOGtQHJq4KrsCcbFZvY&e=>
*94608*Join the Tanium Community <https://community.tanium.com/s/> | Tanium
Asset Demo <https://info.tanium.com/Introducing_Tanium_Asset> |
Documentation
<https://docs.tanium.com/>

**Comment by kjur** [comment]
ECDSA code is provided by bitcoin library. I’ve tried to add secp521r1 before but failed. I can’t resolve the issue. So it’s hard to add it.
