### ISSUE TITLE
Issue signing / verifying jwt with password containing only hex characters  

### ISSUE THREAD

**Issue by Univibe69** [kjur/jsrsasign#324]
Apologies if this is incorrect usage of sdk but am having the following issue:

If I use a string like this as the password, I am unable to verify in jwt.io
    
```javascript
            // Header
            var oHeader = {alg: 'HS256', typ: 'JWT'};
            // Payload
            var oPayload = {};
            var tNow = KJUR.jws.IntDate.get('now');
            var tEnd = KJUR.jws.IntDate.get('now + 1day');
            oPayload.iss = "issuer";
            oPayload.sub = "test@test.com";
            oPayload.iat = tNow;
            oPayload.exp = tEnd;
            // oPayload.nonce = nonce;
            oPayload.aud = "audience";
            // Sign JWT, password=secret
            var sHeader = JSON.stringify(oHeader);
            var sPayload = JSON.stringify(oPayload);
            // broken ...
            var secret = "ae199870b1cff7256807e33570d165bc0a5358d2";
            var sJWT = KJUR.jws.JWS.sign("HS256", sHeader, sPayload, secret);            

            console.log(sJWT)
```

I have also tried `{hex: secret}` as the last argument to `sign` as well as the above to no avail.
If I change one of the characters to fall outside if the hex character set it obviously works fine.

Why am I using this signature string ? It is generated by some other component the I can't immediately change ...

I am using this library out of interest:

```html
    <script src="//kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js"></script>
```

Am I doing something wrong or is this a bug ?

**Comment by kjur** [comment]
Both seem to work fine:

```JavaScript
var sJWT1 = rs.KJUR.jws.JWS.sign("HS256", sHeader, sPayload, secret);
var sJWT2 = rs.KJUR.jws.JWS.sign("HS256", sHeader, sPayload, {hex: secret});
```

**Comment by Univibe69** [comment]
Ok, so that above code does generate a JWT but if I paste it into the debugger on jwt.io and paste the secret into the verify signature text input, it fails to verify claiming the signature is invalid.

The back end system that I am calling with this jwt also claims it to be invalid.

**Comment by kjur** [comment]
See this note for jwt.io interoperability:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation
