### ISSUE TITLE
KJUR is not defined

### ISSUE THREAD

**Issue by slawekwojcik** [kjur/jsrsasign#327]
I've loaded the library (jsrsasign-all-min.js) on Salesforce platform in Lightning Experience.
Receive an error when trying to initialise:

var sig = new KJUR.crypto.Signature({"alg": "SHA1withDSA"});

error message: KJUR is not defined

**Comment by kjur** [comment]
Sorry but such error doesn't raise in other environment such as browser or node. jsrsasign may not be supported on Salesforce. Thanks.
