### ISSUE TITLE
Exporting public key from private key

### ISSUE THREAD

**Issue by getify** [kjur/jsrsasign#328]
I tried to export the public key from a private key, and this lib gave me an error about that not being supported:

```js
KEYUTIL.getPEM( myPrivKeyObj, "PKCS8PUB" );
```

On a whim/fluke, I tried a hack... I took the `isPrivate` and set it to `false`, and the `isPublic` and set it to `true`, and passed it to `KEYUTIL.getPEM(..)`, and it worked like a charm:

```js
myPrivateKeyObj.isPrivate = false;
myPrivateKeyObj.isPublic = true;

var pem = KEYUTIL.getPEM( myPrivateKey );

myPrivateKeyObj.isPrivate = true;
myPrivateKeyObj.isPublic = false;
```

If this hack is so easy (but annoyingly so), is there a good reason to not just support this use-case? I would assume it would be a pretty common use case to export public from private.

Unless I'm missing something, can't you always just safely let someone export from private to public?

For clarity sake, I'm envisioning:

```js
KEYUTIL.getPEM( myPrivateKey, "PKCS8PUB" );
```

**Comment by kjur** [comment]
Sorry but it’s not supported use case. It may not work in the future.

**Comment by getify** [comment]
It would be very helpful to me to understand why it's not a supported use-case? I am wondering specifically if it just runs counter to your API design, or if there's something deeper?

For example, openssl/openssh support extracting the public key from the private key. Node-RSA supports exporting the public key from the private key. Actually I've found half a dozen Node packages that can do it. But these all work on the server.

I'm trying to understand why a pure browser-compatible JS library wouldn't allow the same?

I don't understand all the math, but in my naive understanding the public key is a subset of the private key, from a numbers/data perspective. Extracting it in that sense should be safe, right? In other words, it's not creating a less-secure system, AFAICT?

----

Would my end-user use-case matter at all in your decision here and any possible reconsideration? I'm happy to share more details, but what I'm trying to do is make it as user-friendly as possible for someone to, entirely in browser, provide their private key, create a signature of some piece of data, extract their public key from their private key, discard the private key, and finally send the public key and signature off remotely to prove that they're authorizing some action.

It feels very much limiting and less user-friendly to require the user to have to specify both their private and public key separately -- meaning the user has to, offline in some way, extract their public key ahead of time with some other application. Why shouldn't the browser application be able to do this for them?

**Comment by getify** [comment]
Actually, lemme turn this question around a bit, maybe make it easier for you to answer. Do you expect this approach to "extraction" to continue to be supported?

```js
var privKey = KEYUTIL.getKey( privKeyPEMText );
var privKeyJWK = KEYUTIL.getJWKFromKey( privKey );
var pubKeyJWK;
{
   let { e, kty, n, } = privKeyJWK;
   pubKeyJWK = { e, kty, n, };
}
var pubKey = KEYUTIL.getKey( pubKeyJWK );
var pubKeyPEMText = KETUTIL.getPEM( pubKey );
```

In other words, will it be reliable to use JWK export/tweak/re-import as a means for achieving this extraction I need, as I've shown here?

**NOTE:** this same trick is how I'm accomplishing the extraction desired when using the built-in webcrypto browser API. Works beautifully.

**Comment by pornloge** [comment]
请问你找到解决方式了吗？
