### ISSUE TITLE
Deterministic keypair generation

### ISSUE THREAD

**Issue by falvhb** [kjur/jsrsasign#329]
Please allow me to reference a question on StackExchange:

["Deterministically generate a RSA public/private key pair from a passphrase (with sufficient entropy)?"](https://crypto.stackexchange.com/questions/24514/deterministically-generate-a-rsa-public-private-key-pair-from-a-passphrase-with)
(Short answer: yes.)

Now I would like to use jsrasign for this purpose. Would this be feasible?

Right now I use
`rs.KEYUTIL.generateKeypair(keyalg, keyopt);`

I assume the function would need to be extended to accept a pseudo-random seed:
`rs.KEYUTIL.generateKeypairFromSeed(keyalg, keyopt, function(){return ...});`

_Further reading:_
WarpWallet is a deterministic bitcoin address generator - https://keybase.io/warp

Thanks a lot!

**Comment by kjur** [comment]
Jsrsasign's key generation uses a random number generator of W3C Web Crypto API in most case otherwise Tom Woo's another psudo random number generator. Jsrsasign doesn't use pass phrase for any key generation. Thanks.
