### ISSUE TITLE
How to convert the content of a DER formatted file to a PEM formatted String

### ISSUE THREAD

**Issue by fernando-sendMail** [kjur/jsrsasign#33]
Hello!

I've been using your project with the FileReader API to read a certificate in order to extract the subject as a String, i alreay read your documentation, but I'm a little lost. I would like to know if there's a way to convert the DER formatted content of a file to a PEM formatted string?

As an extra info: im using the function readAsBinaryString (https://developer.mozilla.org/en-US/docs/Web/API/FileReader)

Thanks for your time in advance. Greetings!

**Comment by smrita-garg** [comment]
Hi, 
I am also facing the same problem. 
Getting "Cannot read property 'ASN1Util' of undefined" error. On using asn1-1.0.js is not resloving the error.  Please help me with appropriate js. 

Thanks & Regards
Smrita

**Comment by smrita-garg** [comment]
Hi kjur, please help on the issue

Regards
Smrita

**Comment by kjur** [comment]
Hi @smrita-garg , did you use the whole of latest code?
https://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js
It seems to be lacking other necessary files.

**Comment by smrita-garg** [comment]
Thanks alot for ur help!! 
It worked :)

**Comment by nathalials** [comment]
I'm using this code you suggested:

``` 
 var rawDerFileContents = "..........";
 var hexDerFileContents = rstrtohex(rawDerFileContents); // raw string to hex
 var pemString = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, "CERTIFICATE");   //with PEM Header
```

But it's returning a PEM string that is not able to be parsed.
I tried to parse the returned pem string in many different websites and it's getting an error to parse.

**Comment by kjur** [comment]
I've investigated rawDerFileContents value and it seems not DER encoded data string. That's why the script was failed. Save rawDerFileContents as a file then try to open openssl x509 command as following:

    % openssl x509 -in rawDerFileContents.bin -inform DER -noout -text

**Comment by nathalials** [comment]
I've got this DER:
```
var rawDerFileContents =
"0��0���	�M7��=0
	*�H��
0j10	UUS10
UDenial10USpringfield10
U
IBM10
UTutoia10Utest.ibm.com0
161013221726Z
171023221726Z0j10	UUS10
UDenial10USpringfield10
U
IBM10
UTutoia10Utest.ibm.com0�"0
	*�H��
�0�
�˥/?��Ϡk�%����*h��g����Û���mS��L!eƗV����{��`x���4�&[�6Ҡ}Nz���۠��M�����	�g`_�==Q��"�����Ɇ:�O�����-�y���pURr#��"y�B̙*x��BzIn����ZW�t�O3a�gv�{b�(H�_s�_ƶTc�+F
�3Y�t�C[\�-�adVf4A%��C8�"��\�pq6��$�ۖ��r�k�vH���hmj�{�Zl�ھK#2ıl$��IWj�����P0N0U}���GZ�o@���*�@}�i��0U#0�}���GZ�o@���*�@}�i��0U0�0
	*�H��
�r
5P�u�t��K��U-����Oc�n��R��ߗ�hgؠ	#���$��|PT�ZC��W.2��!V 2�rQ��N�q>x-���W7�Ŵg���Y�z
z�t��7���ۤ�-���z�*nO�j2W,ܐ-��H�Lc
��ۨ̄���Ք�e��t��c���C@w|L@]%;����S�#�C�N�m-�����01��q�Z�it����k�1�H6��8�!�Қ)�.�E]>��Oo1���uۨrY�ߡVlH��"
```

If I save this content into a file and open using this openssl command:
```openssl x509 -noout -text -inform der  -in testingUI.der```
It shows all certificate information.

If I try to convert this DER to PEM using this code:
``` 
var hexDerFileContents = rstrtohex(rawDerFileContents);
var pemString = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, "CERTIFICATE")
```

It returns an invalid PEM.

**Comment by kjur** [comment]
It seems 
    var rawDerFileContents =
"0���0...
is not proper ASN.1 DER data.
That's why it raise error. You need to find a way to set proper ASN.1 DER data to rawDerFileContents. Generally raw data can't be set by raw string. How about to convert testingUI.der to another string format such as Base64 or hexadecimal string?

**Comment by nathalials** [comment]
Yes, you're right. The data was not set proper. I had to pass it as binary instead of string.
Thank you.
