### ISSUE TITLE
pkcs12 support for ECC certificates

### ISSUE THREAD

**Issue by sanaullah82** [kjur/jsrsasign#330]
Hey,

Can i create a p12 file using jsrsasign lib? there are some libraries available to create p12 using javascript but those are only support RSA based keys like forge lib. pkijs support ECC keys too but the generated p12 file are encrypted with stronger ciphers like AES-GCM or AES-CBC where as Windows only support 3DES based p12 encrypted files.
i am looking for some lib that can create the p12 using 3DES and ECC

**Comment by kjur** [comment]
Sorry but PKCS#12 file is not supported in jsrsasign.
