### ISSUE TITLE
Should be more defensive

### ISSUE THREAD

**Issue by shimaore** [kjur/jsrsasign#332]
The library will crash if invalid values are provided, mostly because the `verify` functions use `split` for parsing.

For example, if I provide `"a.b"` as `jwt` parameter to `verifyJWT`, the function will crash because it will [attempt to parse `undefined`](https://github.com/kjur/jsrsasign/blob/master/src/jws-3.3.js#L669). (The exact error reported is `TypeError: Cannot read property 'length' of undefined` in `b64utob64`.)

The code should be made more defensive and (for example) use regex to validate the syntax of the content (and split at the same time).

**Comment by kjur** [comment]
I'll fix this in the next version.

**Comment by kjur** [comment]
This was fixed in 8.0.7 today. Thanks.
