### ISSUE TITLE
Question: verify ECDSA signature only

### ISSUE THREAD

**Issue by petromoldovan** [kjur/jsrsasign#334]
@kjur thank you for the awesome project and the maintenance! 

I am using your  library to verify data on the client with the help of public key and signature. This is how it works for me:
```
const validate = (pubKey, base64Signature, signedMessage) =>  {
    let sig = new KJUR.crypto.Signature({"alg": "SHA384withECDSA"})
    sig.init(pubKey)
    let hexSignature = new Buffer(base64Signature, 'base64').toString('hex')
    sig.updateString(signedMessage)    <--- must be included

    return sig.verify(hexSignature)
}
```
I making an app with react native for mobile devices and the above code is pretty heavy for (for example) old android devices. Is there a way to improve performance of the above code? Is it possible to validate only signature with the help of public key? Because right now i must update signature with `signedMessage` that is pretty big and I assume it increases the function's execution time.

thank you!

**Comment by kjur** [comment]
I would recommend to use W3C Web Crypto API based library such as PKI.js (https://pkijs.org/).

**Comment by petromoldovan** [comment]
@kjur thank you!
