### ISSUE TITLE
KJUR.jws.JWSJS#readJWSJS fails to properly initialize signature when reading JSON object

### ISSUE THREAD

**Issue by GeoffMeredith** [kjur/jsrsasign#336]
When initializing JWSJS object with readJWSJS() with a JSON object the signigure array seems to be assigned to the wrong initial variable.
https://github.com/kjur/jsrsasign/blob/05d2fb9e6c8e65b4eeaa85efcd9eb0bd30b2d3cf/src/jwsjs-2.0.js#L264
should be
`this.aSignatures = spJWSJS.signatures;`
The function works correctly with stringified JSON.

**Comment by kjur** [comment]
Thank you for your report. I'll fix it in the next version.

**Comment by kjur** [comment]
This was fixed in 8.0.7 today. Thanks.
