### ISSUE TITLE
malformed plain PKCS8 private key (code: 001)

### ISSUE THREAD

**Issue by mykokoko** [kjur/jsrsasign#337]
hi
I have a problem using the pkcs # 8 function.

var pkpem = KEYUTIL.getPEM (ecKeypair.prvKeyObj, "PKCS8PRV", passwordOfUser);
// next line fails with malformed format: SEQUENCE(0).items != 2: 11
var key = KEYUTIL.getKeyFromEncryptedPKCS8PEM (pkpem, passwordOfUser);

Is there a way to fix this error in the latest version?

var pkpem1 = KEYUTIL.getPEM (ecKeypair.prvKeyObj, "PKCS8PRV");
var key1 = KEYUTIL.getKeyFromPlainPrivatePKCS8PEM (pkpem1);

For plainPrivateKey, key issuance is normal.

Please confirm!!

**Comment by kjur** [comment]
Sorry but I may close this ticket if there is not any further information to investigate the issue.

**Comment by mykokoko** [comment]
var ecKeypair = KEYUTIL.generateKeypair("EC", "secp256r1");
var publicKey = ecKeypair.pubKeyObj.pubKeyHex;
var privateKey = ecKeypair.prvKeyObj.prvKeyHex;

Sorry.
I checked it now T.T
