### ISSUE TITLE
Is there a way of minimizing the  bundlesize?

### ISSUE THREAD

**Issue by JCofman** [kjur/jsrsasign#338]
Hi there, 

thank you for this project and first of all I am sorry for asking a question in form of a git issue but maybe someone here could help me. I am using this library for validating a JWT token therefore I am importing the library methods KJUR and KEYUTIL from jsrsasign.  But importing these two methods bloat my JS bundle by with 69,7 KB. Is there an easy way to cut of some bytes? 🙈

```js
import { KJUR, KEYUTIL } from 'jsrsasign'; // bundlesize 69,7 KB gzipped
const pubKey = KEYUTIL.getKey(key);
const check = KJUR.jws.JWS.verifyJWT(jwtToken, pubKey, certificate);
```

**Comment by kjur** [comment]
You may minimize it by concatinating just only necessary files in ext/*min.js and min/*min.js. By your above sample code, you may not need asn1cades, asn1cms, asn1csr, asn1ocsp, asn1tsp, dsa, and jwsjs.

**Comment by JCofman** [comment]
@kjur thx ;)
