### ISSUE TITLE
Sign function not working

### ISSUE THREAD

**Issue by blmalone** [kjur/jsrsasign#339]
Receiving this error upon invokation of `doSign()`.
Possible cause could be that a number of 404 error are returned on page load and the correct files are not being downloaded.

```
crypto-1.1.js:768 Uncaught setAlgAndProvider hash alg set fail alg=sha256/setAlgAndProvider hash alg set fail alg=sha256/ReferenceError: CryptoJS is not defined
```

**Comment by kjur** [comment]
Hi, what page do you get the error?

**Comment by blmalone** [comment]
Hi @kjur, 
I'm getting the error on the live site hosted at: 

http://dbis.rwth-aachen.de/~renzel/mobsos/lib/js/jsrsasign/sample-ecdsa.html

![screen shot 2018-03-26 at 23 06 21](https://user-images.githubusercontent.com/15608778/37935676-5a31a974-314a-11e8-994d-486971403f48.png)

**Comment by kjur** [comment]
It isn't mine and something wrong.
This page is the same and work fine.
https://kjur.github.io/jsrsasign/sample/sample-ecdsa.html

**Comment by blmalone** [comment]
@kjur Thank you, apologies for the misunderstanding - there was a link to your Github on that page.

**Comment by kjur** [comment]
No problem ;)
