### ISSUE TITLE
How to print the error message?

### ISSUE THREAD

**Issue by Mike-Yan** [kjur/jsrsasign#340]
KJUR.jws.JWS.verifyJWT(); only return a boolean. Is there a way to read the error message?

**Comment by kjur** [comment]
Some error may raise its exception which contains error message.

**Comment by Mike-Yan** [comment]
Thanks for responding,

is there any example of this?

**Comment by kjur** [comment]
```JavaScript
try {
  var isValid = KJUR.jws.JWS.verifyJWT(...);
} catch (ex) {
  console.log(ex);
}

**Comment by Mike-Yan** [comment]
Thanks it worked ! 👍
