### ISSUE TITLE
How to decrypt the encrypted string by private key with public key?

### ISSUE THREAD

**Issue by shiyunsheng** [kjur/jsrsasign#344]

**Comment by shiyunsheng** [comment]
怎么在网页端使用公钥解密服务器用RSA 私钥加密的数据？

**Comment by kjur** [comment]
You can use RSAKey.doPublic method to encode a message which is encoded by private key by public key. Please find rsasign.js code for your reference. Thanks.
https://github.com/kjur/jsrsasign/blob/master/src/rsasign-1.2.js#L234
