### ISSUE TITLE
RSAKey.generate generates guessable keys

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kjur/jsrsasign#35]
I looked through the SecureRandom code and it doesn't look very good compared to sjcl or forge.

rng.js contains the following comment at the top of the file:

    // For best results, put code like
    // <body onClick='rng_seed_time();' onKeyPress='rng_seed_time();'>

And then further down:

    // TODO: allow reseeding after first request

The issue is that the rng_pool array is never touched after initializing the RC4 prng in prng4.js, so no entropy can  be added to the system.

The other serious issue is that the rng does not use window.crypto.getRandomValues():

This means that Math.random() and the current time (once!) are the only sources of entropy.  

http://stackoverflow.com/questions/578700/how-trustworthy-is-javascripts-random-implementation-in-various-browsers

Given that we must assume Math.random() has maybe 32-bit entropy, and the current time (milliseconds) must give << 10 bits of entropy, then it is likely that the generated RSA key space is easy to enumerate and thus the generated keys are useless.

Probably the files rng.js and prng4.js should be removed and replaced by something that is actively maintained.  It is easy to add support for getRandomValues() but there are other prngs that are both maintained and provide additional entropy sources.

**Comment by kjur** [comment]
Release 5.0.9 updates to use W3C WebCrypto window.crypto.getRandomValues;
