### ISSUE TITLE
Message too long for RSA

### ISSUE THREAD

**Issue by celevra** [kjur/jsrsasign#357]
Hi, 

i want to encrypt big texts and files in base64, how should i do it with jsrsasign? If i use KJUR.crypto.Cipher.encrypt i get the error 'Message too long for RSA'

```
var text = `Latein
"De finibus bonorum et malorum" Cicero
Absatz 1.10.32 - 1.10.33

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?

At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`

var pubKey = KEYUTIL.getKey(`-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----`)
var encHex = KJUR.crypto.Cipher.encrypt(text, pubKey, 'RSAOAEP256');
```

**Comment by rmhrisk** [comment]
Encrypt with AES-GCM and encrypt that key with RSA.

**Comment by celevra** [comment]
thank you for the fast answer, do you've got a little example? if i simply change RSAOAEP256 to AES-GCM i get
```
getAlgByKeyAndName: not supported algorithm name for RSAKey: AES-GCM
```

**Comment by rmhrisk** [comment]
@celevra I am not familiar with @kjur's excellent library enough to explain how to use it to accomplish this task, however, you do not do bulk encryption with RSA for several reasons.

You should do bulk encryption with a symmetric algorithm, and you should encrypt the symmetric key with an asymmetric key.

I can say that In your above example you seem to be using trying to use AES with a RSA class.

**Comment by kjur** [comment]
RSA encryption can encrypt message with its length which is smaller than its key size. That's why you get an error.

Here is the steps to encrypt and deliver a large message:
1) Generate AES shared key.
2) Encrypt your large message with above AES shared key.
3) Encrypt AES shared key with RSA-OAEP or RSA.
4) Deliver encrypted AES shared key and encrypted message.

You can find AES encryption examples in crypto-js page:
https://code.google.com/archive/p/crypto-js/

Also you can find RSA-OAEP or RSA encryption example in a manual:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html

Thanks.
