### ISSUE TITLE
license is MIT or BSD

### ISSUE THREAD

**Issue by b-asaf** [kjur/jsrsasign#359]
Hi,

In this [link](https://www.npmjs.com/package/jsrsasign) the license is of the package is declared as **MIT**.
But in the [license file](https://github.com/kjur/jsrsasign/blob/master/LICENSE.txt#L24) it states that the license is **BSD**.

Which one is it?

**Comment by kjur** [comment]
Sorry for confusion. The jsrsasign is published under MIT license. I'll fix license file. Thanks.

**Comment by assafb81** [comment]
any updates?

**Comment by kjur** [comment]
Sorry to be late response. It's fixed in 8.0.13 release today.
