### ISSUE TITLE
It didn't pass all the test.

### ISSUE THREAD

**Issue by 349989153** [kjur/jsrsasign#360]
I git clone the master branch , and open `/jsrsasign/test/qunit-do-crypto-ecdsa.html`:
<img width="1678" alt="wx20180623-153854 2x" src="https://user-images.githubusercontent.com/10381674/41807076-9852f98c-76fb-11e8-9e01-0cc0c714f588.png">

**Comment by kjur** [comment]
This was fixed in 8.0.13 release today. Thanks.
