### ISSUE TITLE
Add length of value to information retrieved by getExtInfo

### ISSUE THREAD

**Issue by awjh** [kjur/jsrsasign#364]
Currently when I invoke getExtInfo I receive the vidx which I can use to find the starting point of the value I wish to extract from the hex. However as the length is not returned I am unable to extract the value from the hex as I don't know where the data ends. Providing the length would allow me to perform a substring command on the hex and extract just the value for the extension I am targetting.

**Comment by kjur** [comment]
Hi,

You can get a string index of ASN.1 value of the extension by "vidx" value.

https://kjur.github.io/jsrsasign/api/symbols/X509.html#getExtInfo

Then you can get any ASN.1 parameter such as "length"
for the extension by ASN1HEX class:

https://kjur.github.io/jsrsasign/api/symbols/ASN1HEX.html

Thanks.

**Comment by polymorpher** [comment]
@kjur is there an example for using ASN1HEX to get some value based on vidx? For example, I am trying to get a DER encoded ASN.1 sequence value based on a custom extension with some OID (to be specific, OID 1.2.840.113635.100.8.2, which is used for iOS app attestation, see https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server#3579385)

Is ASN1HEX.[getVidx](https://kjur.github.io/jsrsasign/api/symbols/ASN1HEX.html#.getVidx)(s, idx) the method to use? Is `s` the buffer for the certificate?

**Comment by kjur** [comment]
@polymorpher 

Suppose following ASN.1 structure:
```
SEQUENCE
  INTEGER 01
  PrintableString 'a'
```
It will be encoded as a following DER hexadecimal string.
```
var h = "3006020101130161";
```
getVidx is to get a string index of ASN.1 value by specifying string index of ASN.1 TLV structure.
When you want to get a string index of SEQUENCE value:
```
ASN1HEX.getVidx(h, 0) -> 4
3006020101130161
    ^ "020101130106" is a value of SEQUENCE
```
When you want to get a string index of PrintableString
```
ASN1HEX.getVidx(h, 10) -> 14
3006020101130161
          ^ idx:10
              ^ idx:14
```
