### ISSUE TITLE
ESM module using rollup or similar

### ISSUE THREAD

**Issue by manelclos** [kjur/jsrsasign#365]
Hi,

I just need RSA256 verification, and I was wondering if making the library available as an ESM module would allow to reduce the size of the library from 256KB to something under 100KB. I tried the -rsa-min.js variant, but it is lacking KEYUTIL. Using it like this:

```javascript
      const pubkey = KEYUTIL.getKey(certStr)
      const isValid = KJUR.jws.JWS.verifyJWT(token, pubkey, {
        alg: ['RS256']
      })
```

With the rsa-min.js version the error is:

```
TypeError: Cannot read property 'getKey' of undefined
```

Any pointers appreciated!

Thanks!

**Comment by brockallen** [comment]
FWIW, this is what I have done: https://github.com/IdentityModel/oidc-client-js/blob/dev/gulpfile.js#L96-L156

**Comment by kjur** [comment]
Hi @manelcos ,

@brockallen 's resolution is the one of best way. 

jsrsasign is Swiss army knife style library which has rich APIs, is easy to use but has huge size as you said.
To reduce size for your specific purpose, you need to make code snippet of jsrsasign.

Hi @brockallen , thank you for your mention.

Thanks.

**Comment by manelclos** [comment]
ok, noted. Thanks a lot!
