### ISSUE TITLE
b64u utilities question

### ISSUE THREAD

**Issue by sbweeden** [kjur/jsrsasign#366]
I am working with some extended Korean characters. Consider this javascript:

var o={"s":"지창훈"}
Now: stob64u(JSON.stringify(o)) returns: "eyJzIjoiycDMPdbIIn0"

However: b64utos("eyJzIjoiycDMPdbIIn0") returns: {"s":"ÉÀÌ=ÖÈ"}

Why can't b64utos work properly with these chars?

**Comment by kjur** [comment]
Hi @sbweeden , please use utf8tob64u and b64utoutf8 instead of stob64u and b64utos. Then they will works fine. Thanks.

**Comment by sbweeden** [comment]
Thank you - they do work fine. 
I was just trying to understand why these functions were not able to be paired like this.
