### ISSUE TITLE
X509 cert does not parse cert with empty subject DN

### ISSUE THREAD

**Issue by sbweeden** [kjur/jsrsasign#367]
I am trying to use the X509 class to parse the following cert:

-----BEGIN CERTIFICATE-----
MIIEsjCCA5qgAwIBAgIQTvpLJf0bQqey4zTLDw55bzANBgkqhkiG9w0BAQsFADBB
MT8wPQYDVQQDEzZOQ1UtTlRDLUtFWUlELTE1OTFENEI2RUFGOThEMDEwNDg2NEI2
OTAzQTQ4REQwMDI2MDc3RDMwHhcNMTgwNzA1MjIzNDQ0WhcNMjgwNzA1MjIzNDQ0
WjAAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyWXpJpFF7NDsC8pU
zTiSZuahgQmRUx/Q4SuGlih+DIhA8RSTUfjcsctHj1fL1R+lzKJ+icNZEXUll9VR
3AH+GvRIffeR2UV2rAnxGyJ0mB7BZQB+yosYEG9dvsMgsLgKc52KhwGiCUPUcC46
crlGaRamvBtkUAVnTEjceDCDtJV26C9vyLg6JRlwNeMcmFi6G/4nglPGM9v5tcWa
uNXUV4c4tDxws4YITikoocfkblyQGQkduXjcZBYTW9ubcxeWQD65K99z9RETMT7J
hU5nqAcbrpFlGt9E7pn76tMesmS0GrTQaYZK/1Vv42UTmFR4cuNuTUwTZUUUVT+O
0kgX6QIDAQABo4IB5TCCAeEwDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAw
bQYDVR0gAQH/BGMwYTBfBgkrBgEEAYI3FR8wUjBQBggrBgEFBQcCAjBEHkIAVABD
AFAAQQAgACAAVAByAHUAcwB0AGUAZAAgACAAUABsAGEAdABmAG8AcgBtACAAIABJ
AGQAZQBuAHQAaQB0AHkwEAYDVR0lBAkwBwYFZ4EFCAMwSgYDVR0RAQH/BEAwPqQ8
MDoxODAOBgVngQUCAwwFaWQ6MTMwEAYFZ4EFAgIMB05QQ1Q2eHgwFAYFZ4EFAgEM
C2lkOjRFNTQ0MzAwMB8GA1UdIwQYMBaAFMISqVvO+lb4wMFvsVvdAzRHs3qjMB0G
A1UdDgQWBBTn7kagJTwBIGQmLqfY0jZ+cDMpADCBswYIKwYBBQUHAQEEgaYwgaMw
gaAGCCsGAQUFBzAChoGTaHR0cHM6Ly9hemNzcHJvZG5jdWFpa3B1Ymxpc2guYmxv
Yi5jb3JlLndpbmRvd3MubmV0L25jdS1udGMta2V5aWQtMTU5MWQ0YjZlYWY5OGQw
MTA0ODY0YjY5MDNhNDhkZDAwMjYwNzdkMy8zYjkxOGFlNC0wN2UxLTQwNTktOTQ5
MS0wYWQyNDgxOTA4MTguY2VyMA0GCSqGSIb3DQEBCwUAA4IBAQALUIixhxYuuUR5
6DWxSdzF8USV4PSnayZemEQpOeCv1HbKjr6nrCe8GNfmKhq6sHh1q0gVeoBImTpB
FfTAcWBctsEy7BD0WsY0f7baXl6nbfAB9eTJJKI5HOillVsp6vFqCD8uVv3KzdeA
lhznKBCmym3MC+zKuMjf1/xcm29Zs9J+BIxc3pd+QrKqb8bWDmSES2csTMR//AzX
Q6QnoMVSUYOo/gu72svbhVmSwL7GZjv1WHT1DZA6rW9oUkbZ3mDB9Daz9KSGs1Rq
BfW6f+5hOGTpvFwnk3Abfg4eZ9uH8uVkOKTdsihHeBV4lIdhNTnxIWz95oZBhjQj
OZu2YsZg
-----END CERTIFICATE-----

It is *supposed* to have an empty subject field, and part of the rules I need to apply when validating it require me to check that.

When I try to call .getInfo() or .getSubjectString(), I get an error: "malformed RDN"

Using openssl x509 -in <filename> -text prints the information successfully, including the empty subject.

Is this something that can be addressed with the X509 class?

**Comment by kjur** [comment]
Your certificate seems to have empty subject field. This violates RFC 5280. jsrsasign doesn't support empty subject field. Thanks.
