### ISSUE TITLE
Signature: unsupported private key alg: rsa

### ISSUE THREAD

**Issue by soberlyxq** [kjur/jsrsasign#371]
var rsa = new jsrsasign.RSAKey()
 var pk = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3BBEBAQUAA4GNADCBiQKBgQDqkCIzHILA+/jpe1w606Lmc+I9
NrqxH4AH8fP9+BgEgUwxFlg7MTlc/mFtGsXPXdZYMW76uE/TM/M6YMW17YYPyLbg
3NrJuM+7OX0Y4oOoF7eGH/RTZ3MLQ9jw4P29UnCZPBt+gXx82i/rL69IuHogjsFW
rzWICjEDFZrfQGKNzQIDAQAB
-----END PUBLIC KEY-----`
  rsa = jsrsasign.KEYUTIL.getKey(pk )
  var Signature= new jsrsasign.KJUR.crypto.Signature({'alg': 'SHA256withRSA'})
  Signature.init(rsa)
  Signature.updateString(newStr)
  var param= Signature.sign()
  param = encodeURIComponent(param)
  return params

**Comment by kjur** [comment]
Your RSA public key file has wrong OID.

Your file has PKCS#1 oid: 
http://oid-info.com/get/1.2.840.113549.1.1

However it shall be rsaEncryption:
http://oid-info.com/get/1.2.840.113549.1.1.1

Thanks.
