### ISSUE TITLE
Tutorial for JWT generation uses HTTP (not HTTPS!)

### ISSUE THREAD

**Issue by bradisbell** [kjur/jsrsasign#372]
On the wiki, the [tutorial for JWT generation](https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation) includes the jsrasign library via HTTP:

```
<script language="JavaScript" type="text/javascript"
        src="http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js">
</script>
```

This should really be `https://`.

**Comment by kjur** [comment]
Thanks. It was fixed.
