### ISSUE TITLE
malformed plain PKCS8 private key & ECDSA not supported argument

### ISSUE THREAD

**Issue by RealityRipple** [kjur/jsrsasign#379]
Getting the same issue as was mentioned in #337.

The problem is use of hmacWithSHA256. hmacWithSHA1 works just fine, but SHA256 results in a key that can't be read by this script.

---

Additionally, I was testing ECDSA keys generated by PuTTYgen and noticed that encrypted keys work while unencrypted ones result in a `not supported argument` failure. I've tried all three curve options PuTTYgen offers, they all behave the same way.

> Example Keys: [ec.zip](https://github.com/kjur/jsrsasign/files/2407428/ec.zip)
> Password of `ec.p.pem` is "1"

For reference, PuTTYgen's DSA keys and OpenSSL's EC keys seem to behave as expected.

**Comment by kjur** [comment]
Your ec.pem is PKCS#5 PEM EC private key format and it is *NOT* supported in jsrsasign now. Sorry.

**Comment by MillionChen** [comment]
你好我是遇见了这个问题：这样解决的
开头和 -----BEGIN PUBLIC KEY----- 结尾-----END PUBLIC KEY-----
