### ISSUE TITLE
IMPORT IN ANGULAR 6

### ISSUE THREAD

**Issue by dBer** [kjur/jsrsasign#381]
Hello,

How can I import KJUR into Angular 6 project? I need the verify function, to validate the sign.

**Comment by ioannis85** [comment]
Hello dBer you  only need install via npm  jsrsasign in your project.
follow you can import  in this mode:
**import  rs from  'jsrsasign';**
and ready !!!  you can use jsrsasign in angular 6!!

**Comment by krisidmisso** [comment]
`import { KEYUTIL, KJUR } from "jsrsasign";`
