### ISSUE TITLE
Compatibility with CMSSignedData BouncyCastle

### ISSUE THREAD

**Issue by ioannis85** [kjur/jsrsasign#382]
Hi everyone!!.

I have 2 applications  ios Xamarin and angular 6 app.

In my xamarin app I use BouncyCastle.Cripto to generate CMS SignedData container and in my angular 6 app I use Cms.Util.NewSignedData method to generate mi CMS SignedData container. 
my problem is.   When I  sign data in both  I store the  de cms signedData  container in my db
*for  angular 6 app use jsrsasign and store  sd.getContentInfoEncodedHex();  
*for xamarin app use bouncycastle and store SignedData.ContentInfo.ToAsn1Object().GetDerEncoded(); 

but when I try  load my data signed in bouncycastle   I can't use  KJUR.asn1.cms.CMSUtil.verifySignedData   

any suggestions?

**Comment by morrisond91** [comment]
i have a similar experience here, i actually use KJUR to create a signature and pass it to a .NET Core api that implements BouncyCastle.

I created a signature using the same private key pem across both technologies for the same string value and both signature values are different. I haven't found a solution yet.

**Comment by kjur** [comment]
I think BouncyCastle SignedData class generates BER encoded ASN.1 data not DER. The jsrsasign only supports DER encoded SignedData. This may raise the issue. To resolve this, the encoded data generated by signedData.getEncoded() shall be converted by DEROutputStream. It can be handled by jsrsasign. Thanks.
