### ISSUE TITLE
some error in API doc

### ISSUE THREAD

**Issue by ayanamiyume** [kjur/jsrsasign#383]
http://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html
In this page,the method 
<static> {String} KJUR.crypto.Cipher.decrypt(hex, keyObj, algName)
 return param should be a normal decrypted string,not a hexadecimal encrypted string.

**Comment by kjur** [comment]
This will fix in the next 8.0.14 release".
