### ISSUE TITLE
Tool  JWT Decode utf8  garbled text

### ISSUE THREAD

**Issue by Hsinken** [kjur/jsrsasign#384]
https://github.com/kjur/jsrsasign/blob/master/tool/tool_jwt.html

Hi, I found a utf8 decode error,when i decode "中文" ，it will show you  garbled text.
I found out that function _doDecode()'s b64utos should be b64utoutf8.
Thanks for your awesome framework,It's helps me a lot

function _doDecode() {
  var sJWS = document.form1.jws1.value;
  var a = sJWS.split(".");
  var uHeader = b64utos(a[0]); => b64utoutf8(a[0]);
  var uClaim = b64utos(a[1]);  => b64utoutf8(a[0]);

**Comment by JerryUS2019** [comment]
This is not an issue/bug and should be closed...

**Comment by kjur** [comment]
Thanks @JerryUS2019 . This will be closed.
