### ISSUE TITLE
Check RSA key passcode possible?

### ISSUE THREAD

**Issue by SamuelWei** [kjur/jsrsasign#385]
I encrypted the key with openssl: openssl rsa -aes256 -in privKey.key -out encrypted.privKey.key

I'm using KEYUTIL.getKey (https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey) to load an encrypted private key and decrypt it.
The function getKey always returns a decrypted private key, whether the passcode is correct or not.

**Is there a way to check if the passcode is correct or not?**

**Comment by kjur** [comment]
Sorry but jsrsasign can't provide such function. I think you can use getKey then check if valid private key is loaded.
