### ISSUE TITLE
Can 'jsrsasign' encrypt plain text by public rsa key, and decrypt by corresponding private rsa key?

### ISSUE THREAD

**Issue by Nisus-Liu** [kjur/jsrsasign#387]
查到的资料都是用这个插件进行签名的.
但是我想实现加密请求, 然后解密响应数据.

**Comment by JerryUS2019** [comment]
I think you should ask at Stackoverflow how to use it. This is only for reporting bugs/issues...

**Comment by kjur** [comment]
Please use Cipher class. Thanks.
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html
