### ISSUE TITLE
verifySignedData help

### ISSUE THREAD

**Issue by kate1012** [kjur/jsrsasign#393]
I have a CMS base64 encoded string that I converted to hex and passed into KJUR.asn1.cms.CMSUtil.verifySignedData(). Everything appears correct to me but I get the error 'Uncaught checking tag doesn't match: 0!=06'. What does that mean and how can I go about fixing it?

**Comment by michael79bxl** [comment]
I struggled for hours. I found out that you need to use getContentInfoEncodedHex and not getEncodedHex from newSignedData result. This is really not well documented.

**Comment by kjur** [comment]
Thanks @ghost. This ticket will be closed.
