### ISSUE TITLE
why encrypt method produce outputs with different lengths from Same input?

### ISSUE THREAD

**Issue by mahdieh68** [kjur/jsrsasign#399]
this method produce Output with different lengths  from the Same input.
data = 'ccff6e4dffdd0281806667e8a1aeff11f713e79a0466f7d879963a27fa611ebd3ee839ba9dfc68b635117adacdbfc870a80fa83906cda971a4d49';
function encrypt(publicKeyObj, data) {
    if (publicKeyObj instanceof RSAKey && publicKeyObj.isPublic) {
        return KJUR.crypto.Cipher.encrypt(data, publicKeyObj, algName);
    } 
}
result 1: 
1380e4ffac4bb467836786f5894a21d8d0ae45461f39f338e831e20332cf24fa23311dd9fcc201ba78b5b4de5a4db4bf0c4bbf05af44f7dd7b2cd82b7b3f028b325540886efcaf8fa6f860618ea2bff210352bbc7471cdad4ff642939cad83ed7a29eda983469c9fad15d9813a300836376d029d612bc9eecd487e64024d4235
result length = 256 bytes
result 2:
c423149ec418e175bc4105eb30c6aa24ba8e2b23b486cacabd5174ff78c066f3b89a53fd46bd8296c885f8f574a9034039b57063336eeca885ce2b83c321891ea901e87a49749fc3cca75890a6713bd55861235e4d03de16bb83d2c64483b01f4b024ff6a9ed1a62e588dcc43c40acbb1aecef206caaa3f89eebfa2a5ed874
result 2 length = 254 bytes

**Comment by kjur** [comment]
RSA encryption in RSAES-PKCS1-v1_5 uses a random number. That's why encrypted message will be different every time. See
https://www.emc.com/collateral/white-papers/h11300-pkcs-1v2-2-rsa-cryptography-standard-wp.pdf
