### ISSUE TITLE
bug with sign.init method

### ISSUE THREAD

**Issue by wes67stg** [kjur/jsrsasign#400]
I am trying to use the signature object, but the method sign.init fails with the error: "init failed:this only supports pkcs5PBES2". I am using an encrypted private key in PKCS#8PEM that used 3DES as an encryption algorithm. 

The init method from the KJUR.crypto.signature calls KEYUTIL.getKey(keyparam, pass) (line 1076: https://kjur.github.io/jsrsasign/api/symbols/src/crypto-1.1.js.html). 

The getKey method calls _KEYUTIL.getKeyFromEncryptedPKCS8PEM(param, passcode) (line 1188: https://kjur.github.io/jsrsasign/api/symbols/src/keyutil-1.0.js.html). 

The getKeyFromEncryptedPKCS8PEM method then calls this._getPlainPKCS8HexFromEncryptedPKCS8PEM(pkcs8PEM, passcode) (line 568) , which in turn calls the methods this.parseHexOfEncryptedPKCS8(derHex) at the line 544 and KEYUTIL.getPBKDF2KeyHexFromParam(info, passcode) at the line 546. 

These 2 last methods are causing the problem because, in the documentation, it says they only supports PKCS#5.

Here are my questions:

- Why do multiple methods i cited have PKCS8 in their name when they only supports PKCS5? It causes a lot of confusion, a name like parseHexOfEncryptedPKCS8PEM suggests that i should be able to give it an encrypted key in PKCS8PEM and it should return the hex of the given key. Also the KEYUTIL.getKey method has a comment saying "// 11. private key by encrypted PKCS#8 hexadecimal RSA/ECDSA string" so, in my understanding, it should work, but does not.

- Are there any workarounds that can be done in order to sign a message with an encrypted private key in PKCS8PEM?

**Comment by wes67stg** [comment]
I think i might have found the underlying problem, i am using SHA256withECDSA and the doc says : "Encrypted PKCS#8 only supports PBKDF2/HmacSHA1/3DES" which might be the actual source of my problem. I will leave this issue open in case i am wrong on this one, but feel free to close it if i am right

**Comment by kjur** [comment]
Thank you. It's a specification as in the document. So this ticket is closed.

**Comment by wes67stg** [comment]
i am not sure i understand your answer. The documentation says : "NOTE1: Encrypted PKCS#8 only supports PBKDF2/HmacSHA1/3DES". Using keystore explorer, i get my private key in 3DES so it should work.

**Comment by kjur** [comment]
Sorry for confusion however you seem misunderstanding. KEYUTIL.getPBKDF2KeyHexFromParam only supports pkcs5PBKDF2 with HmacSHA1 for PBKDF2 not PKCS#5 key format. Sorry but your key seem not supported format for jsrsasign. Thanks.

**Comment by wes67stg** [comment]
oh alright, thanks
