### ISSUE TITLE
it has a performance problem in IE8 browser

### ISSUE THREAD

**Issue by peanuts6** [kjur/jsrsasign#401]
While running on IE8 browser, it popup a dialog box:
Do you stop running this script?
The footsteps on this page cause the web browser to run slowly.
If you continue to run, your computer will likely Stop the response.

IE8浏览器下运行，弹出对话框：
停止运行此脚本吗？
此页面上的脚步造成 web 浏览器运行速度缓慢。
如果继续运行，您的计算机将可能
停止响应。

**Comment by DinoChiesa** [comment]
That's a problem with IE8. 
You need to use a current browser that is not out of support.
Try Edge or Chrome or FFox.

**Comment by kjur** [comment]
Thank you @DinoChiesa . This ticket will be closed.
