### ISSUE TITLE
Support for X509v3 extension Subject Key Identifier

### ISSUE THREAD

**Issue by sstone1** [kjur/jsrsasign#402]
I am trying to use this library to generate a certificate that has the X509v3 extension Subject Key Identifier, as documented here:

https://tools.ietf.org/html/rfc5280#section-4.2.1.2

There's no built in class for this extension, so I'm trying to build it manually:

```
const extSKI = new KJUR.asn1.x509.Extension();
extSKI.oid = '2.5.29.14';
extSKI.getExtnValueHex = () => { return 'aa' }; // TODO: this needs to return the SKI
```

It would be nice if this library included built in support for this extension, along with automatically generating the SKI from the specified subject public key.

**Comment by sstone1** [comment]
```

**Comment by zcqzcg** [comment]
@sstone1    Hi Simon,
I can see that your SKI is used on the ECDSA-keys, may I ask about the RSA ones?
I have trouble on how to get a SKI from the RSA keys.
The SKI is able to see on the OpenSSL tools with the cert, but I don't know how to get it from keys.
It would be great if you may share any advices.
Thanks!
David

----
I am using that to modify fabric-sdk-node to use with RSA keys/certs.
The fabric part is already modified to use RSA.

**Comment by kjur** [comment]
Thank you. I've add SubjectKeyIdentifier extension support in 8.0.14 release today.
