### ISSUE TITLE
Cannot read property bitLength of undefined

### ISSUE THREAD

**Issue by thingswizard** [kjur/jsrsasign#404]
The code is the one here below and the issue doesn't show itself always and this makes it even more weird. 

pubkey and signature are hexadecimal numbers like they should be. 

`  const r = require("jsrsasign"); 

    let rsa = new r.RSAKey();
    let exp = "010001";
    rsa.setPublic(pubkey, exp);
    let verification = rsa.verify(urlParams, signature);`

Debugging inside the file where this function is located I found that "this.n" was undefined and therefore that error is returned. However "n" is not one of the parameters I passed, which I checked and are passed correctly. If anyone knows where this "n" property come from and has any clue about how to fix it would be really appreciated =)

**Comment by kjur** [comment]
Arguments of rsa.setPublic shall be BigInteger objects. When you provide hexadecimal strings, do lollowing:
```
rsa.setPublic(new BigInteger(pubkey, 16), new BigInteger(exp, 16));
```
