### ISSUE TITLE
generate CSR including expiry date

### ISSUE THREAD

**Issue by hnamzian** [kjur/jsrsasign#405]
Hi,
I'm intended to generate a CSR file including expiry date. how is it possible to set it using jsrsasign library?

**Comment by kjur** [comment]
The newCSRPEM method of CSRUtil class don't support expiry date however I think you can implement to support it.
https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.csr.CSRUtil.html#.newCSRPEM
