### ISSUE TITLE
What's the equivalent of jwt.io debugger demo using private AND public key with RSA256?

### ISSUE THREAD

**Issue by realtebo** [kjur/jsrsasign#406]
https://jwt.io/#debugger, using RS256, creates a demo JWT that uses BOTH private and public key to sign the jwt. 

I suppose it uses private key of sender and public key of target.

But how to generate an RS256 sign in this way using jsrsasign?

**Comment by DinoChiesa** [comment]
Here is one example. https://dinochiesa.github.io/jwt/
This page: 
 - creates a contrived RSA keypair using jsrsasign
 - contrives a JWT with a simple payload, and signs it with the private key
 - exposes the keys and the encoded JWT

**Comment by realtebo** [comment]
Thanks, but 

1. I asked for a demo of js to create a JWS. Your linked page is simply identical to jwt.io, a part that is has a pre-made jws.

2. I was completely wrong on what I understood. I was thinking it need both sender private key and target public key to generate the signature. It was simply a visual thing on jwt.io (and in your linked page). Simply, signature was generated using private key of sender and verified using public key of sender.

**Comment by realtebo** [comment]
If usefull to someone googling to here, I solved using NodeRsa to create PCKS8 version of RSA key pairs

```
const key_pair = new NodeRSA().generateKeyPair();
this.public_key = key_pair.exportKey("pkcs8-public");
this.private_key = key_pair.exportKey("pkcs8-private");
```

Then, I used this kjur package for generate a signed jwt.

```
var header = {
                alg: "RS256",
                typ: "JWT"
            };

            var payload = {
                serial: this.form.device_serial,
                date: 1557388310,
                count: 114,
                code: 0,
                lat: 44.6367087,
                long: 11.352348,
                lot: "ABF000127",
                notes: ""
            };

            var stringifiedHeader = JSON.stringify(header);

            var stringifiedPayload = JSON.stringify(payload);

            var sender_private_key_obj = KJUR.KEYUTIL.getKey(this.private_key);

            this.test_jwt = KJUR.jws.JWS.sign(
                "RS256",
                stringifiedHeader,
                stringifiedPayload,
                sender_private_key_obj
            );
```
