### ISSUE TITLE
Can we encrypy payload using jsrassign?

### ISSUE THREAD

**Issue by realtebo** [kjur/jsrsasign#407]
I know that goal of JWS is to create a criptographic signature, not to encrypt payload.

I ask you if, someway, it's supported to encrypt the payload, for example just invoking a base function 

I'd like to generate a semi-obscured payload like the following

```
var payload = {
  public: {
    serial: 'AB12312'
  },
  private: KJUR.encryptString(JSON.stringigy({ ... some private data  }), rsa_private_key)
}
```

If not supported? Do you know a js library che could simply use RSA+SHA256 to encrypt a string?

**Comment by kjur** [comment]
I think you need to encrypt payload by symmetric ciphers such as AES not RSA. I hope this helps.
