### ISSUE TITLE
PSS verification  - padding bug?

### ISSUE THREAD

**Issue by metalicworker** [kjur/jsrsasign#41]
I am using jsrsasign-latest-all-min.js

1) I compute PSS signature:

var msg = "hello";
var sig = rsa.signStringPSS(msg, "sha1");

2) I try to verify:

console.log("verified: " + rsa.verifyStringPSS( msg, sig, "sha1" ) );

Error: on line 389 of rsasign-1.2.js, "encoded message does not end in 0xbc";

Let me know if you have any difficulty reproducing

3) I think there may be another error, because the signature given by this method cannot be validated using Crypto++ signature scheme RSASS<PSS, SHA1>, which is the same scheme

**Comment by maiermic** [comment]
@sbheinric I try to solve a similar problem (same error). What do you mean by *values that prevent decryption from inverting the encryption result*?

**Comment by maiermic** [comment]
Found the problem: A bug in an unicode-to-hex converter (not part of jsrsasign).
