### ISSUE TITLE
Support for unencrypted EC Private Key

### ISSUE THREAD

**Issue by remko** [kjur/jsrsasign#414]
I'm trying to load an EC private key from PEM (`BEGIN EC PRIVATE KEY`) using `KEYUTIL.getKey`, but am getting a 'not supported argument'.  Looking at the code, only the encrypted format seems supported, and I verified this that it indeed works with an encrypted key. 

Is this an oversight? Can it easily be added?

**Comment by kjur** [comment]
Thank you for your pull request. I've merged it into keyutil.js and published 8.0.14 release today.
