### ISSUE TITLE
Public key conversion to ASN.1 format

### ISSUE THREAD

**Issue by chief0815** [kjur/jsrsasign#417]
Hello,

we are using jsrsasign to try and verify a signature that was created not using the jsrsasign library.
The public key and the signature are encoded as binary but are also available as hex representation.

When we try using jsrsasign to verify the signature, we get the notice that the signature is not a ASN.1 sequence.

How can the signature be converted from binary/hex into the corresponding valid ASN.1 sequence?

```
Our public key hex: 042067FE298C21B32C3EFF09B5C2966933[...]0B2B38ACD6E01053ECF332A5DB3CED296DE
Our signature hex: 1C48AD6B1FBCF21B11FF4DF319705C3ABCD5BAB9CA[...]9960995FD6CE4BFBC6C29383C876834AB8E28
```

```
var sig = new KJUR.crypto.Signature({"alg": sigalg, "prov": "cryptojs/jsrsa"});
sig.init({xy: pubkey, curve: curve});
sig.updateString('thisIsOurHashValue');
var result = sig.verify(sigval); // <-- Error "sigval is not a valid ASN.1 sequence" was thrown
		
if (result) {
	alert("valid ECDSA signature");
}
	
else {
	alert("invalid ECDSA signature (" + result + ")");
}
```

Thank you.

**Comment by kjur** [comment]
You can use concatSigToASN1Sig static method:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.ECDSA.html#.concatSigToASN1Sig

```JavaScript
var asn1SigVal = KJUR.crypto.ECDSA.concatSigToASN1Sig(sigval);
var sig = new KJUR.crypto.Signature({"alg": sigalg, "prov": "cryptojs/jsrsa"});
sig.init({xy: pubkey, curve: curve});
sig.updateString('thisIsOurHashValue');
var result = sig.verify(asn1SigVal);
```
