### ISSUE TITLE
zulutosec shows the wrong time

### ISSUE THREAD

**Issue by tmikaeld** [kjur/jsrsasign#418]
I've got the zulu time `451208142907Z`
Which when using zulutosec gives `-1898611149`
But when using zulutodate gives `Fri, 08 Dec 2045 14:29:07 GMT date`

The zulutodate is the correct date.

Any idea why zulutosec gives this issue?

**Comment by kjur** [comment]
zulutosec returns POSIX time of second which supports until 2038.
https://en.wikipedia.org/wiki/Year_2038_problem
That's why raising issue. It may be described in the manual in the future version. Thanks.
