### ISSUE TITLE
Private key to calculate public key PLEASE

### ISSUE THREAD

**Issue by ghost** [kjur/jsrsasign#421]
Private key to calculate public key, I read his question
https://github.com/kjur/jsrsasign/issues/328
There is no solution. The usage example here is that the user saves the private key locally.
The private key calculates the public key, sends the signature and public key to the server, and passes the message
The server determines that the public key hash is unique, which can guarantee that the user permissions can be authenticated without requiring the user's password, can it? Or you tell me
1. Extract the public key from the signature
2. Calculate the public key with the private key

**Comment by shargon** [comment]
Take a look https://github.com/kjur/jsrsasign/issues/421

**Comment by kjur** [comment]
Hello @ghost, 

1. It's impossible to extract public key from a signature.
2. As for ECDSA, 
```JavaScript
ec = new KJUR.crypto.ECDSA({curve: "secp256r1", prv: "12af...");
console.log(ec.prvKeyHex);
console.log(ec.pubKeyHex);
```
You can refer private and public key when you provide private key.
Thanks.
