### ISSUE TITLE
YUI throwing vulnerability errors

### ISSUE THREAD

**Issue by ulieckstein** [kjur/jsrsasign#426]
i am running a CI pipeline which includes the OWASP dependency checker module, which throws a security warning because of the yahoo script included in your package. i have read the other issue regarding this warning and i understand that your code does not use any of the vulnerable code parts. but since the yahoo script is out of maintenance since 2014 now and you only use the extend method, shoudn't it be about time to get rid of it altogether?

it seems there already is an alternative to the extend package given in https://github.com/kjur/jsrsasign/issues/140#issuecomment-251836974

**Comment by kjur** [comment]
There is no plan to remove a part of YUI at current stage. In the future major release, it will be removed. Thank you.
