### ISSUE TITLE
Compliance with RFC8705/RFC4514

### ISSUE THREAD

**Issue by ruiengana** [kjur/jsrsasign#428]
Hi,

I am using X509 getsubjectString() to register a Financial API client using tls_client_auth, where I am passing the tls_client_auth_subject_dn using getSubjectString().

However, it seems there is a discrepancy regarding the value getSubjectString() calculates versus what the Auth Server calculates from my TLS certificate.

This is what I am sending using getSubejctString(): "/C=GB/O=OpenBanking/OU=0014H00001lFE3TQAW/CN=M8kIuKVwwejkrErfwuJoO9"

And this is what the Auth Server is extracting from the cert: "CN=M8kIuKVwwejkrErfwuJoO9,OU=0014H00001lFE3TQAW,O=OpenBanking,C=GB"

Is getsubjectString() lined up with RFC8705/RFC4514 format?

Thank you,
Rui

**Comment by kjur** [comment]
jsrsasign provides converters. Please see this:
https://github.com/kjur/jsrsasign/wiki/NOTE-distinguished-name-representation-in-jsrsasign

**Comment by ruiengana** [comment]
Thank you Kenji!
Works beautifully. Apologies but originally I couldn’t find this converter. Maybe would be good to have a link or some example to this method from the getSubjectString() one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kjur** [comment]
Thank you. Sample have been added in the next release 8.0.14.
