### ISSUE TITLE
Support for Hermes js engine

### ISSUE THREAD

**Issue by Kotpes** [kjur/jsrsasign#429]
I'm using the library in our react-native project. There's a new js engine from Facebook, that speeds up quite a few things on android https://hermesengine.dev.

However, with this library I'm getting:
![Screenshot_1586161582](https://user-images.githubusercontent.com/2579093/78538559-dd34ab80-77f9-11ea-8f9c-7646da5d09db.png)

that points to line 248 in `jsrsasign.js`

Would be great to get a support for it.

**Comment by kjur** [comment]
Sorry but I can't provide any help by information above.
