### ISSUE TITLE
decrypt binary

### ISSUE THREAD

**Issue by tamascsaba** [kjur/jsrsasign#432]
I need a little help. I want to decrypt a binary file, it is an encrypted image (png). 
I found a method https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Cipher.html to decrypt data, but it works with hexadecial string, but i want to use with `Uint8Array`.  Is there any way to decrypt binary data?

**Comment by kjur** [comment]
jsrsasign provides ArrayBuffertohex method:
https://kjur.github.io/jsrsasign/api/symbols/global__.html#ArrayBuffertohex
Uint8Array can be converted to ArrayBuffer by buffer method.
```JavaScript
var ua = Uint8Array.of(1,2,3,4,5,6); // Uint8Array
var buf = ua.buffer // ArrayBuffer
var hex = ArrayBuffertohex(buf);
```
Then it can be encrypted and decrypted by Cipher class.

```
