### ISSUE TITLE
Issue Converting PEM to HEX

### ISSUE THREAD

**Issue by Swhite215** [kjur/jsrsasign#436]
jsrsasign npm version  -^8.0.16

I am working on a project where I need to convert a PEM certificate (privateKeyPEM) to a HEX encoded key (prvKeyHex), and then create a ecdsa signing key with the prvKeyHex.

I am following documentation for a project on Hyperledger Fabric and it has the below line:

`const { prvKeyHex } = KEYUTIL.getKey(privateKeyPEM);`

When I run that code, prvKeyHex ends up being undefined. Is this the intended behavior?

**Comment by kjur** [comment]
This works fine:
```JavaScript
#!/usr/bin/env node
var rs = require("jsrsasign");
var rsu = require("jsrsasign-util");
var pem = rsu.readFile("k1.prv.p8p.pem"); // read PKCS#8 EC private key
var key = rs.KEYUTIL.getKey(pem);
console.log(key.prvKeyHex);
```

**Comment by Swhite215** [comment]
Thank you for clarity on the key types. I wasn't using the correct key type and I also did not use the correct file when I ultimately called the KEYUTIL.getKey() method. Thank you for your help.
