### ISSUE TITLE
 The encrypted ciphertext is less than 512 long

### ISSUE THREAD

**Issue by 328467639** [kjur/jsrsasign#449]
Hi, Sometimes I find that the encrypted ciphertext is less than 512 long. This is an occasional problem, but with a high probability of occurrence. About five times per 1,000 encryptions.

code like this:
        for(var i=0;i<1000;i++){
		var b = KJUR.crypto.Cipher.encrypt("aaa", pub);
		if(b.length != 512){
			console.log(i+"-"+b);
		}
       }

**Comment by kjur** [comment]
Do you find any trouble when decrypting them?

**Comment by kjur** [comment]
I've tried to generate 1000 encrypted files with RSA 2048bit public key with jsrsasign. 4 of 1000 files are 255 bytes long and others are 256 byte long.

Also I've decrypted the 4 files with short 255 bytes files by openssl however they can decrypted properly. So I didn't find any issue on it.

**Comment by kjur** [comment]
At current stage, there is no interoperability issue among jsrsasign and openssl. So I won't fix the issue. What do you think? May I close this ticket?

**Comment by kjur** [comment]
This ticket is closed.

**Comment by brendanarnold** [comment]
For what it's worth this does cause decryption problems when passing to Python's encryption libraries

Surely this a deterministic operation? We should _never_ get one byte off?

For our case we got 255 bytes sometimes when encrypting with RSA and PKCS 1 padding
