### ISSUE TITLE
How to access private extension details/partial value of private ext

### ISSUE THREAD

**Issue by brajeshawasthi** [kjur/jsrsasign#453]
I was wondering how to access full private extension details in 509 cert? In getExtParamArray(), I do see private extension listed and as part of extn but it has partial value in hex. do we have any limitation on length of  privateext in jsrsasign?

Thanks

**Comment by kjur** [comment]
The extn value shall be a hexadecimal string of ASN.1 encoded byte. There is no limitation for length.

**Comment by brajeshawasthi** [comment]
Thanks for quick response @kjur.  Not sure what I am doing wrong but still I get only partial hex value of private ext  through getExtParamArray(). This x509 certificated was created by another external CA and I am able to see full private ext value through other online cert parser. 
Also, I noticed cert.getInfo() does not display private ext valuue, it just shows OID.

**Comment by kjur** [comment]
I think you can use X509.getParam for your purpose:
https://kjur.github.io/jsrsasign/api/symbols/X509.html#getParam

**Comment by brajeshawasthi** [comment]
I tried getparm() as well but still getParam() orgetExtParamArray() returns partial value of private extension. however the same 509 cert full correct value in go x509 package or other online parser. I will send you the x509 cert I am parsing in another message.  Again, than for your help.

**Comment by kjur** [comment]
When extn value is not enough for you and to parse private or unsupported extension, you need to extend jsrsasign.

**Comment by brajeshawasthi** [comment]
ok. thanks kjur.

**Comment by sgerhardt-trilobyte** [comment]
Hello kjur! Thanks a lot for this great library. I also run into the problem brajeshawasthi described. When I use getExtParamArray(), I get only a part of the private extension value:

```
{
  "extname": "1.2.3.4.5.6.7.8.1",
  "extn": "7b226174747273223a7b2268662e416666696c696174696f6e223a22222c2268662e456e"
}
```

```
$ echo 7b226174747273223a7b2268662e416666696c696174696f6e223a22222c2268662e456e | xxd -r -p
{"attrs":{"hf.Affiliation":"","hf.En
```

The complete value of the private extension "1.2.3.4.5.6.7.8.1" is:

`{"attrs":{"hf.Affiliation":"","hf.EnrollmentID":"paul","hf.Type":"client"}}`

There seems to be a problem with the length of the value

Sorry to ask again

**Comment by kjur** [comment]
Hi @sgerhardt-trilobyte , the extn value "7b2261..." seems wrong value. It should be ASN.1 encoded hexadecimal string. May I have your certificate to investigate the issue?

**Comment by sgerhardt-trilobyte** [comment]
Yes, of course

[paul.pem.txt](https://github.com/kjur/jsrsasign/files/5476617/paul.pem.txt)

**Comment by kjur** [comment]
Your private extension have wrong encoding:
```
        SEQUENCE {
          OBJECT IDENTIFIER authorityKeyIdentifier (2 5 29 35)
          OCTET STRING, encapsulates {
            SEQUENCE {
              [0]
                8E 0D CD 5D 6E 1C D6 D4 20 78 49 57 BA 6C 85 48
                96 51 1A 96 8F FC D6 B7 B9 4D 4F E1 0B 58 21 FF
              }
            }
          }
        SEQUENCE {
          OBJECT IDENTIFIER '1 2 3 4 5 6 7 8 1'
          OCTET STRING
            '{"attrs":{"hf.Affiliation":"","hf.EnrollmentID":'
            '"paul","hf.Type":"client"}}'
          }
```
Extension value shall be ASN.1 encoded data with OCTET STRING encapsulation.
The JSON string may be capsuled by UTF8String or PrintableString.

**Comment by sgerhardt-trilobyte** [comment]
Hi @kjur,

many thanks for the quick response. The certificate is generated by the Hyperledger Fabric CA and uses the following structure for private extension

`1.2.3.4.5.6.7.8.1 = ASN1:UTF8String:{attrs:{hf.Affiliation:{dep},hf.EnrollmentID:{user},hf.Type:client}}`

JSON string is capsuled by UTF8String.

That means if the extension value is not encoded data with octet string encapsulation there is no way with jsrsasign to get the complete value of the extension. 

Thanks again for the support

**Comment by kjur** [comment]
Hyperledger Fabric CA does't seem to provide proper extension ASN.1 encoder and requires fix.
