### ISSUE TITLE
[BUG] in JWS signing on specific password/secret length

### ISSUE THREAD

**Issue by cr15p** [kjur/jsrsasign#464]
I came across your library lately while using it in postman. As i tried to implement signing jwt those couldn't be verified on another system. After some digging and testing i found some kind of problem.
So what i tried to do is a password based signing with a password/secret of length 64 characters. In that case signing seems not working. Also in case of multiples of lengths of 64 like 128 and so on.
I was wondering if this "bug" is by intention and just not mentioned in documentation or if it's a unknown bug so far.
Thanks for your work. Hope to hear from you.

**Comment by kjur** [comment]
Hello. Can you provide any JWS and password having issue?

**Comment by cr15p** [comment]
Hey @kjur i figured out a solution.  

I used to call `pmlib.rs.jws.JWS.sign(null, {alg: "HS256", cty: "JWT"}, "".padEnd(64,"a"), "".padEnd(64,"a"))`, which is some extension of one example of the examples on the documentation page. 
That turned out to work sometimes, but failing most of the times. What helped was wrapping the 4th argument (passphrase) into an object like {"utf8": "".padEnd(64,"a")}. So my initial call becomes  `pmlib.rs.jws.JWS.sign(null, {alg: "HS256", cty: "JWT"}, "".padEnd(64,"a"), {"utf8": "".padEnd(64,"a")})`. That way the signing key always works, until now.
So i'm not quite sure where the problem comes from. Since the library for postman (postman-util-lib) seems just to forward that request to jsrasign library, my first guess was that it could come from this library.

I'm not sure if it's worth digging deeper into that issue, since i found a solution and also seems to be the only one to whom that problem occured. So I leave it to you to try it out and close that issue if you cant find any issue. 

Regards, chr15p

**Comment by kjur** [comment]
A HS256 JWT created by jsrsasign is successfully verified by https://jwt.io/ even though short password. Some JWT implementation requires password length limitation in HS(Hmac) signature. It doesn't seem jsrsasign's bug. So this ticket is closed.
