### ISSUE TITLE
Wrong doc and Typescript type

### ISSUE THREAD

**Issue by jer-sen** [kjur/jsrsasign#466]
The doc at https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Mac.html has errors. Examples for doFinal, doFinalHex and doFinalString show others functions (digest, digestHex, digestString).

Also Typescript type (from @types/jsrsasign) for doFinal is wrong (return type is void instead of string).

**Comment by kjur** [comment]
Thank you for the report. I've fixed the document in the online and source code. As for bundled API document, fix will be affected in the next release.
