### ISSUE TITLE
Get public key object from public key hex

### ISSUE THREAD

**Issue by yuminaut** [kjur/jsrsasign#467]
Hello. I wish to store a generated public key somewhere as a hex string, and then recreate the public key object from it. This is approximately what I've tried:

```js
const rs = require("jsrsasign");
const kp = rs.KEYUTIL.generateKeypair("EC", "secp256r1");

storeOnServer("my_id", kp.pubKeyObj.pubKeyHex)

// elsewhere:

const pubKeyHex = loadFromServer("my_id")

const pubKeyObj = rs.KEYUTIL.getKey(pubKeyHex) // <-- this doesn't work

verify("some text", pubKeyObj, someSignature);
```

... but I can't figure out how to do it or if it is even possible. Am I misunderstanding how to use the library? I've looked through all the issues and the documentation/tutorials but can't seem to understand. Sorry if this is the wrong place to ask.

**Comment by kjur** [comment]
How about storing public key with PEM format?:

```JavaScript
const rs = require("jsrsasign");
const kp = rs.KEYUTIL.generateKeypair("EC", "secp256r1");
const pubpem = rs.KEYUTIL.getPEM(kp.pubKeyObj);
storeOnServer("my_id", pubpem);

// elsewhere:

const pubpem2 = loadFromServer("my_id")
const pubKeyObj = rs.KEYUTIL.getKey(pubpem2);
verify("some text", pubKeyObj, someSignature);
```

**Comment by yuminaut** [comment]
It works great, thank you so much, and thank you for creating this library!
