### ISSUE TITLE
Use CSR to Generate a Certificate

### ISSUE THREAD

**Issue by hazam** [kjur/jsrsasign#468]
I tried but I can't understand how to actually use a generated CSR to create a valid client.
This is what I am banging my head on

```
const caPrivate = fs.readFileSync('./certs/test/intermediate.key.pem').toString();
var json = rs.KJUR.asn1.csr.CSRUtil.getParam(csrPem);
  var certPEM = rs.KJUR.asn1.x509.X509Util.newCertPEM({
    serial: { int: 4 },
    sigalg: json.sigalg,
    issuer: { str: '/C=US/O=a' },
    notbefore: { 'str': '130504235959Z' },
    notafter: { 'str': '240504235959Z' },
    subject: json.subject,
    sbjpubkey: json.sbjpubkey,
    ext: json.extreq,
    cakey: caPrivate
  });
 ```
 
 but all the certs generated this way fail the openssl verify command
 `$ openssl verify -purpose sslclient -verbose -CAfile intermediate.crt.pem ../client_certificate.pem`

**Comment by kjur** [comment]
What error will be raised? CSR's extension is not enough to generate certificate. For further investigation, your CSR is required.

**Comment by kjur** [comment]
For SSL client certificate issuance, you need some proper certificate extensions.

**Comment by kjur** [comment]
By above comment I'll clock this ticket. Thank you.

**Comment by hazam** [comment]
Thank you for your support.
