### ISSUE TITLE
Verification failure - can't find out why.

### ISSUE THREAD

**Issue by ChaosCrafter** [kjur/jsrsasign#469]
Is there a call I can make to determine why the last call to VerifyJWT failed? 
I've been using this successfully, but am now getting issues - I suspect with time-to-live.
It would be very useful if there was a failure-cause available somehow after a VerifyJWT rejected a token.

**Comment by kjur** [comment]
Sorry but at this stage, I can't provide any help. Please send me the token which raise issue. I can investigate further. Thanks.

**Comment by ChaosCrafter** [comment]
Thanks, we sorted the problem (though we're still not sure how)
I mostly wanted to recommend that the Verify calls should set a variable with the failure reason so that can be looked at for debugging.

**Comment by kjur** [comment]
Hi @ChaosCrafter , I'll close this ticket. If you find any failure token, please send me by another issue ticket. Thank you.
