### ISSUE TITLE
there are no function of toByteArrayUnsigned

### ISSUE THREAD

**Issue by emmansun** [kjur/jsrsasign#472]
There are no function **toByteArrayUnsigned()** used in ext/ecc-patch.js

and
`fromByteArrayUnsigned
 toByteArraySigned
`

of BigInteger

**Comment by kjur** [comment]
Do you get any error for their methods?

**Comment by emmansun** [comment]
yes, when I call ECPointFp.getEncoded().

**Comment by kjur** [comment]
There is no plan to provide all ECPointFp method. EC key generation, ECDSA signing and verification don't seem to require ECPointFp.getEncoded() method.

**Comment by emmansun** [comment]
ok, I can find them here: https://github.com/cryptocoinjs/bigi/blob/master/lib/convert.js

**Comment by kjur** [comment]
Thank you. It may be included in the future. This ticket is closed. Thank you for understanding.
