### ISSUE TITLE
verifySignedData: Get "malformed SignerInfo" error 

### ISSUE THREAD

**Issue by yongliang-huang** [kjur/jsrsasign#475]
When using verifySignedData to parse a existing CMS signed data,The error I get is "malformed SignerInfo". I have parsed the CMS signed data with CMSSignedData BouncyCastle and it success.

```
let hexData = "3082032d06092a864886f70d010702a082031e3082031a020101310b300906052b0e03021a0500300b06092a864886f70d010701a0820208308202043082016da003020102020a695eb79bb17229cda368300d06092a864886f70d0101050500303b310d300b0603550403130474657374311a301806092a864886f70d010901160b313233403136332e636f6d310e300c06035504060c053ce697a03e301e170d3136313132333039323234385a170d3231313132333039323234385a303b310d300b0603550403130474657374311a301806092a864886f70d010901160b313233403136332e636f6d310e300c06035504060c053ce697a03e30819f300d06092a864886f70d010101050003818d0030818902818100c5ffdb11c7661a9ff4c7a74dec3d7f7e9b2c590b8292023de5c43d2869ea1e1e19da45f75f0f821a992367db99ef9655acf8e5fa602243d91661120f6ef74c1771df9ccc57f741af053e9b7b935291fb07547dbdeefea9671d59e070086ba39d2adf0d5b0b76b516c25258f3d222a11243ad6da1a5afaaeb18df0b97f399ab130203010001a30f300d300b0603551d0f040403020490300d06092a864886f70d0101050500038181007831d3a76d433d0e898dc27cdba8367600d17399138cd1be889681aaa4bb6bd84fbed2fc98a30fe54d0625e77e41cf08dcefb21760e45c1eea6a252e9fb98c97162439e8626a18899852e18aff153d2aaeb9828dd143cffe4f651eabf50ff3fbf1d6ed91a27cb2655c8095b7c9c291039ffc68ffa1bebee6c5e3dcd0110812563181ee3081eb0201013049303b310d300b0603550403130474657374311a301806092a864886f70d010901160b313233403136332e636f6d310e300c06035504060c053ce697a03e020a695eb79bb17229cda368300906052b0e03021a0500300d06092a864886f70d01010105000481801c411a6e14546e637ec0912a44f086583ac7e729523f5f7e6ea23a3bd1e6214a9fd8fb912efebb3a06a33b99b5b9a2a7c3db36d153073472665cd8b870d859448693d0235a7e8f0931105d1adb5542f6df9577dd84f7064792dc89c452500aebd8ad4e0181ae50b1603420548aa4a629c708744c0514993a54854fc21970d8c0";
var result = jsrsasign.KJUR.asn1.cms.CMSUtil.verifySignedData({ cms: hexData });
```

Maybe I am missing something, so I would appreciate your help with this issue. Thanks!

**Comment by kjur** [comment]
Hi, jsrsasign only supports ASN.1 DER structure. I think CMS SignedData generated by BouncyCastle is ASN.1 BER encoded data not DER. Thus jsrsasign can't parse it. If you can generate DER encoded CMS SignedData by BouncyCastle, you can verify it by jsrsasign.

I think you can get DER encoded CMS SignedData by following method:
https://www.bouncycastle.org/docs/pkixdocs1.4/org/bouncycastle/cms/CMSSignedData.html#getEncoded(java.lang.String)

**Comment by yongliang-huang** [comment]
Hi, The hex data I provided is ASN.1 DER structure, not BER encoded data. and it is raw data not generated by BouncyCastle, I just  use BouncyCastle and jsrsasign to verfiy it. when using jsrsasign, I get the error.

**Comment by kjur** [comment]
Hi, I investigated your data and found it is old style PKCS#7 SignedData which is not supported by jsrsasign. Thank you for understanding.
