### ISSUE TITLE
Wrong types in @types/jsrsasign

### ISSUE THREAD

**Issue by giovanni9793** [kjur/jsrsasign#479]
For [Certificate](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.x509.Certificate.html) and [TBSCertificate](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.x509.TBSCertificate.html) are defined different types than docs, for example in Certificate types define method getPEM() and in TBSCertificate methods like setIssuerByParam(obj).

EDIT: also [tutorials](https://github.com/kjur/jsrsasign/wiki/Tutorial-for-ASN.1-structure-classes-of-X.509-certificate) need update

**Comment by kjur** [comment]
Sorry but I can't catch your comment. How can I update document? Is there any missed API description?

**Comment by kjur** [comment]
Some tutorials described in early days. I may update in the future.

**Comment by kjur** [comment]
I think test code can helps you.

**Comment by giovanni9793** [comment]
Sorry, I'll be more clear.
Code suggested by types: (I assume wrong because not working on runKit)
```ts
class TBSCertificate extends ASN1Object {
        constructor();
        private _initialize(): void;

        /**
         * set serial number field by parameter
         * @param intParam DERInteger param
         * @example
         * tbsc.setSerialNumberByParam({'int': 3});
         */
        setSerialNumberByParam(intParam: IntegerParam): void;
        
        /*...*/
```

Code suggested from docs:
```ts
var tbsc = new TBSCertificate();
tbsc.setByParam({version:3,serial:{hex:'1234...'},...});
```

**Comment by kjur** [comment]
Old API have been such that you suggested.

New API don't require such method for each certificate fields. You can modify any field by "params" property before signing.

``` JavaScript
var cert = new KJUR.asn1.x509.Certificate({
  ...
  issuer: {...}
  subject: {...}
 ...
});
cert.params.issuer = {...};
cert.params.subject = {...};
var hex = cert.getEncodedHex(); // automatically signed
```

Thus new API don't require any setter methods for each fields.

As for "tbsobj" member in Certificate class constructor argument, it requires one more nest structure which is unnecessary. So new API don't use "tbsobj" member and almost the same "params" structures between "Certificate" and "TBSCertfificate" class. Thank you for your understanding.

**Comment by kjur** [comment]
As you commented, wiki pages based on "OLD" API. I'll update in the future.

**Comment by giovanni9793** [comment]
Will you update also @types/jsrsasign? To understand if I can keep it or i can delete.

**Comment by kjur** [comment]
Please contact @types/jsrsasign author to update it since it's not mine. You don't need to delete this ticket. Thank you.

**Comment by kjur** [comment]
@types/jsrsasign seems based on old version of jsrsasign.
https://www.npmjs.com/package/@types/jsrsasign
