### ISSUE TITLE
xml signing issue in jsrsasign?

### ISSUE THREAD

**Issue by mpickell** [kjur/jsrsasign#48]
I am signing XML (SAML) using the jsrsasign library, using KJUR.  I have the "SHA1withRSA" signing and validation set up per the Signature tutorial, and validation is returning as being valid.  But when the signed XML is sent, the server cannot validate.  

(I have this signing working with nodeJS using the xml-crypto plugin, but nodeJs uses its own built-in crypto.  I am trying to use this outside of nodeJS, and therefore replacing the crypto library with jsrsasign)

Is there a limitation using these libraries when creating XML digital signatures?  I think the xml string i'm signing is 650+ chars.  

Is this something that "progressive signing" would solve?  I can't seem to find any documentation on it other than the part mentioned in the tutorial.

**Comment by kjur** [comment]
Thank you for the report. I'll close this ticket.
