### ISSUE TITLE
Support for COSE (RFC8152)

### ISSUE THREAD

**Issue by letmaik** [kjur/jsrsasign#487]
Similar to JWS support it would be nice if jsrsasign would support [COSE](https://datatracker.ietf.org/doc/html/rfc8152) which is based on [CBOR](https://datatracker.ietf.org/doc/html/rfc8949).

**Comment by kjur** [comment]
There are some other COSE libraries already. So there is no plan to support COSE in jsrsasign at this stage.
https://github.com/erdtman/cose-js
