### ISSUE TITLE
JWK to PEM

### ISSUE THREAD

**Issue by maganuk** [kjur/jsrsasign#491]
Hi, 

Thanks for a great library. I'm trying to convert a bunch of JWKs to PEM. I've got the RSA and EC (P-256) ones working. But the following ones are failing.

    const P384 = {
        kty: 'EC',
        d: 'xspcdSSSLxMv-FJq-QAL7AHNPem6iUHolzptaS4VjhHwyOLNTnnhQ1NCFJce4FYI',
        crv: 'P-384',
        x: '2LRADAuSsoV6zpuh36JXoJrJBFcvTonO8aF9nqGZSvPsdhvMBxzLs5AF6kEzw9xX',
        y: 'yFlKEiGF1OjptNQUnmEafthNMti8PvTPwre3e33M664dIc15hNEq4CQV6XX9QMeX',
    };

    const P521 = {
        kty: 'EC',
        d: 'Ac2uM1aLJmV7qMaW69M3CeMq39841rRWLPFQcZW11zq98Ut_ZwOD1OPzllikQpfUNuUrBYc2ih88w2NCdowIpOCx',
        crv: 'P-521',
        x: 'AN43ALHCp0mY8AhgdMSbcFIfEwBLlC8NcDsij4YbBgIW21ao7MJSrSYEgACvNTHJ1i3yvRpjMSWodS3L4gAtLWrl',
        y: 'AKUkq5hDshDDcwvhlOXf3_MqIK1pNzvI3rSmssMIoDpdSksAV9Rwx2D6HIzzuuNzd_v1ENqH_DV2M-EZim2Zp2VJ',
    }

I'm trying this:

    const key = KEYUTIL.getKey(P384);
    const response = KEYUTIL.getPEM(key);

They are both throwing 'algId and/or subjPubKey not set'. 

Thanks
Vishal

**Comment by kjur** [comment]
As for P-521, "jsrsasign" doesn't support it.

As for P-381, there is a workaround.
```JavaScript
var k1 = KEYUTIL.getKey(P384);
k1.curveName = "secp384r1";
KEYUTIL.getPEM(k1, "PKCS8PRV");
```
This issue will be fix in the future.

**Comment by maganuk** [comment]
Thanks @kjur
