### ISSUE TITLE
Is the SHA256withRSA/PSS algorithm supported?

### ISSUE THREAD

**Issue by Gonzalo2683** [kjur/jsrsasign#494]
Hello, I have a query.
Is the `SHA256withRSA/PSS` algorithm supported?

Is there any way that I can define the padding for verification?

Any example using the COSE and CBOR standard? 

Forgive me for bothering you, I had to ask.

Thanks.

**Comment by kjur** [comment]
Hi, I'll answer as following:

(1) RSAPSS supported. You can specify algorithm name "SHAxxxwithRSAandMGF1" for PSS. As for SHA256, you can use "SHA256withRSAandMGF1".

(2) As for RSAPSS algorithm parameters:

- OAEP-PSSDigestAlgorithms
  - For Signature class, it will be the same as signature hash algorithm. So, if "SHA256withRSAandMGF1" it will be "SHA256" and you can't set it.
  - For RSAKey.verifyWithMessageHash method, you can set any algorithm.
- mask generation function: jsrsasign only supports "MGF1".
- salt length: You can set any value for salt length but there are two special values. 
  - -1: sets the salt length to the digest length (jsrsasign DEFAULT)
  - -2: sets the salt length to maximum permissible value (i.e. keybytelen - hashbytelen - 2). This is OpenSSL's DEFAULT.
  - So, interoperability with OpenSSL RSAPSS, you can specify Signature class as  following. `Signature({alg: "SHA256withRSAandMGF1", psssaltlen: -2})`
- trailer field: jsrsasign only supports 1.

(3) As for COSE and CBOR, jsrsasign will not support it.
