### ISSUE TITLE
Feature Request: PKCS#7?

### ISSUE THREAD

**Issue by ikreb7** [kjur/jsrsasign#497]
Hello,

are there any plans to support pkcs7?

**Comment by kjur** [comment]
Do you mean PKCS#7 signature or PKCS#7 certificate bundle or another one?

**Comment by ikreb7** [comment]
I hope I don't miss something at the documentation. I meant the PKCS#7 certificate bundle.

I want to create a PKCS#12 file with a private key and a PKCS#7 file.

**Comment by kjur** [comment]
I'm sorry but there is no plan to support PKCS#7 certificate bundle generation in jsrsasign. I would be better to use openssl for it.

**Comment by ikreb7** [comment]
Pity. But thanks for the very fast response and your project.
