### ISSUE TITLE
Binary Encryption

### ISSUE THREAD

**Issue by sokcuri** [kjur/jsrsasign#502]
Thanks for making this useful library.

I am using RSA for key exchange and validation, this key can contain 0x00 (NULL)
Therefore, input cannot be received as a string, and it must be able to receive and process hex like UInt8Array or decode.
if there is a way to get the input as hex or UInt8Array?

**Comment by kjur** [comment]
Jsrsasign has many converters in base64x.js
https://kjur.github.io/jsrsasign/api/symbols/src/base64x-1.1.js.html

*tohex, hexto* - such as utf8tohex rstrtohex
*toArrayBuffer, ArrayBufferto* - such as hextoArrayBuffer

ArrayBuffer can handle Uint8Array.

**Comment by sokcuri** [comment]
Thanks a lot!!
