### ISSUE TITLE
Broken link in repository description

### ISSUE THREAD

**Issue by BhavyaSheth22** [kjur/jsrsasign#503]
The link to the public page is broken in the Github repository description (https://kjur.github.com/jsrsasign/). It should be changed to https://kjur.github.io/jsrsasign/. Please have a look at that.

**Comment by kjur** [comment]
Could you let me know broken links? I couldn't find any broken links in gh-pages repository.

**Comment by BhavyaSheth22** [comment]
I meant the link is broken in the  repository's About section description (https://github.com/kjur/jsrsasign), not in public documentation.

**Comment by kjur** [comment]
I think they are only in headers and now I've fixed them. So I hope they are fixed in the next release.
