### ISSUE TITLE
incompatibility with Java Nashhorn execution

### ISSUE THREAD

**Issue by pts-danielmanley** [kjur/jsrsasign#508]
hello -- I'm trying to use jsrsasign in Nashorn server side in Java -- but it requires the "navigator" object that's not provided in Nashorn (no browser in the server of course) - do you know of a workaround for this?  thanks in advance

**Comment by kjur** [comment]
In the third party program, navigator is used for random number generation. You may change them, then jsrsasign will work in Nashhorn.

https://github.com/kjur/jsrsasign/blob/master/ext/jsbn.js
https://github.com/kjur/jsrsasign/blob/master/ext/rng.js

Jsrsasign's npm package is also available. This may work in Nashhorn since Node.JS has no navigator object.
https://www.npmjs.com/package/jsrsasign

**Comment by kjur** [comment]
I've confirmed that jsrsasign works fine in Nashhorn on Zulu OpenJDK on M1 Mac.
Please use npm/lib/jsrsasign.js and remove "exports.* = *" lines. Then it can be evaluated in Nashhorn.

**Comment by pts-danielmanley** [comment]
super -- thanks!  I'll give npm/lib/jsrsasign.js a try in Nashorn.  otherwise, our next stop is an implementation in Java.

**Comment by kjur** [comment]
Here is a jsrsasign on Nashhorn sample:
```Java
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import java.net.*;
import java.io.*;

public class Hoge3 {
    public static void main(String... args) throws Exception {
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("nashorn");
        URL url = Thread.currentThread().getContextClassLoader().getResource("jsrsasign1.js");
        engine.eval(new InputStreamReader(url.openStream()));
        engine.eval("print(KJUR.crypto.Util.hashString('aaa','sha256'));");
    }
}
```
Then, this shows:
```
% java Hoge3
9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0
```

**Comment by pts-danielmanley** [comment]
righto - same here - works like a charm!  thanks so much!
