### ISSUE TITLE
KJUR.asn1.cms.CMSUtil.verifySignedData error 

### ISSUE THREAD

**Issue by coachaac** [kjur/jsrsasign#509]
hello, 
i run into an error when using KJUR.asn1.cms.CMSUtil.verifySignedData.
Data has been signed by 2 signers.

here is the error : 

```
TypeError: Cannot read property 'length' of undefined
    at x (/Users/me/dev/a-test/node_modules/jsrsasign/lib/jsrsasign.js:228:19181)
    at e (/Users/me/dev/a-test/node_modules/jsrsasign/lib/jsrsasign.js:228:19532)
    at o (/Users/me/dev/a-test/node_modules/jsrsasign/lib/jsrsasign.js:228:18857)
```
the crash is on the last line of this code (aIdx is undefined)  : 

```
    var _findCert = function(hCMS, result, si, idx) {
	var certsIdx = result.parse.certsIdx;
	var aCert;

	if (result.certs === undefined) {
	    aCert = [];
	    result.certkeys = [];
	    var aIdx = _getChildIdx(hCMS, certsIdx);
	    for (var i = 0; i < aIdx.length; i++) {
		var hCert = _getTLV(hCMS, aIdx[i]);
		var x = new X509();
		x.readCertHex(hCert);
		aCert[i] = x;
		result.certkeys[i] = x.getPublicKey();
	    }
	    result.certs = aCert;
	} else {
	    aCert = result.certs;
	}

	result.cccc = aCert.length;
	result.cccci = aIdx.length;
```

after some debugging , i saw that aIdx is undefined because result.certs is not undefined.
i'm not sure if my fix is correct so i do not send you a pull request

but i think this will fix the bug : 

```
 var _findCert = function(hCMS, result, si, idx) {
	var certsIdx = result.parse.certsIdx;
	var aCert;
         var aIdx;   <--- variable scope here

	if (result.certs === undefined) {
	    aCert = [];
	    result.certkeys = [];
	     aIdx = _getChildIdx(hCMS, certsIdx);
	    for (var i = 0; i < aIdx.length; i++) {
		var hCert = _getTLV(hCMS, aIdx[i]);
		var x = new X509();
		x.readCertHex(hCert);
		aCert[i] = x;
		result.certkeys[i] = x.getPublicKey();
	    }
	    result.certs = aCert;
	} else {
	    aCert = result.certs;
            aIdx = _getChildIdx(hCMS, certsIdx); <--- aIdx generation
	}

	result.cccc = aCert.length;
	result.cccci = aIdx.length;
```

Yann.

**Comment by coachaac** [comment]
sure . 

First certificate : 

-----BEGIN CERTIFICATE-----
MIIBejCCASGgAwIBAgIJBDEYG/yQGfWgMAoGCCqGSM49BAMCMBAxDjAMBgNVBAMM
BXVzZXIxMB4XDTIxMTAwNjAwMDAwMFoXDTI1MTIzMTIzNTk1OVowJjEkMCIGA1UE
AwwbQ29hY2ggQUFDIERpZ2l0YWwgU2lnbmF0dXJlMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEcGdPwx0YLoZZPKj8X9Wa3WXd99XG+a0fzVba+ya86acXVdK9cK6F
QPfKnXHJkWbaJDoDptXCPbeh0Q91DaYut6NOMEwwCQYDVR0TBAIwADAOBgNVHQ8B
Af8EBAMCB4AwLwYDVR0fBCgwJjAkoCKgIIYeaHR0cHM6Ly93d3cuY29hY2hhYWMu
Y29tL2EuY3JsMAoGCCqGSM49BAMCA0cAMEQCIEeRJlFU7Gk1XIOHqd5Z3FneQoBY
iwRJQqn9qgmrKb6wAiBJd3UV4cxiYlzktk1jaXsTbZ6itIri8f9RDnwmgBHzmw==
-----END CERTIFICATE-----

second certificate : 

-----BEGIN CERTIFICATE-----
MIIBfDCCASGgAwIBAgIJAupv9v+kzxBQMAoGCCqGSM49BAMCMBAxDjAMBgNVBAMM
BXVzZXIyMB4XDTIxMTAwNjAwMDAwMFoXDTI1MTIzMTIzNTk1OVowJjEkMCIGA1UE
AwwbQ29hY2ggQUFDIERpZ2l0YWwgU2lnbmF0dXJlMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEUTrNToYYR9A1ll5gJSw3Z5VWKp3x5/KaKaYKbdKFtCo3JI/yTfUI
MbOVpx7htcrQ5RmnOICQBFPm+znKayTgcKNOMEwwCQYDVR0TBAIwADAOBgNVHQ8B
Af8EBAMCB4AwLwYDVR0fBCgwJjAkoCKgIIYeaHR0cHM6Ly93d3cuY29hY2hhYWMu
Y29tL2EuY3JsMAoGCCqGSM49BAMCA0kAMEYCIQCKaISRvU5T835A3vzxEtNwon6Y
3/MikYQnNL6eSNtm5AIhALutATYEELWm94L4gKLbLJTyLJE2RgVKO1Yn4z8/aYHT
-----END CERTIFICATE-----

Signed Data : 

-----BEGIN CMS-----
MIIF9gYJKoZIhvcNAQcCoIIF5zCCBeMCAQExDzANBglghkgBZQMEAgEFADAdBgkq
hkiG9w0BBwGgEAQOVEhJUyBJUyBBIFRFU1SgggL+MIIBejCCASGgAwIBAgIJBDEY
G/yQGfWgMAoGCCqGSM49BAMCMBAxDjAMBgNVBAMMBXVzZXIxMB4XDTIxMTAwNjAw
MDAwMFoXDTI1MTIzMTIzNTk1OVowJjEkMCIGA1UEAwwbQ29hY2ggQUFDIERpZ2l0
YWwgU2lnbmF0dXJlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcGdPwx0YLoZZ
PKj8X9Wa3WXd99XG+a0fzVba+ya86acXVdK9cK6FQPfKnXHJkWbaJDoDptXCPbeh
0Q91DaYut6NOMEwwCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCB4AwLwYDVR0fBCgw
JjAkoCKgIIYeaHR0cHM6Ly93d3cuY29hY2hhYWMuY29tL2EuY3JsMAoGCCqGSM49
BAMCA0cAMEQCIEeRJlFU7Gk1XIOHqd5Z3FneQoBYiwRJQqn9qgmrKb6wAiBJd3UV
4cxiYlzktk1jaXsTbZ6itIri8f9RDnwmgBHzmzCCAXwwggEhoAMCAQICCQLqb/b/
pM8QUDAKBggqhkjOPQQDAjAQMQ4wDAYDVQQDDAV1c2VyMjAeFw0yMTEwMDYwMDAw
MDBaFw0yNTEyMzEyMzU5NTlaMCYxJDAiBgNVBAMMG0NvYWNoIEFBQyBEaWdpdGFs
IFNpZ25hdHVyZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFE6zU6GGEfQNZZe
YCUsN2eVViqd8efymimmCm3ShbQqNySP8k31CDGzlace4bXK0OUZpziAkART5vs5
ymsk4HCjTjBMMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgeAMC8GA1UdHwQoMCYw
JKAioCCGHmh0dHBzOi8vd3d3LmNvYWNoYWFjLmNvbS9hLmNybDAKBggqhkjOPQQD
AgNJADBGAiEAimiEkb1OU/N+QN788RLTcKJ+mN/zIpGEJzS+nkjbZuQCIQC7rQE2
BBC1pveC+ICi2yyU8iyRNkYFSjtWJ+M/P2mB0zGCAqowgdYCAQEwHTAQMQ4wDAYD
VQQDDAV1c2VyMgIJAupv9v+kzxBQMA0GCWCGSAFlAwQCAQUAoEswGAYJKoZIhvcN
AQkDMQsGCSqGSIb3DQEHATAvBgkqhkiG9w0BCQQxIgQg9rUaA96/aAvcwhX0Ke7U
me9ZM+dZYU2iXtRFE+kYVh0wDQYJKoZIhvcNAQELBQAERzBFAiEAp+3ykAq/Th6C
gBhhag5iC870pBgllSj2EtU2s8+0wbwCIBH+33fWWg+dfMqABXnI/eQ94yx9BOIL
wiIXVF7psM9fMIIBzQIBATAdMBAxDjAMBgNVBAMMBXVzZXIxAgkEMRgb/JAZ9aAw
DQYJYIZIAWUDBAIBBQCgggE/MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJ
KoZIhvcNAQkFMQ8XDTIxMTAwODA1NDgwOFowHAYJKoZIhvcNAQkFMQ8XDTIxMTAw
ODA1NDgwOFowLwYJKoZIhvcNAQkEMSIEIPa1GgPev2gL3MIV9Cnu1JnvWTPnWWFN
ol7URRPpGFYdMFoGCyqGSIb3DQEJEAIvMUswSTBHMEUEILz6HDA/kX/ryiwjAhHu
Vyf1iMiVgtykY27NMvkVxKu0MCEwFKQSMBAxDjAMBgNVBAMMBXVzZXIxAgkEMRgb
/JAZ9aAwWgYLKoZIhvcNAQkQAi8xSzBJMEcwRQQg450E70ZJK1Gc7CC0sUlfnRj+
Oh2TjAAVLhwaoOkYPVowITAUpBIwEDEOMAwGA1UEAwwFdXNlcjICCQLqb/b/pM8Q
UDANBgkqhkiG9w0BAQsFAARIMEYCIQD0lEKAAboVCDq2Kuwn45/0QRqi/XHr1GcJ
QnOC04acsAIhAOgAljF5a1Dl3AU04qYWQgZdW+0MpA26WWZC+2/OlX+6
-----END CMS-----

And the bug fix i propose is not working because it crash just after (2 lignes after : x.getIssuerHex(); )

**Comment by kjur** [comment]
Thank you. I'll investigate them and let you know the result later.

**Comment by kjur** [comment]
It seems wrong CMS signed data. The first signerInfo has no SigningCertificateV2 attribute. This may be no problem. However the second signerInfo has two SigningCertificate attributes they are for user1 and user2. This raise conflict. It seems the reason why verifySignedData failed.
