### ISSUE TITLE
Extract public key from X.509 certificate

### ISSUE THREAD

**Issue by letmaik** [kjur/jsrsasign#513]
Input: PEM-encoded X.509 certificate
Output: DER-encoded (hex is fine) SPKI public key

I couldn't find an obvious API for that. Is this possible?

**Comment by kjur** [comment]
Try this:
```JavaScript
var x = new X509();
x.readCertPEM('-----BEGIN CERTIFICATE...');
var hexpubkey = x.getPublicKeyHex();
```
