### ISSUE TITLE
c.getPublicKey().pubKeyHex and c.getPublicKeyHex() give different strings 

### ISSUE THREAD

**Issue by jumpjack** [kjur/jsrsasign#518]
After loading this certificate,  c.getPublicKey().pubKeyHex  and  c.getPublicKeyHex() give different results:

`-----BEGIN CERTIFICATE-----MIIEDzCCAfegAwIBAgIURldu5rsfrDeZtDBxrJ+SujMr2IswDQYJKoZIhvcNAQELBQAwSTELMAkGA1UEBhMCSVQxHzAdBgNVBAoMFk1pbmlzdGVybyBkZWxsYSBTYWx1dGUxGTAXBgNVBAMMEEl0YWx5IERHQyBDU0NBIDEwHhcNMjEwNTEyMDgxODE3WhcNMjMwNTEyMDgxMTU5WjBIMQswCQYDVQQGEwJJVDEfMB0GA1UECgwWTWluaXN0ZXJvIGRlbGxhIFNhbHV0ZTEYMBYGA1UEAwwPSXRhbHkgREdDIERTQyAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnL9+WnIp9fvbcocZSGUFlSw9ffW/jbMONzcvm1X4c+pXOPEs7C4/83+PxS8Swea2hgm/tKt4PI0z8wgnIehoj6OBujCBtzAfBgNVHSMEGDAWgBS+VOVpXmeSQImXYEEAB/pLRVCw/zBlBgNVHR8EXjBcMFqgWKBWhlRsZGFwOi8vY2Fkcy5kZ2MuZ292Lml0L0NOPUl0YWx5JTIwREdDJTIwQ1NDQSUyMHhcMSxPPU1pbmlzdGVybyUyMGRlbGxhJTIwU2FsdXRlLEM9SVQwHQYDVR0OBBYEFC4bAbCvpArrgZ0E+RrqS8V7TNNIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAjxTeF7yhKz/3PKZ9+WfgZPaIzZvnO/nmuUartgVd3xuTPNtd5tuYRNS/1B78HNNk7fXiq5hH2q8xHF9yxYxExov2qFrfUMD5HOZzYKHZcjcWFNHvH6jx7qDCtb5PrOgSK5QUQzycR7MgWIFinoWwsWIrA1AJOwfUoi7v1aoWNMK1eHZmR3Y9LQ84qeE2yDk3jqEGjlJVCbgBp7O8emzy2KhWv3JyRZgTmFz7p6eRXDzUYHtJaufveIhkNM/U8p3S7egQegliIFMmufvEyZemD2BMvb97H9PQpuzeMwB8zcFbuZmNl42AFMQ2PhQe27pU0wFsDEqLe0ETb5eR3T9L6zdSrWldw6UuXoYV0/5fvjA55qCjAaLJ0qi16Ca/jt6iKuws/KKh9yr+FqZMnZUH2D2j2i8LBA67Ie0JoZPSojr8cwSTxQBdJFI722uczCj/Rt69Y4sLdV3hNQ2A9hHrXesyQslr0ez3UHHzDRFMVlOXWCayj3LIgvtfTjKrT1J+/3Vu9fvs1+CCJELuC9gtVLxMsdRc/A6/bvW4mAsyY78ROX27Bi8CxPN5IZbtiyjpmdfr2bufDcwhwzdwsdQQDoSiIF1LZqCn7sHBmUhzoPcBJdXFET58EKow0BWcerZzpvsVHcMTE2uuAUr/JUh1SBpoJCiMIRSl+XPoEA2qqYU=-----END CERTIFICATE-----`

c.getPublicKey().pubKeyHex:

049cbf7e5a7229f5fbdb728719486505952c3d7df5bf8db30e37372f9b55f873ea5738f12cec2e3ff37f8fc52f12c1e6b68609bfb4ab783c8d33f3082721e8688f

c.getPublicKeyHex():

3059301306072a8648ce3d020106082a8648ce3d030107034200**049cbf7e5a7229f5fbdb728719486505952c3d7df5bf8db30e37372f9b55f873ea5738f12cec2e3ff37f8fc52f12c1e6b68609bfb4ab783c8d33f3082721e8688f**

First string lacks these characters:

3059301306072a8648ce3d020106082a8648ce3d030107034200

The key in BASE64 is:
c.getPublicKey().ecparams.params.sbjpubkey =

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnL9+WnIp9fvbcocZSGUFlSw9ffW/
jbMONzcvm1X4c+pXOPEs7C4/83+PxS8Swea2hgm/tKt4PI0z8wgnIehojw==
-----END PUBLIC KEY-----

It [matches ](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)To_Hex('None',0)&input=TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbkw5K1duSXA5ZnZiY29jWlNHVUZsU3c5ZmZXLwpqYk1PTnpjdm0xWDRjK3BYT1BFczdDNC84MytQeFM4U3dlYTJoZ20vdEt0NFBJMHo4d2duSWVob2p3PT0)with second string.

**Comment by kjur** [comment]
These are expected result.
X509().getPublicKeyHex() returns hexadecimal subjectPublicKeyInfo field value of certificate encoded in PKCS#8 ASN.1 public key structure.
X509().getPublicKey() returns RSAKey(), KJUR.crypto.ECDSA() or KJUR.crypto.DSA() key object. In your case, it returns KJUR.crypto.ECDSA() object. It has pubKeyHex member property and it is public key in hex for ECC key.
