### ISSUE TITLE
How to get octet string from sequence?

### ISSUE THREAD

**Issue by jstayton** [kjur/jsrsasign#520]
Hey @kjur!

I'm hoping you can help me here. I have a certificate with a custom extension. The value of the extension is a sequence with a single octet string. I'm trying to get that octet string.

Here's the code I have so far:

```js
const certificate = new jsrsasign.X509()

certificate.readCertHex('...')

const extn = certificate.findExt(certificate.getExtParamArray(), '1.2.840.113635.100.8.2').extn

console.log(jsrsasign.ASN1HEX.dump(extn))
```

That outputs:

```
SEQUENCE
  [1]
    OCTETSTRING 5293c9c6694e743c63134bd00a9212873664cfc33d8dc05b3b26725aa45aab71
```

How do I get that octet string? I'm a bit lost with `ASN1HEX`, so any help is appreciated! Thanks!

**Comment by kjur** [comment]
Hi. Can you provide me sample certificate for it?

**Comment by kjur** [comment]
I hope it can be get by ASN1HEX.getVbyList.
```
ASN1HEX.getVbyList(extn, 0, [0, 0]) ->
"5293c9..."
```

**Comment by jstayton** [comment]
That did it! Thank you!
