### ISSUE TITLE
How to specify CSR attribute?

### ISSUE THREAD

**Issue by jstayton** [kjur/jsrsasign#522]
Hey @kjur,

Is there a way to specify an attribute of a CSR? I see that there's `extreq` to specify extensions, but I don't see anything for attributes. I need to specify the `challengePassword` attribute.

```js
const csr = new jsrsasign.asn1.csr.CertificationRequest({
  subject: { str: '...' },
  sbjpubkey: '...',
  sigalg: 'SHA384withRSA',
  sbjprvkey: '...',
})
```

Thanks!

**Comment by kjur** [comment]
Sorry but it is not supported yet.

**Comment by davidkhala** [comment]
+1 Look forward to have this feature 
And if possible, please also consider adding support for `"extname":"unstructuredName"`

**Comment by kjur** [comment]
Hi @davidkhala san, thank you for your sponsorship as always. Jsrsasign supports arbitrary extensions by specifying extension OID and ASN.1 structure by JSON.

```
{
  subject: {str: '/C=US/O=Test/CN=example.com'},
  sbjpubkey: pubKey,
  sigalg: "SHA256withRSA",
  sbjprvkey: prvKey,
  extreq: [
    {extname:'keyUsage', names:['digitalSignature','nonRepudiation']},
    {extname:'basicConstraints',critical:true},
    {extname: "1.3.6.1.4.1.52266.1",         // <-- here
     extn: {prnstr: {str: "hogehoge"}}}
  ]
}
```
Value for member "extn" is the same as following method:
https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.ASN1Util.html#.newObject

I hope this helps.

**Comment by davidkhala** [comment]
For anyone go through this issue: 
Here is a good search engine for OID info
- challengePassword: `http://oid-info.com/get/1.2.840.113549.1.9.7`
- unstructuredName: `http://oid-info.com/get/1.2.840.113549.1.9.2`

**Comment by kjur** [comment]
Hi @davidkhala , I'm sorry. I found that the above doesn't work for challengePassword and unstructuredName because they  are not request extensions. I'll support them later. It will be my summer time homework :)

**Comment by davidkhala** [comment]
Yes, I find only extensions with OID are not enough. From that, would you consider reopen this issue?

**Comment by kjur** [comment]
You can generate a CSR PEM with challengePassword, unstructuredName and extensionRequest like this:

```JavaScript
new KJUR.asn1.csr.CertificationRequest({
  subject: {str: '/C=US/CN=b'},
  sbjpubkey: "-----BEGIN PUBLIC KEY...",
  attrs: [
    {attr: "challengePassword", password: "secret"},
    {attr: "unstructuredName", names: [{utf8str:"aaa"},{ia5str:"bbb"}]},
    {attr: "extensionRequest", ext: [
      {extname: "basicConstraints", cA: true},
      {extname: "subjectKeyIdentifier", kid: "1a2b..."}
    ]}
  ],
  sigalg: "SHA256withRSA",
  sbjprvkey: "-----BEGIN PRIVATE KEY..."
}).getPEM()
```

**Comment by davidkhala** [comment]
Hi @kjur, for the case of getting an unsigned CSR, which is `asn1.csr.CertificationRequestInfo`, would you mind alos providing an sample on how to create a new object with `challengePassword` and `unstructuredName` attrs?

**Comment by kjur** [comment]
Hi @davidkhala , it will be following:

```JavaScript
new KJUR.asn1.csr.CertificationRequestInfo({
  subject: {str: '/C=US/CN=b'},
  sbjpubkey: "-----BEGIN PUBLIC KEY...",
  attrs: [
    {attr: "challengePassword", password: "secret"},
    {attr: "unstructuredName", names: [{utf8str:"aaa"},{ia5str:"bbb"}]},
    {attr: "extensionRequest", ext: [
      {extname: "basicConstraints", cA: true},
      {extname: "subjectKeyIdentifier", kid: "1a2b..."}
    ]}
  ]
}).tohex()
```

**Comment by davidkhala** [comment]
@kjur I am new to unstructured name, but I wonder what is different between, `utf8str` and `ia5str`. Are they just different in format that we can choose either one ? Or they are independent items working for individual purposes?

**Comment by kjur** [comment]
"UnstructuredName" is defined in RFC 2985 secition 5.2.2.
https://datatracker.ietf.org/doc/html/rfc2985#page-8

It can have multiple values with the type of IA5String or DirectoryString.
DirectoryString definition in RFC 5280 is following
```
   DirectoryString ::= CHOICE {
         teletexString           TeletexString (SIZE (1..MAX)),
         printableString         PrintableString (SIZE (1..MAX)),
         universalString         UniversalString (SIZE (1..MAX)),
         utf8String              UTF8String (SIZE (1..MAX)),
         bmpString               BMPString (SIZE (1..MAX)) }
```

So jsrsasign will accept any ASN1 string types:
- utf8str: UTF8String
- numstr: NumericString
- prnstr: PrintableString
- telstr: TeletexString
- ia5str: IA5String
- visstr: VisualString
- bmpstr: BMPString

OpenSSL seems to use UTF8String for unstructuredName. So I may recommend to use "utf8str".
I hope this helps.

**Comment by kjur** [comment]
> * object makes the overall pem not recognizable

I think KSE only accepts CertificationRequest not CertificationRequestInfo. I think that's the reason why KSE doesn't accept it.

**Comment by davidkhala** [comment]
> > * object makes the overall pem not recognizable
> 
> I think KSE only accepts CertificationRequest not CertificationRequestInfo. I think that's the reason why KSE doesn't accept it.

Oh, to clarify, I tried both way but neither works in KSE. 

1. create CertificationRequest object directly with private key. Then `.getPEM`
2. create CertificationRequestInfo, create `Signature` with init(privateKey), let the signature sign on hex format of CertificationRequestInfo, then use DERSequence to combine above and getHex of it, finnally convert the hex into PEM.

**Comment by kjur** [comment]
Could you share CSR which is created on KSE and acceptable by KSE? I think I can investigate it further.
