### ISSUE TITLE
React performance issue with generateKeypair

### ISSUE THREAD

**Issue by develop1992** [kjur/jsrsasign#524]
Could you please help me with the below issue?

I need to use jsrsasign in my nextjs app, so I am using generateKeypair function of KEYUTIL to generate a keypair. However, it takes too long for generateKeypair to return value.

Here is my code:

const keypair = rs.KEYUTIL.generateKeypair("RSA", 3072); // the app crashes!!

**Comment by kjur** [comment]
Sorry but jsrsasign's RSA key generation is slow for large key size because it depends on Tom Wu's library.
http://www-cs-students.stanford.edu/~tjw/jsbn/
I would recommend to use W3C Web Crypto API, Web Assembly or Node.JS "crypto" module key generation if you need more performance.
