### ISSUE TITLE
Unable to get PEM using KEYUTIL.getPEM.

### ISSUE THREAD

**Issue by trusktr** [kjur/jsrsasign#53]
This is my code:

``` javascript
var rsa = require("jsrsasign");
var keypair = rsa.KEYUTIL.generateKeypair("RSA", 256);
console.log(keypair.prvKeyObj);
console.log(rsa.KEYUTIL.getPEM(keypair.prvKeyObj)); // ERROR
```

It results in this error:

```
Uncaught unsupported object nor format
```

`keypair.prvKeyObj` is a `RSAKey` object, and I believe that is what the `rsa.KEYUTIL.getPEM` method accepts basedon the docs. Why might I be getting this error?

**Comment by animalillo** [comment]
*bumps*

I think this is back in 4.7.1-all-min

 > var kp = KEYUTIL.generateKeypair("RSA", 1024);
<< undefined
>kp
<<Object {prvKeyObj: RSAKey, pubKeyObj: RSAKey}
> KEYUTIL.getPEM(kp.prvKeyObj, "PKCS1PRV")
<< Uncaught TypeError: KJUR.asn1.ASN1Util.newObject is not a functionp @ jsrsasign-4.7.1-all-min.js?v=cf866614b6b18cda13fe699a3a65661b:249KEYUTIL.getPEM @ jsrsasign-4.7.1-all-min.js?v=cf866614b6b18cda13fe699a3a65661b:249(anonymous function) @ VM8562:2InjectedScript._evaluateOn @ VM8247:883InjectedScript._evaluateAndWrap @ VM8247:816InjectedScript.evaluate @ VM8247:682
