### ISSUE TITLE
 how to resolve wrong ctext length

### ISSUE THREAD

**Issue by JamesTaylor04** [kjur/jsrsasign#532]
- Question
   when I use jsrssign to decrypt data from server, it throw this error, how to resolve it?
- Exception
![image](https://user-images.githubusercontent.com/46660297/149271845-46a890bd-0833-4f67-a77d-24aff2b55035.png)

**Comment by kjur** [comment]
It seems proper encrypted data for your key. Sorry but no further help from me.
