### ISSUE TITLE
GeneralName doesn't support otherName

### ISSUE THREAD

**Issue by rarf** [kjur/jsrsasign#534]
KJUR.asn1.x509.GeneralName doesn't support otherName

GeneralName ::= CHOICE {
  otherName                  [0] OtherName,
  rfc822Name                 [1] IA5String,
  dNSName                    [2] IA5String,
  x400Address                [3] ORAddress,
  directoryName              [4] Name,
  ediPartyName               [5] EDIPartyName,
  uniformResourceIdentifier  [6] IA5String,
  iPAddress                  [7] OCTET STRING,
  registeredID               [8] OBJECT IDENTIFIER }

**Comment by kjur** [comment]
```
OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }
```
OtherName value includes ANY. Sorry but there is no plan to support OtherName at this stage.

**Comment by rarf** [comment]
I sent a pull request #535 my approach is to use ASN1Util.newObject so the developer can pass any ASN1Object, this would simplify my PKCS#10 with otherName generations, to do that now i need to create all the SubjectAltName manualy.
