### ISSUE TITLE
zulutosec cannot convert correctly

### ISSUE THREAD

**Issue by s1r-J** [kjur/jsrsasign#538]
- version: 10.5.1

zulutosec cannot convert some future times(e.g. '401231235959Z') correctly.

zulutosec uses `~` for cutting off after the decimal point.
Bitwise not (`~` ) converts  integer with more than 32 bits into a 32-bit signed integer.
So, '401231235959Z'(Unix time is `2240611199000`, more than 32 bits) will be shotened by bitwise not operator and be coverted incorrectly.

[Bitwise NOT (~) - JavaScript \| MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT#description)

Sample code is following.

```js
const overflowDateStr = '401231235959Z'; // 2040 Dec 31 23:59:59
const overflowDate = new Date(Date.UTC(2000 + parseInt(overflowDateStr.slice(0, 2)), parseInt(overflowDateStr.slice(2, 4)) - 1, parseInt(overflowDateStr.slice(4, 6)), parseInt(overflowDateStr.slice(6, 8)), parseInt(overflowDateStr.slice(8, 10)), parseInt(overflowDateStr.slice(10, 12))))
console.log(overflowDate.getTime());                 // 2240611199000
console.log(jsrsasign.zulutomsec(overflowDateStr));  // 2240611199000
console.log(jsrsasign.zulutosec(overflowDateStr));   // -2054356097

console.log(Math.floor(jsrsasign.zulutomsec(overflowDateStr)/1000));  // 2240611199
```

Thanks.

**Comment by kjur** [comment]
Thank you for your report. It will be fixed in the release today.
