### ISSUE TITLE
How to export public key pem from private key pem?

### ISSUE THREAD

**Issue by alanhg** [kjur/jsrsasign#542]
```javascript
const priKey = rs.KEYUTIL.getKey(priPem);

```

I want to get public key pem. I only have a private key Pem. I found no method to do it.

**Comment by kjur** [comment]
Sorry but jsrsasign will not provide method to calculate a public key by a private key in general.

**Comment by alanhg** [comment]
ok.

but I found node-forge can do it on browser or nodejs. maybe some need it.


```javascript
const forgePriKey = forge.pki.privateKeyFromPem(privateKeyPem);
const forgePubKey = forge.pki.setRsaPublicKey(forgePriKey.n, forgePriKey.e);
const publicKeyPem = forge.pki.publicKeyToPem(forgePubKey);
```
