### ISSUE TITLE
Common Name returning null

### ISSUE THREAD

**Issue by celli33** [kjur/jsrsasign#545]
In a certificate when the CNAME contains the character: 'Ñ'. 
The CNAME returned is `null`.
For example: 
I have a certificate and when I parsed it with OpenSSL I obtain this CNAME: `[CN] => COMPAÑIA SANTA MARIA SA DE CV`
However when I use the function: `parsed.getSubject()`.
I obtain: `/CN=null/2.5.4.41=null/O=null/uniqueIdentifier=SMA0112284B2 \\/ GOCA741120HY0/serialNumber= \\/ GOCA741120HVZMNR00/OU=null`.

**Comment by kjur** [comment]
Can you provide the certificate which is raising issue?

**Comment by celli33** [comment]
where can I send you the certificate?

**Comment by kjur** [comment]
I've taken a look the certificate and found that most of subject RDNs are TeletexString not UTF8String. That's why subject CN are null. The issuer name of the certificate are in UTF8String. So issuer name will be displayed successfully. Thanks.

**Comment by kjur** [comment]
ISO 8859-1 latin1 of TeletexString supported since 10.5.12 release today. So 'Ñ' in TeletexString will also be displayed properly.

**Comment by celli33** [comment]
Thanks, you are the best!
