### ISSUE TITLE
jsrsasign generates weak RSA keys, eventually

### ISSUE THREAD

**Issue by augjoh** [kjur/jsrsasign#546]
When generating RSA keys `|p - q|` must not be small. The [Digital Signature Standard (DSS)](https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.186-4.pdf) specifies in B 3.2.2 that it should be smaller than `2^(bits(n)/2-100)` meaning that the first 100 bits of `p` and `q` should differ. jsrsasign does not check this, when generating RSA keys. This makes it hard to prove compliance.

**Comment by kjur** [comment]
Thank you for your report. The |p - q| check have been added in the 10.5.13 release today. Theoretically, a weak RSA key has only a 1 in 2^100 chance of being generated before the fix.
