### ISSUE TITLE
Sign JWS Method does not accept key

### ISSUE THREAD

**Issue by andreisaikouski** [kjur/jsrsasign#551]
As per [documentation](http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.sign), JWS.sign method should accept a key

> KJUR.jws.JWS.sign(alg, spHead, spPayload, key, pass)

The code does not support this (from jsrsasign>modules>KJUR>jws>JWS.d.ts)

```
function sign(
     alg: string | null,
     spHead: string | { alg: string },
     spPayload: string | object,
     pass?: string | { [type: string]: string },
): string;
```

Version `"jsrsasign": "^10.5.20"`

**Comment by kjur** [comment]
Sorry but I'm not "JWS.d.ts" TypeScript type definition file maintainer. Please ask him for it.
