### ISSUE TITLE
New EC curve registed procedure invalid value

### ISSUE THREAD

**Issue by hn63wospuvy** [kjur/jsrsasign#553]
Hi,
I have added some curves that are not currently supported, tried to generate new key pair, exported to pem format successfully, but pem file cannot be read by java. 
Here is the code javascript
`KJUR.asn1.x509.OID.registerOIDs({ 
    'c2pnb163v1': "1.2.840.10045.3.0.1" 
});
KJUR.crypto.ECParameterDB.regist(
    "c2pnb163v1", // name / x^163 + x^8 + x^2 + x^1 + 1
    163,
    "080000000000000000000000000000000000000107", // p
    "072546b5435234a422e0789675f432c89435de5242", // a
    "00c9517d06d5240d3cff38c74b20b6cd4d6f9dd4d9", // b
    "0400000000000000000001e60fc8821cc74daeafc1", // n
    "2", // h
    "07af69989546103d79329fcc3d74880f33bbe803cb", // gx
    "01ec23211b5966adea1d3f87f7ea5848aef0b7ca9f", // gy
    [], // alias
    "1.2.840.10045.3.0.1", // oid (underconstruction)
    "c2pnb163v1 : 163-bit binary field Weierstrass curve."
);
var keypair = KEYUTIL.generateKeypair("EC", "c2pnb163v1");
var privPem = KEYUTIL.getPEM(keypair.prvKeyObj, "PKCS8PRV");
var pubPem = KEYUTIL.getPEM(keypair.pubKeyObj, "PKCS8PUB");
`
and java exception thrown

`Caused by: java.security.spec.InvalidKeySpecException: encoded key spec not recognized: Incorrect length for uncompressed encoding
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi.engineGeneratePublic(Unknown Source)`

and java code
`
BufferedReader br = new BufferedReader(new InputStreamReader(new ByteArrayInputStream(pemData)));
        PEMParser pemParser = new PEMParser(br);
        try {
            Object obj = pemParser.readObject();
            return new JcaPEMKeyConverter().setProvider(new BouncyCastleProvider()).getKeyPair((PEMKeyPair) obj);
        } catch (Exception e) {
            log.error(e.getMessage());
        } finally {
            try {
                pemParser.close();
            } catch (IOException e) {
            }
        }
`

Btw, this is very nice if you add more curves like 
"c2pnb272w1",
  "c2tnb191v3",
  "c2pnb208w1",
  "c2tnb191v2",
  "c2tnb191v1",
  "prime192v3",
  "c2tnb359v1",
  "prime192v2",
  "prime192v1",
  "c2tnb239v3",
  "c2pnb163v3",
  "c2tnb239v2",
  "c2pnb163v2",
  "c2tnb239v1",
  "c2pnb163v1",
  "c2pnb176w1",
  "prime256v1",
  "c2pnb304w1",
  "c2pnb368w1",
  "c2tnb431r1",
  "prime239v3",
  "prime239v2",
  "prime239v1",
  "brainpoolP224t1",
  "brainpoolP512t1",
  "brainpoolP224r1",
  "brainpoolP512r1",
  "brainpoolP192t1",
  "brainpoolP384t1",
  "brainpoolP192r1",
  "brainpoolP384r1",
  "brainpoolP160t1",
  "brainpoolP320t1",
  "brainpoolP160r1",
  "brainpoolP320r1",
  "brainpoolP256t1",
  "brainpoolP256r1",
  "B-163",
  "K-163",
  "B-233",
  "K-233",
  "B-409",
  "B-283",
  "B-571",
  "K-409",
  "K-283",
  "K-571",
  "sect283r1",
  "sect283k1",
  "sect163r2",
  "secp256k1",
  "secp160k1",
  "secp160r1",
  "secp112r2",
  "secp112r1",
  "sect113r2",
  "sect113r1",
  "sect239k1",
  "secp128r2",
  "sect163r1",
  "secp128r1",
  "sect233r1",
  "sect163k1",
  "sect233k1",
  "sect193r2",
  "sect193r1",
  "sect131r2",
  "sect131r1",
  "secp256r1",
  "sect571r1",
  "sect571k1",
  "secp192r1",
  "sect409r1",
  "sect409k1",
  "secp521r1",
  "secp384r1",
  "secp224r1",
  "secp224k1",
  "secp192k1",
  "secp160r2",

Thanks in advance

**Comment by kjur** [comment]
I couldn't add support for other curves too. If anyone send me pull request to add it, I can merge it. Otherwise I have no plan to add other curves.
