### ISSUE TITLE
es module support

### ISSUE THREAD

**Issue by Jxck** [kjur/jsrsasign#560]
Hi, Thanks for working on this great module !

QQ: Is there any plan to support es module support ?

**Comment by kjur** [comment]
Sorry, I'm sorry, I'm not thinking of supporting the ES module at this time. One of the basic design concepts of jsrsasign is that it should work on older browsers. I think it would be better to create another library from jsrsasign to support modern environments such as ES modules, and I am thinking of making a prototype when I have time.
