### ISSUE TITLE
how to convert hexstring key to pem format

### ISSUE THREAD

**Issue by RobertLeeL** [kjur/jsrsasign#561]
hello~ 

I used this method to generate a pair of ecc keys, 

`  const ecdsa = new jsrsasign.KJUR.crypto.ECDSA({
    curve: 'secp256r1',
  });
  const hexString = ecdsa.generateKeyPairHex();
  console.log(hexString);
  const { ecprvhex, ecpubhex } = hexString;`

how to convert hexstring key to pem format?

I am returning the wrong format using this method

`  const res = jsrsasign.KJUR.asn1.ASN1Util.getPEMStringFromHex(
    ecprvhex,
    'PRIVATE KEY',
  );
  console.log(res);
  const res2 = jsrsasign.KJUR.asn1.ASN1Util.getPEMStringFromHex(
    ecprvhex,
    'PUBLIC KEY',
  );`

Looking forward to your reply！

**Comment by kjur** [comment]
This may be more simple way to get PEMs of keys:

```JavaScript
var keypair = KEYUTIL.generateKeypair("EC", "secp256k1");
var pubpem = KEYUTIL.getPEM(keypair.pubKeyObj);
var prvpem = KEYUTIL.getPEM(keypair.prvKeyObj, "PKCS8PRV");
```

**Comment by RobertLeeL** [comment]
> This may be more simple way to get PEMs of keys:
> 
> ```js
> var keypair = KEYUTIL.generateKeypair("EC", "secp256k1");
> var pubpem = KEYUTIL.getPEM(keypair.pubKeyObj);
> var prvpem = KEYUTIL.getPEM(keypair.prvKeyObj, "PKCS8PRV");
> ```

Thanks for your reply, but I used other library to implement ecies, other library needs hexstring. Currently able to pems to hexstring or hexstring to pems.

**Comment by kjur** [comment]
How about this?:

```JavaScript
var prv = new KJUR.crypto.ECDSA({curve: "secp256k1"});
prv.setPublicKeyHex(...your hex public key...);
prv.setPrivateKeyHex(...your hex private key...);

then you can use it for signing
var sig = new KJUR.crypto.Signature({curve: "secp256k1"});
sig.init(prv);
sig.updateString("aaa");
sig.sign() -> generate signature in hex
```
