### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by jasny** [kjur/jsrsasign#563]
I'm trying to create a subset package with only ECDSA. However, I'm unable to build this project from source.

It seems that not all scripts to build this project are included:

* `yuicmp` doesn't seem to be publically available
* `jsrun-jsrsasign.sh` is a custom script

**Comment by kjur** [comment]
As for yuicmp, you can use another JavaScript compressor. As for jsrun-jsrsasign.sh, it will be used for API document generation. I think you may ignore this for creating  subset package.

**Comment by jasny** [comment]
@kjur Could you please give some information / point my in the right direction on how to build a subpackage (similar to jsrsasign-rsa-min.js)? This doesn't seem to be done by the makefile.

🙏 Many thanks

**Comment by kjur** [comment]
Hi @jasny , I'll touch you via email of your info address in your site. Thank you.

**Comment by kjur** [comment]
Hi @jasny san, I've sent a message. Please confirm it.
