### ISSUE TITLE
messy code for Chinese 

### ISSUE THREAD

**Issue by qq854674282** [kjur/jsrsasign#564]
hi , I'm try using it to get Google login credential , but when family_name or given_name is Chinese, it show messy code, Can you help me ? thanks 

here is my code:
```
  var sJWS = googleUser.credential;

  var a = sJWS.split(".");
  var uHeader = b64utos(a[0]);
  var uClaim = b64utos(a[1]);

  var pHeader = KJUR.jws.JWS.readSafeJSONString(uHeader);
  var pClaim = KJUR.jws.JWS.readSafeJSONString(uClaim);

  var sHeader = JSON.stringify(pHeader, null, "  ");
  var sClaim = JSON.stringify(pClaim, null, "  ");
  console.log(uClaim)
```

here is messy code

```
{"iss":"https://accounts.google.com","nbf":1666775488,"aud":"xxxxx","sub":"xxxx","email":"xxxxx@gmail.com","email_verified":true,"azp":"xxxxx","name":"çè½©","picture":"xxx","given_name":"è½©","family_name":"ç","iat":1666775788,"exp":1666779388,"jti":"xxxx"}
```

**Comment by kjur** [comment]
Please use b64utoutf8 instead of b64utos
https://kjur.github.io/jsrsasign/api/symbols/global__.html

I hope this helps.

**Comment by qq854674282** [comment]
> Please use b64utoutf8 instead of b64utos https://kjur.github.io/jsrsasign/api/symbols/global__.html
> 
> I hope this helps.

Its work,  thanks~
