### ISSUE TITLE
Generate pdf hash and send it to external signing service then it return certificate + signed hash

### ISSUE THREAD

**Issue by bakusangel** [kjur/jsrsasign#566]
Is it possible to generate pdf hash and embed the signed hash to the original pdf?

Flow -
1. jsrsasign functions to generate the pdf hash that with empty signature container
2. Send the hash to external signing service
3. External signing service receive hash and sign it with their primary key then return certificate (public key) and signed hash
4. jsrsasign functions to embed the signed hash

**Comment by kjur** [comment]
Jsrsasign doesn't have any PDF parsing or generation function however, it has:

- hash calculation
- reconstruct CMS signed data or CAdES with signature value from a remote signing service

and they may help your remote PDF signing. Thanks.
