### ISSUE TITLE
Uppercase hex string support

### ISSUE THREAD

**Issue by mikecat** [kjur/jsrsasign#567]
In current version, uppercase hex string doesn't looks supported in functions that parses hex strings.

For example, looking at the code of `ASN1HEX.dump()`:

The `tag` is compared to only lowercase string:

https://github.com/kjur/jsrsasign/blob/c665ebcebc62cc7e55ffadbf2efec7ef89279b00/src/asn1hex-1.1.js#L914

The `tag` is not converted to lowercase before comparing:

https://github.com/kjur/jsrsasign/blob/c665ebcebc62cc7e55ffadbf2efec7ef89279b00/src/asn1hex-1.1.js#L846-L866

There looks other functions that has similar problem.

**Comment by kjur** [comment]
Please use lower case hexadecimal in jsrsasign because most of jsrsasign is expected it. I'll describe it in the all part of API document. Thank you.
