### ISSUE TITLE
Does this component support ECDH key negotiation? 

### ISSUE THREAD

**Issue by LubanTech1** [kjur/jsrsasign#586]
Does this component support ECDH key negotiation? I can't find any functions related to ecdh.

**Comment by kjur** [comment]
Sorry but it's not supported.

**Comment by LubanTech1** [comment]
> Sorry but it's not supported.

Is there a plan to support this algorithm? This is important.

**Comment by kjur** [comment]
Sorry but there is no plan to support it for now.
