### ISSUE TITLE
Private certs included in the NPM package.

### ISSUE THREAD

**Issue by Chengxuan** [kjur/jsrsasign#590]
Both https://github.com/kjur/jsrsasign/blob/master/npm/test/t_rsasign.js
and https://github.com/kjur/jsrsasign/blob/master/npm/test/t_sig_rsasha1.js contains private keys used for testing. They are flagged during the security scan and they've been shipped as part of the npm release.

Were they included intentionally?

**Comment by kjur** [comment]
Those are included intentionally just for testing. OpenSSL also concludes testing private key.
