### ISSUE TITLE
KJUR.jws.JWS.sign is very slow.

### ISSUE THREAD

**Issue by xunziheng** [kjur/jsrsasign#592]
Env: 
1. "jsrsasign": "^10.8.6",
2. typescript
3. webpack
4. react

Issue: 

when I use `KJUR.jws.JWS.sign()` Its very slow for me, about 7000ms, **but the answer is all right**.
I'm not sure if it's my problem, but I really have no more idea to debug.

I had try to change version.

thank you guys for any suggestion

I guess the webpack ts-loader cause that?

**Comment by xunziheng** [comment]
By the way, I use "RS256" for sign.

**Comment by kjur** [comment]
Please use Web Crypto API.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
