### ISSUE TITLE
Property 'jws' does not exist on type 'typeof jsrsasign'

### ISSUE THREAD

**Issue by imamnghr** [kjur/jsrsasign#596]

**Comment by kjur** [comment]
How did you used jws? By Node or on the browser?

**Comment by imamnghr** [comment]
> How did you used jws? By Node or on the browser?

i use the browser, i solve the problem but need to update the jsrsasign.d.ts in my node_modules like this 
 namespace jws {
            namespace JWS {

                function sign(algorithm: string, header: string, payload: string, key: string): string;
            }
        }

**Comment by kjur** [comment]
Please ask jsrsasign.d.ts support for it. "jsrsasign.d.ts" is not official one.
