### ISSUE TITLE
crypto-js PBKDF2 vulnerability

### ISSUE THREAD

**Issue by returnSky** [kjur/jsrsasign#599]
Hi， 

`crypto-js` fixed a vulnerability related to PBKDF2 recently.   
Does this vulnerability also affect `jsrsasign`? 
If any impact, when will your start to fix it?

Thanks.

References:
* [Change default hash algorithm and iteration's for PBKDF2 to prevent weak security by using the default configuration.](https://github.com/brix/crypto-js/commit/421dd538b2d34e7c24a5b72cc64dc2b9167db40a)
* [crypto-js PBKDF2 1,000 times weaker than specified in 1993 and 1.3M times weaker than current standard](https://github.com/brix/crypto-js/security/advisories/GHSA-xwcq-pm8m-c4vf)

**Comment by kjur** [comment]
Yes, it seems to affect to jsrsasign. When you generate encrypted PKCS#8 private key, it uses PBKDF2. I'll update it and fix the issue.

**Comment by kjur** [comment]
I've released 10.9.0 today.
https://github.com/kjur/jsrsasign/releases/tag/10.9.0
Regarding to encrypted PKCS#8 private key generation, default encryptionScheme have been updated from des-EDE3-CBC to aes256-CBC and default prf have been updated from hmacWithSHA1 to hmacWithSHA256. Also you can set iteration count.
