### ISSUE TITLE
Export encrypted RSA private key to PEM format

### ISSUE THREAD

**Issue by louismullie** [kjur/jsrsasign#6]
Hello,

I am wondering if it is possible to export encrypted RSA private keys to DER or PEM format using your library. Essentially, I'm looking to do the exact opposite of this: http://kjur.github.io/jsrsasign/tool_pkcs5view.html

Best,
Louis

**Comment by sijanec** [comment]
Is this still supported (i am curious because the provided sample file is not present anymore)?

**Comment by kjur** [comment]
Yes, it is supported in KEYUTIL class:
https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html

**Comment by sijanec** [comment]
Yes, I did realize that after RTFM.
