### ISSUE TITLE
Wechat mini program SHA1withRSA signature function is very slow

### ISSUE THREAD

**Issue by lgr595555169** [kjur/jsrsasign#600]
When using 2048 private keys for signature, wechat mini program takes more than 300ms。
`let signature =  new KJUR.crypto.Signature({"alg": "SHA1withRSA", "prvkeypem": priK});`

**Comment by kjur** [comment]
Please use W3C Web Crypto API.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
