### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by irogers77** [kjur/jsrsasign#601]
![image](https://github.com/kjur/jsrsasign/assets/135271681/8e6be233-99a0-4a91-a07a-d1ce525a9f6f)
Started being thrown today. I'm sourcing the file from https://cdn.rawgit.com/kjur/jsrsasign/c057d3447b194fa0a3fdcea110579454898e093d/jsrsasign-all-min.js

**Comment by kjur** [comment]
It seems rawgit.com issue.
https://cdn.rawgit.com/kjur/jsrsasign/c057d3447b194fa0a3fdcea110579454898e093d/jsrsasign-all-min.js
When you use this URL for latest version, it works fine.
https://kjur.github.io/jsrsasign/jsrsasign-all-min.js

Please ask rawgit.com support.
