### ISSUE TITLE
Generating a CSR with RSA as algorithm does not work with sample script

### ISSUE THREAD

**Issue by robcordes** [kjur/jsrsasign#607]
The example gencsr script does not work as keyutil does not recognize the algorithm RSA.
node testCSRGen.js -a RSA -s 2048 -d /c=us,ou=dep,cn=apples.com 20240501102222

The script contained in the testCSRGen.js is the script I found as an example on GIT >>>  * gencsr - generate keypair and CSR, then save them to files. 
 *
 * Copyright (c) 2016 Kenji Urushima (kenji.urushima@gmail.com) <<<

The exception is :

Error: unknown algorithm: undefined
    at KEYUTIL.generateKeypair

The jsrsasign version is 11 and the same for jsrsasign-util.

**Comment by kjur** [comment]
Please use jsrsasign 11.1.0 released today.
