### ISSUE TITLE
X509 method getExtKeyUsage() not returning the critical flag value

### ISSUE THREAD

**Issue by robcordes** [kjur/jsrsasign#611]
<img width="901" alt="image" src="https://github.com/kjur/jsrsasign/assets/18548804/1d9c657e-9a2e-4e8a-89c0-923a550a9677">

cert file is in PEM format attached. Extension renamed to txt due to Git not wanting to upload pem files through the gui.

[PKIO-issued-client.t05i0014ru075.idd.mindef.nl.txt](https://github.com/kjur/jsrsasign/files/14211917/PKIO-issued-client.t05i0014ru075.idd.mindef.nl.txt)

**Comment by kjur** [comment]
getExtKeyUsage() seems to return proper value for the certificate.
```
> x.getExtKeyUsage()
{
  extname: 'keyUsage',
  critical: true,
  names: [ 'digitalSignature', 'keyEncipherment' ]
}
```

**Comment by robcordes** [comment]
Hi,
Thanks for getting back to me. However it is the getExtExtKeyUsage() method for the extend keyusages extension that I am referring.￼

Beste regards,

Rob Cordes

**Comment by kjur** [comment]
getExtExtKeyUsage() returns proper value as following:
```
> x.getExtExtKeyUsage()
{ extname: 'extKeyUsage', array: [ 'clientAuth', 'serverAuth' ] }
```
That certificate has no critical flag for extKeyUsage.

**Comment by robcordes** [comment]
Then wouldn’t you agree that one would have false returned and true when set ?Sent from my mobileOn 9 Feb 2024, at 08:48, Kenji Urushima ***@***.***> wrote:﻿
getExtExtKeyUsage() returns proper value as following:
> x.getExtExtKeyUsage()
{ extname: 'extKeyUsage', array: [ 'clientAuth', 'serverAuth' ] }

That certificate has no critical flag for extKeyUsage.

**Comment by kjur** [comment]
Yes, that means no critical flag for extKeyUsage.

**Comment by robcordes** [comment]
Allright then this is according to spec then. A bit weird though as when an attribute takes false of true as a boolean, one would expect the attribute to be always present. Anyway if this the expected behavior then that is okay of course. Thanks.

Best regards,

Rob Cordes
