### ISSUE TITLE
Started to bugs, version 11.0. 

### ISSUE THREAD

**Issue by smallfawn** [kjur/jsrsasign#615]
When I use KJUR crypto. Cipher. The encrypt (" text ", key) tip Error: Cipher. Encrypt: unsupported key or algorithm
But when I switched back to version 10.9 it worked
``````JavaScript
const {KEYUTIL,KJUR} = require('jsrsasign');

const publicKey =

    "-----BEGIN PUBLIC KEY-----\n" +
    "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANuiHtpFZeUZCiCdFJsrgDIc398KCOF5\n" +
    "Cr0bmma8SejrJWxCAThggEm9VTvsWPH6iLou8Lyo1zsC4bG2v9XIGusCAwEAAQ==\n" +
    "-----END PUBLIC KEY-----";

const key = KEYUTIL.getKey(publicKey);
console.log(key);
console.log(KJUR.crypto.Cipher.encrypt("哈哈哈", key));
``````
error Error: Cipher.encrypt: unsupported key or algorithm

**Comment by kjur** [comment]
I'm sorry but RSA encryption/decryption is not supported from version 11.0 because of Marvin attack vulnerability.
https://github.com/kjur/jsrsasign/security/advisories/GHSA-rh63-9qcf-83gf
