### ISSUE TITLE
Cannot get matching RSA SHA512 signature compared to nodejs `crypto`

### ISSUE THREAD

**Issue by paullinator** [kjur/jsrsasign#619]
give the same `privateKey` I'm using the following code to generate and verify signatures using nodejs `crypto` and `jsrsasign`. jsrsasign can't seem to create a valid signature that node crypto with verify as correct. Here's my code. Any help would be appreciated

https://github.com/EdgeApp/edge-react-gui/blob/paul/paybisSig/src/testcrypto.ts

**Comment by kjur** [comment]
Sorry but I can't see the link above.

**Comment by kjur** [comment]
I see your code before and it seems the issue of RSAPSS salt length difference between node crypto and jsrsasign.

To verify RSAPSS signature generated by Node crypto, you need to specify salt length in jsrsasign as follows:
``` JavaScript
const s3 = new jsrsasign.KJUR.crypto.Signature({alg: "SHA512withRSAandMGF1", psssaltlen: -2});
```

**Comment by kjur** [comment]
I seems no further comments. This will be closed.
