### ISSUE TITLE
RSA-OAEP encryption isssue

### ISSUE THREAD

**Issue by aniketkumar5676** [kjur/jsrsasign#621]
When i try to encrypt €¥₹ using RSA-OAEP, it return malformed symbol after decryption of encrypted string.
Like
₹ becomes ¹

**Comment by aniketkumar5676** [comment]
@kjur help here

**Comment by kjur** [comment]
I'm sorry but RSA-OAEP was no more supported since jsrsasign 11.0.0 because of vulnerability.
