### ISSUE TITLE
jsrsasign 11.1.0 not support RSA encrypt and decrypt 

### ISSUE THREAD

**Issue by leverwwz** [kjur/jsrsasign#622]
sir, please help to debug.

1、here is the case,
update jsrsasign from 10.8.2 to 11.1.0, but failed to encrypt and decrypt when using rsa.
            rsa.genKeyPair(1024)
            rsa.encodeAny(plain, keyPair.publicKey)

2、error detal,
Error: Cipher.encrypt: unsupported key or algorithm at Function.Object.<anonymous>.KJUR.crypto.Cipher.encrypt

**Comment by Likhith185** [comment]
@leverwwz any workaround on the above issue?

**Comment by kjur** [comment]
RSA encryption is no more supported since 11.0.0 for marvin vulnerability. Thank you for understanding.
