### ISSUE TITLE
CMS - Extra attributes in signedAttrs

### ISSUE THREAD

**Issue by ivoijen** [kjur/jsrsasign#623]
Hello,

Thank you very much for the useful library.

I would like to add attribute `pdfRevocationInfoArchival` (1.2.840.113583.1.1.8) to the SignedAttributes for PDF Long Term Validation.
I am currently unable to - it throws error `unknown attr: pdfRevocationInfoArchival`, which makes sense, because in the `tohex` function from KJUR.asn1.cms.AttributeList only attributes `contentType`, `messageDigest`, `signingTime`, `signingCertificate`, `signingCertificateV2`, `signaturePolicyIdentifier`, `signatureTimeStamp` and `timeStampToken` are supported.

Could you point me in the right direction on how to add the `pdfRevocationInfoArchival` attribute? 

Thank you in advance.

**Comment by kjur** [comment]
It requires code modification for jsrsasign.

(1)
Define custom PdfRevocationInfoArchival attribute class by extending KJUR.asn1.cms.Attribute.
(2)
Add support for it in KJUR.asn1.cms.AttributeList.

**Comment by ivoijen** [comment]
Thank you @kjur 

I was able to minify the files in /src using the Makefile and the `yuicmp` script you provided in an older issue. 

I however do not see any Makefile for combining them into `jsrsasign-all-min.js`, `jsrsasign-jwths-min.js` and `jsrsasign-rsa-min.js`. 

Is there any specific command/script you use for that?

Thank you for your time.
