### ISSUE TITLE
pkcs#8 DER binary input file

### ISSUE THREAD

**Issue by jean1199R** [kjur/jsrsasign#63]
Hi, frist of all thanks for you great job, well now I'm using this code quite similar to your function

function doSign2() {
  var rsa = new RSAKey();
  rsa.readPrivateKeyFromPEMString(document.form1.prvkey1.value);
  var hashAlg = document.form1.hashalg.value;
  var hSig = rsa.signString(document.form1.msgsigned.value, hashAlg);
  return hSig;
}; hex2b64(doSign2());

but before to make this I'm using the openSSL tool for converting from pkcs#8 DER to pkcs#1 just like this

openssl pkcs8 -inform DER -outform PEM -in xxx.key -out xxx_pem.key

and then this

openssl rsa -in "xxx_pem.key" -out xxx_pem_rsa.key

I've been reading the documentation and I really feel a little bit lost, I'm trying to convert the binary file to Hex and using this code that you provide in an issue before but I really don't know how to use it

var rawDerFileContents = "..........";
var hexDerFileContents = rstrtohex(rawDerFileContents); // raw string to hex
var pemString = KJUR.asn1.ASN1Util.getPEMStringFromHex(hexDerFileContents, "CERTIFICATE"); // with PEM Header

Thanks

**Comment by kjur** [comment]
I'm sorry but I can't catch your goal.
I would recommend to use KEYUTIL.getKey to read any format of key such like
PKCS#1 private key or PKCS#8 private key with pin.

Regards.

**Comment by kjur** [comment]
If you want to read PKCS#8 DER private key,
how about this?:

prvp8bin = '.....'; // raw PKCS#8 private key;
prvp8pem = KJUR.asn1.ASN1Util.getPEMStringFromHex(rstrtohex(prvp8bin), 'PRIVATE KEY');
prvkey = KEYUTIL.getKey(prvp8pem, 'password');

**Comment by nafiux** [comment]
Hello Team, I have the same question, I have a Private Key File in DER format, and I want to use it to sign a TEXT with jsrsasign, but, I don't know how to load this binary file with your library, could you please help me? Thanks.

**Comment by kjur** [comment]
Hi @nafiux , is it on browser or node?

**Comment by nafiux** [comment]
Hello Kenji,

In the browser.

Regards.

On Sat, May 28, 2016 at 4:11 PM, Kenji Urushima <notifications@github.com>
wrote:

> Hi @nafiux <https://github.com/nafiux> , is it on browser or node?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222333924>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc9i1cXlf0SGJaVNmPO2N5DH4siNbks5qGMuWgaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
Can you convert from your binary private key to PEM private key?
Please see bottom of this:
https://github.com/kjur/jsrsasign/wiki/Tutorial-for-PKCS5-and-PKCS8-PEM-private-key-formats-differences
The "jsrsasign" supports a PEM private key. Thanks.

**Comment by nafiux** [comment]
Hello Kenji,

Yes, I tried with the PEM version and works perfectly.

But, my end user does don't know how to convert this (using openssl) so
that I would like to know if is possible to convert the binary DER to PEM.

Thanks.

Regards.

On Sat, May 28, 2016 at 6:58 PM, Kenji Urushima <notifications@github.com>
wrote:

> Can you convert from your binary private key to PEM private key?
> Please see bottom of this:
>
> https://github.com/kjur/jsrsasign/wiki/Tutorial-for-PKCS5-and-PKCS8-PEM-private-key-formats-differences
> The "jsrsasign" supports a PEM private key. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222338349>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc9VRwZd3RfR-xNxJAHPwMc0bQs1Yks5qGPLFgaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
Can you find your binary private key format such like PKCS#1, PKCS#8 or PKCS#12? I can tell you how to convert.

**Comment by nafiux** [comment]
I have attached an example private key.

Passwd: 12345678a

On Sat, May 28, 2016 at 7:02 PM, Kenji Urushima <notifications@github.com>
wrote:

> Can you find your binary private key format such like PKCS#1, PKCS#8 or
> PKCS#12? I can tell you how to convert.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222338475>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc_rhlBD22JcTiYYGEOmWbznhLp7Fks5qGPPAgaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
Hi @nafiux , sorry but I can't find any attachment.

**Comment by nafiux** [comment]
I think that I don't have you direct email, I'm using the distribution list
for the repo, could you please provide me an email address? Thanks!

On Sat, May 28, 2016 at 7:07 PM, Kenji Urushima <notifications@github.com>
wrote:

> Hi @nafiux <https://github.com/nafiux> , sorry but I can't find any
> attachment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222338591>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc4ccY-1AiBjSHsjkVwRLUDOansrjks5qGPTZgaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
I've sent to your gmail address. Thanks.

**Comment by kjur** [comment]
Hi @nafiux , thank you for sending. I found your key is PKCS#8 binary encrypted key. To convert it to PEM, do following:

```
% openssl pkcs8 -inform DER -in CSD01_AAA010101AAA.key -out plain.key
Enter password:
% openssl pkcs8 -in plain.key -topk8 -v2 des3 -out new-encrypted.key
Enter Encryption Password:
Verifying - Enter Encryption Password:
```

Thanks.

**Comment by nafiux** [comment]
Hello Kenji,

Thanks, I can do that with openssl, but, I would like to know if is
possible to convert the DER to PEM, in JavaScript in the Web Browser
without openssl.

Regards.

On Sat, May 28, 2016 at 7:32 PM, Kenji Urushima <notifications@github.com>
wrote:

> Hi @nafiux <https://github.com/nafiux> , thank you for sending. I found
> your key is PKCS#8 binary encrypted key. To convert it to PEM, do following:
>
> % openssl pkcs8 -inform DER -in CSD01_AAA010101AAA.key -out plain.key
> Enter password:
> % openssl pkcs8 -in plain.key -topk8 -v2 des3 -out new-encrypted.key
> Enter Encryption Password:
> Verifying - Enter Encryption Password:
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222339248>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc29yI3aMTVk_c1bIoiOo2KazWTdDks5qGPq3gaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
How do you get DER binary on the browser such like drag drop or input form? If you get DER binary as raw string. You can convert it to hexadecimal string by 'rstrtohex' function then you can use  it with KEYUTIL.getKey() method.

**Comment by nafiux** [comment]
Thanks Kenji,

Finally,  I would like to know how can I extract information from a
Certificate (PEM FILE).

var x509 = new X509(); // https://kjur.github.io/jsrsasign/api/symbols/X509.html
var pem = KJUR.asn1.ASN1Util.getPEMStringFromHex(rstrtohex(binary),
"CERTIFICATE");
x509.readCertPEM(pem);
console.log(x509);
console.log(x509.getIssuerString());
console.log(x509.getNotAfter());
console.log(x509.getSerialNumberHex());
console.log(x509.getSignatureAlgorithmField());
console.log(x509.getSubjectString());

Thanks in advance.

Regards.


On Sat, May 28, 2016 at 7:38 PM, Kenji Urushima <notifications@github.com>
wrote:

> How do you get DER binary on the browser such like drag drop or input
> form? If you get DER binary as raw string. You can convert it to
> hexadecimal string by 'rstrtohex' function then you can use it with
> KEYUTIL.getKey() method.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kjur/jsrsasign/issues/63#issuecomment-222339391>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFrwc4vyvqbdfVd_ISBjyO_FEco2q_CUks5qGPwvgaJpZM4ChFeK>
> .
>



-- 
Ignacio Ocampo Millán

**Comment by kjur** [comment]
I hope X509.getInfo() method implementation will be helpful for you.

https://kjur.github.io/jsrsasign/api/symbols/X509.html#getInfo
https://kjur.github.io/jsrsasign/api/symbols/src/x509-1.1.js.html
