### ISSUE TITLE
ECDSA Example returns "invalid ECDSA signature" for valid signatures

### ISSUE THREAD

**Issue by mplatt** [kjur/jsrsasign#67]
I am experimenting with http://kjur.github.io/jsrsasign/sample-ecdsa.html because I would like to use KJUR.crypto.Signature with `SHA256withECDSA`.

However, with signatures generated from my application, the example returns `invalid ECDSA signature`. Consider the following example message (SHA256withECDSA, secp256r1):

| Input Type | Data |
| --- | --- |
| Message | a |
| Signature | `304402203ca92ab9d691135d7b5bfc2ba4a7c3a428159e29366370837419b29ee65d8c07022017e0bd344360da9955c2ae5964ac810256a8356e1f85532465a555dedd4b34d3` |
| Public Key | `3059301306072a8648ce3d020106082a8648ce3d03010703420004200d067a5f96240a63fb2e0192fe202de0bf4af679345285b1f8fdc90b2518569d41a2d432d1454ab6db9ac61b9d29a4c6970cea099ad081cf7570d999b3b67e` |

I am optimistic that the signature is in fact a valid signature over the message, since I have generated and verified it in Java (BouncyCastleProvider) as `SHA256withECDSA` signature with a `secp256r1` public key.

Perhaps this could be about the internals of the `KJUR.crypto.Signature.updateString` method. I am unsure if this is actually performs an UTF-8 conversion the same way `String.getBytes("UTF-8")` does in Java.

FYI this is a minimal example on how I have generated the signatures in Java:

``` Java
public class SimpleTest {
    public static void main(String[] args) throws CertificateException, NoSuchAlgorithmException, InvalidKeyException, SignatureException, NoSuchProviderException, UnsupportedEncodingException, InvalidAlgorithmParameterException {
        String plaintext = "a";

        /*
         * Sign
         */
        KeyPair pair = generateKeys();
        Signature ecdsaSign = Signature.getInstance("SHA256withECDSA", new BouncyCastleProvider());
        ecdsaSign.initSign(pair.getPrivate());
        ecdsaSign.update(plaintext.getBytes("UTF-8"));
        byte[] signature = ecdsaSign.sign();
        System.out.println("Message: " + plaintext);
        System.out.println("Signature: " + DatatypeConverter.printHexBinary(signature).toLowerCase());
        System.out.println("Public Key: " + DatatypeConverter.printHexBinary(pair.getPublic().getEncoded()).toLowerCase());

        /*
         * Verify
         */
        Signature ecdsaVerify = Signature.getInstance("SHA256withECDSA", new BouncyCastleProvider());
        ecdsaVerify.initVerify(pair.getPublic());
        ecdsaVerify.update(plaintext.getBytes("UTF-8"));
        System.out.println("Valid? " + ecdsaVerify.verify(signature));
    }
    private static KeyPair generateKeys() throws NoSuchAlgorithmException, NoSuchProviderException, InvalidAlgorithmParameterException {
        ECParameterSpec ecSpec = ECNamedCurveTable.getParameterSpec("secp256r1");
        KeyPairGenerator g = (KeyPairGenerator) KeyPairGenerator.getInstance("ECDSA", new BouncyCastleProvider());
        g.initialize(ecSpec, new SecureRandom());
        KeyPair pair = g.generateKeyPair();
        return pair;
    }

}
```

**Comment by ukari** [comment]
@mplatt , I meet the same problem, and it wastes me almost 3 hours.

I guess that what caused it is the `private key` what you generate in Java with BouncyCastle is encode in format `PKCS8` and directly use it in jsrsasign.

Although you didn't show the `private key` you used in jsrsasign, but the `public key` you give in example is the stuff looks like '3059......', which format is `PKCS8`, so I guess that.

When you want to sign in jsrsasign, the `private key` need to be decode to the format `hex`.

For example,
``` javascript
let privatekey = '3041......';
let ecdsa = new KJUR.crypto.Signature({"alg": "SHA256withECDSA"});
ecdsa.initSign({'ecprvhex': privatekey, 'eccurvename': 'secp256r1'});
```
it won't signature correctly because it use a wrong encode `private key`;

Here is my code to transfer the format:
``` javascript
let parse_PKCS8PrvKey = encode => KEYUTIL.getKey(encode, null, "pkcs8prv").prvKeyHex;
```
You can do `ecdsa.initSign({'ecprvhex': parse_PKCS8PrvKey(privateKey), 'eccurvename': 'secp256r1'});` to solve it.

[Here is the document](https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey)

**Comment by Ruffio** [comment]
@mplatt has this 'issue' been resolved? It looks like in the end it was a question about implementation. Please close this issue, if it has been resolved. Thanks.

**Comment by hfossli** [comment]
@mplatt is right that his key is valid. Using his values with openssl works fine. 

```
#! /bin/sh
echo 61 | xxd -r -p > dataToSign.dat
echo 304402203ca92ab9d691135d7b5bfc2ba4a7c3a428159e29366370837419b29ee65d8c07022017e0bd344360da9955c2ae5964ac810256a8356e1f85532465a555dedd4b34d3 | xxd -r -p > signature.dat
echo "-----BEGIN PUBLIC KEY-----" > key.pem
echo 3059301306072a8648ce3d020106082a8648ce3d03010703420004200d067a5f96240a63fb2e0192fe202de0bf4af679345285b1f8fdc90b2518569d41a2d432d1454ab6db9ac61b9d29a4c6970cea099ad081cf7570d999b3b67e | xxd -r -p | base64 -b 64 >> key.pem
echo "-----END PUBLIC KEY-----" >> key.pem
openssl dgst -sha256 -verify key.pem -signature signature.dat dataToSign.dat
```

Outputs
```
Verified OK
```

Inspecting with ASN1 explorer shows key structure is fine as well https://lapo.it/asn1js/#3059301306072A8648CE3D020106082A8648CE3D03010703420004200D067A5F96240A63FB2E0192FE202DE0BF4AF679345285B1F8FDC90B2518569D41A2D432D1454AB6DB9AC61B9D29A4C6970CEA099AD081CF7570D999B3B67E

**Comment by mplatt** [comment]
Closing this because I lack the context to validate the suggested solutions now
