### ISSUE TITLE
Is there an example of creating a Certificate Signing Request using PKCS#10 format?

### ISSUE THREAD

**Issue by EduardGimenez** [kjur/jsrsasign#68]
Thanks

**Comment by kjur** [comment]
I've release jsrsasign 4.9.0 today and it supports certificate signing request generation.
You can use KJUR.asn1.csr.CSRUtil.newCSRPEM method as following:
http://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.csr.CSRUtil.html#.newCSRPEM
pem = KJUR.asn1.csr.CSRUtil.newCSRPEM({
  subject: {str: '/C=US/O=Test/CN=example.com'},
  sbjpubkey: pubKeyObj,
  sigalg: "SHA256withRSA",
  sbjprvkey: prvKeyObj
});

**Comment by kurtsson** [comment]
Well done @kjur ! :clap:

**Comment by kjur** [comment]
Demo page is also added.
http://kjur.github.io/jsrsasign/tool_csr.html

**Comment by nathalials** [comment]
How can I parse CSR info from CSR PEM

**Comment by kjur** [comment]
Hi @nathalials . I'm sorry but there is no API for CSR parsing. So you need to convert it from PEM to hexadecimal string, then parse it by ASN1HEX class methods. The source code of x509-1.0.js may helps you.
