### ISSUE TITLE
KEYUTIL.getKey semantics for ECDSA

### ISSUE THREAD

**Issue by zoowar** [kjur/jsrsasign#69]
The KEYUTIL.getKey semantics for ECDSA appear to be inverted. 

When specifying the ECDSA private parameter 'd', a public key is generated. Similarly, when specifying the ECDSA public paramters 'x' and 'y', a private key is generated. Example code follows.

```
var d = '8e9b109e719098bf980487df1f5d77e9cb29606ebed2263b5f57c213df84f4b2';
var private_key = r.KEYUTIL.getKey({d: d, curve: 'secp256r1'});
console.log('isPrivate:', private_key.isPrivate);
console.log('isPublic:', private_key.isPublic);

[localhost]$ node index.js 
isPrivate: undefined
isPublic: true
```

**Comment by kjur** [comment]
I've fixed the issue on jsrsasign 4.8.2. When d is specfied, public key object was generated by mistake.
