### ISSUE TITLE
feature request: fingerprinting keys and certs

### ISSUE THREAD

**Issue by creativeprogramming** [kjur/jsrsasign#71]
Hi, awesome library thank you for sharing this massive work.

Can  you add a function to get md5 fingerprinting of keys and certificates?

Useful to quickly check a keypair and other things

Ideally something that will be accessible in a way like this:

```
X509.getMD5Fingerprint()
RSAKey.getMD5Fingerprint()
```

The equivalent openssl command is:
```
openssl rsa -noout -modulus -in private.key | openssl md5
(stdout=) a6c21de4195bb70ee3d5027806a285a7

openssl x509 -noout -modulus -in public.crt | openssl md5
(stdout=) a6c21de4195bb70ee3d5027806a285a7
```

Or this feature is already here but with another name?

Thank you in any case.

**Comment by kjur** [comment]
hex = KEYUTIL.getHexFromPEM(pemString);
fingerPrint = KJUR.crypto.Util.hashHex('md5', hex);

This provides MD5 finger print. Thanks.
