### ISSUE TITLE
Use the Web Cryptographic API in supported browsers

### ISSUE THREAD

**Issue by kurtsson** [kjur/jsrsasign#73]
Key generation, importing and exporting of certificates are coming in the [W3C standard web cryptographic API](http://www.w3.org/TR/WebCryptoAPI/). Most functionality is already implemented and stable in all the modern browsers, even IE11. Jsrsasign could berhaps use this methods for faster and more secure key generations when they are available.

**Comment by dodekeract** [comment]
This would also be a huge step in the direction of greatly reducing the bundle size. In a few years when the majority of websites has dropped IE10 support, this package would probably be only 1/10 of its current size.

**Comment by kjur** [comment]
jrsasign is a swiss army knife style all
in one package of crypto library which will also work on any old environment. If you need to use W3C WebCrypto and work on modern environments I would strongly recommend to use other libraries such as PKI.js.

**Comment by dodekeract** [comment]
@kjur In case you're interested in anecdotes, my current problem is that I'm looking for a small JWT library that also works in IE10. So neither JSRSASIGN nor WebCrypto are good for this. Right now I'm using the JWT-only version of JSRSASIGN, but it's still quite huge.

**Comment by rmhrisk** [comment]
@dodekeract I :heart: JRSASIGN but if that is the pattern you want to look at https://github.com/PeculiarVentures/webcrypto-liner and https://github.com/square/js-jose.
