### ISSUE TITLE
X509 - read extensions denoting key usage

### ISSUE THREAD

**Issue by alxndrsn** [kjur/jsrsasign#75]
As per https://en.wikipedia.org/wiki/X.509#Extensions_informing_a_specific_usage_of_a_certificate, I'm interested in reading the key usage flags (specifically signing vs encryption) from X509 certs.  Is this currently supported?  If not, I am happy to have a go at implementing, especially if you can give me some pointers.

**Comment by kjur** [comment]
I've added following two methods to access key usage extension. Regards.

http://kjur.github.io/jsrsasign/api/symbols/X509.html#.getExtKeyUsageBin
http://kjur.github.io/jsrsasign/api/symbols/X509.html#.getExtKeyUsageString

**Comment by alxndrsn** [comment]
Thanks :)
