### ISSUE TITLE
function X509() not available in npm module

### ISSUE THREAD

**Issue by erossignon** [kjur/jsrsasign#76]
this could be sorted out by adding the following line in  jsrsasign\npm\lib\jsrsasign.js and  jsrsasign\npm\lib\footer.js

    exports.X509 = X509;

**Comment by kjur** [comment]
I've officially released npm module today.
https://www.npmjs.com/package/jsrsasign for jsrsasign 4.8.2.
Also missing X509 is fixed.
Thanks
