### ISSUE TITLE
Non blocking key generation

### ISSUE THREAD

**Issue by animalillo** [kjur/jsrsasign#80]
if you try to generate a big key (For example, RSA 2048 bit lenght) it hangs the whole browser, it would be nice to have a non blocking method, and, if possible, some sort of progress tracking in the generation.

**Comment by frikeldon** [comment]
Hi

You can encapsulate your key generation in a [web worker](http://www.html5rocks.com/es/tutorials/workers/basics/), and then you can execute it in background with a non blocking way.

**Comment by kjur** [comment]
Otherwise, you can use W3C Web Crypto. It provides non blocking key generation.
https://www.w3.org/TR/WebCryptoAPI/
Most of modern browsers support it.

**Comment by Ruffio** [comment]
@kjur this issue should be closed

**Comment by getify** [comment]
FYI: you cannot just use this lib in a web worker, because it references `window`, and thus throws an exception.

I had to add this line of code hack to my web worker to use the lib:

```js
// hacking jsrsasign to work in a webworker
self.window = {};
```

+@kjur
