### ISSUE TITLE
jsrsasign cannot be used on sites using Content Security Policy due to eval()

### ISSUE THREAD

**Issue by LeeUK** [kjur/jsrsasign#83]
I'm trying to implement the Signature functionality of jsrsasign, but Content Security Policy on the domain prevents any eval() blocks from running. Is there a way that jsrsasign can be made 'eval-free'? As web security becomes a bigger issue I can only see the strict use of CSP becoming larger.

Chrome says: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
jsrsasign-4.7.0-all-min.js:234 setAlgAndProviderjsrsasign-4.7.0-all-min.js:234 KJUR.crypto.MessageDigestjsrsasign-4.7.0-all-min.js:234 setAlgAndProviderjsrsasign-4.7.0-all-min.js:234 KJUR.crypto.Signaturesign_test.js:5 (anonymous function)

Uncaught setAlgAndProvider hash alg set fail alg=sha1/setAlgAndProvider hash alg set fail alg=sha1/EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
jsrsasign-4.7.0-all-min.js:234 setAlgAndProviderjsrsasign-4.7.0-all-min.js:234 KJUR.crypto.Signaturesign_test.js:5 (anonymous function)

Enabling unsafe-eval isn't a workable option.

**Comment by LeeUK** [comment]
Already fixed by someone else on a Fork it seems. I implemented the changes and it works great on the CSP host. Perhaps a merge?

https://github.com/matiu/jsrsasign/commit/12e8bc5e7872180a5b9915626e78f62df18f3221

**Comment by couch** [comment]
Echoing @LeeUK, would love to see the eval fix merged, and as an added bonus, first-class npm module treatment.

matiu/jsrsasign@93e3810a221524d0e91832eda60cf4b119189eec

**Comment by cblair** [comment]
@couch, starting npm module treatment at https://github.com/mdcone/jsrsasign.

**Comment by Zamicol** [comment]
Any word?

For googlers:

I got this error when attempting `new KJUR.crypto.Signature({"alg": sigalg});`

I got around this with a change to the policy in the manifest, `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`, but it would be nice not to have to add this exception.

**Comment by mpcm** [comment]
I suspect this will also be an issue when used in chrome extensions? I recently hit this with the old jsjws repo, and haven't tried this new repo yet, but will confirm if it is an issue when I do.

**Comment by zboralski** [comment]
:+1:

**Comment by kjur** [comment]
Its push request is accepted and issue was fixed in 5.0.6. Thanks.

**Comment by zboralski** [comment]
Thanks @kjur

**Comment by Zamicol** [comment]
Works great.  Thanks!
