### ISSUE TITLE
Makefile in npm folder fails due to missing files

### ISSUE THREAD

**Issue by iamolivinius** [kjur/jsrsasign#85]
The Makefile within the npm folder fails because the following files are missing:

	../../../../jsjws/_gitpg/jsjws/ext/json-sans-eval-min.js \
	../../../../jsjws/_gitpg/jsjws/jws-3.0.min.js \
	../../../../jsjws/_gitpg/jsjws/jwsjs-2.0.min.js \

Please make sure that all necessary files to run this project are included in this repository.

**Comment by kjur** [comment]
I've officially released npm module today.
https://www.npmjs.com/package/jsrsasign for jsrsasign 4.8.2.
Missing files issue also fixed.
Thanks
