### ISSUE TITLE
CMS Signed data result doesn't coincide with Java (bouncycastle) generated CMS

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [kjur/jsrsasign#87]
I'm using [forge](https://github.com/digitalbazaar/forge) library in orfer to read and extract private key from .p12 container. After extracting key in PEM format (RSA PRIVATE KEY) I tried to sign string with value `"test"` and result is not same with both Java's enveloped=true/false CMS calculation results.

Also, I'm using the latest version of jsrsasign.

Surely, Java code uses the same hash and encryption algo as JS. I'm using `SHA1withRSA`.

Does jsrsasign calculates detached signature (enveloped=false, econtent=null) or resulting PEM contains encapsulated data? 

My code is copied from example and looks like:

            
            certPEM = ... // extracted from p12 via forge
            var keyPEM = forge.pki.privateKeyToPem(privateKey);
	
			console.log(keyPEM);
	
			var param = {
			  content: {str: "test"},
			  certs: [certPEM],
			  signerInfos: [{
				hashAlg: 'sha1',
				sAttr: {
				},
				signerCert: certPEM,
				sigAlg: 'SHA1withRSA',
				signerPrvKey: keyPEM
			  }]
			};
			var sd = KJUR.asn1.cms.CMSUtil.newSignedData(param);
			console.log(sd.getPEM());

May be there are additional configuration which I omitted or jsrsasign internally adds to signing data some additional text?

**Comment by kjur** [comment]
I afraid that CMS signatures by bouncy castle and jsrsasign may have different signed attributes. Have you check them?

**Comment by ioannis85** [comment]
> I'm using [forge](https://github.com/digitalbazaar/forge) library in orfer to read and extract private key from .p12 container. After extracting key in PEM format (RSA PRIVATE KEY) I tried to sign string with value `"test"` and result is not same with both Java's enveloped=true/false CMS calculation results.
> 
> Also, I'm using the latest version of jsrsasign.
> 
> Surely, Java code uses the same hash and encryption algo as JS. I'm using `SHA1withRSA`.
> 
> Does jsrsasign calculates detached signature (enveloped=false, econtent=null) or resulting PEM contains encapsulated data?
> 
> My code is copied from example and looks like:
> 
> ```
>         certPEM = ... // extracted from p12 via forge
>         var keyPEM = forge.pki.privateKeyToPem(privateKey);
> 
>         console.log(keyPEM);
> 
>         var param = {
>           content: {str: "test"},
>           certs: [certPEM],
>           signerInfos: [{
>             hashAlg: 'sha1',
>             sAttr: {
>             },
>             signerCert: certPEM,
>             sigAlg: 'SHA1withRSA',
>             signerPrvKey: keyPEM
>           }]
>         };
>         var sd = KJUR.asn1.cms.CMSUtil.newSignedData(param);
>         console.log(sd.getPEM());
> ```
> May be there are additional configuration which I omitted or jsrsasign internally adds to signing data some additional text?

Baurzhan   I have the same issue , can you resolved it??
