### ISSUE TITLE
Signing with encrypted RSA key fails using jsrsasign

### ISSUE THREAD

**Issue by thxmike** [kjur/jsrsasign#89]
When using the library javascript library, jsrsasign, we are attempting to sign a value using a private key. We are using SHA256 with RSA (i.e. -----BEGIN ENCRYPTED PRIVATE KEY-----....-----END ENCRYPTED PRIVATE KEY-----)

snippet:

var sig = new KJUR.crypto.Signature({"alg": "SHA256withRSA", "prov":   "cryptojs/jsrsa"});
var key = KEYUTIL.getKey(privateKey, 'password');
sig.initSign(key);
sig.updateString(data);
var signature = sig.sign();
In using the process, We receive the following error message: bi.intValue is not a function

In debugging it it appears that the value that is used has an alpha character that fails a function for the BigInteger library.

My first thought was it was the private key file, However, we are able to do the signing process using NodeJS's Crypto library and it works as expected.

I have tried different versions of the above with no success.

**Comment by kjur** [comment]
Thank you for the report. I seem to get the same issue. It seems KEYUTIL.getKey issue while reading a private key. I'm checking it now.

**Comment by kjur** [comment]
Sorry but I couldn't reproduct your issue. So I'll close this ticket. Thanks.

**Comment by edamazzio** [comment]
Hi @thxmike Were you able to solve this?
