### ISSUE TITLE
HTTPS設定ファイル生成ツール0.2(ベータ版)が出力するnginx.conf(Mozilla推奨設定)について

### ISSUE THREAD

**Issue by cubicdaiya** [kjur/jsrsasign#90]
https://kjur.github.io/jsrsasign/tool_httpscfg.html

上記ページの説明文中のリンクから来ました。

nginxでガイドラインの種類をMozilla推奨設定にした際の`ssl_protocols`の値がおかしい気がします。
[Mozillaの本家Wikiページ](https://wiki.mozilla.org/Security/Server_Side_TLS) では3種類の推奨設定でTLSのバージョンはそれぞれ、

 * Modern compatibility ->  TLSv1.1, TLSv1.2
 * Intermediate compatibility -> TLSv1, TLSv1.1, TLSv1.2
 * Old backward compatibility -> SSLv3, TLSv1, TLSv1.1, TLSv1.2

となっていますが、上記3種類のどれを選択しても常に下記の設定が出力されます。

```nginx
ssl_protocols TLSv1.2 TLSv1.1 TLSv1 SSLv3;
```

## 環境

 * Mac OS X 10.10.3
 * Google Chrome 42.0.2311.135 (64-bit)

**Comment by kjur** [comment]
@cubicdaiya さん、ご指摘ありがとうごいざいます。明日、修正しておきます。

**Comment by kjur** [comment]
修正したものを公開しました。ご確認ください。

**Comment by cubicdaiya** [comment]
@kjur 確認しました。ありがとうございます。
