### ISSUE TITLE
Question: Is jsrsasign supports converting SSHPublicKey to Pkcs1PublicKey supported?

### ISSUE THREAD

**Issue by anuchandy** [kjur/jsrsasign#91]
Hello,  is it possible to convert SSHPublicKey in the format "ssh-rsa {body} {info}" to Pkcs1PublicKey format using this library?

If yes, could you please provide some pointers?

**Comment by kjur** [comment]
Sorry but there is no such API. If you can get a modulus and public exponent of SSH public key then you can have RSAKey object for this and you can get PKCS#1 key.

**Comment by anuchandy** [comment]
Thanks @kjur for confirming

**Comment by anuchandy** [comment]
@kjur I could derive Pkcs1PublicKey from SSH Public Key. 

Is there any way to generate PKCS#12 from PKCS#1 key using this library?

I am working on a tool that needs to generates (PKCS#12/PFX) given PKCS#1 key (generated from SSHPublicKey), but I don't have access to private key.

Could you please provide some inputs if possible?
