### ISSUE TITLE
Question/request for example: PKCS1 to PKCS12

### ISSUE THREAD

**Issue by anuchandy** [kjur/jsrsasign#92]
I have SSHPublicKey in the format "ssh-rsa {body} {info}" (I don't have access to private key) from which I want to generate PKCS#12

As a first step tried generating the PKCS#1 from the SSHPublicKey. I have asked the question here https://github.com/kjur/jsrsasign/issues/91, based on your guideline I understood that to generate PKCS#1 we need exponent and modulus. After some investigation found this project https://github.com/dominictarr/ssh-key-to-pem and used it to generate PEM (PKCS#1) from the SSHPublicKey.

```bash
var fs = require('fs');
var sshKeyToPEM = require('ssh-key-to-pem');
// the file 'id_rsa.pub' contains ssh public key in the format "ssh-rsa {body} {info}" 
var sshPublicKey = fs.readFileSync('./id_rsa.pub', 'ascii')
var pkcs1 = sshKeyToPEM(sshPublicKey);
// I got pkcs1 in the format
// -----BEGIN PUBLIC KEY-----
// key
//-----END PUBLIC KEY-----
```

Now we want to generate PKCS12 from the pkcs1.

After going through jsrsasign examples/doc I feel like this is possible using 'TBSCertificate', but I don't have access to the private key, we cannot create a signature for the TBS. However, a valid certificate requires a bit string for the signature value.

Can you please provide some inputs ?

**Comment by kjur** [comment]
prvKey = KEYUTIL.getKey(PKCS1PRVKEY, 'password');

To issue certificate, following sample may helps:
https://github.com/kjur/jsrsasign/blob/master/tool_ca.html

There is no functionality for generate and reading PKCS#12 at this stage.

To generate PKCS#12 CMS structure following codes may helps:
https://github.com/kjur/jsrsasign/blob/master/asn1cms-1.0.js

Regards,
