### ISSUE TITLE
KEYUTIL.getPEM not working

### ISSUE THREAD

**Issue by animalillo** [kjur/jsrsasign#93]
Using jsrsasign-4.7.1-all-min.js

I think the same or really similar problem that in #53 

 > var kp = KEYUTIL.generateKeypair("RSA", 1024);
<< undefined
>kp
<<Object {prvKeyObj: RSAKey, pubKeyObj: RSAKey}
> KEYUTIL.getPEM(kp.prvKeyObj, "PKCS1PRV")
<< Uncaught TypeError: KJUR.asn1.ASN1Util.newObject is not a functionp @ jsrsasign-4.7.1-all-min.js?v=cf866614b6b18cda13fe699a3a65661b:249KEYUTIL.getPEM @ jsrsasign-4.7.1-all-min.js?v=cf866614b6b18cda13fe699a3a65661b:249(anonymous function) @ VM8562:2InjectedScript._evaluateOn @ VM8247:883InjectedScript._evaluateAndWrap @ VM8247:816InjectedScript.evaluate @ VM8247:682

**Comment by animalillo** [comment]
Tried with jsrsasign-4.8.0-all.min.js, still present

**Comment by kjur** [comment]
Thank you for the report. I'll check it later.

**Comment by kjur** [comment]
Hmm, this works fine for me. It should be Node.js issue. Following test works on browser.

test("PRV getPEM", function() {
  var kp = KEYUTIL.generateKeypair("RSA", 1024);
  equal(KEYUTIL.getPEM(kp.prvKeyObj, "PKCS1PRV").substr(0, 34), "-----BEGIN RSA PRIVATE KEY-----\r\nM", "");
});

test("PUB getPEM", function() {
  var kp = KEYUTIL.generateKeypair("RSA", 1024);
  equal(KEYUTIL.getPEM(kp.pubKeyObj, "PKCS8PUB").substr(0, 29), "-----BEGIN PUBLIC KEY-----\r\nM", "");
});

**Comment by animalillo** [comment]
I'm using it on the browser (firefox)

**Comment by kjur** [comment]
I've created a test case for it and it works fine on Firefox.
https://kjur.github.io/jsrsasign/test/qunit-do-keyutil-pairpem.html
Could you try?

**Comment by animalillo** [comment]
hmmm
it seems to be working outside of my application.
It might be related with this sjcl issue 
https://github.com/bitwiseshiftleft/sjcl/issues/223

**Comment by HerberthAlvarado** [comment]
I can see this happening in 10.1.13

I created a keypair in mkjwk.org (2048, Sig, RS256: RSA, Kid: Specify - random number, No X.509)

I copied the Public and Private keypair (the one on the left), assign it to a variable in my code and call getkey. I was able to print the object (private=yes, public=no). Then it fails trying to obtain the private key (PKCS1PRV)

My workaround, as I read in an old post post was to set isPublic=true.

**Comment by kjur** [comment]
(1) Generate key with mkjwk.org (2048, Sig, RS256: RSA, Kid: Specify - random number, *YES* X.509).
(2) Copy PEM private and public key.
(3) execute code

``` JavaScript
var rs = require("jsrsasign");
var prvpem = '%%%PRVITE KEY PEM of mkjwk %%%';
var pubpem = '%%%PUBLIC kEY PEM of mkjwk %%%';
var prv = rs.KEYUTIL.getKey(prvpem);
var pub = rs.KEYUTIL.getKey(pubpem);
console.log(rs.KEYUTIL.getPEM(pub);
console.log(rs.KEYUTIL.getPEM(pub, "PKCS8PRV");
console.log(rs.KEYUTIL.getPEM(pub, "PKCS1PRV");
```

It works fine for me.
