### ISSUE TITLE
KEYUTIL.getKey unable to read RSA JWK public/private keypair

### ISSUE THREAD

**Issue by jricher** [kjur/jsrsasign#96]
When using a JWK in the form:

```
{
  "d": "K_L9VXSzbvWJ_WAySAXhTEakd1kUCzpYGRHssV1mYKJcuyqMkpxWrlCs4_dn8SCtDzpjbUjVHU-VSYoklB-GfM0uTeFnMlfY6wqJLJeaP179w7U3rbuUUw3oeEXJHU6ZMzko6v1b-bO7zRSoYizuKuTxkc4vrRi4ca7Ew8L3jQcYZHGxxG_0--QIZBrXPMNd87-BxbfCyQqnkwIJAMS9NQSOOAgGDys8YP_IFjA0ChUE__OI0zeIin7E5ddYqVyDHojKhfZuy7YKK85C32KyXO23oTwyPKc8MUjMRcVlNQIfn08qVnD7qo8x8usbjeujCiP8KQnapMt1-kEb_0cY-Q",
  "e": "AQAB",
  "n": "xG7Z_-5G-2PvFLEqwr1QBFQqNymGLVSBvpB8XWgjTXF0UgtX_uYGtzPbRxSVG8DEYEswgznHS8QyOz7fISgCT26oCwdnZ5oYzqJWMmZkyjIgfFwIXKiwYYePZKezGFmklQAo20D7QJNPQp0e7yzSsOm_fCVjT6wDvkVaxzOUPliwmO1CJhfQU8Cx1Ifb1JGhNjc0pPZMfwALG8z2D173mGh749wHwLxnef5wEqfFgmdgFmI6uEHqyHZW98FDhkyPFMS5N3lJftvBHUY3M8bv7OM2QoqGHzdW25_8kBFy7VWhnprutGCogltd-UfWkZDg7RxYBh_EXfrmEUfYH6Vgiw",
  "kty": "RSA"
}
```
(issued by https://mkjwk.org/), the library is unable to create the key object. The error given is:

```
TypeError: undefined is not a function
    at Object.KEYUTIL.getKey (/Users/jricher/node_modules/jsrsasign/lib/jsrsasign.js:254:15495)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
```

This is while running jsrsasign 4.8.2 under commandline interactive node 0.12.2 on Mac OSX.

The tests for RSA private keys all seem to pass, but the values in the tests seem to both use the optional extra private key parameters such as `dp`, `dq`, and `qi`.

**Comment by kjur** [comment]
Dear @jricher , getKey method requires dp, dq and qi for RSA private key of JWK. A sample JWK RSA private key in RFC 7517 Appendix also has dp, dq and qi. Regards.

**Comment by jricher** [comment]
The only required parameter of an RSA private-key JWK is the "d" parameter, as defined in RFC7518:

https://tools.ietf.org/html/rfc7518#section-6.3.2

All other fields are optimizations and are optional. There are many JWKs in the wild, including the key generator that I pointed to earlier, that do not add the extra optional parameters. The getKey method of this library should be able to create an RSAKey using only the "d" private parameter alongside the "n" and "e" parameters for the public key.

Please re-open this issue.
