### ISSUE TITLE
Please include project build tools in repository

### ISSUE THREAD

**Issue by Infeligo** [kjur/jsrsasign#98]
Currently the tools that are used to create minified versions of source files as well as concatenated final versions are not in the repository. It would be nice if they were included.

**Comment by kjur** [comment]
Sorry but you can use any minifying tools such as yuicompressor.
http://yui.github.io/yuicompressor/
There is no plan to include such tools. Thanks.

**Comment by Infeligo** [comment]
What I actually meant is publishing **scripts** that use those concatenating/minifying tools to produce the final version of the lib. For npm packaging you use Make. How do you produce the `jsrsasign-xxx-all-min.js` files?

**Comment by kjur** [comment]
It's just concatenated all min files.
