### ISSUE TITLE
Signed by jsrasign tokens fail verification in other modules

### ISSUE THREAD

**Issue by thomasbhatia** [kjur/jsrsasign#99]
Sample token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdfaWQiOiIxIiwiZW1wX251bSI6IjEyMyJ9.QMAQW20MM0Dr5onHpMia3w9N9bRz62THNYJPkZn_Xr0 . 

Generated using following steps:
var oHeader = {alg: 'HS256',typ:'JWT'};
                        var oPayload = {};
                        oPayload.org_id = '1';
                        oPayload.emp_num = username;
                        var sHeader = JSON.stringify(oHeader);
                        var sPayload = JSON.stringify(oPayload);
                        var sJWT = KJUR.jws.JWS.sign("HS256", sHeader, sPayload, 'icarus');

Token fails verification in other modules e.g pyjwt or online at jwt.io.

**Comment by kjur** [comment]
var sJWT = KJUR.jws.JWS.sign("HS256", sHeader, sPayload, 'icarus');

Passcode shall be specified as a hexadecimal string.
As for the text 'icarus', it will be '696361727573'.
